import Mathlib

/-!
# Conjecture 00000007928 (disproof)

The conjecture asserts, for number fields `F`, the explicit formula
`w_2(F) = |K_2(O_F)| = |zeta_F(-1)| * D_F * 2^[F:Q]`.

For `F = Q` the right-hand side is `|zeta(-1)| * 1 * 2 = 1/6`, which is not a natural number, so it
is not the order of any group (finite or not), whatever `K_2(Z)` is.

Mathlib's `NumberField.dedekindZeta` is the raw L-series `sum_n a_n n^{-s}`, with `a_n` the number
of ideals of norm `n`; the series diverges at `s = -1`, so its Lean value there is a junk value,
not `zeta_Q(-1)`. We prove that for `F = Q` this
L-series equals `riemannZeta` on `re s > 1`, and that every function holomorphic on `C \ {1}` that
agrees with it there takes the value `riemannZeta (-1) = -1/12` at `-1` (identity theorem).
-/

open NumberField Complex

namespace C7928

/-- The right-hand side `|z| * |D_Q| * 2^[Q:Q]` of the conjectured formula for `F = Q`, where
`z` is the value `zeta_Q(-1)`. -/
noncomputable def rhsQ (z : ℂ) : ℝ :=
  ‖z‖ * |((NumberField.discr ℚ : ℤ) : ℝ)| * 2 ^ Module.finrank ℚ ℚ

theorem riemannZeta_neg_one : riemannZeta (-1) = -1 / 12 := by
  have h := riemannZeta_neg_nat_eq_bernoulli 1
  rw [bernoulli_two] at h
  push_cast at h
  rw [h]
  norm_num

theorem rhsQ_riemannZeta : rhsQ (riemannZeta (-1)) = 1 / 6 := by
  rw [rhsQ, riemannZeta_neg_one, Rat.numberField_discr, Module.finrank_self]
  have : ‖(-1 / 12 : ℂ)‖ = 1 / 12 := by
    rw [norm_div, norm_neg, norm_one]
    norm_num
  rw [this]
  norm_num

/-! ## The Dedekind zeta function of `Q` -/

/-- Every ideal of `𝓞 ℚ` is generated by a natural number, namely its absolute norm. -/
theorem ideal_eq_span_absNorm (I : Ideal (𝓞 ℚ)) :
    I = Ideal.span {((Ideal.absNorm I : ℕ) : 𝓞 ℚ)} := by
  have : IsPrincipalIdealRing (𝓞 ℚ) := IsPrincipalIdealRing.of_surjective
    Rat.ringOfIntegersEquiv.symm Rat.ringOfIntegersEquiv.symm.surjective
  obtain ⟨x, rfl⟩ := (IsPrincipalIdealRing.principal I).principal
  obtain ⟨k, rfl⟩ : ∃ k : ℤ, x = (k : 𝓞 ℚ) :=
    ⟨Rat.ringOfIntegersEquiv x, by
      conv_lhs => rw [← Rat.ringOfIntegersEquiv.symm_apply_apply x]
      exact eq_intCast (Rat.ringOfIntegersEquiv.symm : ℤ →+* 𝓞 ℚ) _⟩
  have hk : ((k : ℤ) : 𝓞 ℚ) = algebraMap ℤ (𝓞 ℚ) k := by simp
  rw [Ideal.absNorm_span_singleton, hk, Algebra.norm_algebraMap, RingOfIntegers.rank,
    Module.finrank_self, pow_one, ← hk]
  rcases Int.natAbs_eq k with h | h
  · conv_lhs => rw [h]
    simp
  · conv_lhs => rw [h]
    simp

theorem absNorm_span_nat (m : ℕ) : Ideal.absNorm (Ideal.span {((m : ℕ) : 𝓞 ℚ)}) = m := by
  rw [Ideal.absNorm_span_singleton]
  have : ((m : ℕ) : 𝓞 ℚ) = algebraMap ℤ (𝓞 ℚ) (m : ℤ) := by simp
  rw [this, Algebra.norm_algebraMap, RingOfIntegers.rank, Module.finrank_self, pow_one,
    Int.natAbs_natCast]

theorem card_ideals_of_norm (n : ℕ) :
    Nat.card {I : Ideal (𝓞 ℚ) // Ideal.absNorm I = n} = 1 := by
  rw [Nat.card_eq_one_iff_exists]
  refine ⟨⟨Ideal.span {((n : ℕ) : 𝓞 ℚ)}, absNorm_span_nat n⟩, ?_⟩
  rintro ⟨I, hI⟩
  exact Subtype.ext ((ideal_eq_span_absNorm I).trans (by rw [hI]))

theorem dedekindZeta_rat {s : ℂ} (hs : 1 < s.re) : dedekindZeta ℚ s = riemannZeta s := by
  rw [dedekindZeta, ← LSeries_one_eq_riemannZeta hs]
  refine LSeries_congr (fun {n} _ => ?_) s
  simp [card_ideals_of_norm n]

/-- Uniqueness of the continuation: every function holomorphic on `C \ {1}` that agrees with the
Dedekind zeta L-series of `Q` on `re s > 1` takes the value `-1/12` at `s = -1`. -/
theorem continuation_value (Z : ℂ → ℂ) (hZ : DifferentiableOn ℂ Z {1}ᶜ)
    (hZeq : ∀ s : ℂ, 1 < s.re → Z s = dedekindZeta ℚ s) : Z (-1) = -1 / 12 := by
  have hZan : AnalyticOnNhd ℂ Z {1}ᶜ := hZ.analyticOnNhd isOpen_compl_singleton
  have heq : Set.EqOn Z riemannZeta {1}ᶜ :=
    hZan.eqOn_of_preconnected_of_eventuallyEq analyticOn_riemannZeta
      (isConnected_compl_singleton_of_one_lt_rank (by simp) 1).isPreconnected
      (by norm_num : (2 : ℂ) ∈ _)
      (Filter.eventuallyEq_of_mem
        ((isOpen_lt continuous_const continuous_re).mem_nhds (by norm_num))
        (fun s hs => (hZeq s hs).trans (dedekindZeta_rat hs)))
  rw [heq (by norm_num : (-1 : ℂ) ∈ ({1}ᶜ : Set ℂ)), riemannZeta_neg_one]

/-- `riemannZeta` itself satisfies the hypotheses of `continuation_value`, so they are not
vacuous: it is holomorphic on `C \ {1}` and equals the Dedekind zeta L-series of `Q` on
`re s > 1`. -/
theorem riemannZeta_is_continuation :
    DifferentiableOn ℂ riemannZeta {1}ᶜ ∧
      ∀ s : ℂ, 1 < s.re → riemannZeta s = dedekindZeta ℚ s :=
  ⟨fun _ hs => (differentiableAt_riemannZeta hs).differentiableWithinAt,
    fun _ hs => (dedekindZeta_rat hs).symm⟩

/-! ## The disproof -/

/-- No natural number equals the right-hand side `|zeta(-1)| * |D_Q| * 2^[Q:Q] = 1/6`. -/
theorem nat_ne_rhsQ (n : ℕ) : (n : ℝ) ≠ rhsQ (riemannZeta (-1)) := by
  rw [rhsQ_riemannZeta]
  intro h
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · norm_num at h
  · have : (1 : ℝ) ≤ n := by exact_mod_cast hn
    linarith

/-- Main theorem. Let `Z` be any function holomorphic on `C \ {1}` that agrees with the Dedekind
zeta function of `Q` on `re s > 1` (so `Z (-1)` is the value `zeta_Q(-1)` of the meromorphic
continuation). Then for every type `G` (in particular for `G = K_2(Z)`, whatever it is),
`Nat.card G` differs from `|Z(-1)| * |D_Q| * 2^[Q:Q]`. -/
theorem conjecture_7928_false (Z : ℂ → ℂ) (hZ : DifferentiableOn ℂ Z {1}ᶜ)
    (hZeq : ∀ s : ℂ, 1 < s.re → Z s = dedekindZeta ℚ s) (G : Type*) :
    (Nat.card G : ℝ) ≠
      ‖Z (-1)‖ * |((NumberField.discr ℚ : ℤ) : ℝ)| * 2 ^ Module.finrank ℚ ℚ := by
  have h := nat_ne_rhsQ (Nat.card G)
  rwa [rhsQ, riemannZeta_neg_one, ← continuation_value Z hZ hZeq] at h

/-- The main theorem with `Z = riemannZeta`, the continuation of the Dedekind zeta function
of `Q`. -/
theorem conjecture_7928_false_riemannZeta (G : Type*) :
    (Nat.card G : ℝ) ≠
      ‖riemannZeta (-1)‖ * |((NumberField.discr ℚ : ℤ) : ℝ)| * 2 ^ Module.finrank ℚ ℚ :=
  conjecture_7928_false riemannZeta riemannZeta_is_continuation.1
    riemannZeta_is_continuation.2 G

/-- The same for every finite group `G`, with its order `Fintype.card G`. -/
theorem conjecture_7928_false_finite_group (G : Type*) [Group G] [Fintype G] :
    (Fintype.card G : ℝ) ≠
      ‖riemannZeta (-1)‖ * |((NumberField.discr ℚ : ℤ) : ℝ)| * 2 ^ Module.finrank ℚ ℚ := by
  rw [← Nat.card_eq_fintype_card]
  exact conjecture_7928_false_riemannZeta G

end C7928
