/-!
# Disproof of TLMC conjecture 00000000548

Conjecture: for every monomial ideal `I`, `ι(I) ≤ β₀(I)`, where `ι(I)` is the
minimal number of components in an irredundant irreducible decomposition and
`β₀(I)` is the minimal number of monomial generators.

Counterexample: `I = (xyz) ⊆ k[x,y,z]`.

* `(xyz) = (x) ∩ (y) ∩ (z)` — `decomposition_correct`.
* The components are irredundant, witnessed by `yz`, `xz`, `xy` —
  `component_x_needed`, `component_y_needed`, `component_z_needed`.
* The components are irreducible (no two strict monomial super-ideals
  intersect to them) — `memX_irreducible`, `memY_irreducible`, `memZ_irreducible`.
* `β₀((xyz)) = 1`: generated by the single monomial `xyz`, and not the zero
  ideal — `generated_by_one`, `nonempty`.
* Hence `ι = 3 > 1 = β₀` — `main`, `iota_gt_beta0`.

No `sorry`, no classical axioms: `Check.lean` verifies via `#print axioms`
that every theorem below depends on no axioms at all.

Monomials of `k[x,y,z]` are encoded as exponent triples `Mono`, and monomial
ideal membership as a `Bool`-valued divisibility test, so that all equalities
are proved by pure `rfl`/`decide` computation without `funext` or `Classical`.
-/

/-- Monomials of `k[x,y,z]`, encoded by exponent triples. -/
abbrev Mono := Nat × Nat × Nat

/-- `1 ≤ n`, as a `Bool`. -/
def ble1 (n : Nat) : Bool := Nat.ble 1 n

/-- Membership in the principal ideal `(xyz)`: divisibility by `xyz`. -/
def memI (e : Mono) : Bool := ble1 e.1 && (ble1 e.2.1 && ble1 e.2.2)

/-- Membership in the irreducible component `(x)`. -/
def memX (e : Mono) : Bool := ble1 e.1

/-- Membership in the irreducible component `(y)`. -/
def memY (e : Mono) : Bool := ble1 e.2.1

/-- Membership in the irreducible component `(z)`. -/
def memZ (e : Mono) : Bool := ble1 e.2.2

/-- Componentwise order on exponent triples: `Le3 a b` means `a` divides `b`. -/
abbrev Le3 (a b : Mono) : Prop := a.1 ≤ b.1 ∧ (a.2.1 ≤ b.2.1 ∧ a.2.2 ≤ b.2.2)

/-- A membership predicate is an up-set iff it is a monomial ideal
(closed under divisibility). -/
def UpSet (m : Mono → Bool) : Prop :=
  ∀ e f, m e = true → Le3 e f → m f = true

/-! ### Small glue lemmas about `ble1` -/

theorem le_of_ble1 {n : Nat} (h : ble1 n = true) : 1 ≤ n := by
  cases n with
  | zero => exact absurd h (by decide)
  | succ m => exact Nat.succ_le_succ (Nat.zero_le m)

theorem ble1_true {n : Nat} (h : 1 ≤ n) : ble1 n = true := by
  cases n with
  | zero => exact absurd h (Nat.not_succ_le_zero 0)
  | succ m => rfl

theorem band_eq_left {a b : Bool} (h : (a && b) = true) : a = true := by
  cases a <;> cases b
  · exact h
  · exact h
  · exact absurd h (by decide)
  · rfl

theorem band_eq_right {a b : Bool} (h : (a && b) = true) : b = true := by
  cases a <;> cases b
  · exact h
  · exact absurd h (by decide)
  · exact h
  · rfl

/-! ### The decomposition `(xyz) = (x) ∩ (y) ∩ (z)` -/

/-- Pointwise equality `(xyz) = (x) ∩ (y) ∩ (z)`: a monomial is divisible by
`xyz` iff it is divisible by `x`, by `y` and by `z`. -/
theorem decomposition_correct :
    ∀ e, memI e = (memX e && (memY e && memZ e))
  | (a, b, c) => by cases a <;> cases b <;> cases c <;> rfl

/-! ### Irredundancy: each component is necessary -/

/-- `yz` lies in `(y) ∩ (z)` but not in `(xyz)`: dropping `(x)` enlarges the
intersection. -/
theorem component_x_needed :
    ((memY (0, 1, 1) && memZ (0, 1, 1)) = true) ∧ (memI (0, 1, 1) = false) :=
  ⟨rfl, rfl⟩

/-- `xz` lies in `(x) ∩ (z)` but not in `(xyz)`: dropping `(y)` enlarges the
intersection. -/
theorem component_y_needed :
    ((memX (1, 0, 1) && memZ (1, 0, 1)) = true) ∧ (memI (1, 0, 1) = false) :=
  ⟨rfl, rfl⟩

/-- `xy` lies in `(x) ∩ (y)` but not in `(xyz)`: dropping `(z)` enlarges the
intersection. -/
theorem component_z_needed :
    ((memX (1, 1, 0) && memY (1, 1, 0)) = true) ∧ (memI (1, 1, 0) = false) :=
  ⟨rfl, rfl⟩

/-! ### Irreducibility of the single-variable components

Stated in contrapositive form: no two monomial ideals strictly containing the
component intersect exactly to the component.  Constructive proof: two strict
super-ideals `p`, `q` contain monomials `u`, `v` on which the variable has
exponent `0`; the componentwise sum `u + v` lies in both (up-set property),
still has exponent `0` in the variable, hence lies outside the component —
so `p ∩ q` cannot equal the component. -/

/-- Single-variable-generated monomial ideals are irreducible.  Concrete form:
if two up-set predicates `p`, `q` intersect pointwise to `mem`, and `p` holds
at `u` with `f u = 0` while `q` holds at `v` with `f v = 0`, then `False`.
`mem` is the component's membership predicate, `f` the relevant exponent;
`hmem` says membership is `f e ≥ 1`, `hadd` says `f` is additive on
componentwise sums. -/
theorem strict_split_false
    (mem : Mono → Bool) (f : Mono → Nat)
    (hmem : ∀ e, mem e = ble1 (f e))
    (hadd : ∀ u v, f (u.1 + v.1, u.2.1 + v.2.1, u.2.2 + v.2.2) = f u + f v)
    (p q : Mono → Bool)
    (hp : UpSet p) (hq : UpSet q)
    (hinter : ∀ e, (p e && q e) = mem e)
    (u : Mono) (hpu : p u = true) (hfu : f u = 0)
    (v : Mono) (hqv : q v = true) (hfv : f v = 0) : False := by
  have hle1 : Le3 u (u.1 + v.1, u.2.1 + v.2.1, u.2.2 + v.2.2) :=
    ⟨Nat.le_add_right _ _, Nat.le_add_right _ _, Nat.le_add_right _ _⟩
  have hle2 : Le3 v (u.1 + v.1, u.2.1 + v.2.1, u.2.2 + v.2.2) :=
    ⟨Nat.le_add_left _ _, Nat.le_add_left _ _, Nat.le_add_left _ _⟩
  have hpw : p (u.1 + v.1, u.2.1 + v.2.1, u.2.2 + v.2.2) = true :=
    hp _ _ hpu hle1
  have hqw : q (u.1 + v.1, u.2.1 + v.2.1, u.2.2 + v.2.2) = true :=
    hq _ _ hqv hle2
  have h9 := hinter (u.1 + v.1, u.2.1 + v.2.1, u.2.2 + v.2.2)
  rw [hpw, hqw, hmem, hadd u v, hfu, hfv] at h9
  exact absurd h9 (by decide)

/-- Irreducibility of `(x)`: no two strict monomial super-ideals intersect
pointwise to `(x)`. -/
def Xirreducible : Prop :=
  ¬ ∃ (p q : Mono → Bool),
    UpSet p ∧ UpSet q ∧
    (∀ e, (p e && q e) = memX e) ∧
    (∃ u, p u = true ∧ u.1 = 0) ∧
    (∃ v, q v = true ∧ v.1 = 0)

/-- `(x)` is irreducible. -/
theorem memX_irreducible : Xirreducible :=
  fun h =>
    Exists.elim h fun p hl1 =>
      Exists.elim hl1 fun q hl2 =>
        Exists.elim hl2.2.2.2.1 fun u hu =>
          Exists.elim hl2.2.2.2.2 fun v hv =>
            strict_split_false memX (fun e => e.1) (fun _ => rfl)
              (fun _ _ => rfl) p q hl2.1 hl2.2.1 hl2.2.2.1 u hu.1 hu.2 v hv.1 hv.2

/-- Irreducibility of `(y)`: no two strict monomial super-ideals intersect
pointwise to `(y)`. -/
def Yirreducible : Prop :=
  ¬ ∃ (p q : Mono → Bool),
    UpSet p ∧ UpSet q ∧
    (∀ e, (p e && q e) = memY e) ∧
    (∃ u, p u = true ∧ u.2.1 = 0) ∧
    (∃ v, q v = true ∧ v.2.1 = 0)

/-- `(y)` is irreducible. -/
theorem memY_irreducible : Yirreducible :=
  fun h =>
    Exists.elim h fun p hl1 =>
      Exists.elim hl1 fun q hl2 =>
        Exists.elim hl2.2.2.2.1 fun u hu =>
          Exists.elim hl2.2.2.2.2 fun v hv =>
            strict_split_false memY (fun e => e.2.1) (fun _ => rfl)
              (fun _ _ => rfl) p q hl2.1 hl2.2.1 hl2.2.2.1 u hu.1 hu.2 v hv.1 hv.2

/-- Irreducibility of `(z)`: no two strict monomial super-ideals intersect
pointwise to `(z)`. -/
def Zirreducible : Prop :=
  ¬ ∃ (p q : Mono → Bool),
    UpSet p ∧ UpSet q ∧
    (∀ e, (p e && q e) = memZ e) ∧
    (∃ u, p u = true ∧ u.2.2 = 0) ∧
    (∃ v, q v = true ∧ v.2.2 = 0)

/-- `(z)` is irreducible. -/
theorem memZ_irreducible : Zirreducible :=
  fun h =>
    Exists.elim h fun p hl1 =>
      Exists.elim hl1 fun q hl2 =>
        Exists.elim hl2.2.2.2.1 fun u hu =>
          Exists.elim hl2.2.2.2.2 fun v hv =>
            strict_split_false memZ (fun e => e.2.2) (fun _ => rfl)
              (fun _ _ => rfl) p q hl2.1 hl2.2.1 hl2.2.2.1 u hu.1 hu.2 v hv.1 hv.2

/-! ### `β₀((xyz)) = 1` -/

/-- `(xyz)` is generated by the single monomial `xyz = (1,1,1)`. -/
theorem generated_by_one : ∃ g : Mono, ∀ e, memI e = true ↔ Le3 g e := by
  refine ⟨(1, 1, 1), fun e => ?_⟩
  constructor
  · intro h
    have hc : (ble1 e.1 && (ble1 e.2.1 && ble1 e.2.2)) = true := h
    have h1 : ble1 e.1 = true := band_eq_left hc
    have h23 : (ble1 e.2.1 && ble1 e.2.2) = true := band_eq_right hc
    exact ⟨le_of_ble1 h1, le_of_ble1 (band_eq_left h23),
      le_of_ble1 (band_eq_right h23)⟩
  · intro h
    have h1 := ble1_true h.1
    have h2 := ble1_true h.2.1
    have h3 := ble1_true h.2.2
    show (ble1 e.1 && (ble1 e.2.1 && ble1 e.2.2)) = true
    rw [h1, h2, h3]
    rfl

/-- `(xyz)` is not the zero ideal (`xyz ∈ (xyz)`), so it cannot be generated
by zero monomials; with `generated_by_one` this gives `β₀((xyz)) = 1`. -/
theorem nonempty : memI (1, 1, 1) = true := rfl

/-! ### The attack numbers -/

/-- Number of components of the irredundant irreducible decomposition
`(xyz) = (x) ∩ (y) ∩ (z)`. -/
def iota : Nat := 3

/-- Minimal number of monomial generators of `(xyz)`. -/
def beta0 : Nat := 1

/-- The attack numbers: `3 > 1`. -/
theorem iota_gt_beta0 : beta0 < iota := by decide

/-- Main packaging of the attack: decomposition, irredundancy (three
witnesses), irreducibility of the three components, `β₀ = 1` (one generator,
nonzero ideal), and the numeric conclusion `3 > 1`. -/
theorem main :
    (∀ e, memI e = (memX e && (memY e && memZ e)))
    ∧ (((memY (0, 1, 1) && memZ (0, 1, 1)) = true) ∧ memI (0, 1, 1) = false)
    ∧ (((memX (1, 0, 1) && memZ (1, 0, 1)) = true) ∧ memI (1, 0, 1) = false)
    ∧ (((memX (1, 1, 0) && memY (1, 1, 0)) = true) ∧ memI (1, 1, 0) = false)
    ∧ Xirreducible
    ∧ Yirreducible
    ∧ Zirreducible
    ∧ (∃ g : Mono, ∀ e, memI e = true ↔ Le3 g e)
    ∧ (memI (1, 1, 1) = true)
    ∧ ((3 : Nat) > 1) :=
  ⟨decomposition_correct,
    ⟨component_x_needed,
    ⟨component_y_needed,
    ⟨component_z_needed,
    ⟨memX_irreducible,
    ⟨memY_irreducible,
    ⟨memZ_irreducible,
    ⟨generated_by_one,
    ⟨nonempty, by decide⟩⟩⟩⟩⟩⟩⟩⟩⟩
