import Mathlib

/-!
# Conjecture 00000002058 is false

An algebra `A` is *equationally Noetherian* if every system of equations over `A`
(in finitely many unknowns) is equivalent to a finite subsystem: some finite
subsystem has the same solution set. Conjecture 00000002058 asserts that the matrix
algebra `M_n(K)` is equationally Noetherian if and only if `n ≤ 2`, and in particular
that `M₃(K)` is not.

In fact `M_n(K)` is equationally Noetherian for every `n` and every field `K`. An
equation in unknowns `X₁, …, X_k` is a noncommutative polynomial in the unknowns with
constants from `M_n(K)`. Evaluated at matrices, each of its `n²` entries is a
commutative polynomial in the `k n²` entries of the unknowns; this is the "generic
matrix" `G`. A system `S` therefore has the same solutions as the system of
polynomial equations `{G(p)ᵢⱼ = 0 : p ∈ S}`. By Hilbert's basis theorem, the ideal
these polynomials generate is generated by finitely many of them, so finitely many
equations of `S` already cut out the same set.
-/

namespace Submission00000002058

open MvPolynomial

variable (K : Type*) [Field K] (n k : ℕ)

/-- An equation over `M_n(K)` in `k` unknowns: a noncommutative polynomial with
coefficients in `K` in the unknowns `inl l` (`l < k`) and in constants `inr A`, one
for each matrix `A ∈ M_n(K)`. -/
abbrev Equation := FreeAlgebra K (Fin k ⊕ Matrix (Fin n) (Fin n) K)

/-- The value of an equation at a tuple of matrices `X`: unknowns are replaced by `X`,
and each constant `inr A` by `A` itself. -/
def value {K : Type*} [Field K] {n k : ℕ} (X : Fin k → Matrix (Fin n) (Fin n) K) :
    Equation K n k →ₐ[K] Matrix (Fin n) (Fin n) K :=
  FreeAlgebra.lift K (Sum.elim X id)

/-- The solution set (algebraic set) of a system `S` of equations. -/
def solutions {K : Type*} [Field K] {n k : ℕ} (S : Set (Equation K n k)) :
    Set (Fin k → Matrix (Fin n) (Fin n) K) :=
  {X | ∀ p ∈ S, value X p = 0}

/-- `M_n(K)` is equationally Noetherian: every system of equations, in any finite
number of unknowns, has a finite subsystem with the same solution set. -/
def EqNoetherian : Prop :=
  ∀ (k : ℕ) (S : Set (Equation K n k)), ∃ S₀ ⊆ S, S₀.Finite ∧ solutions S₀ = solutions S

/-- Conjecture 00000002058: algebraic sets over `M_n(K)` are Noetherian if and only if
`n ≤ 2`. -/
def ConjectureHolds : Prop :=
  ∀ (K : Type) [Field K] (n : ℕ), EqNoetherian K n ↔ n ≤ 2

/-! ## Generic matrices -/

/-- The entries of a `k`-tuple of `n × n` matrices, as a point of `K^(k n²)`. -/
def coords {K : Type*} {n k : ℕ} (X : Fin k → Matrix (Fin n) (Fin n) K) :
    Fin k × Fin n × Fin n → K :=
  fun c => X c.1 c.2.1 c.2.2

/-- The generic matrix of an equation: its entries are commutative polynomials in the
entries of the unknowns. -/
noncomputable def generic :
    Equation K n k →ₐ[K] Matrix (Fin n) (Fin n) (MvPolynomial (Fin k × Fin n × Fin n) K) :=
  FreeAlgebra.lift K (Sum.elim (fun l => Matrix.of fun i j => X (l, i, j))
    (fun A => A.map (algebraMap K _)))

/-- Evaluating the generic matrix at the entries of `X` gives the value of the
equation at `X`. -/
theorem generic_eval (X : Fin k → Matrix (Fin n) (Fin n) K) (p : Equation K n k) (i j : Fin n) :
    eval (coords X) (generic K n k p i j) = value X p i j := by
  have h : (aeval (coords X)).mapMatrix.comp (generic K n k) = value X := by
    refine FreeAlgebra.hom_ext ?_
    funext v
    rcases v with l | A
    · ext i j
      simp [generic, value, coords]
    · ext i j
      simp [generic, value]
  have := congrArg (fun φ => φ p i j) h
  simpa [coe_aeval_eq_eval] using this

/-! ## Hilbert's basis theorem gives the finite subsystem -/

theorem eqNoetherian : EqNoetherian K n := by
  intro k S
  -- the polynomial system attached to `S`
  set T : Set (MvPolynomial (Fin k × Fin n × Fin n) K) :=
    {t | ∃ p ∈ S, ∃ i j, generic K n k p i j = t} with hT
  obtain ⟨T₀, hT₀T, hspan⟩ :=
    (Submodule.fg_span_iff_fg_span_finset_subset
      (R := MvPolynomial (Fin k × Fin n × Fin n) K) T).1
      (IsNoetherian.noetherian (Submodule.span (MvPolynomial (Fin k × Fin n × Fin n) K) T))
  have hchoose : ∀ t ∈ (T₀ : Set _), ∃ p ∈ S, ∃ i j, generic K n k p i j = t :=
    fun t ht => hT₀T ht
  choose! g hgS hgij using hchoose
  refine ⟨g '' T₀, ?_, (T₀.finite_toSet.image g), ?_⟩
  · rintro _ ⟨t, ht, rfl⟩
    exact hgS t ht
  · apply Set.Subset.antisymm
    · -- a common zero of the finitely many chosen equations kills the whole ideal
      intro X hX p hp
      have hker : Ideal.span (T₀ : Set _) ≤ RingHom.ker (eval (coords X)) := by
        rw [Ideal.span_le]
        intro t ht
        obtain ⟨i, j, hij⟩ := hgij t ht
        rw [SetLike.mem_coe, RingHom.mem_ker, ← hij, generic_eval]
        have := hX (g t) ⟨t, ht, rfl⟩
        rw [this]
        rfl
      ext i j
      have hmem : generic K n k p i j ∈ Ideal.span (T₀ : Set _) := by
        have : generic K n k p i j ∈ Ideal.span T := Ideal.subset_span ⟨p, hp, i, j, rfl⟩
        rwa [Ideal.span, hspan] at this
      have := hker hmem
      rw [RingHom.mem_ker, generic_eval] at this
      simpa using this
    · intro X hX p hp
      obtain ⟨t, ht, rfl⟩ := hp
      exact hX (g t) (hgS t ht)

/-- Conjecture 00000002058 is false: `M₃(ℚ)` is equationally Noetherian. -/
theorem conjecture_00000002058_false : ¬ ConjectureHolds := by
  intro h
  have := (h ℚ 3).1 (eqNoetherian ℚ 3)
  omega

end Submission00000002058

#print axioms Submission00000002058.conjecture_00000002058_false
