import Std

namespace Conjecture8656
universe u v
set_option maxRecDepth 100000
set_option maxHeartbeats 10000000

/-- Ordinary groups, with no extra identities imposed. -/
structure Group (A : Type u) where
  mul : A → A → A
  one : A
  inv : A → A
  assoc : ∀ a b c, mul (mul a b) c = mul a (mul b c)
  one_mul : ∀ a, mul one a = a
  mul_one : ∀ a, mul a one = a
  inv_mul : ∀ a, mul (inv a) a = one
  mul_inv : ∀ a, mul a (inv a) = one

abbrev Letter (A : Type u) := A × Bool
abbrev Word (A : Type u) := List (Letter A)
def flip {A : Type u} (x : Letter A) : Letter A := (x.1, !x.2)
@[simp] theorem flip_flip {A : Type u} (x : Letter A) : flip (flip x)=x := by
  cases x with | mk a b => cases b <;> rfl
def inverseWord {A : Type u} (w : Word A) : Word A := (w.map flip).reverse
@[simp] theorem inverse_append {A : Type u} (w z : Word A) :
    inverseWord (w++z)=inverseWord z++inverseWord w := by
  simp [inverseWord]
@[simp] theorem inverse_inverse {A : Type u} (w : Word A) : inverseWord (inverseWord w)=w := by
  simp [inverseWord, List.map_reverse, List.map_map, Function.comp_def]

/-- The congruence generated by free cancellation, on ALL finite words. -/
inductive WordRel {A : Type u} : Word A → Word A → Prop
  | refl (w) : WordRel w w
  | symm {w z} : WordRel w z → WordRel z w
  | trans {w z t} : WordRel w z → WordRel z t → WordRel w t
  | append {w z t s} : WordRel w z → WordRel t s → WordRel (w++t) (z++s)
  | cancel (x : Letter A) : WordRel [x, flip x] []

def wordSetoid (A : Type u) : Setoid (Word A) where
  r := WordRel
  iseqv := ⟨WordRel.refl, WordRel.symm, WordRel.trans⟩
abbrev Free (A : Type u) := Quotient (wordSetoid A)
def ofWord {A : Type u} (w : Word A) : Free A := Quotient.mk _ w
def freeMul {A : Type u} (x y : Free A) : Free A :=
  Quotient.liftOn₂ x y (fun w z => ofWord (w++z))
    (fun _ _ _ _ h k => Quotient.sound (WordRel.append h k))

theorem inverse_respects {A : Type u} {w z : Word A} (h : WordRel w z) :
    WordRel (inverseWord w) (inverseWord z) := by
  induction h with
  | refl w => exact WordRel.refl _
  | symm _ ih => exact WordRel.symm ih
  | trans _ _ ih ik => exact WordRel.trans ih ik
  | append _ _ ih ik => simpa using WordRel.append ik ih
  | cancel x => simpa [inverseWord] using WordRel.cancel x
def freeInv {A : Type u} (x : Free A) : Free A :=
  Quotient.liftOn x (fun w => ofWord (inverseWord w))
    (fun _ _ h => Quotient.sound (inverse_respects h))
theorem contextual {A : Type u} {w z : Word A} (h : WordRel w z) (p s : Word A) :
    WordRel ((p++w)++s) ((p++z)++s) :=
  WordRel.append (WordRel.append (WordRel.refl p) h) (WordRel.refl s)
theorem word_mul_inverse {A : Type u} (w : Word A) : WordRel (w++inverseWord w) [] := by
  induction w with
  | nil => exact WordRel.refl []
  | cons x w ih =>
    have h : WordRel ((x::w)++inverseWord (x::w)) [x,flip x] := by
      simpa [inverseWord, List.append_assoc] using contextual ih [x] [flip x]
    exact WordRel.trans h (WordRel.cancel x)
theorem word_inverse_mul {A : Type u} (w : Word A) : WordRel (inverseWord w++w) [] := by
  simpa using word_mul_inverse (inverseWord w)

def freeGroup (A : Type u) : Group (Free A) where
  mul := freeMul
  one := ofWord []
  inv := freeInv
  assoc := by
    intro x y z
    refine Quotient.inductionOn₃ x y z ?_
    intro w t s
    change ofWord ((w++t)++s)=ofWord (w++(t++s))
    rw [List.append_assoc]
  one_mul := by
    intro x; refine Quotient.inductionOn x ?_; intro w; rfl
  mul_one := by
    intro x; refine Quotient.inductionOn x ?_; intro w
    change ofWord (w++[])=ofWord w
    rw [List.append_nil]
  inv_mul := by
    intro x; refine Quotient.inductionOn x ?_; intro w
    exact Quotient.sound (word_inverse_mul w)
  mul_inv := by
    intro x; refine Quotient.inductionOn x ?_; intro w
    exact Quotient.sound (word_mul_inverse w)

/-- The universal property establishes that this is the genuine free group. -/
def letterEval {A : Type u} {B : Type v} (G : Group B) (f : A → B) (x : Letter A) : B :=
  if x.2 then G.inv (f x.1) else f x.1
def eval {A : Type u} {B : Type v} (G : Group B) (f : A → B) : Word A → B
  | [] => G.one
  | x::w => G.mul (letterEval G f x) (eval G f w)
theorem eval_append {A : Type u} {B : Type v} (G : Group B) (f : A → B) (w z : Word A) :
    eval G f (w++z)=G.mul (eval G f w) (eval G f z) := by
  induction w with
  | nil => exact (G.one_mul _).symm
  | cons x w ih => simp only [List.cons_append, eval, ih, G.assoc]
theorem eval_respects {A : Type u} {B : Type v} (G : Group B) (f : A → B)
    {w z : Word A} (h : WordRel w z) : eval G f w=eval G f z := by
  induction h with
  | refl w => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih ik => exact ih.trans ik
  | append _ _ ih ik => simp only [eval_append, ih, ik]
  | cancel x =>
    cases x with
    | mk a b => cases b <;> simp [eval, letterEval, flip, G.mul_one, G.mul_inv, G.inv_mul]
def lift {A : Type u} {B : Type v} (G : Group B) (f : A → B) (x : Free A) : B :=
  Quotient.liftOn x (eval G f) (fun _ _ h => eval_respects G f h)

def Hom {A : Type u} {B : Type v} (G : Group A) (H : Group B) (f : A → B) : Prop :=
  f G.one=H.one ∧ ∀ x y, f (G.mul x y)=H.mul (f x) (f y)
theorem inverse_unique {B : Type v} (G : Group B) {x y : B}
    (h : G.mul y x=G.one) : y=G.inv x := by
  calc
    y = G.mul y G.one := (G.mul_one y).symm
    _ = G.mul y (G.mul x (G.inv x)) := congrArg (G.mul y) (G.mul_inv x).symm
    _ = G.mul (G.mul y x) (G.inv x) := (G.assoc _ _ _).symm
    _ = G.inv x := by rw [h, G.one_mul]
theorem hom_preserves_inverse {A : Type u} {B : Type v} (G : Group A) (H : Group B)
    (f : A → B) (hf : Hom G H f) (x : A) : f (G.inv x)=H.inv (f x) := by
  apply inverse_unique H
  rw [← hf.2, G.inv_mul, hf.1]
theorem lift_hom {A : Type u} {B : Type v} (G : Group B) (f : A → B) :
    Hom (freeGroup A) G (lift G f) := by
  refine ⟨rfl, ?_⟩
  intro x y
  refine Quotient.inductionOn₂ x y ?_
  exact eval_append G f
def generator {A : Type u} (a : A) : Free A := ofWord [(a,false)]
theorem lift_generators {A : Type u} {B : Type v} (G : Group B) (f : A → B) (a : A) :
    lift G f (generator a)=f a := G.mul_one _
theorem hom_determined {A : Type u} {B : Type v} (G : Group B) (f : A → B)
    (h : Free A → B) (hh : Hom (freeGroup A) G h)
    (hg : ∀ a, h (generator a)=f a) : h=lift G f := by
  funext x
  refine Quotient.inductionOn x ?_
  intro w
  induction w with
  | nil => exact hh.1
  | cons x w ih =>
    change h (freeMul (ofWord [x]) (ofWord w)) = G.mul (letterEval G f x) (eval G f w)
    have hm := hh.2 (ofWord [x]) (ofWord w)
    change h (freeMul (ofWord [x]) (ofWord w)) = G.mul (h (ofWord [x])) (h (ofWord w)) at hm
    change h (ofWord w)=eval G f w at ih
    rw [hm, ih]
    apply congrArg (fun z => G.mul z (eval G f w))
    cases x with
    | mk a b =>
      cases b
      · exact hg a
      · have hi := hom_preserves_inverse (freeGroup A) G h hh (generator a)
        change h (ofWord [(a,true)]) = G.inv (h (generator a)) at hi
        exact hi.trans (congrArg G.inv (hg a))
theorem free_universal_property {A : Type u} {B : Type v} (G : Group B) (f : A → B) :
    ∃ h : Free A → B, Hom (freeGroup A) G h ∧ (∀ a, h (generator a)=f a) ∧
      ∀ k : Free A → B, Hom (freeGroup A) G k → (∀ a, k (generator a)=f a) → k=h :=
  ⟨lift G f, lift_hom G f, lift_generators G f, fun k hk hg => hom_determined G f k hk hg⟩

structure Automorphism {A : Type u} (G : Group A) where
  toFun : A → A
  invFun : A → A
  left_inv : ∀ x, invFun (toFun x)=x
  right_inv : ∀ x, toFun (invFun x)=x
  hom : Hom G G toFun
def identityAut {A : Type u} (G : Group A) : Automorphism G where
  toFun := id
  invFun := id
  left_inv := fun _ => rfl
  right_inv := fun _ => rfl
  hom := ⟨rfl, fun _ _ => rfl⟩
theorem aut_injective {A : Type u} {G : Group A} (p : Automorphism G)
    {x y : A} (h : p.toFun x=p.toFun y) : x=y := by
  have hi := congrArg p.invFun h
  simpa only [p.left_inv] using hi

/-- A signed permutation of the basis: invert EACH basis letter separately.
    This is an automorphism even in rank at least two, not group inversion. -/
def renameWord {A : Type u} (w : Word A) : Word A := w.map flip
theorem rename_respects {A : Type u} {w z : Word A} (h : WordRel w z) :
    WordRel (renameWord w) (renameWord z) := by
  induction h with
  | refl w => exact WordRel.refl _
  | symm _ ih => exact WordRel.symm ih
  | trans _ _ ih ik => exact WordRel.trans ih ik
  | append _ _ ih ik => simpa [renameWord] using WordRel.append ih ik
  | cancel x => simpa [renameWord] using WordRel.cancel (flip x)
def rename {A : Type u} (x : Free A) : Free A :=
  Quotient.liftOn x (fun w => ofWord (renameWord w))
    (fun _ _ h => Quotient.sound (rename_respects h))
theorem rename_involution {A : Type u} (x : Free A) : rename (rename x)=x := by
  refine Quotient.inductionOn x ?_
  intro w
  change ofWord (renameWord (renameWord w))=ofWord w
  simp [renameWord, List.map_map, Function.comp_def]
theorem rename_hom {A : Type u} : Hom (freeGroup A) (freeGroup A) (@rename A) := by
  refine ⟨rfl, ?_⟩
  intro x y
  refine Quotient.inductionOn₂ x y ?_
  intro w z
  change ofWord (renameWord (w++z)) = ofWord (renameWord w++renameWord z)
  simp [renameWord]
def renameAut (A : Type u) : Automorphism (freeGroup A) where
  toFun := rename
  invFun := rename
  left_inv := rename_involution
  right_inv := rename_involution
  hom := rename_hom
theorem signed_permutation_length {A : Type u} (w : Word A) :
    (renameWord w).length=w.length := by simp [renameWord]

def integerGroup : Group Int where
  mul := Int.add
  one := 0
  inv := Int.neg
  assoc := Int.add_assoc
  one_mul := Int.zero_add
  mul_one := Int.add_zero
  inv_mul := by intro a; change -a+a=0; omega
  mul_inv := by intro a; change a+ -a=0; omega
def exponent {A : Type u} : Free A → Int := lift integerGroup (fun _ => 1)
theorem generator_nonidentity {A : Type u} (a : A) : generator a ≠ (freeGroup A).one := by
  intro h
  have he := congrArg (@exponent A) h
  change (1 : Int)=0 at he
  omega
theorem inverse_generator_distinct {A : Type u} (a : A) :
    ofWord [(a,false)] ≠ ofWord [(a,true)] := by
  intro h
  have he := congrArg (@exponent A) h
  change (1 : Int) = -1 at he
  omega

def InOrbit {A : Type u} (g h : Free A) : Prop :=
  ∃ p : Automorphism (freeGroup A), p.toFun g=h
/-- Minimal among ALL representatives of ALL elements in the automorphism
    orbit; this also implies minimal reduced-word length. -/
def MinimalWord {A : Type u} (g : Free A) (w : Word A) : Prop :=
  InOrbit g (ofWord w) ∧ ∀ z : Word A, InOrbit g (ofWord z) → w.length ≤ z.length
theorem orbit_words_nonempty {A : Type u} {g : Free A} (hg : g≠(freeGroup A).one)
    (w : Word A) (hw : InOrbit g (ofWord w)) : w≠[] := by
  intro he
  subst w
  rcases hw with ⟨p, hp⟩
  apply hg
  exact aut_injective p (hp.trans p.hom.1.symm)
theorem one_letter_minimal {A : Type u} {g : Free A} (hg : g≠(freeGroup A).one)
    (x : Letter A) (hx : InOrbit g (ofWord [x])) : MinimalWord g [x] := by
  refine ⟨hx, ?_⟩
  intro w hw
  have hpos := List.length_pos_iff.mpr (orbit_words_nonempty hg w hw)
  change 1 ≤ w.length
  omega

abbrev Basis := Fin 2
def positive : Word Basis := [(0,false)]
def negative : Word Basis := [(0,true)]
def start : Free Basis := generator 0
def Reduced {A : Type u} : Word A → Prop
  | [] => True
  | [_] => True
  | x::y::w => y≠flip x ∧ Reduced (y::w)
theorem both_words_reduced : Reduced positive ∧ Reduced negative := ⟨True.intro, True.intro⟩
theorem positive_minimal : MinimalWord start positive := by
  apply one_letter_minimal (generator_nonidentity (0 : Basis))
  exact ⟨identityAut (freeGroup Basis), rfl⟩
theorem negative_minimal : MinimalWord start negative := by
  apply one_letter_minimal (generator_nonidentity (0 : Basis))
  exact ⟨renameAut Basis, rfl⟩
def UniqueMinimum (g : Free Basis) : Prop :=
  ∀ w z : Word Basis, MinimalWord g w → MinimalWord g z → ofWord w=ofWord z
theorem conjecture8656_counterexample :
    MinimalWord start positive ∧ MinimalWord start negative ∧
    ofWord positive≠ofWord negative ∧ positive.length=1 ∧ negative.length=1 ∧
    ¬UniqueMinimum start := by
  refine ⟨positive_minimal, negative_minimal, inverse_generator_distinct 0, rfl, rfl, ?_⟩
  intro hu
  exact inverse_generator_distinct (0 : Basis) (hu positive negative positive_minimal negative_minimal)

end Conjecture8656
#print axioms Conjecture8656.free_universal_property
#print axioms Conjecture8656.conjecture8656_counterexample
