import Mathlib

/-!
# Conjecture 00000002416 (disproved)

Conjecture: "The spectrum of the minimal number of generators of open subgroups of `G_ℚ` is `{2, 3}`; ..."

Here `G_ℚ = Gal(ℚ̄/ℚ)` is Mathlib's `Field.absoluteGaloisGroup ℚ` (the automorphism group of
`AlgebraicClosure ℚ` over `ℚ`) with its Krull topology. A subset `s` of a topological group `H`
*topologically generates* `H` if the subgroup generated by `s` is dense in `H`; the minimal number of
generators `minGen H : ℕ∞` is the least cardinality of a finite topological generating set (`⊤` if there is
none). For an open subgroup `U` we use the subspace topology on `U`.

We prove that **no open subgroup of `G_ℚ` is topologically finitely generated**, so every open subgroup has
`minGen = ⊤`; the spectrum is `{⊤}` and in particular is not `{2, 3}`. Since abstract generation implies
topological generation, no open subgroup is abstractly finitely generated either.

Proof: for each prime `p` let `√p ∈ ℚ̄` be a square root of `p` and `χ_p(σ) = ±1` according as
`σ(√p) = ±√p`. Each `χ_p` is a homomorphism `G_ℚ →* ℤˣ` with open kernel (it contains `Gal(ℚ̄/ℚ(√p))`).
If `χ_p = χ_q` then `√p·√q` is fixed by all of `G_ℚ`, hence rational, so `pq` is a rational square and
`p = q`. A homomorphism with open kernel is determined by its values on a topological generating set, so a
finite topological generating set `t` would give an injection from the (infinite) primes into the finite
set `t → ℤˣ`. Finally, an open subgroup of the compact group `G_ℚ` has finitely many cosets, so a finite
topological generating set of it, together with coset representatives, topologically generates `G_ℚ`.
-/

open scoped Pointwise

namespace C2416

/- Instance plumbing: `AlgebraicClosure ℚ` carries two `ℚ`-algebra structures that are equal but not
reducibly so (the generic `AlgebraicClosure.instAlgebra`, used in `Field.absoluteGaloisGroup ℚ`, and
`DivisionRing.toRatAlgebra`). We make the former the preferred one in this file. -/
attribute [local instance 2000] AlgebraicClosure.instAlgebra

/-! ## Topological generation and the generator spectrum -/

/-- `s` topologically generates the topological group `H`: the subgroup generated by `s` is dense. -/
def TopGenerates {H : Type*} [Group H] [TopologicalSpace H] (s : Set H) : Prop :=
  Dense (Subgroup.closure s : Set H)

/-- The minimal number of topological generators of `H`, in `ℕ∞`: the least cardinality of a finite
topological generating set, and `⊤` if `H` is not topologically finitely generated. -/
noncomputable def minGen (H : Type*) [Group H] [TopologicalSpace H] : ℕ∞ :=
  ⨅ (s : Finset H) (_ : TopGenerates (s : Set H)), (s.card : ℕ∞)

/-- The spectrum of minimal numbers of generators of open subgroups of `G` (each open subgroup `U`
carries the subspace topology). -/
def genSpectrum (G : Type*) [Group G] [TopologicalSpace G] : Set ℕ∞ :=
  {d | ∃ U : Subgroup G, IsOpen (U : Set G) ∧ minGen U = d}

/-! ## Two general lemmas on topological groups -/

/-- In a compact topological group, if an open subgroup `U` is topologically finitely generated then so
is the whole group (add finitely many coset representatives). -/
theorem topFG_of_open {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [CompactSpace G] (U : Subgroup G) (hU : IsOpen (U : Set G)) (s : Finset U)
    (hs : TopGenerates (s : Set U)) : ∃ t : Finset G, TopGenerates (t : Set G) := by
  classical
  obtain ⟨R, hR⟩ := isCompact_univ.elim_finite_subcover (fun g : G => g • (U : Set G))
    (fun g => hU.smul g) (fun x _ => Set.mem_iUnion.2 ⟨x, ⟨1, U.one_mem, mul_one x⟩⟩)
  refine ⟨s.map (Function.Embedding.subtype _) ∪ R, ?_⟩
  set H := Subgroup.closure (((s.map (Function.Embedding.subtype _) ∪ R : Finset G)) : Set G)
  have hsH : (Subgroup.closure (s : Set U)).map U.subtype ≤ H := by
    rw [MonoidHom.map_closure]
    apply Subgroup.closure_mono
    rintro _ ⟨x, hx, rfl⟩
    exact Finset.mem_coe.2 (Finset.mem_union_left _ (Finset.mem_map_of_mem _ (Finset.mem_coe.1 hx)))
  have hUH : ∀ u ∈ U, u ∈ H.topologicalClosure := by
    intro u hu
    have h1 : (⟨u, hu⟩ : U) ∈ closure (Subgroup.closure (s : Set U) : Set U) := hs ⟨u, hu⟩
    have h2 := map_mem_closure continuous_subtype_val h1
      (t := (H : Set G)) (fun x hx => hsH ⟨x, hx, rfl⟩)
    rw [← Subgroup.topologicalClosure_coe] at h2
    exact h2
  intro g
  rw [← Subgroup.topologicalClosure_coe]
  obtain ⟨r, hr, hgr⟩ := Set.mem_iUnion₂.1 (hR (Set.mem_univ g))
  obtain ⟨u, hu, rfl⟩ := hgr
  have hrH : r ∈ H.topologicalClosure :=
    H.le_topologicalClosure (Subgroup.subset_closure (by simp [hr]))
  exact H.topologicalClosure.mul_mem hrH (hUH u hu)

/-- Two homomorphisms with open kernels that agree on a topological generating set are equal. -/
theorem eq_of_eqOn_gen {G M : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [Group M]
    {s : Set G} (hs : TopGenerates s) (f g : G →* M) (hf : IsOpen (f.ker : Set G))
    (hg : IsOpen (g.ker : Set G)) (h : ∀ x ∈ s, f x = g x) : f = g := by
  have hE : IsOpen (f.eqLocus g : Set G) := by
    refine Subgroup.isOpen_mono (H₁ := f.ker ⊓ g.ker) ?_ (hf.inter hg)
    intro x hx
    simp only [Subgroup.mem_inf, MonoidHom.mem_ker] at hx
    show f x = g x
    rw [hx.1, hx.2]
  have hEc : IsClosed (f.eqLocus g : Set G) := Subgroup.isClosed_of_isOpen _ hE
  have hle : Subgroup.closure s ≤ f.eqLocus g := (Subgroup.closure_le _).2 h
  ext x
  have hx : x ∈ closure (Subgroup.closure s : Set G) := hs x
  exact (closure_minimal hle hEc) hx

/-! ## Quadratic characters of `Gal(ℚ̄/ℚ)` -/

local notation "Qbar" => AlgebraicClosure ℚ

/-- A chosen square root of `n` in `ℚ̄`. -/
noncomputable def sqrtQ (n : ℕ) : Qbar :=
  Classical.choose (IsAlgClosed.exists_pow_nat_eq ((n : ℚ) : Qbar) (n := 2) two_pos)

theorem sqrtQ_sq (n : ℕ) : sqrtQ n ^ 2 = (n : Qbar) := by
  have := Classical.choose_spec (IsAlgClosed.exists_pow_nat_eq ((n : ℚ) : Qbar) (n := 2) two_pos)
  simpa [sqrtQ] using this

theorem sqrtQ_ne_zero {n : ℕ} (hn : n ≠ 0) : sqrtQ n ≠ 0 := by
  intro h
  have := sqrtQ_sq n
  rw [h] at this
  simp at this
  exact hn (by exact_mod_cast this.symm)

theorem sqrtQ_ne_neg {n : ℕ} (hn : n ≠ 0) : sqrtQ n ≠ -sqrtQ n := by
  intro h
  have h2 : (2 : Qbar) * sqrtQ n = 0 := by linear_combination h
  rcases mul_eq_zero.1 h2 with h2 | h2
  · exact two_ne_zero h2
  · exact sqrtQ_ne_zero hn h2

theorem apply_sqrtQ (n : ℕ) (σ : Qbar ≃ₐ[ℚ] Qbar) : σ (sqrtQ n) = sqrtQ n ∨ σ (sqrtQ n) = -sqrtQ n := by
  apply sq_eq_sq_iff_eq_or_eq_neg.1
  rw [← map_pow, sqrtQ_sq]
  simp

open Classical in
/-- The quadratic character `χ_n(σ) = σ(√n)/√n ∈ {±1}`. -/
noncomputable def chi (n : ℕ) (σ : Qbar ≃ₐ[ℚ] Qbar) : ℤˣ := if σ (sqrtQ n) = sqrtQ n then 1 else -1

/-- For `n ≠ 0`, `χ_n` is a group homomorphism `Gal(ℚ̄/ℚ) →* ℤˣ`. -/
noncomputable def chiHom (n : ℕ) (hn : n ≠ 0) : (Qbar ≃ₐ[ℚ] Qbar) →* ℤˣ where
  toFun := chi n
  map_one' := by simp [chi]
  map_mul' σ τ := by
    have hne := sqrtQ_ne_neg hn
    have hne' : -sqrtQ n ≠ sqrtQ n := fun h => hne h.symm
    rcases apply_sqrtQ n τ with hτ | hτ <;> rcases apply_sqrtQ n σ with hσ | hσ <;>
      simp [chi, AlgEquiv.mul_apply, hτ, hσ, hne']

theorem chiHom_ker_isOpen (n : ℕ) (hn : n ≠ 0) :
    IsOpen ((chiHom n hn).ker : Set (Qbar ≃ₐ[ℚ] Qbar)) := by
  have hint : IsIntegral ℚ (sqrtQ n) := Algebra.IsIntegral.isIntegral _
  have := IntermediateField.adjoin.finiteDimensional hint
  refine Subgroup.isOpen_mono (H₁ := (IntermediateField.adjoin ℚ {sqrtQ n}).fixingSubgroup) ?_
    (IntermediateField.fixingSubgroup_isOpen _)
  intro σ hσ
  have : σ (sqrtQ n) = sqrtQ n :=
    (mem_fixingSubgroup_iff _).1 hσ _ (IntermediateField.mem_adjoin_simple_self ℚ (sqrtQ n))
  simp [MonoidHom.mem_ker, chiHom, chi, this]

/-- An element of `ℚ̄` fixed by every automorphism is rational. -/
theorem mem_range_of_fixed (x : Qbar) (hx : ∀ σ : Qbar ≃ₐ[ℚ] Qbar, σ x = x) :
    ∃ r : ℚ, algebraMap ℚ Qbar r = x := by
  have h := InfiniteGalois.fixedField_fixingSubgroup (⊥ : IntermediateField ℚ Qbar)
  have hmem : x ∈ IntermediateField.fixedField (⊥ : IntermediateField ℚ Qbar).fixingSubgroup :=
    (IntermediateField.mem_fixedField_iff _ _).2 fun σ _ => hx σ
  rw [h, IntermediateField.mem_bot] at hmem
  exact hmem

/-- The product of two distinct primes is not a square. -/
theorem not_isSquare_mul {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q) :
    ¬ IsSquare (p * q) := by
  rintro ⟨m, hm⟩
  have hpm : p ∣ m := hp.dvd_mul.1 (hm ▸ dvd_mul_right p q) |>.elim id id
  obtain ⟨k, rfl⟩ := hpm
  have : q = p * (k * k) := by
    apply Nat.eq_of_mul_eq_mul_left hp.pos
    rw [hm]; ring
  exact hpq ((Nat.prime_dvd_prime_iff_eq hp hq).1 ⟨_, this⟩)

/-- Distinct primes give distinct quadratic characters. -/
theorem chiHom_injective {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (h : chiHom p hp.ne_zero = chiHom q hq.ne_zero) : p = q := by
  by_contra hpq
  have hfix : ∀ σ : Qbar ≃ₐ[ℚ] Qbar, σ (sqrtQ p * sqrtQ q) = sqrtQ p * sqrtQ q := by
    intro σ
    have hσ : chi p σ = chi q σ := DFunLike.congr_fun h σ
    have hnp := sqrtQ_ne_neg hp.ne_zero
    have hnq := sqrtQ_ne_neg hq.ne_zero
    rw [map_mul]
    rcases apply_sqrtQ p σ with h1 | h1 <;> rcases apply_sqrtQ q σ with h2 | h2 <;>
      simp_all [chi, eq_comm (a := -sqrtQ p), eq_comm (a := -sqrtQ q)]
  obtain ⟨r, hr⟩ := mem_range_of_fixed _ hfix
  have hr2 : r ^ 2 = ((p * q : ℕ) : ℚ) := by
    apply (algebraMap ℚ Qbar).injective
    rw [map_pow, hr, mul_pow, sqrtQ_sq, sqrtQ_sq]
    simp
  exact not_isSquare_mul hp hq hpq (Rat.isSquare_natCast_iff.1 ⟨r, by rw [← hr2]; ring⟩)

/-! ## Main results -/

/-- `Gal(ℚ̄/ℚ)` is not topologically finitely generated. -/
theorem gal_not_topFG :
    ¬ ∃ t : Finset (Qbar ≃ₐ[ℚ] Qbar), TopGenerates (t : Set (Qbar ≃ₐ[ℚ] Qbar)) := by
  rintro ⟨t, ht⟩
  let F : Nat.Primes → (t → ℤˣ) := fun p x => chiHom p.1 p.2.ne_zero x.1
  have hF : Function.Injective F := by
    intro p q hpq
    apply Subtype.ext
    apply chiHom_injective p.2 q.2
    apply eq_of_eqOn_gen ht _ _ (chiHom_ker_isOpen _ _) (chiHom_ker_isOpen _ _)
    intro x hx
    exact congrFun hpq ⟨x, hx⟩
  have := Finite.of_injective F hF
  exact not_finite Nat.Primes

/-- `G_ℚ = Field.absoluteGaloisGroup ℚ` itself is not topologically finitely generated. -/
theorem absGal_not_topFG :
    ¬ ∃ t : Finset (Field.absoluteGaloisGroup ℚ), TopGenerates (t : Set (Field.absoluteGaloisGroup ℚ)) :=
  gal_not_topFG

/-- **No open subgroup of `G_ℚ` is topologically finitely generated.** -/
theorem open_subgroup_not_topFG (U : Subgroup (Field.absoluteGaloisGroup ℚ))
    (hU : IsOpen (U : Set (Field.absoluteGaloisGroup ℚ))) :
    ¬ ∃ s : Finset U, TopGenerates (s : Set U) := by
  rintro ⟨s, hs⟩
  have : CompactSpace (Field.absoluteGaloisGroup ℚ) :=
    inferInstanceAs (CompactSpace (Qbar ≃ₐ[ℚ] Qbar))
  exact absGal_not_topFG (topFG_of_open U hU s hs)

/-- No open subgroup of `G_ℚ` is (abstractly) finitely generated either. -/
theorem open_subgroup_not_fg (U : Subgroup (Field.absoluteGaloisGroup ℚ))
    (hU : IsOpen (U : Set (Field.absoluteGaloisGroup ℚ))) :
    ¬ ∃ s : Finset U, Subgroup.closure (s : Set U) = ⊤ := by
  rintro ⟨s, hs⟩
  refine open_subgroup_not_topFG U hU ⟨s, ?_⟩
  simp [TopGenerates, hs]

/-- Every open subgroup of `G_ℚ` has minimal number of topological generators `⊤` (infinite). -/
theorem minGen_open_subgroup (U : Subgroup (Field.absoluteGaloisGroup ℚ))
    (hU : IsOpen (U : Set (Field.absoluteGaloisGroup ℚ))) : minGen U = ⊤ := by
  simp only [minGen, iInf_eq_top]
  intro s hs
  exact absurd ⟨s, hs⟩ (open_subgroup_not_topFG U hU)

/-- The generator spectrum of `G_ℚ` is `{⊤}`. -/
theorem genSpectrum_absGal : genSpectrum (Field.absoluteGaloisGroup ℚ) = {⊤} := by
  ext d
  simp only [genSpectrum, Set.mem_ofPred_eq, Set.mem_singleton_iff]
  constructor
  · rintro ⟨U, hU, rfl⟩
    exact minGen_open_subgroup U hU
  · rintro rfl
    exact ⟨⊤, by simp, minGen_open_subgroup ⊤ (by simp)⟩

/-- The minimal number of *abstract* generators of a group `H`, in `ℕ∞` (`⊤` if not finitely
generated). -/
noncomputable def minGenAbs (H : Type*) [Group H] : ℕ∞ :=
  ⨅ (s : Finset H) (_ : Subgroup.closure (s : Set H) = ⊤), (s.card : ℕ∞)

/-- The spectrum of minimal numbers of abstract generators of open subgroups of `G`. -/
def genSpectrumAbs (G : Type*) [Group G] [TopologicalSpace G] : Set ℕ∞ :=
  {d | ∃ U : Subgroup G, IsOpen (U : Set G) ∧ minGenAbs U = d}

/-- With abstract generation the spectrum of `G_ℚ` is also `{⊤}`. -/
theorem genSpectrumAbs_absGal : genSpectrumAbs (Field.absoluteGaloisGroup ℚ) = {⊤} := by
  have key : ∀ U : Subgroup (Field.absoluteGaloisGroup ℚ),
      IsOpen (U : Set (Field.absoluteGaloisGroup ℚ)) → minGenAbs U = ⊤ := by
    intro U hU
    simp only [minGenAbs, iInf_eq_top]
    intro s hs
    exact absurd ⟨s, hs⟩ (open_subgroup_not_fg U hU)
  ext d
  simp only [genSpectrumAbs, Set.mem_ofPred_eq, Set.mem_singleton_iff]
  constructor
  · rintro ⟨U, hU, rfl⟩
    exact key U hU
  · rintro rfl
    exact ⟨⊤, by simp, key ⊤ (by simp)⟩

/-- **Conjecture 00000002416 is false**: the spectrum of minimal numbers of (topological) generators of
open subgroups of `G_ℚ` is not `{2, 3}`; indeed, neither `2` nor `3` occurs in it. -/
theorem conjecture_2416_false :
    genSpectrum (Field.absoluteGaloisGroup ℚ) ≠ {2, 3} ∧
    2 ∉ genSpectrum (Field.absoluteGaloisGroup ℚ) ∧ 3 ∉ genSpectrum (Field.absoluteGaloisGroup ℚ) := by
  rw [genSpectrum_absGal]
  refine ⟨fun h => ?_, by simp, by simp⟩
  have : (2 : ℕ∞) ∈ ({⊤} : Set ℕ∞) := h ▸ (by simp)
  simp at this

/-- The same with abstract (non-topological) generation. -/
theorem conjecture_2416_false_abstract :
    genSpectrumAbs (Field.absoluteGaloisGroup ℚ) ≠ {2, 3} ∧
    2 ∉ genSpectrumAbs (Field.absoluteGaloisGroup ℚ) ∧
    3 ∉ genSpectrumAbs (Field.absoluteGaloisGroup ℚ) := by
  rw [genSpectrumAbs_absGal]
  refine ⟨fun h => ?_, by simp, by simp⟩
  have : (2 : ℕ∞) ∈ ({⊤} : Set ℕ∞) := h ▸ (by simp)
  simp at this

end C2416
