import Mathlib

/-!
# Conjecture 00000000537 is false

The conjecture asserts: for bipartite graphs `G`, `depth R/I(G) ≥ ν(G) + 1`, where
`R = k[x_v : v ∈ V(G)]`, `I(G)` is the edge ideal and `ν(G)` is the matching number.

We refute it with the bipartite graph `K₂` (one edge on two vertices), over every field `k`:
`R/I(K₂) = k[x, y]/(x y)` has depth `≤ 1`, while `ν(K₂) = 1`, so `ν + 1 = 2 > depth`.

Conventions.
* `depth` is the depth with respect to the homogeneous maximal ideal `m = (x_v : v ∈ V)`:
  the supremum (in `ℕ∞`) of the lengths of `R/I(G)`-regular sequences of elements of `m`,
  where "regular" is Mathlib's `RingTheory.Sequence.IsRegular` (each element is a
  nonzerodivisor modulo the previous ones, and the quotient by all of them is nonzero).
* `ν(G)` is the supremum (in `ℕ∞`) of the number of edges of a matching of `G`.
* "bipartite" is Mathlib's `SimpleGraph.IsBipartite` (`G.Colorable 2`).
-/

open MvPolynomial RingTheory.Sequence Pointwise

namespace C537

/-- The edge ideal `I(G) ⊆ k[x_v : v ∈ V]`, generated by `x_u x_v` for the edges `uv` of `G`. -/
noncomputable def edgeIdeal (k : Type*) [Field k] {V : Type*} (G : SimpleGraph V) :
    Ideal (MvPolynomial V k) :=
  Ideal.span {f | ∃ u v, G.Adj u v ∧ f = X u * X v}

/-- The homogeneous maximal ideal `m = (x_v : v ∈ V)` of `k[x_v : v ∈ V]`. -/
noncomputable def irrelevantIdeal (k : Type*) [Field k] (V : Type*) : Ideal (MvPolynomial V k) :=
  Ideal.span (Set.range X)

/-- `depth R/I(G)`: the supremum of the lengths of `R/I(G)`-regular sequences in `m`. -/
noncomputable def depth (k : Type*) [Field k] {V : Type*} (G : SimpleGraph V) : ℕ∞ :=
  ⨆ (rs : List (MvPolynomial V k)) (_ : (∀ r ∈ rs, r ∈ irrelevantIdeal k V) ∧
      IsRegular (MvPolynomial V k ⧸ edgeIdeal k G) rs), (rs.length : ℕ∞)

/-- The matching number `ν(G)`: the supremum of the edge counts of matchings of `G`. -/
noncomputable def matchingNumber {V : Type*} (G : SimpleGraph V) : ℕ∞ :=
  ⨆ (M : G.Subgraph) (_ : M.IsMatching), M.edgeSet.encard

/-- The complete graph `K₂` on two vertices (a single edge). -/
abbrev K2 : SimpleGraph (Fin 2) := ⊤

theorem K2_isBipartite : K2.IsBipartite := ⟨SimpleGraph.Coloring.mk id (fun h => h)⟩

theorem matchingNumber_K2 : matchingNumber K2 = 1 := by
  have h01 : K2.Adj 0 1 := by decide
  apply le_antisymm
  · refine iSup₂_le fun M _ => ?_
    have hsub : M.edgeSet ⊆ {s(0, 1)} := by
      intro e he
      induction e using Sym2.ind with
      | _ a b =>
        have hab : a ≠ b := (M.adj_sub he).ne
        simp only [Set.mem_singleton_iff]
        fin_cases a <;> fin_cases b <;> simp_all [Sym2.eq_swap]
    calc M.edgeSet.encard ≤ ({s(0, 1)} : Set (Sym2 (Fin 2))).encard := Set.encard_le_encard hsub
      _ = 1 := Set.encard_singleton _
  · refine le_iSup₂_of_le (K2.subgraphOfAdj h01) (SimpleGraph.Subgraph.IsMatching.subgraphOfAdj h01) ?_
    simp

section Poly

variable {k : Type*} [Field k]

local notation "R" => MvPolynomial (Fin 2) k

theorem edgeIdeal_K2 : edgeIdeal k K2 = Ideal.span {(X 0 * X 1 : R)} := by
  unfold edgeIdeal
  congr 1
  ext f
  simp only [Set.mem_ofPred_eq, Set.mem_singleton_iff]
  constructor
  · rintro ⟨u, v, huv, rfl⟩
    fin_cases u <;> fin_cases v <;> simp_all [mul_comm]
  · rintro rfl
    exact ⟨0, 1, by decide, rfl⟩

/-- If an algebra endomorphism `φ` moves every variable only within `J`, then `f - φ f ∈ J`. -/
theorem sub_mem_of_gen (φ : R →ₐ[k] R) (J : Ideal R) (h : ∀ i, X i - φ (X i) ∈ J) (f : R) :
    f - φ f ∈ J := by
  have hc : (Ideal.Quotient.mkₐ k J).comp φ = Ideal.Quotient.mkₐ k J := by
    apply MvPolynomial.algHom_ext
    intro i
    simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk]
    exact (Ideal.Quotient.eq.mpr (h i)).symm
  have h2 := congrArg (fun g => g f) hc
  simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk] at h2
  exact Ideal.Quotient.eq.mp h2.symm

/-- `phiY` sets `y = 0`. -/
noncomputable def phiY : R →ₐ[k] R := aeval ![X 0, 0]
/-- `psiX` sets `x = 0`. -/
noncomputable def psiX : R →ₐ[k] R := aeval ![0, X 1]

theorem phiY_phiY (f : R) : phiY (phiY f) = phiY f := by
  have : (phiY (k := k)).comp phiY = phiY := by
    apply MvPolynomial.algHom_ext; intro i; fin_cases i <;> simp [phiY]
  exact congrArg (fun g => g f) this

theorem psiX_phiY_comm (f : R) : psiX (phiY f) = phiY (psiX f) := by
  have : (psiX (k := k)).comp phiY = phiY.comp psiX := by
    apply MvPolynomial.algHom_ext; intro i; fin_cases i <;> simp [phiY, psiX]
  exact congrArg (fun g => g f) this

theorem psiX_phiY_of_mem {f : R} (hf : f ∈ irrelevantIdeal k (Fin 2)) : psiX (phiY f) = 0 := by
  have hle : irrelevantIdeal k (Fin 2) ≤ RingHom.ker ((psiX (k := k)).comp phiY).toRingHom := by
    refine Ideal.span_le.mpr ?_
    rintro _ ⟨i, rfl⟩
    fin_cases i <;> simp [RingHom.mem_ker, phiY, psiX]
  simpa [RingHom.mem_ker] using hle hf

theorem sub_phiY_mem (f : R) : f - phiY f ∈ Ideal.span {(X 1 : R)} :=
  sub_mem_of_gen _ _ (fun i => by
    fin_cases i
    · simp [phiY]
    · simp [phiY]) f

theorem sub_psiX_mem (f : R) : f - psiX f ∈ Ideal.span {(X 0 : R)} :=
  sub_mem_of_gen _ _ (fun i => by
    fin_cases i
    · simp [psiX]
    · simp [psiX]) f

theorem X0_not_mem : (X 0 : R) ∉ Ideal.span {(X 0 * X 1 : R)} := by
  intro h
  obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp h
  have := congrArg (MvPolynomial.eval ![(1 : k), 0]) ha
  simp at this

theorem X1_not_mem : (X 1 : R) ∉ Ideal.span {(X 0 * X 1 : R)} := by
  intro h
  obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp h
  have := congrArg (MvPolynomial.eval ![(0 : k), 1]) ha
  simp at this

local notation "I" => Ideal.span {(X 0 * X 1 : R)}
local notation "M" => R ⧸ I

theorem smul_mk (r a : R) : r • (Ideal.Quotient.mk I a) = Ideal.Quotient.mk I (r * a) := rfl

theorem mem_smul_top_iff (f a : R) :
    Ideal.Quotient.mk I a ∈ f • (⊤ : Submodule R M) ↔ ∃ g : R, a - f * g ∈ I := by
  rw [Submodule.mem_smul_pointwise_iff_exists]
  constructor
  · rintro ⟨b, -, hb⟩
    obtain ⟨g, rfl⟩ := Ideal.Quotient.mk_surjective b
    refine ⟨g, ?_⟩
    rw [smul_mk] at hb
    exact Ideal.Quotient.eq.mp hb.symm
  · rintro ⟨g, hg⟩
    exact ⟨Ideal.Quotient.mk I g, trivial, by rw [smul_mk]; exact (Ideal.Quotient.eq.mpr hg).symm⟩

/-- Key lemma: `k[x,y]/(xy)` has no regular sequence of length two inside `m`. -/
theorem no_regular_pair (f1 f2 : R) (rest : List R) (hm1 : f1 ∈ irrelevantIdeal k (Fin 2))
    (hm2 : f2 ∈ irrelevantIdeal k (Fin 2)) (h : IsWeaklyRegular M (f1 :: f2 :: rest)) : False := by
  rw [isWeaklyRegular_cons_iff] at h
  obtain ⟨h1, h2⟩ := h
  rw [isWeaklyRegular_cons_iff] at h2
  obtain ⟨h2, -⟩ := h2
  set u : R := phiY f1 with hu
  have hψu : psiX u = 0 := psiX_phiY_of_mem hm1
  -- `f1` is not divisible by `y`, nor by `x` (it is a nonzerodivisor on `M`)
  have hu0 : u ≠ 0 := by
    intro h0
    have := sub_phiY_mem f1
    rw [← hu, h0, sub_zero] at this
    obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp this
    apply X0_not_mem (k := k)
    have : f1 • Ideal.Quotient.mk I (X 0) = f1 • (0 : M) := by
      rw [smul_mk, smul_zero, Ideal.Quotient.eq_zero_iff_mem, ← hc,
        Ideal.mem_span_singleton']
      exact ⟨c, by ring⟩
    exact Ideal.Quotient.eq_zero_iff_mem.mp (h1 this)
  have hψ0 : psiX f1 ≠ 0 := by
    intro h0
    have := sub_psiX_mem f1
    rw [h0, sub_zero] at this
    obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp this
    apply X1_not_mem (k := k)
    have : f1 • Ideal.Quotient.mk I (X 1) = f1 • (0 : M) := by
      rw [smul_mk, smul_zero, Ideal.Quotient.eq_zero_iff_mem, ← hc,
        Ideal.mem_span_singleton']
      exact ⟨c, by ring⟩
    exact Ideal.Quotient.eq_zero_iff_mem.mp (h1 this)
  -- `u ∉ f1 • M`
  have hnot : Ideal.Quotient.mk I u ∉ f1 • (⊤ : Submodule R M) := by
    rw [mem_smul_top_iff]
    rintro ⟨g, hg⟩
    obtain ⟨h', hh'⟩ := Ideal.mem_span_singleton'.mp hg
    have e1 := congrArg phiY hh'
    have e2 := congrArg psiX hh'
    simp only [map_mul, map_sub, hu, phiY_phiY] at e1 e2
    simp only [phiY, psiX, aeval_X, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.cons_val_fin_one, mul_zero, zero_mul] at e1 e2
    change (0 : R) = u - u * phiY g at e1
    change (0 : R) = psiX u - psiX f1 * psiX g at e2
    rw [hψu] at e2
    -- e1 : 0 = u - u * φ g ; e2 : 0 = 0 - ψ f1 * ψ g
    have hφg : phiY g = 1 := by
      have : u * (1 - phiY g) = 0 := by rw [mul_sub, mul_one]; exact e1.symm
      rcases mul_eq_zero.mp this with h | h
      · exact absurd h hu0
      · exact (sub_eq_zero.mp h).symm
    have hψg : psiX g = 0 := by
      have : psiX f1 * psiX g = 0 := by
        have := e2.symm; rw [zero_sub, neg_eq_zero] at this; exact this
      rcases mul_eq_zero.mp this with h | h
      · exact absurd h hψ0
      · exact h
    have := psiX_phiY_comm g
    rw [hφg, hψg, map_one, map_zero] at this
    exact one_ne_zero this
  -- `m · u ⊆ f1 • M`
  have hx : (X 0 : R) • Ideal.Quotient.mk I u ∈ f1 • (⊤ : Submodule R M) := by
    rw [smul_mk, mem_smul_top_iff]
    obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp (sub_phiY_mem f1)
    refine ⟨X 0, Ideal.mem_span_singleton'.mpr ⟨-c, ?_⟩⟩
    rw [← hu] at hc
    linear_combination (-(X 0 : R)) * hc
  have hy : (X 1 : R) • Ideal.Quotient.mk I u ∈ f1 • (⊤ : Submodule R M) := by
    rw [smul_mk, mem_smul_top_iff]
    have := sub_psiX_mem u
    rw [hψu, sub_zero] at this
    obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp this
    refine ⟨0, Ideal.mem_span_singleton'.mpr ⟨c, ?_⟩⟩
    linear_combination (X 1 : R) * hc
  have hcol : ∀ r ∈ irrelevantIdeal k (Fin 2),
      r • Ideal.Quotient.mk I u ∈ f1 • (⊤ : Submodule R M) := by
    intro r hr
    induction hr using Submodule.span_induction with
    | mem x hx' =>
      obtain ⟨i, rfl⟩ := hx'
      fin_cases i
      · exact hx
      · exact hy
    | zero => simp
    | add a b _ _ ha hb => rw [add_smul]; exact add_mem ha hb
    | smul a b _ hb => rw [smul_assoc]; exact Submodule.smul_mem _ a hb
  apply hnot
  have key : f2 • (Submodule.Quotient.mk (Ideal.Quotient.mk I u) : QuotSMulTop f1 M) =
      f2 • (0 : QuotSMulTop f1 M) := by
    rw [smul_zero, ← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero]
    exact hcol f2 hm2
  exact (Submodule.Quotient.mk_eq_zero _).mp (h2 key)

end Poly

/-- Over every field, `depth k[x,y]/I(K₂) ≤ 1`. -/
theorem depth_K2_le (k : Type*) [Field k] : depth k K2 ≤ 1 := by
  refine iSup₂_le fun rs hrs => ?_
  obtain ⟨hm, hreg⟩ := hrs
  match rs, hm, hreg with
  | [], _, _ => simp
  | [_], _, _ => simp
  | f1 :: f2 :: rest, hm, hreg =>
    rw [edgeIdeal_K2] at hreg
    exact (no_regular_pair f1 f2 rest (hm f1 (by simp)) (hm f2 (by simp))
      hreg.toIsWeaklyRegular).elim

/-- Over every field `k`, the bipartite graph `K₂` violates `depth R/I(G) ≥ ν(G) + 1`. -/
theorem K2_counterexample (k : Type*) [Field k] :
    K2.IsBipartite ∧ matchingNumber K2 = 1 ∧ depth k K2 ≤ 1 ∧ depth k K2 < matchingNumber K2 + 1 := by
  refine ⟨K2_isBipartite, matchingNumber_K2, depth_K2_le k, ?_⟩
  rw [matchingNumber_K2]
  exact lt_of_le_of_lt (depth_K2_le k) (by norm_num)

/-- **Conjecture 00000000537 is false**: it is not true that every (finite) bipartite graph
satisfies `depth R/I(G) ≥ ν(G) + 1`; it fails for `K₂` over every field. -/
theorem conjecture_537_false :
    ¬ ∀ (V : Type) [Fintype V] (G : SimpleGraph V), G.IsBipartite →
        ∀ (k : Type) [Field k], matchingNumber G + 1 ≤ depth k G := by
  intro h
  have h1 := h (Fin 2) K2 K2_isBipartite ℚ
  exact absurd h1 (not_le.mpr (K2_counterexample ℚ).2.2.2)

end C537
