name = "conjecture2291"
version = "0.1.0"
defaultTargets = ["Conjecture2291"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "Conjecture2291"
