import Main
/-! Axiom audit: every theorem must be axiom-free. -/
#print axioms kMulSucc
#print axioms kAddMul
#print axioms kMulAssoc
#print axioms kLeMulSucc
#print axioms kParity
#print axioms kLeEx
#print axioms kAddCancel
#print axioms kTwoAbsurd
#print axioms kle
#print axioms kFibPosOdd
#print axioms myLeZero
#print axioms q4
#print axioms q3
#print axioms q2
#print axioms hr
#print axioms cassini_even
#print axioms cassini_odd
#print axioms not_prime_of_even_ne_two
#print axioms period_even
#print axioms only_two
#print axioms kTwoMulThree
#print axioms prime2
#print axioms prime3
#print axioms pisano2
#print axioms pisano3
#print axioms pisano5
#print axioms pisano7
#print axioms pisano11
#print axioms pisano13
#print axioms two_survives
#print axioms two_period_ex
