import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.RingTheory.Ideal.Quotient.Defs
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.Data.Rat.Defs

noncomputable section

namespace IdealBridge
open MvPolynomial

variable {E V k : Type*} [CommRing k]

def exponentMap (inc : E → V →₀ ℕ) : (E →₀ ℕ) →+ (V →₀ ℕ) where
  toFun a := a.sum fun e n => n • inc e
  map_zero' := by simp
  map_add' a b := Finsupp.sum_add_index' (by simp) (by simp [add_nsmul])

@[simp] theorem exponentMap_single (inc : E → V →₀ ℕ) (e : E) (n : ℕ) :
    exponentMap inc (Finsupp.single e n) = n • inc e := by
  simp [exponentMap]

def monomialMap (A : (E →₀ ℕ) →+ (V →₀ ℕ)) :
    MvPolynomial E k →+* MvPolynomial V k :=
  AddMonoidAlgebra.mapDomainRingHom k A

@[simp] theorem monomialMap_monomial (A : (E →₀ ℕ) →+ (V →₀ ℕ))
    (a : E →₀ ℕ) (r : k) :
    monomialMap (k := k) A (monomial a r) = monomial (A a) r :=
  Finsupp.mapDomain_single

def toricMap (inc : E → V →₀ ℕ) : MvPolynomial E k →+* MvPolynomial V k :=
  monomialMap (k := k) (exponentMap inc)

@[simp] theorem toricMap_monomial (inc : E → V →₀ ℕ) (a : E →₀ ℕ) (r : k) :
    toricMap (k := k) inc (monomial a r) = monomial (exponentMap inc a) r :=
  monomialMap_monomial _ _ _

@[simp] theorem toricMap_X (inc : E → V →₀ ℕ) (e : E) :
    toricMap (k := k) inc (X e) = monomial (inc e) 1 := by
  simp [X]

@[simp] theorem toricMap_C (inc : E → V →₀ ℕ) (r : k) :
    toricMap (k := k) inc (C r) = C r := by
  change toricMap (k := k) inc (monomial 0 r) = monomial 0 r
  rw [toricMap_monomial, map_zero]

theorem toricMap_eq_eval₂Hom (inc : E → V →₀ ℕ) :
    toricMap (k := k) inc = eval₂Hom C (fun e => monomial (inc e) 1) := by
  apply MvPolynomial.ringHom_ext <;> intro x <;> simp

/-- Every polynomial in the kernel is generated by its equal-fiber binomials.
The premise ranges over all exponents, with no degree bound. -/
theorem ker_monomialMap_le_of_fiber_binomials
    (A : (E →₀ ℕ) →+ (V →₀ ℕ)) (J : Ideal (MvPolynomial E k))
    (h : ∀ a b, A a = A b → monomial a 1 - monomial b 1 ∈ J) :
    RingHom.ker (monomialMap (k := k) A) ≤ J := by
  classical
  let π := Ideal.Quotient.mk J
  let g : (V →₀ ℕ) → MvPolynomial E k ⧸ J := fun v =>
    if hv : ∃ a, A a = v then π (monomial (Classical.choose hv) 1) else 0
  have hg (a : E →₀ ℕ) : g (A a) = π (monomial a 1) := by
    have ha : ∃ b, A b = A a := ⟨a, rfl⟩
    simp only [g, dif_pos ha]
    exact Ideal.Quotient.eq.mpr (h _ _ (Classical.choose_spec ha))
  intro p hp
  have hp0 : Finsupp.mapDomain A p = 0 := hp
  have hs : (Finsupp.mapDomain A p).sum (fun v r => π (C r) * g v) = π p := by
    rw [Finsupp.sum_mapDomain_index (by simp) (by simp [map_add, add_mul])]
    calc
      p.sum (fun a r => π (C r) * g (A a)) =
          p.sum (fun a r => π (monomial a r)) := by
        apply Finsupp.sum_congr
        intro a ha
        rw [hg, ← map_mul, C_mul_monomial, mul_one]
      _ = π (p.sum fun a r => monomial a r) := by
        exact (map_sum π _ _).symm
      _ = π p := by rw [show p.sum (fun a r => monomial a r) = p from Finsupp.sum_single p]
  rw [hp0, Finsupp.sum_zero_index] at hs
  exact Ideal.Quotient.eq_zero_iff_mem.mp hs.symm

theorem ker_le_of_fiber_binomials
    (inc : E → V →₀ ℕ) (J : Ideal (MvPolynomial E k))
    (h : ∀ a b, exponentMap inc a = exponentMap inc b →
      monomial a 1 - monomial b 1 ∈ J) :
    RingHom.ker (toricMap (k := k) inc) ≤ J :=
  ker_monomialMap_le_of_fiber_binomials (exponentMap inc) J h

/-- The set of all pure binomials whose two exponent vectors have equal image. -/
def fiberBinomials (A : (E →₀ ℕ) →+ (V →₀ ℕ)) : Set (MvPolynomial E k) :=
  {p | ∃ a b, A a = A b ∧ p = monomial a 1 - monomial b 1}

/-- The complete toric kernel is spanned by the binomials in its fibers. -/
theorem ker_monomialMap_eq_span (A : (E →₀ ℕ) →+ (V →₀ ℕ)) :
    RingHom.ker (monomialMap (k := k) A) = Ideal.span (fiberBinomials (k := k) A) := by
  apply le_antisymm
  · apply ker_monomialMap_le_of_fiber_binomials
    intro a b hab
    exact Ideal.subset_span ⟨a, b, hab, rfl⟩
  · apply Ideal.span_le.mpr
    rintro p ⟨a, b, hab, rfl⟩
    change monomialMap (k := k) A (monomial a 1 - monomial b 1) = 0
    simp [hab]

theorem ker_toricMap_eq_span (inc : E → V →₀ ℕ) :
    RingHom.ker (toricMap (k := k) inc) = Ideal.span (fiberBinomials (k := k) (exponentMap inc)) :=
  ker_monomialMap_eq_span (exponentMap inc)

end IdealBridge

