/-!
# Conjecture 00000008556 (free distributive lattices): the logarithm clause is false

The conjecture (paraphrased): for the free distributive lattice `FD(n)` on `n` generators,
(1) `Aut(FD(n))` is the symmetric group `S_n`;
(2) its fixed-point lattice is "of partition-symmetric type";
(3) the maximal chain length of the fixed-point lattice is exactly `log p(n)`,
where `p(n)` is the partition number.

We refute clause (3), hence the conjunction.  Everything is defined from scratch in core Lean 4:

* Boolean functions on `n` variables are truth tables, encoded as natural numbers `f < 2^(2^n)`
  (bit `m` of `f` is the value at the point `m ∈ {0,1}^n`, coordinate `i` = bit `i` of `m`).
* `FD(n)` is defined in two ways and proved equal for `n ≤ 3`:
  the closure `Gen` of the projections under `∧`/`∨` (pointwise `&&&`/`|||`), and the set
  `FDset` of nonconstant monotone functions.  The flag `bnd = true` gives the free *bounded*
  distributive lattice (constants `0`, `1` adjoined).
* `S_n` acts by permuting variables (`act`); `Fixed` is the set of `S_n`-fixed elements;
  `IsAut` is a genuine lattice automorphism of `FD(n)`; `FixedAut` is the set of elements fixed
  by every automorphism.
* `MaxChainLen P k`: the longest chain in `P` (for the lattice order) has `k` edges.
* `p n` is the number of partitions of `n` (an explicit enumeration, proved to list exactly the
  partitions).
* A logarithm `log_b x = y` (base `b > 0`, `b ≠ 1`) means `b^y = x`; the base is quantified over
  an arbitrary number system `NumSys` (anything with an associative multiplication, a unit and an
  injective multiplicative cast of `ℕ`: e.g. `ℕ, ℤ, ℚ, ℝ, ℂ`).
-/

namespace FDL

/-! ## 1. Truth tables -/

/-- `maskOf P N = Σ_{m < N, P m} 2^m`. -/
def maskOf (P : Nat → Bool) : Nat → Nat
  | 0 => 0
  | m + 1 => maskOf P m + (if P m then 2 ^ m else 0)

/-- The constant-true truth table on `n` variables. -/
def full (n : Nat) : Nat := 2 ^ (2 ^ n) - 1

/-- The projection `x_i` as a truth table. -/
def proj (n i : Nat) : Nat := maskOf (fun m => m.testBit i) (2 ^ n)

/-- Monotonicity: `x ≤ y` coordinatewise (`x &&& y = x`) and `f x = 1` imply `f y = 1`. -/
def Mono (n f : Nat) : Prop :=
  ∀ x, x < 2 ^ n → ∀ y, y < 2 ^ n → x &&& y = x → f.testBit x = true → f.testBit y = true

instance (n f : Nat) : Decidable (Mono n f) := by unfold Mono; infer_instance

/-- Elements of `FD(n)`: monotone truth tables, nonconstant unless `bnd = true`. -/
def FDset (n : Nat) (bnd : Bool) (f : Nat) : Prop :=
  f < 2 ^ (2 ^ n) ∧ Mono n f ∧ (bnd = true ∨ (f ≠ 0 ∧ f ≠ full n))

instance (n : Nat) (bnd : Bool) (f : Nat) : Decidable (FDset n bnd f) := by
  unfold FDset; infer_instance

/-- `FD(n)` as the sublattice generated by the projections (and by `0`, `1` if `bnd`). -/
inductive Gen (n : Nat) (bnd : Bool) : Nat → Prop
  | proj (i : Nat) : i < n → Gen n bnd (proj n i)
  | bot : bnd = true → Gen n bnd 0
  | top : bnd = true → Gen n bnd (full n)
  | meet {f g : Nat} : Gen n bnd f → Gen n bnd g → Gen n bnd (f &&& g)
  | join {f g : Nat} : Gen n bnd f → Gen n bnd g → Gen n bnd (f ||| g)

/-! ## 2. Computing the generated lattice -/

def insertAll (acc : List Nat) : List Nat → List Nat
  | [] => acc
  | x :: xs => insertAll (acc.insert x) xs

theorem mem_insertAll : ∀ (l acc : List Nat) (x : Nat),
    x ∈ insertAll acc l ↔ x ∈ acc ∨ x ∈ l
  | [], acc, x => by simp [insertAll]
  | y :: ys, acc, x => by
    rw [insertAll, mem_insertAll ys (acc.insert y) x, List.mem_insert_iff]
    simp only [List.mem_cons]
    constructor
    · rintro ((h | h) | h) <;> simp [h]
    · rintro (h | h | h) <;> simp [h]

def step (S : List Nat) : List Nat :=
  insertAll S (S.flatMap fun a => S.flatMap fun b => [a &&& b, a ||| b])

def initGens (n : Nat) (bnd : Bool) : List Nat :=
  (List.range n).map (proj n) ++ (if bnd then [0, full n] else [])

def iter : Nat → List Nat → List Nat
  | 0, S => S
  | k + 1, S => iter k (step S)

/-- The closure of the generators after `n` rounds of `∧`/`∨`. -/
def closureL (n : Nat) (bnd : Bool) : List Nat := iter n (initGens n bnd)

theorem gen_step (n : Nat) (bnd : Bool) (S : List Nat) (h : ∀ x ∈ S, Gen n bnd x) :
    ∀ x ∈ step S, Gen n bnd x := by
  intro x hx
  rw [step, mem_insertAll] at hx
  rcases hx with hx | hx
  · exact h x hx
  · rw [List.mem_flatMap] at hx
    obtain ⟨a, ha, hx⟩ := hx
    rw [List.mem_flatMap] at hx
    obtain ⟨b, hb, hx⟩ := hx
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
    rcases hx with rfl | rfl
    · exact Gen.meet (h a ha) (h b hb)
    · exact Gen.join (h a ha) (h b hb)

theorem gen_iter (n : Nat) (bnd : Bool) :
    ∀ (k : Nat) (S : List Nat), (∀ x ∈ S, Gen n bnd x) → ∀ x ∈ iter k S, Gen n bnd x
  | 0, _, h => h
  | k + 1, S, h => gen_iter n bnd k (step S) (gen_step n bnd S h)

theorem gen_init (n : Nat) (bnd : Bool) : ∀ x ∈ initGens n bnd, Gen n bnd x := by
  intro x hx
  rw [initGens, List.mem_append] at hx
  rcases hx with hx | hx
  · rw [List.mem_map] at hx
    obtain ⟨i, hi, rfl⟩ := hx
    exact Gen.proj i (List.mem_range.mp hi)
  · cases hb : bnd
    · simp [hb] at hx
    · simp only [hb, if_true, List.mem_cons, List.not_mem_nil, or_false] at hx
      rcases hx with rfl | rfl
      · exact Gen.bot rfl
      · exact Gen.top rfl

theorem gen_closure (n : Nat) (bnd : Bool) : ∀ x ∈ closureL n bnd, Gen n bnd x :=
  gen_iter n bnd n _ (gen_init n bnd)

/-- Generic bridge: if a finite list `L` equals the computed closure, is closed under `∧`/`∨`,
contains the generators, and coincides with `FDset` (checked on all truth tables), then the
generated lattice `Gen` and the monotone description `FDset` coincide and equal `L`. -/
theorem gen_iff_of (n : Nat) (bnd : Bool) (L : List Nat)
    (hcl : closureL n bnd = L)
    (hclosed : ∀ a ∈ L, ∀ b ∈ L, a &&& b ∈ L ∧ a ||| b ∈ L)
    (hproj : ∀ i, i < n → proj n i ∈ L)
    (hbt : bnd = true → 0 ∈ L ∧ full n ∈ L)
    (hsound : ∀ f ∈ L, FDset n bnd f)
    (hcomp : ∀ f, f < 2 ^ (2 ^ n) → FDset n bnd f → f ∈ L) :
    ∀ f, (Gen n bnd f ↔ FDset n bnd f) ∧ (FDset n bnd f ↔ f ∈ L) := by
  have hmemL : ∀ f, Gen n bnd f → f ∈ L := by
    intro f hf
    induction hf with
    | proj i hi => exact hproj i hi
    | bot h => exact (hbt h).1
    | top h => exact (hbt h).2
    | meet _ _ iha ihb => exact (hclosed _ iha _ ihb).1
    | join _ _ iha ihb => exact (hclosed _ iha _ ihb).2
  intro f
  have h1 : FDset n bnd f ↔ f ∈ L := ⟨fun h => hcomp f h.1 h, hsound f⟩
  refine ⟨⟨fun h => h1.mpr (hmemL f h), fun h => ?_⟩, h1⟩
  exact gen_closure n bnd f (hcl ▸ h1.mp h)

/-! Explicit element lists (the computed closures). -/

def L1u : List Nat := [2]
def L1b : List Nat := [2, 0, 3]
def L2u : List Nat := [14, 8, 10, 12]
def L2b : List Nat := [14, 8, 10, 12, 0, 15]
def L3u : List Nat := [232, 234, 200, 224, 128, 168, 236, 254, 248, 252, 192, 250, 160, 238, 136,
  170, 204, 240]
def L3b : List Nat := [232, 234, 200, 224, 128, 168, 236, 254, 248, 252, 192, 250, 160, 238, 136,
  170, 204, 240, 0, 255]

def FDL : Nat → Bool → List Nat
  | 1, false => L1u
  | 1, true => L1b
  | 2, false => L2u
  | 2, true => L2b
  | 3, false => L3u
  | 3, true => L3b
  | _, _ => []

theorem closure_eq : ∀ n bnd, 1 ≤ n → n ≤ 3 → closureL n bnd = FDL n bnd := by
  intro n bnd h1 h3
  match n, bnd, h1, h3 with
  | 1, false, _, _ => decide +kernel
  | 1, true, _, _ => decide +kernel
  | 2, false, _, _ => decide +kernel
  | 2, true, _, _ => decide +kernel
  | 3, false, _, _ => decide +kernel
  | 3, true, _, _ => decide +kernel

/-- The defining data of `FD(n)` for `n ≤ 3`, both unbounded and bounded. -/
structure FDFacts (n : Nat) (bnd : Bool) : Prop where
  closed : ∀ a ∈ FDL n bnd, ∀ b ∈ FDL n bnd, a &&& b ∈ FDL n bnd ∧ a ||| b ∈ FDL n bnd
  projs : ∀ i, i < n → proj n i ∈ FDL n bnd
  bt : bnd = true → 0 ∈ FDL n bnd ∧ full n ∈ FDL n bnd
  sound : ∀ f ∈ FDL n bnd, FDset n bnd f
  comp : ∀ f, f < 2 ^ (2 ^ n) → FDset n bnd f → f ∈ FDL n bnd

theorem fdFacts : ∀ n bnd, 1 ≤ n → n ≤ 3 → FDFacts n bnd := by
  intro n bnd h1 h3
  match n, bnd, h1, h3 with
  | 1, false, _, _ => exact ⟨by decide +kernel, by decide +kernel, by decide +kernel,
      by decide +kernel, by decide +kernel⟩
  | 1, true, _, _ => exact ⟨by decide +kernel, by decide +kernel, by decide +kernel,
      by decide +kernel, by decide +kernel⟩
  | 2, false, _, _ => exact ⟨by decide +kernel, by decide +kernel, by decide +kernel,
      by decide +kernel, by decide +kernel⟩
  | 2, true, _, _ => exact ⟨by decide +kernel, by decide +kernel, by decide +kernel,
      by decide +kernel, by decide +kernel⟩
  | 3, false, _, _ => exact ⟨by decide +kernel, by decide +kernel, by decide +kernel,
      by decide +kernel, by decide +kernel⟩
  | 3, true, _, _ => exact ⟨by decide +kernel, by decide +kernel, by decide +kernel,
      by decide +kernel, by decide +kernel⟩

/-- For `1 ≤ n ≤ 3`: the sublattice generated by the projections is exactly the set of
(nonconstant, unless `bnd`) monotone Boolean functions, and it is the explicit list `FDL n bnd`. -/
theorem fd_spec (n : Nat) (bnd : Bool) (h1 : 1 ≤ n) (h3 : n ≤ 3) :
    ∀ f, (Gen n bnd f ↔ FDset n bnd f) ∧ (FDset n bnd f ↔ f ∈ FDL n bnd) :=
  let F := fdFacts n bnd h1 h3
  gen_iff_of n bnd (FDL n bnd) (closure_eq n bnd h1 h3) F.closed F.projs F.bt F.sound F.comp

/-- Sizes: `|FD(n)| = 1, 4, 18` and, bounded, `3, 6, 20` (Dedekind numbers minus 0 / 2). -/
theorem fd_sizes :
    (FDL 1 false).length = 1 ∧ (FDL 2 false).length = 4 ∧ (FDL 3 false).length = 18 ∧
    (FDL 1 true).length = 3 ∧ (FDL 2 true).length = 6 ∧ (FDL 3 true).length = 20 ∧
    (FDL 3 false).Nodup ∧ (FDL 3 true).Nodup := by decide

/-! ## 3. The symmetric group acting on variables -/

/-- `σ` (a list) is a permutation of `{0,…,n-1}`. -/
def IsPerm (n : Nat) (σ : List Nat) : Prop := σ.length = n ∧ σ.Nodup ∧ ∀ x ∈ σ, x < n

instance (n : Nat) (σ : List Nat) : Decidable (IsPerm n σ) := by unfold IsPerm; infer_instance

def permPointAux : List Nat → Nat → Nat → Nat
  | [], _, _ => 0
  | s :: σ, i, m => (if m.testBit i then 2 ^ s else 0) + permPointAux σ (i + 1) m

/-- The point `σ(x) = {σ(i) : i ∈ x}`. -/
def permPoint (σ : List Nat) (m : Nat) : Nat := permPointAux σ 0 m

/-- The action of `σ` on truth tables: `(σ·f)(x) = f(σ(x))` (permutation of the variables). -/
def act (n : Nat) (σ : List Nat) (f : Nat) : Nat :=
  maskOf (fun m => f.testBit (permPoint σ m)) (2 ^ n)

/-- All lists of length `n` with entries `< k`. -/
def allLists : Nat → Nat → List (List Nat)
  | 0, _ => [[]]
  | n + 1, k => (List.range k).flatMap fun a => (allLists n k).map (a :: ·)

theorem mem_allLists (k : Nat) : ∀ (n : Nat) (l : List Nat),
    l.length = n → (∀ x ∈ l, x < k) → l ∈ allLists n k
  | 0, [], _, _ => List.Mem.head _
  | 0, _ :: _, h, _ => absurd h (Nat.succ_ne_zero _)
  | _ + 1, [], h, _ => absurd h.symm (Nat.succ_ne_zero _)
  | n + 1, a :: l, h, hb => by
    rw [allLists, List.mem_flatMap]
    refine ⟨a, List.mem_range.mpr (hb a (List.Mem.head _)), ?_⟩
    rw [List.mem_map]
    exact ⟨l, mem_allLists k n l (Nat.succ.inj h) (fun x hx => hb x (List.mem_cons_of_mem a hx)),
      rfl⟩

theorem isPerm_mem {n : Nat} {σ : List Nat} (h : IsPerm n σ) : σ ∈ allLists n n :=
  mem_allLists n n σ h.1 h.2.2

/-- `S_n`-fixed elements of `FD(n)` (the fixed-point set of the variable-permutation action). -/
def Fixed (n : Nat) (bnd : Bool) (f : Nat) : Prop :=
  FDset n bnd f ∧ ∀ σ, IsPerm n σ → act n σ f = f

/-- A bounded (hence decidable) form of `Fixed`. -/
def FixedB (n : Nat) (bnd : Bool) (f : Nat) : Prop :=
  FDset n bnd f ∧ ∀ σ ∈ allLists n n, IsPerm n σ → act n σ f = f

instance (n : Nat) (bnd : Bool) (f : Nat) : Decidable (FixedB n bnd f) := by
  unfold FixedB; infer_instance

theorem fixed_iff_fixedB (n : Nat) (bnd : Bool) (f : Nat) : Fixed n bnd f ↔ FixedB n bnd f :=
  ⟨fun h => ⟨h.1, fun σ _ hσ => h.2 σ hσ⟩, fun h => ⟨h.1, fun σ hσ => h.2 σ (isPerm_mem hσ) hσ⟩⟩

/-! ## 4. Fixed points are the threshold functions -/

/-- Hamming weight of the first `n` bits. -/
def weight : Nat → Nat → Nat
  | 0, _ => 0
  | i + 1, m => weight i m + (if m.testBit i then 1 else 0)

/-- The threshold function "at least `k` of the `n` variables are true". -/
def threshold (n k : Nat) : Nat := maskOf (fun m => decide (k ≤ weight n m)) (2 ^ n)

/-- The admissible thresholds: `1 ≤ k ≤ n` (nonconstant), or `0 ≤ k ≤ n+1` if bounded. -/
def thrList (n : Nat) (bnd : Bool) : List Nat :=
  ((List.range (n + 2)).filter fun k => bnd || (1 ≤ k && k ≤ n)).map (threshold n)

theorem iff_of_bounded (P Q : Nat → Prop) (B : Nat) (hP : ∀ f, P f → f < B)
    (hQ : ∀ f, Q f → f < B) (h : ∀ f, f < B → (P f ↔ Q f)) : ∀ f, P f ↔ Q f := by
  intro f
  exact if hf : f < B then h f hf
    else ⟨fun hp => absurd (hP f hp) hf, fun hq => absurd (hQ f hq) hf⟩

theorem fixedB_iff_thr : ∀ n bnd, 1 ≤ n → n ≤ 3 →
    ∀ f, f < 2 ^ (2 ^ n) → (FixedB n bnd f ↔ f ∈ thrList n bnd) := by
  intro n bnd h1 h3
  match n, bnd, h1, h3 with
  | 1, false, _, _ => decide +kernel
  | 1, true, _, _ => decide +kernel
  | 2, false, _, _ => decide +kernel
  | 2, true, _, _ => decide +kernel
  | 3, false, _, _ => decide +kernel
  | 3, true, _, _ => decide +kernel

theorem thr_lt : ∀ n bnd, 1 ≤ n → n ≤ 3 → ∀ f ∈ thrList n bnd, f < 2 ^ (2 ^ n) := by
  intro n bnd h1 h3
  match n, bnd, h1, h3 with
  | 1, false, _, _ => decide
  | 1, true, _, _ => decide
  | 2, false, _, _ => decide
  | 2, true, _, _ => decide
  | 3, false, _, _ => decide
  | 3, true, _, _ => decide

/-- **Fixed points.** For `1 ≤ n ≤ 3` the `S_n`-fixed elements of `FD(n)` are exactly the
threshold functions (`1 ≤ k ≤ n`; with `0 ≤ k ≤ n+1` in the bounded lattice). -/
theorem fixed_iff_thr (n : Nat) (bnd : Bool) (h1 : 1 ≤ n) (h3 : n ≤ 3) :
    ∀ f, Fixed n bnd f ↔ f ∈ thrList n bnd := by
  intro f
  rw [fixed_iff_fixedB]
  exact iff_of_bounded _ _ (2 ^ (2 ^ n)) (fun f h => h.1.1) (thr_lt n bnd h1 h3)
    (fixedB_iff_thr n bnd h1 h3) f

theorem thrList_values :
    thrList 1 false = [2] ∧ thrList 2 false = [14, 8] ∧ thrList 3 false = [254, 232, 128] ∧
    thrList 1 true = [3, 2, 0] ∧ thrList 2 true = [15, 14, 8, 0] ∧
    thrList 3 true = [255, 254, 232, 128, 0] := by decide

/-! ## 5. Chains -/

/-- Strict lattice order `f < g` (`f ∧ g = f`, `f ≠ g`). -/
def lt (f g : Nat) : Prop := f &&& g = f ∧ f ≠ g

instance (f g : Nat) : Decidable (lt f g) := by unfold lt; infer_instance

/-- A chain inside `P`, listed in increasing order. -/
def IsChainIn (P : Nat → Prop) (L : List Nat) : Prop := (∀ f ∈ L, P f) ∧ L.Pairwise lt

/-- The maximal length (number of covering steps = elements − 1) of a chain in `P` is `k`. -/
def MaxChainLen (P : Nat → Prop) (k : Nat) : Prop :=
  (∃ L, IsChainIn P L ∧ L.length = k + 1) ∧ ∀ L, IsChainIn P L → L.length ≤ k + 1

/-- Remove the first occurrence of `a`. -/
def rem (a : Nat) : List Nat → List Nat
  | [] => []
  | x :: xs => if x = a then xs else x :: rem a xs

theorem rem_length (a : Nat) : ∀ S : List Nat, a ∈ S → (rem a S).length + 1 = S.length
  | [], h => nomatch h
  | x :: xs, h => by
    unfold rem
    split
    · rfl
    · rename_i hx
      have ha : a ∈ xs := by
        cases h with
        | head => exact absurd rfl hx
        | tail _ h' => exact h'
      show (rem a xs).length + 1 + 1 = xs.length + 1
      rw [rem_length a xs ha]

theorem mem_rem (a x : Nat) (hxa : x ≠ a) : ∀ S : List Nat, x ∈ S → x ∈ rem a S
  | [], h => nomatch h
  | y :: ys, h => by
    unfold rem
    split
    · rename_i hy
      cases h with
      | head => exact absurd hy hxa
      | tail _ h' => exact h'
    · cases h with
      | head => exact List.Mem.head _
      | tail _ h' => exact List.mem_cons_of_mem _ (mem_rem a x hxa ys h')

/-- Pigeonhole: a duplicate-free list inside `S` is no longer than `S`. -/
theorem nodup_len_le : ∀ (L S : List Nat), L.Nodup → (∀ x ∈ L, x ∈ S) → L.length ≤ S.length
  | [], _, _, _ => Nat.zero_le _
  | a :: L, S, hnd, hsub => by
    have ha : a ∈ S := hsub a (List.Mem.head _)
    have hnd' := List.nodup_cons.mp hnd
    have ih := nodup_len_le L (rem a S) hnd'.2 (fun x hx => by
      have hxa : x ≠ a := fun h => hnd'.1 (h ▸ hx)
      exact mem_rem a x hxa S (hsub x (List.mem_cons_of_mem a hx)))
    have := rem_length a S ha
    show L.length + 1 ≤ S.length
    omega

theorem maxChain_of (P : Nat → Prop) (S W : List Nat) (k : Nat) (hS : ∀ f, P f ↔ f ∈ S)
    (hSlen : S.length = k + 1) (hW : ∀ f ∈ W, f ∈ S) (hWc : W.Pairwise lt)
    (hWlen : W.length = k + 1) : MaxChainLen P k := by
  refine ⟨⟨W, ⟨fun f hf => (hS f).mpr (hW f hf), hWc⟩, hWlen⟩, ?_⟩
  intro L hL
  have hnd : L.Nodup := hL.2.imp fun h => h.2
  rw [← hSlen]
  exact nodup_len_le L S hnd fun x hx => (hS x).mp (hL.1 x hx)

theorem maxChain_congr {P Q : Nat → Prop} (h : ∀ f, P f ↔ Q f) {k : Nat}
    (hP : MaxChainLen P k) : MaxChainLen Q k := by
  have : P = Q := funext fun f => propext (h f)
  exact this ▸ hP

/-- **Chain lengths.** The `S_n`-fixed lattice of `FD(n)` is a chain of length `n - 1`
(of length `n + 1` in the bounded lattice), for `n = 1, 2, 3`. -/
theorem maxChain_fixed :
    MaxChainLen (Fixed 1 false) 0 ∧ MaxChainLen (Fixed 2 false) 1 ∧
    MaxChainLen (Fixed 3 false) 2 ∧ MaxChainLen (Fixed 1 true) 2 ∧
    MaxChainLen (Fixed 2 true) 3 ∧ MaxChainLen (Fixed 3 true) 4 := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩
  · exact maxChain_of _ (thrList 1 false) [2] 0 (fixed_iff_thr 1 false (by decide) (by decide))
      (by decide) (by decide) (by decide) (by decide)
  · exact maxChain_of _ (thrList 2 false) [8, 14] 1 (fixed_iff_thr 2 false (by decide) (by decide))
      (by decide) (by decide) (by decide) (by decide)
  · exact maxChain_of _ (thrList 3 false) [128, 232, 254] 2
      (fixed_iff_thr 3 false (by decide) (by decide)) (by decide) (by decide) (by decide) (by decide)
  · exact maxChain_of _ (thrList 1 true) [0, 2, 3] 2 (fixed_iff_thr 1 true (by decide) (by decide))
      (by decide) (by decide) (by decide) (by decide)
  · exact maxChain_of _ (thrList 2 true) [0, 8, 14, 15] 3
      (fixed_iff_thr 2 true (by decide) (by decide)) (by decide) (by decide) (by decide) (by decide)
  · exact maxChain_of _ (thrList 3 true) [0, 128, 232, 254, 255] 4
      (fixed_iff_thr 3 true (by decide) (by decide)) (by decide) (by decide) (by decide) (by decide)

/-! ## 6. Automorphisms -/

/-- `φ` is a lattice automorphism of `FD(n)`: a bijection of `FD(n)` preserving `∧` and `∨`. -/
def IsAut (n : Nat) (bnd : Bool) (φ : Nat → Nat) : Prop :=
  (∀ f, FDset n bnd f → FDset n bnd (φ f)) ∧
  (∀ f g, FDset n bnd f → FDset n bnd g → φ f = φ g → f = g) ∧
  (∀ g, FDset n bnd g → ∃ f, FDset n bnd f ∧ φ f = g) ∧
  (∀ f g, FDset n bnd f → FDset n bnd g →
    φ (f &&& g) = φ f &&& φ g ∧ φ (f ||| g) = φ f ||| φ g)

/-- Clause (1), "`Aut(FD(n))` is the symmetric group": every automorphism is induced by a
permutation of the variables. -/
def AutIsSym (n : Nat) (bnd : Bool) : Prop :=
  ∀ φ, IsAut n bnd φ → ∃ σ, IsPerm n σ ∧ ∀ f, FDset n bnd f → φ f = act n σ f

/-- Elements fixed by the whole automorphism group. -/
def FixedAut (n : Nat) (bnd : Bool) (f : Nat) : Prop :=
  FDset n bnd f ∧ ∀ φ, IsAut n bnd φ → φ f = f

/-- The finite check behind `act_isAut`. -/
def ActAutCheck (n : Nat) (bnd : Bool) : Prop :=
  ∀ σ ∈ allLists n n, IsPerm n σ →
    (∀ f ∈ FDL n bnd, act n σ f ∈ FDL n bnd) ∧
    (∀ f ∈ FDL n bnd, ∀ g ∈ FDL n bnd, act n σ f = act n σ g → f = g) ∧
    (∀ g ∈ FDL n bnd, ∃ f ∈ FDL n bnd, act n σ f = g) ∧
    (∀ f ∈ FDL n bnd, ∀ g ∈ FDL n bnd,
      act n σ (f &&& g) = act n σ f &&& act n σ g ∧ act n σ (f ||| g) = act n σ f ||| act n σ g)

instance (n : Nat) (bnd : Bool) : Decidable (ActAutCheck n bnd) := by
  unfold ActAutCheck; infer_instance

theorem actAutCheck : ∀ n bnd, 1 ≤ n → n ≤ 3 → ActAutCheck n bnd := by
  intro n bnd h1 h3
  match n, bnd, h1, h3 with
  | 1, false, _, _ => decide +kernel
  | 1, true, _, _ => decide +kernel
  | 2, false, _, _ => decide +kernel
  | 2, true, _, _ => decide +kernel
  | 3, false, _, _ => decide +kernel
  | 3, true, _, _ => decide +kernel

/-- Every permutation of the variables is a lattice automorphism of `FD(n)` (`1 ≤ n ≤ 3`),
so `S_n ≤ Aut(FD(n))`; in particular `IsAut` is satisfiable. -/
theorem act_isAut (n : Nat) (bnd : Bool) (h1 : 1 ≤ n) (h3 : n ≤ 3) (σ : List Nat)
    (hσ : IsPerm n σ) : IsAut n bnd (act n σ) := by
  have hm := fun f => (fd_spec n bnd h1 h3 f).2
  obtain ⟨c1, c2, c3, c4⟩ := actAutCheck n bnd h1 h3 σ (isPerm_mem hσ) hσ
  refine ⟨fun f hf => (hm _).mpr (c1 f ((hm f).mp hf)),
    fun f g hf hg h => c2 f ((hm f).mp hf) g ((hm g).mp hg) h,
    fun g hg => ?_, fun f g hf hg => c4 f ((hm f).mp hf) g ((hm g).mp hg)⟩
  obtain ⟨f, hf, h⟩ := c3 g ((hm g).mp hg)
  exact ⟨f, (hm f).mpr hf, h⟩

/-- Under clause (1), the fixed points of the full automorphism group are the `S_n`-fixed points.
(No assumption that clause (1) is true is made: it is a hypothesis here.) -/
theorem fixedAut_iff (n : Nat) (bnd : Bool) (h1 : 1 ≤ n) (h3 : n ≤ 3) (hA : AutIsSym n bnd) :
    ∀ f, FixedAut n bnd f ↔ Fixed n bnd f := by
  intro f
  constructor
  · intro h
    exact ⟨h.1, fun σ hσ => h.2 _ (act_isAut n bnd h1 h3 σ hσ)⟩
  · intro h
    refine ⟨h.1, fun φ hφ => ?_⟩
    obtain ⟨σ, hσ, he⟩ := hA φ hφ
    rw [he f h.1]
    exact h.2 σ hσ

/-! ## 7. Partition numbers -/

/-- `l` is a partition of `n`: positive parts, nonincreasing, summing to `n`. -/
def IsPartition (n : Nat) (l : List Nat) : Prop :=
  l.sum = n ∧ (∀ x ∈ l, 0 < x) ∧ l.Pairwise (fun a b => b ≤ a)

instance (n : Nat) (l : List Nat) : Decidable (IsPartition n l) := by
  unfold IsPartition; infer_instance

/-- All partitions of `n` (every partition has at most `n` parts, each `≤ n`). -/
def partitionsL (n : Nat) : List (List Nat) :=
  ((List.range (n + 1)).flatMap fun len => allLists len (n + 1)).filter
    fun l => decide (IsPartition n l)

/-- The partition number `p(n)`. -/
def p (n : Nat) : Nat := (partitionsL n).length

theorem le_sum_of_mem : ∀ (l : List Nat) (x : Nat), x ∈ l → x ≤ l.sum
  | [], _, h => by simp at h
  | a :: l, x, h => by
    simp only [List.mem_cons] at h
    simp only [List.sum_cons]
    rcases h with rfl | h
    · omega
    · have := le_sum_of_mem l x h; omega

theorem length_le_sum : ∀ (l : List Nat), (∀ x ∈ l, 0 < x) → l.length ≤ l.sum
  | [], _ => by simp
  | a :: l, h => by
    have ha := h a (by simp)
    have := length_le_sum l (fun x hx => h x (by simp [hx]))
    simp only [List.length_cons, List.sum_cons]
    omega

/-- `partitionsL n` lists exactly the partitions of `n` (for every `n`). -/
theorem mem_partitionsL (n : Nat) (l : List Nat) : l ∈ partitionsL n ↔ IsPartition n l := by
  unfold partitionsL
  rw [List.mem_filter]
  constructor
  · intro h; exact of_decide_eq_true h.2
  · intro h
    refine ⟨?_, decide_eq_true h⟩
    rw [List.mem_flatMap]
    have hlen := length_le_sum l h.2.1
    have hs : l.sum = n := h.1
    refine ⟨l.length, List.mem_range.mpr (by omega), mem_allLists (n + 1) _ l rfl ?_⟩
    intro x hx
    have := le_sum_of_mem l x hx
    omega

/-- `p(1..5) = 1, 2, 3, 5, 7`, and the enumerations are duplicate-free (so `p` counts). -/
theorem p_values : p 1 = 1 ∧ p 2 = 2 ∧ p 3 = 3 ∧ p 4 = 5 ∧ p 5 = 7 ∧
    (partitionsL 1).Nodup ∧ (partitionsL 2).Nodup ∧ (partitionsL 3).Nodup := by
  decide +kernel

/-! ## 8. Logarithms in an arbitrary number system -/

/-- A number system: associative multiplication with unit and an injective multiplicative cast
of the naturals.  `ℕ`, `ℤ`, `ℚ`, `ℝ`, `ℂ` (and every ring of characteristic 0) are instances. -/
structure NumSys (α : Type) where
  one : α
  mul : α → α → α
  cast : Nat → α
  one_mul : ∀ x, mul one x = x
  mul_one : ∀ x, mul x one = x
  mul_assoc : ∀ x y z, mul (mul x y) z = mul x (mul y z)
  cast_one : cast 1 = one
  cast_mul : ∀ a b, cast (a * b) = mul (cast a) (cast b)
  cast_inj : ∀ a b, cast a = cast b → a = b

variable {α : Type}

/-- Natural powers `b^k`. -/
def NumSys.pow (R : NumSys α) (b : α) : Nat → α
  | 0 => R.one
  | k + 1 => R.mul (R.pow b k) b

/-- `log_b x = y` with `y` a natural number means `b^y = x`; for real `b > 0`, `b ≠ 1`, and
`x > 0` this is the definition of the logarithm, so `y = log_b x ↔ R.pow b y = R.cast x`. -/
def IsLog (R : NumSys α) (b : α) (x y : Nat) : Prop := R.pow b y = R.cast x

/-- **Clause (3), `S_n` version.**  There is a base `b` with
`(maximal chain length of the fixed lattice) = log_b p(n)` for every `n ≥ 1`.
`bnd` selects the bounded free distributive lattice, `elems` counts chain length in elements. -/
def LogClause (R : NumSys α) (bnd elems : Bool) : Prop :=
  ∃ b : α, ∀ n k, 1 ≤ n → MaxChainLen (Fixed n bnd) k →
    IsLog R b (p n) (k + if elems then 1 else 0)

/-- The arithmetic heart: `b^s = 1, b^(s+1) = 2, b^(s+2) = 3` is impossible
(the middle equation forces `b = 2`, and then `b^(s+2) = 4 ≠ 3`). -/
theorem no_consecutive (R : NumSys α) (b : α) (s : Nat) (h1 : R.pow b s = R.cast 1)
    (h2 : R.pow b (s + 1) = R.cast 2) (h3 : R.pow b (s + 2) = R.cast 3) : False := by
  have hb : b = R.cast 2 := by
    have : R.pow b (s + 1) = b := by
      show R.mul (R.pow b s) b = b
      rw [h1, R.cast_one, R.one_mul]
    rw [← this, h2]
  have h4 : R.pow b (s + 2) = R.cast (2 * 2) := by
    show R.mul (R.pow b (s + 1)) b = R.cast (2 * 2)
    rw [h2, R.cast_mul, ← hb]
  have := R.cast_inj _ _ (h4.symm.trans h3)
  omega

theorem chainLen_unique {P : Nat → Prop} {k k' : Nat} (h : MaxChainLen P k)
    (h' : MaxChainLen P k') : k = k' := by
  obtain ⟨⟨L, hL, hlen⟩, hmax⟩ := h
  obtain ⟨⟨L', hL', hlen'⟩, hmax'⟩ := h'
  have a := hmax L' hL'
  have b := hmax' L hL
  omega

theorem pow_zero_eq (R : NumSys α) (b : α) : R.pow b 0 = R.cast 1 := by
  rw [R.cast_one]; rfl

/-- The contradiction only uses `n = 1, 2, 3`. -/
theorem log_contra (R : NumSys α) (b : α) (bnd elems : Bool)
    (hb : ∀ n k, 1 ≤ n → n ≤ 3 → MaxChainLen (Fixed n bnd) k →
      IsLog R b (p n) (k + if elems then 1 else 0)) : False := by
  obtain ⟨c1u, c2u, c3u, c1b, c2b, c3b⟩ := maxChain_fixed
  obtain ⟨p1, p2, p3, -⟩ := p_values
  have e1 := hb 1
  have e2 := hb 2
  have e3 := hb 3
  unfold IsLog at e1 e2 e3
  rw [p1] at e1; rw [p2] at e2; rw [p3] at e3
  cases bnd <;> cases elems
  · -- free lattice, edges: lengths 0, 1, 2
    exact no_consecutive R b 0 (e1 0 (by decide) (by decide) c1u)
      (e2 1 (by decide) (by decide) c2u) (e3 2 (by decide) (by decide) c3u)
  · -- free lattice, elements: 1, 2, 3
    exact no_consecutive R b 1 (e1 0 (by decide) (by decide) c1u)
      (e2 1 (by decide) (by decide) c2u) (e3 2 (by decide) (by decide) c3u)
  · -- bounded lattice, edges: 2, 3, 4
    exact no_consecutive R b 2 (e1 2 (by decide) (by decide) c1b)
      (e2 3 (by decide) (by decide) c2b) (e3 4 (by decide) (by decide) c3b)
  · -- bounded lattice, elements: 3, 4, 5
    exact no_consecutive R b 3 (e1 2 (by decide) (by decide) c1b)
      (e2 3 (by decide) (by decide) c2b) (e3 4 (by decide) (by decide) c3b)

/-- **Clause (3) is false (`S_n` fixed points)**, for every base in every number system, for both
the free and the free bounded distributive lattice, and for chain length counted in covering
steps or in elements. -/
theorem logClause_false (R : NumSys α) (bnd elems : Bool) : ¬ LogClause R bnd elems := by
  rintro ⟨b, hb⟩
  exact log_contra R b bnd elems fun n k h1 _ hk => hb n k h1 hk

/-- **The conjecture**, with clause (1) `Aut(FD(n)) = S_n`, an arbitrary clause (2) `C2`, and
clause (3) for the fixed-point lattice of the full automorphism group. -/
def Conjecture (R : NumSys α) (C2 : Nat → Prop) (bnd elems : Bool) : Prop :=
  (∀ n, 1 ≤ n → AutIsSym n bnd) ∧ (∀ n, 1 ≤ n → C2 n) ∧
  ∃ b : α, ∀ n k, 1 ≤ n → MaxChainLen (FixedAut n bnd) k →
    IsLog R b (p n) (k + if elems then 1 else 0)

/-- **Main theorem: conjecture 00000008556 is false**, for every base `b` of the logarithm in
every number system, whatever clause (2) means, for the free and the free bounded distributive
lattice, and for chain length in edges or in elements.  If clause (1) fails the conjunction fails;
if it holds, the fixed lattice of `Aut` is the `S_n`-fixed chain and clause (3) fails. -/
theorem conjecture_00000008556_false (R : NumSys α) (C2 : Nat → Prop) (bnd elems : Bool) :
    ¬ Conjecture R C2 bnd elems := by
  rintro ⟨hA, -, b, hb⟩
  exact log_contra R b bnd elems fun n k h1 h3 hk =>
    hb n k h1 (maxChain_congr (fun f => (fixedAut_iff n bnd h1 h3 (hA n h1) f).symm) hk)

/-! ## 9. A stronger arithmetic fact: no chain lengths whatsoever fit at `n = 2, 3` -/

theorem pow_add (R : NumSys α) (b : α) (m : Nat) : ∀ k, R.pow b (m + k) = R.mul (R.pow b m) (R.pow b k)
  | 0 => by show R.pow b m = R.mul (R.pow b m) R.one; rw [R.mul_one]
  | k + 1 => by
    show R.mul (R.pow b (m + k)) b = R.mul (R.pow b m) (R.mul (R.pow b k) b)
    rw [pow_add R b m k, R.mul_assoc]

theorem pow_mul (R : NumSys α) (b : α) (m : Nat) : ∀ k, R.pow b (m * k) = R.pow (R.pow b m) k
  | 0 => rfl
  | k + 1 => by
    rw [Nat.mul_succ, pow_add, pow_mul R b m k]
    rfl

theorem cast_pow (R : NumSys α) (a : Nat) : ∀ k, R.cast (a ^ k) = R.pow (R.cast a) k
  | 0 => R.cast_one
  | k + 1 => by
    rw [Nat.pow_succ, R.cast_mul, cast_pow R a k]
    rfl

theorem three_pow_odd : ∀ c : Nat, 3 ^ c % 2 = 1
  | 0 => rfl
  | c + 1 => by
    rw [Nat.pow_succ]
    have := three_pow_odd c
    omega

theorem two_pow_eq_three_pow (a c : Nat) (h : 2 ^ a = 3 ^ c) : a = 0 ∧ c = 0 := by
  have hodd := three_pow_odd c
  cases a with
  | succ a =>
    rw [Nat.pow_succ] at h
    omega
  | zero =>
    refine ⟨rfl, ?_⟩
    cases c with
    | zero => rfl
    | succ c =>
      rw [Nat.pow_succ] at h
      simp at h
      omega

/-- **Robustness.** For *any* natural numbers `L₂, L₃` (whatever lattice, chain notion or
convention produced them) and any base `b`: `L₂ = log_b p(2)` and `L₃ = log_b p(3)` cannot both
hold, since `b^(L₂L₃)` would equal both `2^L₃` and `3^L₂`. -/
theorem no_lengths_fit (R : NumSys α) (b : α) (L2 L3 : Nat) :
    ¬ (IsLog R b (p 2) L2 ∧ IsLog R b (p 3) L3) := by
  rintro ⟨h2, h3⟩
  unfold IsLog at h2 h3
  obtain ⟨-, p2, p3, -⟩ := p_values
  rw [p2] at h2; rw [p3] at h3
  have e1 : R.pow b (L2 * L3) = R.cast (2 ^ L3) := by rw [pow_mul, h2, cast_pow]
  have e2 : R.pow b (L3 * L2) = R.cast (3 ^ L2) := by rw [pow_mul, h3, cast_pow]
  rw [Nat.mul_comm] at e1
  have h := R.cast_inj _ _ (e1.symm.trans e2)
  obtain ⟨rfl, rfl⟩ := two_pow_eq_three_pow L3 L2 h
  have h0 : R.cast 1 = R.cast 2 := by rw [← pow_zero_eq R b]; exact h2
  have := R.cast_inj _ _ h0
  omega

/-! ## 10. Non-vacuity -/

def natSys : NumSys Nat where
  one := 1
  mul := (· * ·)
  cast := id
  one_mul := Nat.one_mul
  mul_one := Nat.mul_one
  mul_assoc := Nat.mul_assoc
  cast_one := rfl
  cast_mul := fun _ _ => rfl
  cast_inj := fun _ _ h => h

def intSys : NumSys Int where
  one := 1
  mul := (· * ·)
  cast := Int.ofNat
  one_mul := Int.one_mul
  mul_one := Int.mul_one
  mul_assoc := Int.mul_assoc
  cast_one := rfl
  cast_mul := fun _ _ => rfl
  cast_inj := fun _ _ h => Int.ofNat.inj h

/-- The clause does hold for `n = 1, 2` with base `b = 2` (edges, free lattice): so the predicate
is satisfiable and the failure genuinely happens at `n = 3`. -/
theorem clause_holds_n_le_2 : ∀ n k, 1 ≤ n → n ≤ 2 → MaxChainLen (Fixed n false) k →
    IsLog natSys 2 (p n) k := by
  intro n k h1 h2 hk
  obtain ⟨c1, c2, -⟩ := maxChain_fixed
  obtain ⟨p1, p2, -⟩ := p_values
  unfold IsLog
  match n, h1, h2 with
  | 1, _, _ => rw [chainLen_unique hk c1, p1]; rfl
  | 2, _, _ => rw [chainLen_unique hk c2, p2]; rfl

/-- In `ℤ`: the conjecture fails (instance of the main theorem). -/
theorem conjecture_false_int (C2 : Nat → Prop) : ¬ Conjecture intSys C2 false false :=
  conjecture_00000008556_false intSys C2 false false

end FDL

#print axioms FDL.fd_spec
#print axioms FDL.fixed_iff_thr
#print axioms FDL.maxChain_fixed
#print axioms FDL.act_isAut
#print axioms FDL.p_values
#print axioms FDL.logClause_false
#print axioms FDL.conjecture_00000008556_false
#print axioms FDL.no_lengths_fit
#print axioms FDL.clause_holds_n_le_2
