"""Independent exact polynomial multiplication for Conjecture 6557 only."""
from fractions import Fraction as Q
from itertools import product
from math import factorial
from pathlib import Path
import json

stages=[(0,Q(1,12)),(1,Q(1,6)),(0,Q(1,6)),(1,Q(1,6)),
        (0,Q(1,6)),(1,Q(1,6)),(0,Q(1,6)),(1,Q(1,6)),
        (0,Q(-1,12)),(1,Q(-1,3)),(0,Q(-1,12)),(1,Q(1,6)),
        (0,Q(1,6)),(1,Q(1,6)),(0,Q(1,6)),(1,Q(1,6)),
        (0,Q(1,6)),(1,Q(1,6)),(0,Q(1,12))]
assert all(a!=0 for b,a in stages)
assert all(stages[i][0]!=stages[i+1][0] for i in range(18))
assert stages==list(reversed(stages))
for letter in (0,1):
    assert sum((a for b,a in stages if b==letter),Q(0))==1
coeff={():Q(1)}
for letter,a in stages:
    factor={tuple([letter]*n):a**n/factorial(n) for n in range(5)}
    nxt={}
    for u,cu in coeff.items():
        for v,cv in factor.items():
            if len(u+v)<=4:
                nxt[u+v]=nxt.get(u+v,Q(0))+cu*cv
    coeff=nxt
words=[w for n in range(5) for w in product((0,1),repeat=n)]
assert len(words)==31
assert all(coeff.get(w,Q(0))==Q(1,factorial(len(w))) for w in words)
neg=[a for b,a in stages if a<0]
assert neg==[Q(-1,12),Q(-1,3),Q(-1,12)]
assert sum(neg)==Q(-1,2)
assert sum(abs(a) for a in neg)==Q(1,2)
result={'id':6557,'stages':19,'all_words_through_degree':4,
        'words_checked':31,'formal_order_at_least':4,
        'negative_coefficients':['-1/12','-1/3','-1/12'],
        'signed_negative_sum':'-1/2','negative_absolute_sum':'1/2',
        'pdf_validation':'separate; no PDF generated by this check'}
Path(__file__).with_name('independent_check.json').write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8')
print(json.dumps(result))
