import Conjecture7744
import Audit

#print Conjecture7744.RegularGraph
#print Conjecture7744.quadraticTrace
#print Conjecture7744.uniformGraphs
#print Conjecture7744.quadraticExpectation
#print Conjecture7744.quadraticFluctuation
#print Conjecture7744.quadraticLaw
#print Conjecture7744.zeroLaw
#print Conjecture7744.polynomialTrace
#print Conjecture7744.polynomialExpectation
#print Conjecture7744.polynomialFluctuation
#print Conjecture7744.polynomialLaw
#print Conjecture7744.jointFluctuation
#print Conjecture7744.jointLaw
#print Conjecture7744.coordinateLaw
#print Conjecture7744.BlockVertices
#print Conjecture7744.blockGraph
#print Conjecture7744.lawVariance
#print Conjecture7744.claimedVariance
#print Conjecture7744.RequiredSecondOrderLimit

#check Conjecture7744.regularGraphFintype
#print axioms Conjecture7744.regularGraphFintype
#check Conjecture7744.regularGraphMeasurableSpace
#print axioms Conjecture7744.regularGraphMeasurableSpace
#check Conjecture7744.quadraticTrace_eq
#print axioms Conjecture7744.quadraticTrace_eq
#check Conjecture7744.uniformGraphs_mass
#print axioms Conjecture7744.uniformGraphs_mass
#check Conjecture7744.quadraticExpectation_eq
#print axioms Conjecture7744.quadraticExpectation_eq
#check Conjecture7744.quadraticFluctuation_zero
#print axioms Conjecture7744.quadraticFluctuation_zero
#check Conjecture7744.finite_quadratic_variance_zero
#print axioms Conjecture7744.finite_quadratic_variance_zero
#check Conjecture7744.quadraticLaw_is_pushforward
#print axioms Conjecture7744.quadraticLaw_is_pushforward
#check Conjecture7744.quadraticLaw_eq_zeroLaw
#print axioms Conjecture7744.quadraticLaw_eq_zeroLaw
#check Conjecture7744.polynomialTrace_square
#print axioms Conjecture7744.polynomialTrace_square
#check Conjecture7744.polynomialTrace_integrable
#print axioms Conjecture7744.polynomialTrace_integrable
#check Conjecture7744.polynomialFluctuation_square
#print axioms Conjecture7744.polynomialFluctuation_square
#check Conjecture7744.polynomialLaw_is_pushforward
#print axioms Conjecture7744.polynomialLaw_is_pushforward
#check Conjecture7744.polynomialLaw_square
#print axioms Conjecture7744.polynomialLaw_square
#check Conjecture7744.jointLaw_is_pushforward
#print axioms Conjecture7744.jointLaw_is_pushforward
#check Conjecture7744.jointLaw_coordinate
#print axioms Conjecture7744.jointLaw_coordinate
#check Conjecture7744.coordinateLaw_tendsto
#print axioms Conjecture7744.coordinateLaw_tendsto
#check Conjecture7744.blockVerticesFintype
#print axioms Conjecture7744.blockVerticesFintype
#check Conjecture7744.blockGraph_regular
#print axioms Conjecture7744.blockGraph_regular
#check Conjecture7744.blockRegularGraphsNonempty
#print axioms Conjecture7744.blockRegularGraphsNonempty
#check Conjecture7744.blockVertices_card
#print axioms Conjecture7744.blockVertices_card
#check Conjecture7744.blockVertices_card_pos
#print axioms Conjecture7744.blockVertices_card_pos
#check Conjecture7744.blockVertices_card_tendsto
#print axioms Conjecture7744.blockVertices_card_tendsto
#check Conjecture7744.zeroLaw_variance
#print axioms Conjecture7744.zeroLaw_variance
#check Conjecture7744.quadraticLaws_tendsto_zero
#print axioms Conjecture7744.quadraticLaws_tendsto_zero
#check Conjecture7744.quadratic_weak_limit_variance
#print axioms Conjecture7744.quadratic_weak_limit_variance
#check Conjecture7744.claimedVariance_three
#print axioms Conjecture7744.claimedVariance_three
#check Conjecture7744.no_claimed_quadratic_limit
#print axioms Conjecture7744.no_claimed_quadratic_limit
#check Conjecture7744.no_required_second_order_limit
#print axioms Conjecture7744.no_required_second_order_limit
#check Conjecture7744.conjecture7744_false
#print axioms Conjecture7744.conjecture7744_false
