import Mathlib

/-!
# Conjecture 00000000504 (disproof)

Statement: "pd R/I(G) has threshold 2r - 1 for r-partite r-uniform hypergraphs (generalizing the
Froberg-type theorem pd <= 3 for bipartite graphs)", where `R = k[x_v : v ∈ V]` and `I(G)` is the
edge ideal.

We refute
* (A) `pd_R (R ⧸ I(G)) ≤ 2r - 1` for every `r`-partite `r`-uniform `G`
  (`conjecture504_upper_bound_false`, every field `k`, every `r ≥ 1`; for `r = 2` this is the
  quoted bound `pd ≤ 3` for bipartite graphs);
* (B) "the supremum of `pd` over the class is `2r - 1`": `pd` is unbounded on the class
  (`conjecture504_unbounded`).

Witness: the `r`-uniform matching with `m` pairwise disjoint edges. Its edge monomials involve
pairwise disjoint variables, hence form a regular sequence, and `pd_R (R ⧸ I) ≥ m`.

`pd` is Mathlib's `CategoryTheory.projectiveDimension` (values in `WithBot ℕ∞`) of the `R`-module
`R ⧸ I(G)` in `ModuleCat R`. Only lower bounds on `pd` are proved; since every finite free
resolution of length `ℓ` gives `pd ≤ ℓ`, a minimal free resolution has length `≥ pd`.
-/

open MvPolynomial CategoryTheory RingTheory.Sequence

namespace Conjecture504

universe u

/-- A finite hypergraph on the vertex type `V`: a finite set of edges, each a finite set of
vertices. -/
structure Hypergraph (V : Type) where
  edges : Finset (Finset V)

namespace Hypergraph

variable {V : Type} (G : Hypergraph V) (r : ℕ)

/-- `G` is `r`-uniform: every edge has exactly `r` vertices. -/
def IsUniform : Prop := ∀ e ∈ G.edges, e.card = r

/-- `G` is `r`-partite: the vertex set is split into `r` parts `part ⁻¹' {j}` (`j : Fin r`)
such that every edge meets every part in exactly one vertex. -/
def IsPartite : Prop :=
  ∃ part : V → Fin r, ∀ e ∈ G.edges, ∀ j : Fin r, ∃! v, v ∈ e ∧ part v = j

end Hypergraph

/-- The edge ideal `I(G) ⊆ k[x_v : v ∈ V]`, generated by the edge monomials `∏_{v ∈ e} x_v`. -/
noncomputable def edgeIdeal (k : Type u) [Field k] {V : Type} (G : Hypergraph V) : Ideal (MvPolynomial V k) :=
  Ideal.span ((fun e : Finset V => ∏ v ∈ e, (X v : MvPolynomial V k)) '' (G.edges : Set (Finset V)))

section Regular

variable {k : Type u} [Field k] {σ : Type}

/-- Colon step: if `x^e` shares no variable with any generator `x^d` (`d ∈ s`) of a monomial
ideal, then `x^e * g ∈ (x^d : d ∈ s)` forces `g ∈ (x^d : d ∈ s)`. -/
theorem mem_of_monomial_mul_mem {s : Set (σ →₀ ℕ)} {e : σ →₀ ℕ}
    (hdisj : ∀ d ∈ s, ∀ v, d v = 0 ∨ e v = 0) {g : MvPolynomial σ k}
    (h : monomial e 1 * g ∈ Ideal.span ((fun d => monomial d (1 : k)) '' s)) :
    g ∈ Ideal.span ((fun d => monomial d (1 : k)) '' s) := by
  rw [mem_ideal_span_monomial_image] at h ⊢
  intro x hx
  have hx' : e + x ∈ (monomial e 1 * g).support := by
    rw [mem_support_iff, coeff_monomial_mul, one_mul]; exact mem_support_iff.mp hx
  obtain ⟨d, hd, hle⟩ := h _ hx'
  refine ⟨d, hd, Finsupp.le_def.2 fun v => ?_⟩
  have := Finsupp.le_def.1 hle v
  rcases hdisj d hd v with h0 | h0
  · simp [h0]
  · simpa [h0] using this

/-- Monomials `x^{d 0}, …, x^{d (m-1)}` whose exponent vectors have pairwise disjoint supports
form a weakly regular sequence in `k[x_σ]`. -/
theorem isWeaklyRegular_monomials {m : ℕ} (d : Fin m → σ →₀ ℕ)
    (hd : ∀ a b, a ≠ b → ∀ v, d a v = 0 ∨ d b v = 0) :
    IsWeaklyRegular (MvPolynomial σ k) ((List.ofFn d).map fun e => monomial e (1 : k)) := by
  rw [isWeaklyRegular_iff_Fin]
  intro i
  have hI : (Ideal.ofList (((List.ofFn d).map fun e => monomial e (1 : k)).take i) • ⊤ :
      Submodule (MvPolynomial σ k) (MvPolynomial σ k)) =
      Ideal.span ((fun e => monomial e (1 : k)) '' {e | e ∈ (List.ofFn d).take i}) := by
    rw [smul_eq_mul, Ideal.mul_top, ← List.map_take, Ideal.ofList]
    congr 1
    ext f
    simp only [Set.mem_ofPred_eq, Set.mem_image, List.mem_map]
  rw [hI]
  have hi : ((List.ofFn d).map fun e => monomial e (1 : k))[i] =
      monomial (d ⟨i, by simpa using i.2⟩) 1 := by simp
  rw [hi]
  intro x y hxy
  obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ x
  obtain ⟨y, rfl⟩ := Submodule.Quotient.mk_surjective _ y
  simp only [← Submodule.Quotient.mk_smul, Submodule.Quotient.eq, smul_eq_mul, ← mul_sub] at hxy ⊢
  refine mem_of_monomial_mul_mem (fun e he v => ?_) hxy
  obtain ⟨j, hj, rfl⟩ := List.mem_iff_getElem.mp he
  simp only [List.length_take, List.length_ofFn, lt_min_iff] at hj
  rw [List.getElem_take, List.getElem_ofFn]
  exact hd _ _ (fun h => by simp [Fin.ext_iff] at h; omega) v

/-- Lower bound for the projective dimension: if `rs` is a weakly regular sequence in
`R = k[x_σ]` (`σ` finite) whose members have zero constant term, then
`length rs ≤ pd_R (R ⧸ (rs))`. Proof: localize at the maximal ideal `p = ker (constantCoeff)`;
there `rs` is a regular sequence of the Noetherian local ring `R_p`, so
`pd_{R_p} (R_p ⧸ (rs)) = length rs` (Mathlib), and localization does not increase `pd`. -/
theorem length_le_projectiveDimension [Finite σ] (rs : List (MvPolynomial σ k))
    (reg : IsWeaklyRegular (MvPolynomial σ k) rs) (h0 : ∀ f ∈ rs, constantCoeff f = 0) :
    (rs.length : WithBot ℕ∞) ≤ projectiveDimension
      (ModuleCat.of (MvPolynomial σ k) (MvPolynomial σ k ⧸ Ideal.ofList rs)) := by
  let R := MvPolynomial σ k
  let p : Ideal R := RingHom.ker (constantCoeff : R →+* k)
  have : p.IsPrime := RingHom.ker_isPrime _
  let Rp := Localization.AtPrime p
  have : IsNoetherianRing Rp := IsLocalization.isNoetherianRing p.primeCompl Rp inferInstance
  have hreg : IsRegular Rp (rs.map (algebraMap R Rp)) :=
    reg.isRegular_of_isLocalization_of_mem Rp p (fun f hf => RingHom.mem_ker.2 (h0 f hf))
  have hpd := ModuleCat.projectiveDimension_quotient_eq_length (R := Rp) _ hreg
  rw [List.length_map] at hpd
  let M := ModuleCat.of R (R ⧸ Ideal.ofList rs)
  have hle := ModuleCat.projectiveDimension_le_projectiveDimension_of_isLocalizedModule
    p.primeCompl M
  let g := (Ideal.ofList rs : Submodule R R).toLocalizedQuotient' Rp p.primeCompl
    (Algebra.linearMap R Rp)
  have := ModuleCat.localizedModule_isLocalizedModule M p.primeCompl
  let e1 := IsLocalizedModule.linearEquiv p.primeCompl (M.localizedModuleMkLinearMap p.primeCompl) g
  let e2 := e1.extendScalarsOfIsLocalization p.primeCompl Rp
  have hJ : (Ideal.ofList rs : Submodule R R).localized' Rp p.primeCompl (Algebra.linearMap R Rp) =
      (Ideal.ofList (rs.map (algebraMap R Rp)) : Submodule Rp Rp) := by
    rw [Ideal.ofList, Ideal.ofList]
    erw [Submodule.localized'_span]
    congr 1
    ext f
    simp [List.mem_map]
  let e := (e2.trans (Submodule.quotEquivOfEq _ _ hJ)).trans (Shrink.linearEquiv Rp _).symm
  calc (rs.length : WithBot ℕ∞) = _ := hpd.symm
    _ = projectiveDimension (M.localizedModule p.primeCompl) :=
        (projectiveDimension_eq_of_iso e.toModuleIso).symm
    _ ≤ _ := hle

end Regular

section Matching

/-- The `r`-uniform matching with `m` edges: vertex `(i, j)` is the `j`-th vertex of the `i`-th
edge `e_i = {(i, 0), …, (i, r - 1)}`; distinct edges are disjoint. -/
def matching (m r : ℕ) : Hypergraph (Fin m × Fin r) where
  edges := Finset.univ.image fun i : Fin m =>
    Finset.univ.map ⟨Prod.mk i, Prod.mk_right_injective i⟩

theorem matching_isUniform (m r : ℕ) : (matching m r).IsUniform r := by
  intro e he
  obtain ⟨i, -, rfl⟩ := Finset.mem_image.mp he
  simp

/-- The matching is `r`-partite with parts `V_j = {(i, j) : i < m}`. -/
theorem matching_isPartite (m r : ℕ) : (matching m r).IsPartite r := by
  refine ⟨Prod.snd, fun e he j => ?_⟩
  obtain ⟨i, -, rfl⟩ := Finset.mem_image.mp he
  refine ⟨(i, j), by simp, ?_⟩
  rintro ⟨a, b⟩ ⟨hv, rfl⟩
  simp only [Finset.mem_map, Finset.mem_univ, Function.Embedding.coeFn_mk, true_and,
    Prod.mk.injEq] at hv
  obtain ⟨_, rfl, -⟩ := hv
  rfl

/-- Exponent vector of the edge monomial of `e_i`: `∑_j δ_{(i,j)}`. -/
noncomputable def edgeExp {m r : ℕ} (i : Fin m) : Fin m × Fin r →₀ ℕ :=
  ∑ j : Fin r, Finsupp.single (i, j) 1

theorem edgeExp_apply_of_ne {m r : ℕ} {i : Fin m} {v : Fin m × Fin r} (h : v.1 ≠ i) :
    edgeExp i v = 0 := by
  rcases v with ⟨a, b⟩
  simp only at h
  simp [edgeExp, Ne.symm h]

variable (k : Type u) [Field k]

/-- The edge ideal of the matching is generated by the list of its edge monomials. -/
theorem edgeIdeal_matching (m r : ℕ) : edgeIdeal k (matching m r) =
    Ideal.ofList ((List.ofFn (edgeExp (m := m) (r := r))).map fun e => monomial e (1 : k)) := by
  unfold edgeIdeal Ideal.ofList
  congr 1
  ext f
  simp [matching, edgeExp, monomial_sum_one, X, List.mem_ofFn]

/-- For `r ≥ 1`, the matching with `m` edges has `m ≤ pd_R (R ⧸ I)` (`R = k[x_v]`, any field `k`):
its edge monomials, in pairwise disjoint variables, form a regular sequence. -/
theorem matching_pd_ge (m r : ℕ) (hr : 0 < r) :
    (m : WithBot ℕ∞) ≤ projectiveDimension (ModuleCat.of (MvPolynomial (Fin m × Fin r) k)
      (MvPolynomial (Fin m × Fin r) k ⧸ edgeIdeal k (matching m r))) := by
  rw [edgeIdeal_matching]
  have := length_le_projectiveDimension (k := k) _
    (isWeaklyRegular_monomials (edgeExp (m := m) (r := r)) ?_) ?_
  · simpa using this
  · intro a b hab v
    by_cases h : v.1 = a
    · exact Or.inr (edgeExp_apply_of_ne (h ▸ hab))
    · exact Or.inl (edgeExp_apply_of_ne h)
  · intro f hf
    simp only [List.mem_map, List.mem_ofFn] at hf
    obtain ⟨_, ⟨i, rfl⟩, rfl⟩ := hf
    classical
    rw [constantCoeff_monomial, if_neg]
    intro h0
    have := congrArg (fun d => d (i, ⟨0, hr⟩)) h0
    simp [edgeExp, Finsupp.single_apply] at this

end Matching

/-- **Conjecture 00000000504, reading (A), is false.** For every field `k` and every `r ≥ 1` it is
not true that `pd_R (R ⧸ I(G)) ≤ 2r - 1` for all `r`-partite `r`-uniform hypergraphs `G`
(`R = k[x_v : v ∈ V]`). Witness: the matching with `2r` edges, for which `pd ≥ 2r`. -/
theorem conjecture504_upper_bound_false (k : Type u) [Field k] (r : ℕ) (hr : 0 < r) :
    ¬ ∀ (V : Type) [Fintype V] (G : Hypergraph V), G.IsUniform r → G.IsPartite r →
      projectiveDimension (ModuleCat.of (MvPolynomial V k) (MvPolynomial V k ⧸ edgeIdeal k G)) ≤
        ((2 * r - 1 : ℕ) : WithBot ℕ∞) := by
  intro h
  have h1 := (matching_pd_ge k (2 * r) r hr).trans
    (h _ (matching (2 * r) r) (matching_isUniform _ _) (matching_isPartite _ _))
  have : 2 * r ≤ 2 * r - 1 := by exact_mod_cast h1
  omega

/-- **Reading (B): no finite supremum.** For every field `k`, every `r ≥ 1` and every `N`, some
`r`-partite `r`-uniform hypergraph has `pd_R (R ⧸ I(G)) > N`; so the supremum of `pd` over this
class is not `2r - 1` (nor any finite number). -/
theorem conjecture504_unbounded (k : Type u) [Field k] (r : ℕ) (hr : 0 < r) (N : ℕ) :
    ∃ (V : Type) (_ : Fintype V) (G : Hypergraph V), G.IsUniform r ∧ G.IsPartite r ∧
      (N : WithBot ℕ∞) < projectiveDimension
        (ModuleCat.of (MvPolynomial V k) (MvPolynomial V k ⧸ edgeIdeal k G)) := by
  refine ⟨Fin (N + 1) × Fin r, inferInstance, matching (N + 1) r, matching_isUniform _ _,
    matching_isPartite _ _, lt_of_lt_of_le ?_ (matching_pd_ge k (N + 1) r hr)⟩
  exact_mod_cast Nat.lt_succ_self N

end Conjecture504
