import Conjecture1277.Entropy
import Conjecture1277.Words
import Mathlib.Analysis.SpecificLimits.Basic

open scoped BigOperators
open Filter

namespace Conjecture1277

variable {α : Type*} [Fintype α]

/-- The actual finite trajectory distribution generated by an initial law and a transition kernel. -/
noncomputable def blockLaw (π : PMF α) (K : α → PMF α) : (n : ℕ) → PMF (Word α n)
  | 0 => π
  | n + 1 => joint (blockLaw π K n) (fun x => K (lastState x))

/-- Stationarity of the initial law under one transition. -/
def Stationary (π : PMF α) (K : α → PMF α) : Prop := π.bind K = π

/-- A finite sum used in the theorem identifying the entropy-rate limit. -/
noncomputable def meanRowEntropy (π : PMF α) (K : α → PMF α) : ℝ :=
  ∑ i, (π i).toReal * entropy (K i)

/-- Entropy rate means the limit of actual block entropies per state. -/
def HasEntropyRate (π : PMF α) (K : α → PMF α) (h : ℝ) : Prop :=
  Tendsto (fun n : ℕ => entropy (blockLaw π K n) / ((n : ℝ) + 1)) atTop (nhds h)

theorem blockLaw_append (π : PMF α) (K : α → PMF α) (n : ℕ)
    (x : Word α n) (y : α) :
    blockLaw π K (n + 1) (x, y) = blockLaw π K n x * K (lastState x) y :=
  joint_apply _ _ _ _

omit [Fintype α] in
theorem blockLaw_consistent (π : PMF α) (K : α → PMF α) (n : ℕ) :
    (blockLaw π K (n + 1)).map Prod.fst = blockLaw π K n :=
  joint_map_fst _ _

theorem blockLaw_markov (π : PMF α) (K : α → PMF α) (n : ℕ)
    (x : Word α n) (y : α) (hx : blockLaw π K n x ≠ 0) :
    (blockLaw π K (n + 1) (x, y)).toReal / (blockLaw π K n x).toReal =
      (K (lastState x) y).toReal := by
  rw [blockLaw_append, ENNReal.toReal_mul]
  exact mul_div_cancel_left₀ _ (ne_of_gt (ENNReal.toReal_pos hx ((blockLaw π K n).apply_ne_top x)))

omit [Fintype α] in
theorem blockLaw_last (π : PMF α) (K : α → PMF α) (h : Stationary π K) (n : ℕ) :
    (blockLaw π K n).map lastState = π := by
  induction n with
  | zero => exact PMF.map_id π
  | succ n ih =>
    change (joint (blockLaw π K n) (fun x => K (lastState x))).map Prod.snd = π
    rw [joint_map_snd]
    change (blockLaw π K n).bind (K ∘ lastState) = π
    rw [← PMF.bind_map, ih]
    exact h

theorem block_entropy (π : PMF α) (K : α → PMF α) (h : Stationary π K) (n : ℕ) :
    entropy (blockLaw π K n) = entropy π + (n : ℝ) * meanRowEntropy π K := by
  induction n with
  | zero => simp [blockLaw]
  | succ n ih =>
    have hs := expectation_map (blockLaw π K n) (@lastState α n) (fun i => entropy (K i))
    rw [blockLaw_last π K h n] at hs
    change entropy (joint (blockLaw π K n) (fun x => K (lastState x))) = _
    rw [entropy_joint, ih, ← hs]
    simp only [Nat.cast_add, Nat.cast_one, meanRowEntropy]
    ring

theorem normalized_block_entropy (π : PMF α) (K : α → PMF α)
    (h : Stationary π K) (n : ℕ) :
    entropy (blockLaw π K n) / ((n : ℝ) + 1) = meanRowEntropy π K +
      (entropy π - meanRowEntropy π K) / ((n : ℝ) + 1) := by
  rw [block_entropy π K h]
  have hn : (n : ℝ) + 1 ≠ 0 := by positivity
  field_simp
  ring

theorem stationary_hasEntropyRate (π : PMF α) (K : α → PMF α)
    (h : Stationary π K) : HasEntropyRate π K (meanRowEntropy π K) := by
  have ht : Tendsto (fun n : ℕ => ((n : ℝ) + 1)⁻¹) atTop (nhds 0) :=
    by simpa only [one_div] using (tendsto_one_div_add_atTop_nhds_zero_nat :
      Tendsto (fun n : ℕ => 1 / ((n : ℝ) + 1)) atTop (nhds 0))
  have hc : Tendsto (fun n : ℕ => meanRowEntropy π K +
      (entropy π - meanRowEntropy π K) * ((n : ℝ) + 1)⁻¹) atTop
      (nhds (meanRowEntropy π K)) := by
    simpa using (tendsto_const_nhds.add (tendsto_const_nhds.mul ht))
  unfold HasEntropyRate
  simpa only [normalized_block_entropy π K h, div_eq_mul_inv] using hc

theorem entropyRate_unique (π : PMF α) (K : α → PMF α) {a b : ℝ}
    (ha : HasEntropyRate π K a) (hb : HasEntropyRate π K b) : a = b :=
  tendsto_nhds_unique ha hb

theorem block_entropy_le (π : PMF α) (K : α → PMF α) (c : ℝ)
    (hrow : ∀ i, entropy (K i) ≤ c) (n : ℕ) :
    entropy (blockLaw π K n) ≤ entropy π + (n : ℝ) * c := by
  induction n with
  | zero => simp [blockLaw]
  | succ n ih =>
    have hs : (∑ x, (blockLaw π K n x).toReal * entropy (K (lastState x))) ≤ c := by
      calc
        _ ≤ ∑ x, (blockLaw π K n x).toReal * c := by
          apply Finset.sum_le_sum
          intro x _
          exact mul_le_mul_of_nonneg_left (hrow _) ENNReal.toReal_nonneg
        _ = c := by rw [← Finset.sum_mul, sum_prob, one_mul]
    change entropy (joint (blockLaw π K n) (fun x => K (lastState x))) ≤ _
    rw [entropy_joint]
    push_cast
    linarith

theorem block_entropy_of_constant_rows (π : PMF α) (K : α → PMF α) (c : ℝ)
    (hrow : ∀ i, entropy (K i) = c) (n : ℕ) :
    entropy (blockLaw π K n) = entropy π + (n : ℝ) * c := by
  induction n with
  | zero => simp [blockLaw]
  | succ n ih =>
    have hs : (∑ x, (blockLaw π K n x).toReal * entropy (K (lastState x))) = c := by
      simp_rw [hrow]
      rw [← Finset.sum_mul, sum_prob, one_mul]
    change entropy (joint (blockLaw π K n) (fun x => K (lastState x))) = _
    rw [entropy_joint, ih, hs]
    push_cast
    ring

theorem affine_div_tendsto (a c : ℝ) :
    Tendsto (fun n : ℕ => (a + (n : ℝ) * c) / ((n : ℝ) + 1)) atTop (nhds c) := by
  have ht : Tendsto (fun n : ℕ => ((n : ℝ) + 1)⁻¹) atTop (nhds 0) := by
    simpa only [one_div] using (tendsto_one_div_add_atTop_nhds_zero_nat :
      Tendsto (fun n : ℕ => 1 / ((n : ℝ) + 1)) atTop (nhds 0))
  have hc : Tendsto (fun n : ℕ => c + (a - c) * ((n : ℝ) + 1)⁻¹) atTop (nhds c) := by
    simpa using (tendsto_const_nhds.add (tendsto_const_nhds.mul ht))
  convert hc using 1
  ext n
  have hn : (n : ℝ) + 1 ≠ 0 := by positivity
  field_simp
  ring

theorem hasEntropyRate_of_constant_rows (π : PMF α) (K : α → PMF α) (c : ℝ)
    (hrow : ∀ i, entropy (K i) = c) : HasEntropyRate π K c := by
  unfold HasEntropyRate
  simpa only [block_entropy_of_constant_rows π K c hrow] using affine_div_tendsto (entropy π) c

theorem entropyRate_le (π : PMF α) (K : α → PMF α) (c : ℝ)
    (hrow : ∀ i, entropy (K i) ≤ c) {h : ℝ} (hh : HasEntropyRate π K h) : h ≤ c := by
  apply le_of_tendsto_of_tendsto' hh (affine_div_tendsto (entropy π) c)
  intro n
  exact div_le_div_of_nonneg_right (block_entropy_le π K c hrow n) (by positivity)

/-- The same path distribution on conventional coordinate tuples. -/
noncomputable def tupleLaw (π : PMF α) (K : α → PMF α) (n : ℕ) :
    PMF (Fin (n + 1) → α) := (blockLaw π K n).map (wordEquiv α n)

theorem tupleLaw_entropy (π : PMF α) (K : α → PMF α) (n : ℕ) :
    entropy (tupleLaw π K n) = entropy (blockLaw π K n) :=
  entropy_map_equiv _ _

theorem tupleLaw_entropy_rate (π : PMF α) (K : α → PMF α)
    (h : Stationary π K) :
    Tendsto (fun n : ℕ => entropy (tupleLaw π K n) / ((n : ℝ) + 1)) atTop
      (nhds (meanRowEntropy π K)) := by
  simpa only [tupleLaw_entropy] using stationary_hasEntropyRate π K h

end Conjecture1277
