import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.Algebra.CharP.Lemmas
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.Data.Real.Archimedean
import Mathlib.Topology.Instances.Real.Lemmas
import Mathlib.Data.Real.Basic
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic

noncomputable section

namespace Conjecture525

variable (K : Type*) [Field K]

abbrev Plane := MvPolynomial (Fin 2) K

noncomputable def x : Plane K := MvPolynomial.X 0

noncomputable def y : Plane K := MvPolynomial.X 1

noncomputable def cusp : Plane K := x K ^ 2 + y K ^ 3

/-- The Frobenius power of the maximal ideal at the origin when `q` is a
power of the characteristic. -/
noncomputable def originPower (q : ℕ) : Ideal (Plane K) := Ideal.span {x K ^ q, y K ^ q}

/-- The standard all-level supremum definition of the F-pure threshold
at the origin of affine two-space. -/
noncomputable def fpt (p : ℕ) (f : Plane K) : ℝ :=
  sSup {t : ℝ | ∃ e n : ℕ, f ^ n ∉ originPower K (p ^ e) ∧ t = (n : ℝ) / (p : ℝ) ^ e}

lemma x_pow_mem (q : ℕ) : x K ^ q ∈ originPower K q :=
  Ideal.subset_span (by simp)

lemma y_pow_mem (q : ℕ) : y K ^ q ∈ originPower K q :=
  Ideal.subset_span (by simp)

lemma cusp_four_mem : cusp K ^ 4 ∈ originPower K 5 := by
  have hx : x K ^ 5 * (x K ^ 3 + 4 * x K * y K ^ 3) ∈ originPower K 5 :=
    Ideal.mul_mem_right _ _ (x_pow_mem K 5)
  have hy : y K ^ 5 * (6 * x K ^ 4 * y K + 4 * x K ^ 2 * y K ^ 4 + y K ^ 7)
      ∈ originPower K 5 := Ideal.mul_mem_right _ _ (y_pow_mem K 5)
  convert (originPower K 5).add_mem hx hy using 1
  simp only [cusp]
  ring


lemma one_not_mem (q : ℕ) (hq : 0 < q) : (1 : Plane K) ∉ originPower K q := by
  intro h
  obtain ⟨a, b, hab⟩ := Ideal.mem_span_pair.mp h
  have hh := congrArg MvPolynomial.constantCoeff hab
  simp [x, y, hq.ne'] at hh

lemma pow_mem_of_mem {f : Plane K} {q n m : ℕ}
    (h : f ^ n ∈ originPower K q) (hnm : n ≤ m) :
    f ^ m ∈ originPower K q := by
  obtain ⟨d, rfl⟩ := Nat.exists_eq_add_of_le hnm
  rw [pow_add]
  exact Ideal.mul_mem_right _ _ h

lemma cusp_mem_origin : cusp K ∈ originPower K 1 := by
  exact (originPower K 1).add_mem
    ((originPower K 1).pow_mem_of_mem (by simpa using x_pow_mem K 1) 2 (by norm_num))
    ((originPower K 1).pow_mem_of_mem (by simpa using y_pow_mem K 1) 3 (by norm_num))

/-- The ordinary Frobenius/bracket power: the ideal generated by all qth
powers of elements of I. For Frobenius levels q = p^e. -/
noncomputable def bracketPower (I : Ideal (Plane K)) (q : ℕ) : Ideal (Plane K) :=
  Ideal.span ((fun g : Plane K => g ^ q) '' (I : Set (Plane K)))

/-- The F-threshold at a maximal ideal containing f in the regular
polynomial ring. The definition uses all Frobenius levels and exponents. -/
noncomputable def thresholdAt (p : ℕ) (f : Plane K) (I : Ideal (Plane K)) : ℝ :=
  sSup {t : ℝ | ∃ e n : ℕ, f ^ n ∉ bracketPower K I (p ^ e) ∧
    t = (n : ℝ) / (p : ℝ) ^ e}

/-- The local-infimum characterization of the global F-pure threshold
for F-finite regular polynomial rings, in particular every prime-field
polynomial ring used below. The displayed infimum also defines an
algebraic quantity over other fields. It ranges over all maximal ideals
containing the polynomial, not just ideals of rational points. -/
noncomputable def globalFpt (p : ℕ) (f : Plane K) : ℝ :=
  sInf {t : ℝ | ∃ I : Ideal (Plane K), I.IsMaximal ∧ f ∈ I ∧ t = thresholdAt K p f I}

/-- The maximal ideal of the origin, as the kernel of evaluation there. -/
noncomputable def originIdeal : Ideal (Plane K) := RingHom.ker MvPolynomial.constantCoeff

lemma origin_isMaximal : (originIdeal K).IsMaximal := by
  apply RingHom.ker_isMaximal_of_surjective
  intro a
  exact ⟨MvPolynomial.C a, by simp⟩

lemma cusp_mem_originIdeal : cusp K ∈ originIdeal K := by
  simp [originIdeal, RingHom.mem_ker, cusp, x, y]

lemma originPower_le_bracket (q : ℕ) :
    originPower K q ≤ bracketPower K (originIdeal K) q := by
  apply Ideal.span_le.mpr
  intro g hg
  rcases (Set.mem_insert_iff.mp hg) with rfl | hg
  · exact Ideal.subset_span ⟨x K, by simp [originIdeal, x, RingHom.mem_ker], rfl⟩
  · have heq : g = y K ^ q := Set.mem_singleton_iff.mp hg
    subst g
    exact Ideal.subset_span ⟨y K, by simp [originIdeal, y, RingHom.mem_ker], rfl⟩

lemma bracketPower_le (I : Ideal (Plane K)) (q : ℕ) (hq : 0 < q) :
    bracketPower K I q ≤ I := by
  apply Ideal.span_le.mpr
  rintro g ⟨a, ha, rfl⟩
  exact I.pow_mem_of_mem ha q hq

lemma thresholdAt_set_nonempty (p : ℕ) (f : Plane K) (I : Ideal (Plane K))
    (hI : I.IsMaximal) :
    {t : ℝ | ∃ e n : ℕ, f ^ n ∉ bracketPower K I (p ^ e) ∧
      t = (n : ℝ) / (p : ℝ) ^ e}.Nonempty := by
  refine ⟨0, 0, 0, ?_, by norm_num⟩
  simp only [pow_zero]
  intro h
  exact hI.ne_top (Ideal.eq_top_of_isUnit_mem _
    (bracketPower_le K I 1 (by norm_num) h) isUnit_one)

lemma thresholdAt_admissible_le_one (p : ℕ) (hp : 0 < p) (f : Plane K)
    (I : Ideal (Plane K)) (hf : f ∈ I) (e n : ℕ)
    (h : f ^ n ∉ bracketPower K I (p ^ e)) :
    (n : ℝ) / (p : ℝ) ^ e ≤ 1 := by
  have hn : n < p ^ e := by
    by_contra hn
    apply h
    apply (bracketPower K I (p ^ e)).pow_mem_of_pow_mem ?_ (show p ^ e ≤ n by omega)
    exact Ideal.subset_span ⟨f, hf, rfl⟩
  have hpos : (0 : ℝ) < (p : ℝ) ^ e := by positivity
  apply (div_le_iff₀ hpos).mpr
  simpa using (show (n : ℝ) ≤ (p : ℝ) ^ e by exact_mod_cast hn.le)

lemma thresholdAt_le_one (p : ℕ) (hp : 0 < p) (f : Plane K)
    (I : Ideal (Plane K)) (hI : I.IsMaximal) (hf : f ∈ I) :
    thresholdAt K p f I ≤ 1 := by
  apply csSup_le (thresholdAt_set_nonempty K p f I hI)
  rintro t ⟨e, n, h, rfl⟩
  exact thresholdAt_admissible_le_one K p hp f I hf e n h

lemma thresholdAt_nonneg (p : ℕ) (f : Plane K) (I : Ideal (Plane K)) :
    0 ≤ thresholdAt K p f I := by
  apply Real.sSup_nonneg
  rintro t ⟨e, n, _, rfl⟩
  positivity

lemma globalFpt_le_thresholdAt (p : ℕ) (f : Plane K) (I : Ideal (Plane K))
    (hI : I.IsMaximal) (hf : f ∈ I) : globalFpt K p f ≤ thresholdAt K p f I := by
  apply csInf_le
  · refine ⟨0, ?_⟩
    rintro t ⟨J, _, _, rfl⟩
    exact thresholdAt_nonneg K p f J
  · exact ⟨I, hI, hf, rfl⟩

lemma bracketPower_one (I : Ideal (Plane K)) : bracketPower K I 1 = I := by
  simp [bracketPower]

/-- Including the zeroth Frobenius level does not change the defining
set: that level contributes only zero, already present at level one. -/
lemma allLevels_eq_positive (p : ℕ) (f : Plane K) (J : ℕ → Ideal (Plane K))
    (hf : f ∈ J 1) (hproper : ∀ e : ℕ, (1 : Plane K) ∉ J (p ^ e)) :
    {t : ℝ | ∃ e n : ℕ, f ^ n ∉ J (p ^ e) ∧ t = (n : ℝ) / (p : ℝ) ^ e} =
    {t : ℝ | ∃ e n : ℕ, 0 < e ∧ f ^ n ∉ J (p ^ e) ∧
      t = (n : ℝ) / (p : ℝ) ^ e} := by
  ext t
  constructor
  · rintro ⟨e, n, h, rfl⟩
    cases e with
    | zero =>
      have hn : n = 0 := by
        by_contra hn
        apply h
        simpa using (J 1).pow_mem_of_mem hf n (Nat.pos_of_ne_zero hn)
      refine ⟨1, 0, by norm_num, ?_, ?_⟩
      · simpa using hproper 1
      · simp [hn]
    | succ e => exact ⟨e + 1, n, by omega, h, rfl⟩
  · rintro ⟨e, n, _, h, rfl⟩
    exact ⟨e, n, h, rfl⟩

lemma fpt_eq_positive_levels (p : ℕ) (hp : 0 < p) :
    fpt K p (cusp K) =
    sSup {t : ℝ | ∃ e n : ℕ, 0 < e ∧ cusp K ^ n ∉ originPower K (p ^ e) ∧
      t = (n : ℝ) / (p : ℝ) ^ e} := by
  unfold fpt
  rw [allLevels_eq_positive K p (cusp K) (originPower K) (cusp_mem_origin K)
    (fun e => one_not_mem K _ (pow_pos hp e))]

lemma thresholdAt_eq_positive_levels (p : ℕ) (hp : 0 < p) (f : Plane K)
    (I : Ideal (Plane K)) (hI : I.IsMaximal) (hf : f ∈ I) :
    thresholdAt K p f I =
    sSup {t : ℝ | ∃ e n : ℕ, 0 < e ∧ f ^ n ∉ bracketPower K I (p ^ e) ∧
      t = (n : ℝ) / (p : ℝ) ^ e} := by
  unfold thresholdAt
  apply congrArg sSup
  apply allLevels_eq_positive K p f (bracketPower K I)
  · simpa [bracketPower_one K I] using hf
  · intro e h
    exact hI.ne_top (Ideal.eq_top_of_isUnit_mem _
      (bracketPower_le K I _ (pow_pos hp e) h) isUnit_one)

variable [CharP K 5]

lemma frobenius_mem {f : Plane K} {q : ℕ} (h : f ∈ originPower K q) (e : ℕ) :
    f ^ 5 ^ e ∈ originPower K (q * 5 ^ e) := by
  letI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  obtain ⟨a, b, hab⟩ := Ideal.mem_span_pair.mp h
  rw [← hab, add_pow_char_pow, mul_pow, mul_pow, ← pow_mul, ← pow_mul]
  exact (originPower K (q * 5 ^ e)).add_mem
    (Ideal.mul_mem_left _ _ (x_pow_mem K _))
    (Ideal.mul_mem_left _ _ (y_pow_mem K _))

lemma cusp_all_levels (e : ℕ) :
    cusp K ^ (4 * 5 ^ e) ∈ originPower K (5 ^ (e + 1)) := by
  rw [pow_succ']
  simpa only [pow_mul] using frobenius_mem K (cusp_four_mem K) e

lemma admissible_bound (e n : ℕ) (h : cusp K ^ n ∉ originPower K (5 ^ e)) :
    (n : ℝ) / (5 : ℝ) ^ e ≤ 4 / 5 := by
  cases e with
  | zero =>
    have hn : n = 0 := by
      by_contra hn
      apply h
      simpa using pow_mem_of_mem K (by simpa using cusp_mem_origin K)
        (Nat.one_le_iff_ne_zero.mpr hn)
    simp [hn]
    norm_num
  | succ e =>
    have hn : n < 4 * 5 ^ e := by
      by_contra hn
      exact h (pow_mem_of_mem K (cusp_all_levels K e) (by omega))
    have hn' : (n : ℝ) ≤ 4 * (5 : ℝ) ^ e := by exact_mod_cast hn.le
    apply (div_le_iff₀ (by positivity : (0 : ℝ) < 5 ^ (e + 1))).mpr
    rw [pow_succ]
    nlinarith

lemma fpt_le_four_fifths : fpt K 5 (cusp K) ≤ 4 / 5 := by
  apply csSup_le
  · exact ⟨0, 0, 0, by simpa using one_not_mem K 1 (by norm_num), by norm_num⟩
  · rintro t ⟨e, n, h, rfl⟩
    exact admissible_bound K e n h

theorem fpt_ne_five_sixths : fpt K 5 (cusp K) ≠ 5 / 6 := by
  have h := fpt_le_four_fifths K
  norm_num at *
  linarith

/-- The origin-local threshold set is bounded above, as well as nonempty. -/
lemma origin_values_bddAbove :
    BddAbove {t : ℝ | ∃ e n : ℕ, cusp K ^ n ∉ originPower K (5 ^ e) ∧
      t = (n : ℝ) / (5 : ℝ) ^ e} := by
  refine ⟨4 / 5, ?_⟩
  rintro t ⟨e, n, h, rfl⟩
  exact admissible_bound K e n h

lemma thresholdAt_origin_le_fpt :
    thresholdAt K 5 (cusp K) (originIdeal K) ≤ fpt K 5 (cusp K) := by
  apply csSup_le_csSup (origin_values_bddAbove K)
    (thresholdAt_set_nonempty K 5 (cusp K) (originIdeal K) (origin_isMaximal K))
  rintro t ⟨e, n, h, rfl⟩
  exact ⟨e, n, (fun hmem => h (originPower_le_bracket K _ hmem)), rfl⟩

/-- Only the inequality is required; no local/global equality is claimed. -/
theorem globalFpt_le_origin_fpt : globalFpt K 5 (cusp K) ≤ fpt K 5 (cusp K) :=
  (globalFpt_le_thresholdAt K 5 (cusp K) (originIdeal K)
    (origin_isMaximal K) (cusp_mem_originIdeal K)).trans
    (thresholdAt_origin_le_fpt K)

theorem globalFpt_le_four_fifths : globalFpt K 5 (cusp K) ≤ 4 / 5 :=
  (globalFpt_le_origin_fpt K).trans (fpt_le_four_fifths K)

theorem globalFpt_ne_five_sixths : globalFpt K 5 (cusp K) ≠ 5 / 6 := by
  have h := globalFpt_le_four_fifths K
  norm_num at *
  linarith

/-- Prime characteristics, with no restriction on their size. -/
abbrev PrimeCharacteristic := {p : ℕ // p.Prime}

/-- The reduction of the integer cusp over the prime field. -/
noncomputable def localPrimeThreshold (p : PrimeCharacteristic) : ℝ := by
  letI : Fact p.val.Prime := ⟨p.property⟩
  exact fpt (ZMod p.val) p.val (cusp (ZMod p.val))

noncomputable def globalPrimeThreshold (p : PrimeCharacteristic) : ℝ := by
  letI : Fact p.val.Prime := ⟨p.property⟩
  exact globalFpt (ZMod p.val) p.val (cusp (ZMod p.val))

/-- The residue-class assertion in both language versions. -/
noncomputable def ResidueClaim (T : PrimeCharacteristic → ℝ) : Prop :=
  ∀ p : PrimeCharacteristic, p.val % 3 = 2 → T p = 5 / 6

/-- The conjunction in the conjecture, with a real candidate L for the
characteristic-zero log threshold. The prime variable tends to infinity. -/
noncomputable def ConjectureAt (T : PrimeCharacteristic → ℝ) (L : ℝ) : Prop :=
  Filter.Tendsto T (Filter.comap Subtype.val Filter.atTop) (nhds L) ∧ ResidueClaim T

lemma local_residue_claim_false : ¬ ResidueClaim localPrimeThreshold := by
  intro h
  letI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  let five : PrimeCharacteristic := ⟨5, by norm_num⟩
  have hh := h five (by decide)
  exact fpt_ne_five_sixths (ZMod 5) hh

lemma global_residue_claim_false : ¬ ResidueClaim globalPrimeThreshold := by
  intro h
  letI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  let five : PrimeCharacteristic := ⟨5, by norm_num⟩
  have hh := h five (by decide)
  exact globalFpt_ne_five_sixths (ZMod 5) hh

/-- For every candidate characteristic-zero log threshold, the original
conjunction is false under the local-at-origin interpretation. No claim
about the truth or value of the limiting first conjunct is needed. -/
theorem local_conjecture_false (L : ℝ) : ¬ ConjectureAt localPrimeThreshold L :=
  fun h => local_residue_claim_false h.2

/-- The same disproof under the ordinary global interpretation. -/
theorem global_conjecture_false (L : ℝ) : ¬ ConjectureAt globalPrimeThreshold L :=
  fun h => global_residue_claim_false h.2

end Conjecture525
