/-!
# Conjecture 00000003824: the Nakajima monomial crystal `M(λ)` is not `⊕_{μ ≤ λ} B(μ)`

The conjecture: the Nakajima monomial crystal `M(λ)` (the monomial graph generated by the
highest-weight monomial under the Kashiwara operators) decomposes into connected components
`⊕ B(μ)`, where `μ` runs exactly over the dominant integral weights `μ ≤ λ` in dominance order,
each appearing exactly once.

We work in type `A₁` (`sl₂`), with Kashiwara's monomial crystal (Kashiwara 2003, "Realizations
of crystals"; Nakajima's version is the same up to re-indexing; the constants `c_{ij}` play no
role in rank 1):

* monomials `M = ∏ Y_m^{y_m}` (`m ∈ ℤ`, finitely many `y_m ≠ 0`), `A_m = Y_m Y_{m+1}`;
* `wt M = Σ y_m`, `φ(M) = max_n Σ_{k ≤ n} y_k`, `ε(M) = max_n (-Σ_{k > n} y_k)`;
* `f̃ M = A_{n_f}^{-1} M` with `n_f = min {n | Σ_{k≤n} y_k = φ(M)}` if `φ(M) > 0`, else `0`;
* `ẽ M = A_{n_e} M` with `n_e = max {n | -Σ_{k>n} y_k = ε(M)}` if `ε(M) > 0`, else `0`.

Dominant integral weights of `sl₂` are `μ ∈ ℕ`; `μ ≤ λ` in dominance order iff `λ - μ ∈ ℕ·α = 2ℕ`.
`B(μ)` is the string `b₀ → b₁ → ⋯ → b_μ` with `wt b_k = μ - 2k`.

Main results:
* `M2_eq`: `M(2) = {Y₀², Y₀Y₁⁻¹, Y₁⁻²}` (the exact component of `Y₀²`), `iso_M2_B2 : M(2) ≅ B(2)`.
* `conjecture_00000003824_clause_false : ¬ (M(2) ≅ B(2) ⊕ B(0))`, hence
  `conjecture_00000003824_false : ¬ Conjecture`.
* `main_fails_all`: the clause fails for every `λ ≥ 2` (`M(λ)` is a single string `≅ B(λ)`).
* Alternative readings: `union_fails` (union of the components of all highest-weight monomials of
  weight `λ`: fails for every `λ`), `prod3_fails` (tensor-power reading, products of `λ`
  fundamental monomials: fails at `λ = 3`), `all_readings_fail_at_3`.
* Non-vacuity: `main_holds_0`, `main_holds_1`, `prod_holds_2` show `Decomposes` is satisfiable.
-/

namespace MonomialCrystal

/-- A Laurent monomial `∏ Y_m^{a_m}`: the list of pairs `(m, a_m)` with `a_m ≠ 0`, indices
strictly increasing (canonical form; checked by `canon` in `sanity`). -/
abbrev Mon := List (Int × Int)

/-- Multiply by `Y_n^d`, keeping the canonical form. -/
def mulY (n d : Int) : Mon → Mon
  | [] => if d = 0 then [] else [(n, d)]
  | (m, a) :: t =>
    if n < m then (if d = 0 then (m, a) :: t else (n, d) :: (m, a) :: t)
    else if n = m then (if a + d = 0 then t else (n, a + d) :: t)
    else (m, a) :: mulY n d t

/-- Multiply by `A_n^s = (Y_n Y_{n+1})^s` (type `A₁`). -/
def mulA (n s : Int) (M : Mon) : Mon := mulY n s (mulY (n + 1) s M)

/-- Weight `Σ a_m` (in units of the fundamental weight). -/
def wt : Mon → Int
  | [] => 0
  | (_, a) :: t => a + wt t

/-- `max(s, s + a₁, s + a₁ + a₂, …)`: prefix-sum maximum. -/
def prefMax (s : Int) : Mon → Int
  | [] => s
  | (_, a) :: t => max s (prefMax (s + a) t)

/-- `φ(M) = max_n Σ_{k ≤ n} y_k` (the value `0` is attained for `n` below all indices). -/
def phi (M : Mon) : Int := prefMax 0 M

/-- Suffix version, run on the reversed list. -/
def sufMax (s : Int) : Mon → Int
  | [] => s
  | (_, a) :: t => max s (sufMax (s - a) t)

/-- `ε(M) = max_n (-Σ_{k > n} y_k)`. -/
def eps (M : Mon) : Int := sufMax 0 M.reverse

/-- Smallest index at which the prefix sum reaches `target` (this is `n_f`). -/
def firstHit (target s : Int) : Mon → Option Int
  | [] => none
  | (m, a) :: t => if s + a = target then some m else firstHit target (s + a) t

/-- On the reversed list: the largest `n` with `-Σ_{k>n} y_k = target` (this is `n_e`). -/
def lastHit (target s : Int) : Mon → Option Int
  | [] => none
  | (m, a) :: t => if s - a = target then some (m - 1) else lastHit target (s - a) t

/-- Kashiwara operator `f̃` (`none` stands for `0`). -/
def fT (M : Mon) : Option Mon :=
  if 0 < phi M then (firstHit (phi M) 0 M).map (fun n => mulA n (-1) M) else none

/-- Kashiwara operator `ẽ` (`none` stands for `0`). -/
def eT (M : Mon) : Option Mon :=
  if 0 < eps M then (lastHit (eps M) 0 M.reverse).map (fun n => mulA n 1 M) else none

def addNew (acc : List Mon) : List Mon → List Mon
  | [] => acc
  | x :: xs => if acc.contains x then addNew acc xs else addNew (acc ++ [x]) xs

def nbrs (L : List Mon) : List Mon := L.filterMap fT ++ L.filterMap eT

/-- Breadth-first closure of a list of monomials under `f̃` and `ẽ` (fuel `n`). -/
def closeN : Nat → List Mon → List Mon
  | 0, L => L
  | n + 1, L => closeN n (addNew L (nbrs L))

def optIn (L : List Mon) : Option Mon → Bool
  | none => true
  | some y => L.contains y

/-- `L` is closed under `f̃` and `ẽ`. -/
def closedB (L : List Mon) : Bool := L.all fun x => optIn L (fT x) && optIn L (eT x)

/-- The highest-weight monomial `Y₀^λ` of weight `λ`. -/
def Y0pow (l : Nat) : Mon := if l = 0 then [] else [(0, (l : Int))]





/-- `Reach s x`: `x` is obtained from `s` by a finite sequence of `f̃` and `ẽ`. Since `ẽ`, `f̃` are
mutually inverse partial maps (checked on all components used, see `sanity`), this is the
connected component of `s` in the crystal graph, i.e. the subcrystal generated by `s`. -/
inductive Reach (s : Mon) : Mon → Prop
  | refl : Reach s s
  | f {x y : Mon} : Reach s x → fT x = some y → Reach s y
  | e {x y : Mon} : Reach s x → eT x = some y → Reach s y

/-- Subcrystal generated by a list of monomials. -/
def FromS (S : List Mon) (y : Mon) : Prop := ∃ s ∈ S, Reach s y

theorem closed_f {L : List Mon} (hc : closedB L = true) {x y : Mon} (hx : x ∈ L)
    (h : fT x = some y) : y ∈ L := by
  unfold closedB at hc
  rw [List.all_eq_true] at hc
  have := hc x hx
  simp [h, optIn] at this
  exact this.1

theorem closed_e {L : List Mon} (hc : closedB L = true) {x y : Mon} (hx : x ∈ L)
    (h : eT x = some y) : y ∈ L := by
  unfold closedB at hc
  rw [List.all_eq_true] at hc
  have := hc x hx
  simp [h, optIn] at this
  exact this.2

theorem mem_of_closed {L : List Mon} (hc : closedB L = true) {s x : Mon} (hs : s ∈ L)
    (h : Reach s x) : x ∈ L := by
  induction h with
  | refl => exact hs
  | f _ hxy ih => exact closed_f hc ih hxy
  | e _ hxy ih => exact closed_e hc ih hxy

theorem addNew_sound {P : Mon → Prop} : ∀ (xs acc : List Mon), (∀ y ∈ acc, P y) →
    (∀ y ∈ xs, P y) → ∀ y ∈ addNew acc xs, P y := by
  intro xs
  induction xs with
  | nil => intro acc hacc _ y hy; exact hacc y hy
  | cons x xs ih =>
    intro acc hacc hxs y hy
    unfold addNew at hy
    split at hy
    · exact ih acc hacc (fun z hz => hxs z (List.mem_cons_of_mem _ hz)) y hy
    · refine ih (acc ++ [x]) ?_ (fun z hz => hxs z (List.mem_cons_of_mem _ hz)) y hy
      intro z hz
      rcases List.mem_append.1 hz with hz | hz
      · exact hacc z hz
      · simp at hz; subst hz; exact hxs _ List.mem_cons_self

theorem addNew_mono : ∀ (xs acc : List Mon) (y : Mon), y ∈ acc → y ∈ addNew acc xs := by
  intro xs
  induction xs with
  | nil => intro acc y hy; exact hy
  | cons x xs ih =>
    intro acc y hy
    unfold addNew
    split
    · exact ih acc y hy
    · exact ih _ y (List.mem_append_left _ hy)

theorem nbrs_sound {S L : List Mon} (h : ∀ y ∈ L, FromS S y) : ∀ y ∈ nbrs L, FromS S y := by
  intro y hy
  rcases List.mem_append.1 hy with hy | hy
  · obtain ⟨x, hx, hxy⟩ := List.mem_filterMap.1 hy
    obtain ⟨s, hs, hr⟩ := h x hx
    exact ⟨s, hs, Reach.f hr hxy⟩
  · obtain ⟨x, hx, hxy⟩ := List.mem_filterMap.1 hy
    obtain ⟨s, hs, hr⟩ := h x hx
    exact ⟨s, hs, Reach.e hr hxy⟩

theorem closeN_sound {S : List Mon} : ∀ (n : Nat) (L : List Mon), (∀ y ∈ L, FromS S y) →
    ∀ y ∈ closeN n L, FromS S y := by
  intro n
  induction n with
  | zero => intro L h; exact h
  | succ n ih =>
    intro L h
    exact ih _ (addNew_sound _ _ h (nbrs_sound h))

theorem closeN_mono : ∀ (n : Nat) (L : List Mon) (y : Mon), y ∈ L → y ∈ closeN n L := by
  intro n
  induction n with
  | zero => intro L y h; exact h
  | succ n ih => intro L y h; exact ih _ _ (addNew_mono _ _ _ h)

/-- If the computed closure is closed, it is exactly the set generated by `S`. -/
theorem mem_closeN_iff {S : List Mon} {n : Nat} (hc : closedB (closeN n S) = true) (y : Mon) :
    y ∈ closeN n S ↔ FromS S y := by
  constructor
  · intro hy
    exact closeN_sound n S (fun s hs => ⟨s, hs, Reach.refl⟩) y hy
  · rintro ⟨s, hs, hr⟩
    exact mem_of_closed hc (closeN_mono n S s hs) hr

def comp2 : List Mon := closeN 3 [Y0pow 2]
theorem comp2_closed : closedB comp2 = true := by decide
theorem comp2_eq : comp2 = [[(0, 2)], [(0, 1), (1, -1)], [(1, -2)]] := by decide

/-! ## The target crystal `⊕ B(μ)` -/

/-- Vertex `(μ, k)` = the element `f̃^k b_μ` of the copy of `B(μ)`. -/
abbrev Vtx := Nat × Nat

/-- `μ ≤ λ` in dominance order for dominant integral `sl₂` weights: `λ - μ ∈ ℕ·α`, `α = 2`. -/
def Dominated (l μ : Nat) : Prop := μ ≤ l ∧ (l - μ) % 2 = 0

instance (l μ : Nat) : Decidable (Dominated l μ) := by unfold Dominated; infer_instance

/-- Vertices of `⊕_{μ dominant, μ ≤ λ} B(μ)`, one copy of each `B(μ)`. -/
def Target (l : Nat) (v : Vtx) : Prop := Dominated l v.1 ∧ v.2 ≤ v.1

instance (l : Nat) (v : Vtx) : Decidable (Target l v) := by unfold Target; infer_instance

def wtB (v : Vtx) : Int := (v.1 : Int) - 2 * (v.2 : Int)
def fB (v : Vtx) : Option Vtx := if v.2 < v.1 then some (v.1, v.2 + 1) else none
def eB (v : Vtx) : Option Vtx := if 0 < v.2 then some (v.1, v.2 - 1) else none

/-- Crystal isomorphism from the monomial set `V` onto the abstract crystal on `D`:
a bijection preserving weights and the arrows `f̃`, `ẽ` (including where they vanish). -/
structure CrystalIso (V : Mon → Prop) (D : Vtx → Prop) (ψ : Mon → Vtx) : Prop where
  into : ∀ x, V x → D (ψ x)
  inj : ∀ x y, V x → V y → ψ x = ψ y → x = y
  onto : ∀ v, D v → ∃ x, V x ∧ ψ x = v
  wt_eq : ∀ x, V x → wtB (ψ x) = wt x
  f_comm : ∀ x, V x → (fT x).map ψ = fB (ψ x)
  e_comm : ∀ x, V x → (eT x).map ψ = eB (ψ x)

/-- `V ≅ ⊕_{μ dominant, μ ≤ λ} B(μ)`, each `B(μ)` exactly once. -/
def Decomposes (V : Mon → Prop) (l : Nat) : Prop := ∃ ψ : Mon → Vtx, CrystalIso V (Target l) ψ

/-- Main (standard) reading: `M(λ)` = the subcrystal generated by `Y₀^λ`. -/
def Mmain (l : Nat) : Mon → Prop := Reach (Y0pow l)

/-- The conjecture under the main reading (for `sl₂`). -/
def Conjecture : Prop := ∀ l : Nat, Decomposes (Mmain l) l

theorem target_hw_unique {l : Nat} {v w : Vtx} (hv : Target l v) (hw : Target l w)
    (hev : eB v = none) (hew : eB w = none) (hwt : wtB v = wtB w) : v = w := by
  obtain ⟨a, b⟩ := v
  obtain ⟨c, d⟩ := w
  simp only [eB] at hev hew
  simp only [wtB] at hwt
  split at hev
  · simp at hev
  · split at hew
    · simp at hew
    · simp only at *
      have : b = 0 := by omega
      have : d = 0 := by omega
      subst_vars
      simp only [Prod.mk.injEq, and_true]
      omega

theorem hw_preimage {V : Mon → Prop} {l : Nat} {ψ : Mon → Vtx}
    (h : CrystalIso V (Target l) ψ) {v : Vtx} (hv : Target l v) (he : eB v = none) :
    ∃ x, V x ∧ eT x = none ∧ wt x = wtB v := by
  obtain ⟨x, hx, rfl⟩ := h.onto v hv
  refine ⟨x, hx, ?_, (h.wt_eq x hx).symm⟩
  have := h.e_comm x hx
  rw [he] at this
  cases hh : eT x with
  | none => rfl
  | some y => rw [hh] at this; simp at this

theorem not_decomposes_of_missing {V : Mon → Prop} {l : Nat} (L : List Mon)
    (hL : ∀ x, V x → x ∈ L) (v : Vtx) (hv : Target l v) (he : eB v = none)
    (hbad : ∀ x ∈ L, eT x = none → wt x ≠ wtB v) : ¬ Decomposes V l := by
  rintro ⟨ψ, h⟩
  obtain ⟨x, hx, hex, hwx⟩ := hw_preimage h hv he
  exact hbad x (hL x hx) hex hwx

theorem not_decomposes_of_double {V : Mon → Prop} {l : Nat} (x y : Mon) (hx : V x) (hy : V y)
    (hxy : x ≠ y) (hex : eT x = none) (hey : eT y = none) (hw : wt x = wt y) :
    ¬ Decomposes V l := by
  rintro ⟨ψ, h⟩
  have h1 : eB (ψ x) = none := by have := h.e_comm x hx; rw [hex] at this; exact this.symm
  have h2 : eB (ψ y) = none := by have := h.e_comm y hy; rw [hey] at this; exact this.symm
  have hwt : wtB (ψ x) = wtB (ψ y) := by rw [h.wt_eq x hx, h.wt_eq y hy, hw]
  exact hxy (h.inj x y hx hy (target_hw_unique (h.into x hx) (h.into y hy) h1 h2 hwt))

theorem Mmain_iff_mem {l n : Nat} (hc : closedB (closeN n [Y0pow l]) = true) (x : Mon) :
    Mmain l x ↔ x ∈ closeN n [Y0pow l] := by
  rw [mem_closeN_iff hc]
  constructor
  · intro h; exact ⟨_, List.mem_singleton_self _, h⟩
  · rintro ⟨s, hs, h⟩; rw [List.mem_singleton] at hs; subst hs; exact h

theorem M2_eq (x : Mon) : Mmain 2 x ↔ x ∈ [[(0, 2)], [(0, 1), (1, -1)], [(1, -2)]] := by
  rw [Mmain_iff_mem comp2_closed, ← comp2_eq]; rfl

/-- Finite lookup table used to define explicit isomorphisms. -/
def lk (x : Mon) : List (Mon × Vtx) → Vtx
  | [] => (0, 0)
  | (y, v) :: t => if x = y then v else lk x t

def tbl22 : List (Mon × Vtx) := [([(0, 2)], (2, 0)), ([(0, 1), (1, -1)], (2, 1)), ([(1, -2)], (2, 2))]

/-- What `M(2)` actually is: a single string `≅ B(2)`. -/
theorem iso_M2_B2 : ∃ ψ : Mon → Vtx, CrystalIso (Mmain 2) (fun v => v.1 = 2 ∧ v.2 ≤ 2) ψ := by
  refine ⟨fun x => lk x tbl22, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · intro x hx; have h := (M2_eq x).1 hx; clear hx; revert x; decide
  · intro x y hx hy
    have h1 := (M2_eq x).1 hx; have h2 := (M2_eq y).1 hy; clear hx hy
    revert h2 y; revert h1 x; decide
  · rintro ⟨a, b⟩ ⟨ha, hb⟩
    simp only at ha hb; subst ha
    have : b = 0 ∨ b = 1 ∨ b = 2 := by omega
    rcases this with rfl | rfl | rfl
    · exact ⟨[(0, 2)], (M2_eq _).2 (by decide), by decide⟩
    · exact ⟨[(0, 1), (1, -1)], (M2_eq _).2 (by decide), by decide⟩
    · exact ⟨[(1, -2)], (M2_eq _).2 (by decide), by decide⟩
  · intro x hx; have h := (M2_eq x).1 hx; clear hx; revert x; decide
  · intro x hx; have h := (M2_eq x).1 hx; clear hx; revert x; decide
  · intro x hx; have h := (M2_eq x).1 hx; clear hx; revert x; decide

/-- The clause for `sl₂`, `λ = 2`: `M(2) ≅ B(2) ⊕ B(0)` is false (`B(0)` has a highest-weight
vertex of weight `0`; `M(2)` has none). -/
theorem conjecture_00000003824_clause_false : ¬ Decomposes (Mmain 2) 2 :=
  not_decomposes_of_missing _ (fun x hx => (M2_eq x).1 hx) (0, 0) (by decide) (by decide)
    (by decide)

theorem conjecture_00000003824_false : ¬ Conjecture := fun h =>
  conjecture_00000003824_clause_false (h 2)


/-! ## The main reading fails for every `λ ≥ 2`: `M(λ)` is the string `{Y₀^{λ-k} Y₁^{-k}}` -/
theorem fT_s1 (a : Int) (ha : 0 < a) :
    fT [(0, a)] = some (if a = 1 then [(1, -1)] else [(0, a - 1), (1, -1)]) := by
  have hphi : phi [(0, a)] = a := by simp [phi, prefMax]; omega
  unfold fT; rw [hphi]
  simp [firstHit, mulA, mulY, ha]
  by_cases h : a = 1
  · subst h; simp
  · have h' : a + -1 ≠ 0 := by omega
    simp [h, h']; omega

theorem eT_s1 (a : Int) (ha : 0 < a) : eT [(0, a)] = none := by
  simp [eT, eps, sufMax]; omega

theorem fT_s2 (a b : Int) (ha : 0 < a) (hb : b < 0) :
    fT [(0, a), (1, b)] = some (if a = 1 then [(1, b - 1)] else [(0, a - 1), (1, b - 1)]) := by
  have hphi : phi [(0, a), (1, b)] = a := by simp [phi, prefMax]; omega
  unfold fT; rw [hphi]
  simp [firstHit, mulA, mulY, ha]
  have hb' : b + -1 ≠ 0 := by omega
  by_cases h : a = 1
  · subst h; simp [hb']; omega
  · have h' : a + -1 ≠ 0 := by omega
    simp [h, h', hb']; omega

theorem eT_s2 (a b : Int) (ha : 0 < a) (hb : b < 0) :
    eT [(0, a), (1, b)] = some (if b = -1 then [(0, a + 1)] else [(0, a + 1), (1, b + 1)]) := by
  have heps : eps [(0, a), (1, b)] = -b := by simp [eps, sufMax]; omega
  unfold eT; rw [heps]
  simp [lastHit, mulA, mulY, hb]
  have ha' : a + 1 ≠ 0 := by omega
  by_cases h : b = -1
  · subst h; simp [ha']
  · have h' : b + 1 ≠ 0 := by omega
    simp [h, h', ha']

theorem fT_s3 (b : Int) (hb : b < 0) : fT [(1, b)] = none := by
  simp [fT, phi, prefMax]; omega

theorem eT_s3 (b : Int) (hb : b < 0) :
    eT [(1, b)] = some (if b = -1 then [(0, 1)] else [(0, 1), (1, b + 1)]) := by
  have heps : eps [(1, b)] = -b := by simp [eps, sufMax]; omega
  unfold eT; rw [heps]
  simp [lastHit, mulA, mulY, hb]
  by_cases h : b = -1
  · subst h; simp [mulY]
  · have h' : b + 1 ≠ 0 := by omega
    simp [h, h', mulY]

/-- The string `{Y₀^{l-k} Y₁^{-k} : 0 ≤ k ≤ l}`. -/
def InStr (l : Nat) (x : Mon) : Prop :=
  x = [(0, (l : Int))] ∨ (∃ a b : Int, 0 < a ∧ b < 0 ∧ a - b = l ∧ x = [(0, a), (1, b)]) ∨
    x = [(1, -(l : Int))]

theorem InStr_f {l : Nat} (hl : 0 < l) {x y : Mon} (hx : InStr l x) (h : fT x = some y) :
    InStr l y := by
  rcases hx with rfl | ⟨a, b, ha, hb, hab, rfl⟩ | rfl
  · rw [fT_s1 _ (by omega)] at h
    cases h
    by_cases h1 : (l : Int) = 1
    · rw [if_pos h1]; right; right; rw [h1]
    · rw [if_neg h1]; right; left; exact ⟨(l : Int) - 1, -1, by omega, by omega, by omega, rfl⟩
  · rw [fT_s2 _ _ ha hb] at h
    cases h
    by_cases h1 : a = 1
    · rw [if_pos h1]; right; right; congr; omega
    · rw [if_neg h1]; right; left; exact ⟨a - 1, b - 1, by omega, by omega, by omega, rfl⟩
  · rw [fT_s3 _ (by omega)] at h; cases h

theorem InStr_e {l : Nat} (hl : 0 < l) {x y : Mon} (hx : InStr l x) (h : eT x = some y) :
    InStr l y := by
  rcases hx with rfl | ⟨a, b, ha, hb, hab, rfl⟩ | rfl
  · rw [eT_s1 _ (by omega)] at h; cases h
  · rw [eT_s2 _ _ ha hb] at h
    cases h
    by_cases h1 : b = -1
    · rw [if_pos h1]; left; congr; omega
    · rw [if_neg h1]; right; left; exact ⟨a + 1, b + 1, by omega, by omega, by omega, rfl⟩
  · rw [eT_s3 _ (by omega)] at h
    cases h
    by_cases h1 : -(l : Int) = -1
    · rw [if_pos h1]; left; have : (l : Int) = 1 := by omega
      rw [this]
    · rw [if_neg h1]; right; left; exact ⟨1, -(l : Int) + 1, by omega, by omega, by omega, rfl⟩

theorem Mmain_InStr {l : Nat} (hl : 0 < l) {x : Mon} (h : Mmain l x) : InStr l x := by
  induction h with
  | refl => left; simp [Y0pow]; omega
  | f _ hxy ih => exact InStr_f hl ih hxy
  | e _ hxy ih => exact InStr_e hl ih hxy

theorem InStr_hw {l : Nat} (hl : 0 < l) {x : Mon} (hx : InStr l x) (he : eT x = none) :
    wt x = l := by
  rcases hx with rfl | ⟨a, b, ha, hb, hab, rfl⟩ | rfl
  · simp [wt]
  · rw [eT_s2 _ _ ha hb] at he; cases he
  · rw [eT_s3 _ (by omega)] at he; cases he

theorem main_fails_all (l : Nat) (h2 : 2 ≤ l) : ¬ Decomposes (Mmain l) l := by
  rintro ⟨ψ, h⟩
  obtain ⟨x, hx, hex, hwx⟩ := hw_preimage h (v := (l - 2, 0)) ⟨⟨by omega, by omega⟩, by simp⟩
    (by simp [eB])
  have := InStr_hw (by omega) (Mmain_InStr (by omega) hx) hex
  rw [this] at hwx
  simp [wtB] at hwx
  omega

/-! ## Reading (U): union of the components of all highest-weight monomials of weight `λ` -/

/-- Reading (U): union of the subcrystals generated by all highest-weight monomials of weight `λ`. -/
def Munion (l : Nat) (x : Mon) : Prop := ∃ h : Mon, eT h = none ∧ wt h = (l : Int) ∧ Reach h x

theorem eT_single (m : Int) (l : Nat) : eT [(m, (l : Int))] = none := by
  simp [eT, eps, sufMax]
  omega

theorem union_fails (l : Nat) : ¬ Decomposes (Munion l) l := by
  cases l with
  | zero =>
    exact not_decomposes_of_double [] [(1, -1), (2, 1)]
      ⟨_, by decide, by decide, Reach.refl⟩ ⟨_, by decide, by decide, Reach.refl⟩
      (by decide) (by decide) (by decide) (by decide)
  | succ k =>
    refine not_decomposes_of_double [(0, ((k + 1 : Nat) : Int))] [(1, ((k + 1 : Nat) : Int))]
      ⟨_, eT_single _ _, by simp [wt], Reach.refl⟩ ⟨_, eT_single _ _, by simp [wt], Reach.refl⟩
      (by simp) (eT_single _ _) (eT_single _ _) (by simp [wt])

/-! ## Reading (P): products of `λ` fundamental monomials (tensor-power reading) -/

/-- Products `∏_{j<λ} c_j`, `c_j ∈ {Y_{2j}, Y_{2j+1}⁻¹}` (each factor is a copy of `B(1)`). -/
def prods : Nat → List Mon
  | 0 => [[]]
  | l + 1 => (prods l).flatMap fun M => [mulY (2 * l) 1 M, mulY (2 * l + 1) (-1) M]

/-- Reading (P): the subcrystal generated by all products of `λ` fundamental monomials. -/
def Mprod (l : Nat) : Mon → Prop := FromS (prods l)

def compProd3 : List Mon := closeN 4 (prods 3)
theorem compProd3_closed : closedB compProd3 = true := by decide

theorem prod3_fails : ¬ Decomposes (Mprod 3) 3 := by
  have hm : ∀ x, x ∈ compProd3 → Mprod 3 x := fun x hx => (mem_closeN_iff compProd3_closed x).1 hx
  exact not_decomposes_of_double [(0, 1), (3, -1), (4, 1)] [(1, -1), (2, 1), (4, 1)]
    (hm _ (by decide)) (hm _ (by decide)) (by decide) (by decide) (by decide) (by decide)

/-- `λ = 3` defeats all three readings simultaneously. -/
theorem all_readings_fail_at_3 :
    ¬ Decomposes (Mmain 3) 3 ∧ ¬ Decomposes (Munion 3) 3 ∧ ¬ Decomposes (Mprod 3) 3 :=
  ⟨main_fails_all 3 (by decide), union_fails 3, prod3_fails⟩

/-! ## Non-vacuity: the predicate `Decomposes` does hold in the cases where it should -/

theorem decomposes_of_check {V : Mon → Prop} {l : Nat} (L : List Mon) (hV : ∀ x, V x ↔ x ∈ L)
    (ψ : Mon → Vtx)
    (h1 : ∀ x ∈ L, Target l (ψ x)) (h2 : ∀ x ∈ L, ∀ y ∈ L, ψ x = ψ y → x = y)
    (h3 : ∀ a, a < l + 1 → ∀ b, b < a + 1 → Dominated l a → ∃ x ∈ L, ψ x = (a, b))
    (h4 : ∀ x ∈ L, wtB (ψ x) = wt x) (h5 : ∀ x ∈ L, (fT x).map ψ = fB (ψ x))
    (h6 : ∀ x ∈ L, (eT x).map ψ = eB (ψ x)) : Decomposes V l := by
  refine ⟨ψ, fun x hx => h1 x ((hV x).1 hx), fun x y hx hy => h2 x ((hV x).1 hx) y ((hV y).1 hy),
    ?_, fun x hx => h4 x ((hV x).1 hx), fun x hx => h5 x ((hV x).1 hx),
    fun x hx => h6 x ((hV x).1 hx)⟩
  rintro ⟨a, b⟩ ⟨hd, hb⟩
  obtain ⟨x, hx, hψ⟩ := h3 a (by have := hd.1; omega) b (by simp at hb; omega) hd
  exact ⟨x, (hV x).2 hx, hψ⟩

def compMain (l : Nat) : List Mon := closeN (l + 1) [Y0pow l]

def tbl1 : List (Mon × Vtx) := [([(0, 1)], (1, 0)), ([(1, -1)], (1, 1))]

theorem main_holds_1 : Decomposes (Mmain 1) 1 := by
  have hc : closedB (compMain 1) = true := by decide
  refine decomposes_of_check (compMain 1) (Mmain_iff_mem hc) (fun x => lk x tbl1)
    ?_ ?_ ?_ ?_ ?_ ?_ <;> decide

theorem main_holds_0 : Decomposes (Mmain 0) 0 := by
  have hc : closedB (compMain 0) = true := by decide
  refine decomposes_of_check (compMain 0) (Mmain_iff_mem hc) (fun _ => (0, 0))
    ?_ ?_ ?_ ?_ ?_ ?_ <;> decide

def compProd2 : List Mon := closeN 3 (prods 2)

def tbl2 : List (Mon × Vtx) :=
  [([(0, 1), (2, 1)], (2, 0)), ([(0, 1), (3, -1)], (2, 1)), ([(1, -1), (3, -1)], (2, 2)),
   ([(1, -1), (2, 1)], (0, 0))]

/-- Under the tensor-power reading the case `λ = 2` is true (`B(1)⊗B(1) ≅ B(2) ⊕ B(0)`). -/
theorem prod_holds_2 : Decomposes (Mprod 2) 2 := by
  have hc : closedB compProd2 = true := by decide
  refine decomposes_of_check compProd2 (fun x => (mem_closeN_iff hc x).symm)
    (fun x => lk x tbl2) ?_ ?_ ?_ ?_ ?_ ?_ <;> decide

/-! ## Sanity checks on the computed components -/

def canon : Mon → Bool
  | [] => true
  | [(_, a)] => a != 0
  | (m, a) :: (m', a') :: t => a != 0 && decide (m < m') && canon ((m', a') :: t)

/-- Canonical form, `φ - ε = wt`, and `f̃`, `ẽ` mutually inverse on `L`. -/
def axiomsB (L : List Mon) : Bool := L.all fun x =>
  canon x && (phi x - eps x == wt x) &&
  (match fT x with | none => true | some y => eT y == some x) &&
  (match eT x with | none => true | some y => fT y == some x)

theorem sanity : (List.range 11).all (fun l => axiomsB (compMain l)) = true ∧
    axiomsB compProd3 = true ∧ axiomsB compProd2 = true ∧
    compMain 3 = [[(0, 3)], [(0, 2), (1, -1)], [(0, 1), (1, -2)], [(1, -3)]] ∧
    compProd3.length = 8 := by decide

end MonomialCrystal

#print axioms MonomialCrystal.conjecture_00000003824_false
#print axioms MonomialCrystal.conjecture_00000003824_clause_false
#print axioms MonomialCrystal.M2_eq
#print axioms MonomialCrystal.main_fails_all
#print axioms MonomialCrystal.iso_M2_B2
#print axioms MonomialCrystal.union_fails
#print axioms MonomialCrystal.prod3_fails
#print axioms MonomialCrystal.all_readings_fail_at_3
#print axioms MonomialCrystal.main_holds_0
#print axioms MonomialCrystal.main_holds_1
#print axioms MonomialCrystal.prod_holds_2
#print axioms MonomialCrystal.sanity
