import Mathlib

/-!
# Conjecture 00000002853 is false

The conjecture: "the minimal degree where cactus rank falls below rank is 5" (and the
mechanism of the separation is a splitting constraint of apolar ideals).

We work in `S = K[x_0, ..., x_{n-1}]` (forms) and the dual ring `T = K[y_0, ..., y_{n-1}]`
(both are `MvPolynomial (Fin n) K`), with `T` acting on `S` by differentiation,
`y_i ↦ ∂/∂x_i` (and, as a second convention, by contraction).

* The **Waring rank** of a form `F` of degree `d` is the least `r` such that `F` is a sum of
  `r` `d`-th powers of linear forms.
* A **zero-dimensional subscheme of length `r`** of `P^{n-1} = Proj T` is given by its ideal:
  a homogeneous, saturated ideal `I ⊆ T` whose Hilbert function `t ↦ dim_K (T/I)_t` equals `r`
  for all large `t` (closed subschemes of `P^{n-1}` correspond to saturated homogeneous ideals;
  the scheme is zero-dimensional of length `r` iff its Hilbert polynomial is the constant `r`).
  It is **apolar** to `F` if `I ⊆ F^⊥ = {g ∈ T : g ∘ F = 0}`.
* The **cactus rank** of `F` is the least length of a zero-dimensional apolar subscheme.

Counterexample in degree 3: `F = x_0^2 x_1`.  The double point `I = (y_1^2)` is apolar to `F`
and has length 2, so the cactus rank is `≤ 2`, while the Waring rank is exactly `3`.

The monomial-ideal Hilbert function machinery (`monomialIdeal`, `gradedPiece`,
`hilbertFunction`, `standard`, `hilbertFunction_monomialIdeal`) is copied from the accepted
solution of conjecture 00000000539 (`C539.lean`).
-/

open MvPolynomial Module Finset

namespace C2853

/-! ### Copied from C539: Hilbert functions of monomial ideals -/

section C539copy

variable {σ : Type*} {K : Type*} [Field K]

/-- The monomial ideal of `K[x_σ]` generated by the monomials `x^g`, `g ∈ G`. -/
noncomputable def monomialIdeal (K : Type*) [Field K] (G : Set (σ →₀ ℕ)) :
    Ideal (MvPolynomial σ K) :=
  Ideal.span ((fun g => monomial g (1 : K)) '' G)

/-- The degree-`j` component `(R/I)_j`: the image of the degree-`j` forms in `R/I`. -/
noncomputable def gradedPiece (I : Ideal (MvPolynomial σ K)) (j : ℕ) :
    Submodule K (MvPolynomial σ K ⧸ I) :=
  (homogeneousSubmodule σ K j).map (Ideal.Quotient.mkₐ K I).toLinearMap

/-- The Hilbert function `j ↦ dim_K (R/I)_j`. -/
noncomputable def hilbertFunction (I : Ideal (MvPolynomial σ K)) (j : ℕ) : ℕ :=
  finrank K (gradedPiece I j)

/-- The standard monomials of degree `j`: degree-`j` exponents dominating no generator. -/
noncomputable def standard [Fintype σ] (G : Set (σ →₀ ℕ)) (j : ℕ) : Finset (σ →₀ ℕ) := by
  classical
  exact (univ.finsuppAntidiag j).filter fun m => ∀ g ∈ G, ¬ g ≤ m

lemma mem_standard [Fintype σ] {G : Set (σ →₀ ℕ)} {j : ℕ} {m : σ →₀ ℕ} :
    m ∈ standard G j ↔ m.degree = j ∧ ∀ g ∈ G, ¬ g ≤ m := by
  classical
  simp [standard, mem_finsuppAntidiag, Finsupp.degree_eq_sum]

theorem hilbertFunction_monomialIdeal [Fintype σ] (G : Set (σ →₀ ℕ)) (j : ℕ) :
    hilbertFunction (monomialIdeal K G) j = (standard G j).card := by
  classical
  set I := monomialIdeal K G
  set T := standard G j
  let mk := (Ideal.Quotient.mkₐ K I).toLinearMap
  let w : T → MvPolynomial σ K := fun m => monomial m.1 1
  have hw : LinearIndependent K w := by
    have h := (basisMonomials σ K).linearIndependent.comp (Subtype.val : T → _)
      Subtype.val_injective
    have e : w = ⇑(basisMonomials σ K) ∘ Subtype.val := by
      funext m; simp [w, coe_basisMonomials]
    rw [e]; exact h
  have hspanw : Submodule.span K (Set.range w) = restrictSupport K (T : Set (σ →₀ ℕ)) := by
    rw [restrictSupport_eq_span]; congr 1; ext p; simp [w]
  have hdisj : Disjoint (Submodule.span K (Set.range w)) (LinearMap.ker mk) := by
    rw [Submodule.disjoint_def, hspanw]
    intro p hp hpI
    have hpI' : p ∈ I := by
      simpa [mk, Ideal.Quotient.eq_zero_iff_mem] using hpI
    rw [mem_restrictSupport_iff] at hp
    by_contra hne
    obtain ⟨m, hm⟩ := (support_nonempty (p := p)).2 hne
    obtain ⟨g, hg, hgm⟩ := (mem_ideal_span_monomial_image.1 hpI') m hm
    exact (mem_standard.1 (hp hm)).2 g hg hgm
  have hli : LinearIndependent K (mk ∘ w) := hw.map hdisj
  have hspan : Submodule.span K (Set.range (mk ∘ w)) = gradedPiece I j := by
    unfold gradedPiece
    rw [homogeneousSubmodule_eq_finsupp_supported, ← restrictSupport,
      restrictSupport_eq_span, Submodule.map_span]
    apply le_antisymm
    · rw [Submodule.span_le]
      rintro _ ⟨m, rfl⟩
      exact Submodule.subset_span ⟨monomial m.1 1, ⟨m.1, (mem_standard.1 m.2).1, rfl⟩, rfl⟩
    · rw [Submodule.span_le]
      rintro _ ⟨_, ⟨m, hm, rfl⟩, rfl⟩
      by_cases hs : ∀ g ∈ G, ¬ g ≤ m
      · exact Submodule.subset_span ⟨⟨m, mem_standard.2 ⟨hm, hs⟩⟩, rfl⟩
      · push Not at hs
        obtain ⟨g, hg, hgm⟩ := hs
        have : monomial m (1 : K) ∈ I := by
          refine mem_ideal_span_monomial_image.2 ?_
          intro xi hxi
          rw [support_monomial, if_neg one_ne_zero, Finset.mem_singleton] at hxi
          exact ⟨g, hg, hxi ▸ hgm⟩
        have h0 : (Ideal.Quotient.mkₐ K I).toLinearMap (monomial m 1) = 0 := by
          simpa [Ideal.Quotient.eq_zero_iff_mem] using this
        rw [SetLike.mem_coe, h0]
        exact Submodule.zero_mem _
  unfold hilbertFunction
  rw [← hspan, finrank_span_eq_card hli, Fintype.card_coe]

end C539copy

/-! ### Apolarity, zero-dimensional schemes, cactus rank and Waring rank -/

variable {K : Type*} [Field K] {n : ℕ}

/-- The differential operator `∂^m = ∂_0^{m_0} ∘ ∂_1^{m_1} ∘ ⋯ ∘ ∂_{n-1}^{m_{n-1}}`
(`∂_i = ∂/∂x_i`), i.e. the action of the dual monomial `y^m`. -/
noncomputable def partialPow (m : Fin n →₀ ℕ) : Module.End K (MvPolynomial (Fin n) K) :=
  ((List.finRange n).map fun i =>
    ((pderiv i : Derivation K (MvPolynomial (Fin n) K) (MvPolynomial (Fin n) K)) :
      Module.End K (MvPolynomial (Fin n) K)) ^ (m i)).prod

/-- Apolarity by differentiation: `g ∘ F = g(∂_0, ..., ∂_{n-1}) F = ∑_m g_m ∂^m F`. -/
noncomputable def diffAct (g F : MvPolynomial (Fin n) K) : MvPolynomial (Fin n) K :=
  ∑ m ∈ g.support, coeff m g • partialPow m F

/-- Apolarity by contraction: `y^m ⌟ x^a = x^{a-m}` if `m ≤ a` and `0` otherwise,
extended bilinearly. -/
noncomputable def contractAct (g F : MvPolynomial (Fin n) K) : MvPolynomial (Fin n) K :=
  ∑ m ∈ g.support, ∑ a ∈ F.support,
    if m ≤ a then monomial (a - m) (coeff m g * coeff a F) else 0

/-- The apolar (annihilator) ideal `F^⊥ = {g ∈ T : g ∘ F = 0}` (differentiation). -/
def annDiff (F : MvPolynomial (Fin n) K) : Set (MvPolynomial (Fin n) K) :=
  {g | diffAct g F = 0}

/-- The annihilator of `F` for the contraction action. -/
def annContract (F : MvPolynomial (Fin n) K) : Set (MvPolynomial (Fin n) K) :=
  {g | contractAct g F = 0}

/-- A homogeneous ideal: it contains every homogeneous component of each of its elements. -/
def IsHomogeneousIdeal (I : Ideal (MvPolynomial (Fin n) K)) : Prop :=
  ∀ p ∈ I, ∀ j, homogeneousComponent j p ∈ I

/-- The irrelevant ideal `m = (y_0, ..., y_{n-1})`. -/
noncomputable def irrelevant : Ideal (MvPolynomial (Fin n) K) := Ideal.span (Set.range X)

/-- `I` is saturated: `(I : m^∞) = ⋃_k (I : m^k) ⊆ I`. -/
def IsSaturated (I : Ideal (MvPolynomial (Fin n) K)) : Prop :=
  ∀ g, (∃ k : ℕ, ∀ h ∈ (irrelevant : Ideal (MvPolynomial (Fin n) K)) ^ k, h * g ∈ I) → g ∈ I

/-- `I` is the (saturated homogeneous) ideal of a zero-dimensional subscheme of `P^{n-1}` of
length `r`: homogeneous, saturated, with Hilbert function equal to `r` in all large degrees
(Hilbert polynomial the constant `r`). -/
def IsZeroDimLength (I : Ideal (MvPolynomial (Fin n) K)) (r : ℕ) : Prop :=
  IsHomogeneousIdeal I ∧ IsSaturated I ∧ ∃ t₀, ∀ t ≥ t₀, hilbertFunction I t = r

/-- Cactus rank (differentiation): the least length of a zero-dimensional subscheme whose
ideal is contained in `F^⊥` (`⊤` if there is none). -/
noncomputable def cactusRank (F : MvPolynomial (Fin n) K) : ℕ∞ :=
  ⨅ (r : ℕ) (_ : ∃ I : Ideal (MvPolynomial (Fin n) K), IsZeroDimLength I r ∧
    (I : Set (MvPolynomial (Fin n) K)) ⊆ annDiff F), (r : ℕ∞)

/-- Cactus rank for the contraction action. -/
noncomputable def cactusRankContract (F : MvPolynomial (Fin n) K) : ℕ∞ :=
  ⨅ (r : ℕ) (_ : ∃ I : Ideal (MvPolynomial (Fin n) K), IsZeroDimLength I r ∧
    (I : Set (MvPolynomial (Fin n) K)) ⊆ annContract F), (r : ℕ∞)

/-- The linear form `∑_j a_j x_j`. -/
noncomputable def linForm (a : Fin n → K) : MvPolynomial (Fin n) K := ∑ j, C (a j) * X j

/-- Waring rank of a form `F` of degree `d`: the least `r` with `F = L_1^d + ⋯ + L_r^d`,
`L_i` linear forms (`⊤` if there is none). -/
noncomputable def waringRank (d : ℕ) (F : MvPolynomial (Fin n) K) : ℕ∞ :=
  ⨅ (r : ℕ) (_ : ∃ a : Fin r → Fin n → K, F = ∑ i, linForm (a i) ^ d), (r : ℕ∞)

/-- The positive degrees `d` in which cactus rank falls below Waring rank: some nonzero complex
form of degree `d > 0` (in some number of variables) has `cactus rank < Waring rank`.
(Degrees are positive: the coefficient-free Waring-rank definition is standard only for
`d > 0`.) -/
def separatingDegrees : Set ℕ :=
  {d | 0 < d ∧ ∃ (n : ℕ) (F : MvPolynomial (Fin n) ℂ), F ≠ 0 ∧ F.IsHomogeneous d ∧
    cactusRank F < waringRank d F}

/-! ### The example `F = x_0^2 x_1` and the double point `I = (y_1^2)` -/

/-- The binary cubic `F = x_0^2 x_1`. -/
noncomputable def F0 (K : Type*) [Field K] : MvPolynomial (Fin 2) K := X 0 ^ 2 * X 1

/-- The ideal `(y_1^2)` of the double point at `[1 : 0]`. -/
noncomputable def I0 (K : Type*) [Field K] : Ideal (MvPolynomial (Fin 2) K) :=
  monomialIdeal K {Finsupp.single 1 2}

lemma mem_I0 {g : MvPolynomial (Fin 2) K} : g ∈ I0 K ↔ ∀ m ∈ g.support, 2 ≤ m 1 := by
  unfold I0 monomialIdeal
  rw [mem_ideal_span_monomial_image]
  simp [Finsupp.single_le_iff]

theorem I0_homogeneous : IsHomogeneousIdeal (I0 K) := by
  intro p hp j
  rw [mem_I0] at hp ⊢
  intro m hm
  rw [MvPolynomial.mem_support_iff, coeff_homogeneousComponent] at hm
  split_ifs at hm with h
  · exact hp m (MvPolynomial.mem_support_iff.2 hm)
  · exact absurd rfl hm

theorem I0_saturated : IsSaturated (I0 K) := by
  rintro g ⟨k, hk⟩
  have hX : (X 0 : MvPolynomial (Fin 2) K) ^ k ∈ (irrelevant : Ideal (MvPolynomial (Fin 2) K)) ^ k :=
    Ideal.pow_mem_pow (Ideal.subset_span (Set.mem_range_self 0)) k
  have h := mem_I0.1 (hk _ hX)
  rw [mem_I0]
  intro m hm
  have hm' : m + Finsupp.single 0 k ∈ (X 0 ^ k * g).support := by
    rw [MvPolynomial.mem_support_iff, X_pow_eq_monomial, coeff_monomial_mul',
      if_pos le_add_self, add_tsub_cancel_right, one_mul]
    exact MvPolynomial.mem_support_iff.1 hm
  simpa using h _ hm'

lemma standard_I0 {t : ℕ} (ht : 1 ≤ t) :
    standard ({Finsupp.single 1 2} : Set (Fin 2 →₀ ℕ)) t =
      {Finsupp.single 0 t, Finsupp.single 0 (t - 1) + Finsupp.single 1 1} := by
  ext m
  rw [mem_standard, Finsupp.degree_eq_sum, Fin.sum_univ_two]
  simp only [Set.mem_singleton_iff, forall_eq, Finsupp.single_le_iff, not_le,
    Finset.mem_insert, Finset.mem_singleton]
  constructor
  · rintro ⟨h1, h2⟩
    have : m 1 = 0 ∨ m 1 = 1 := by omega
    rcases this with h | h
    · left; ext i; fin_cases i <;> simp <;> omega
    · right; ext i; fin_cases i <;> simp <;> omega
  · rintro (rfl | rfl) <;> (simp; try omega)

theorem hilbertFunction_I0 {t : ℕ} (ht : 1 ≤ t) : hilbertFunction (I0 K) t = 2 := by
  rw [I0, hilbertFunction_monomialIdeal, standard_I0 ht, Finset.card_pair]
  intro h
  have := congrArg (fun m : Fin 2 →₀ ℕ => m 1) h
  simp at this

/-- `I0 = (y_1^2)` is the ideal of a zero-dimensional scheme of length `2`. -/
theorem I0_zeroDim : IsZeroDimLength (I0 K) 2 :=
  ⟨I0_homogeneous, I0_saturated, 1, fun _ ht => hilbertFunction_I0 ht⟩

lemma F0_eq : F0 K = monomial (Finsupp.single 0 2 + Finsupp.single 1 1) 1 := by
  rw [F0, X_pow_eq_monomial, X, monomial_mul, one_mul]

lemma pderiv1_sq_F0 : (pderiv 1 : Derivation K _ _) (pderiv 1 (F0 K)) = 0 := by
  rw [F0_eq, pderiv_monomial, pderiv_monomial]
  simp

/-- Every element of `(y_1^2)` annihilates `F0` (differentiation). -/
theorem I0_apolar : (I0 K : Set (MvPolynomial (Fin 2) K)) ⊆ annDiff (F0 K) := by
  intro g hg
  have hg' := mem_I0.1 hg
  simp only [annDiff, Set.mem_ofPred_eq, diffAct]
  refine Finset.sum_eq_zero fun m hm => ?_
  obtain ⟨k, hk⟩ : ∃ k, m 1 = k + 2 := ⟨m 1 - 2, by have := hg' m hm; omega⟩
  have : partialPow m (F0 K) = 0 := by
    simp only [partialPow, List.finRange_succ, List.finRange_zero, List.map_cons,
      List.map_nil, List.prod_cons, List.prod_nil, mul_one, Module.End.mul_apply]
    simp only [Fin.succ_zero_eq_one]
    rw [hk, pow_add, Module.End.mul_apply, sq, Module.End.mul_apply]
    simp [pderiv1_sq_F0]
  rw [this, smul_zero]

/-- Every element of `(y_1^2)` annihilates `F0` (contraction). -/
theorem I0_apolar_contract :
    (I0 K : Set (MvPolynomial (Fin 2) K)) ⊆ annContract (F0 K) := by
  intro g hg
  have hg' := mem_I0.1 hg
  simp only [annContract, Set.mem_ofPred_eq, contractAct]
  refine Finset.sum_eq_zero fun m hm => Finset.sum_eq_zero fun a ha => ?_
  have ha' : a = Finsupp.single 0 2 + Finsupp.single 1 1 := by
    rw [F0_eq] at ha
    exact Finset.mem_singleton.1 (support_monomial_subset ha)
  rw [if_neg]
  intro hle
  have := hle 1
  have := hg' m hm
  simp [ha'] at *
  omega

theorem cactusRank_F0_le : cactusRank (F0 K) ≤ 2 :=
  iInf₂_le 2 ⟨I0 K, I0_zeroDim, I0_apolar⟩

theorem cactusRankContract_F0_le : cactusRankContract (F0 K) ≤ 2 :=
  iInf₂_le 2 ⟨I0 K, I0_zeroDim, I0_apolar_contract⟩

/-! ### Waring rank of `x_0^2 x_1` is `3` -/

/-- `x^2 y` is not a sum of two cubes of linear forms (dehomogenized at `x = 1`). -/
lemma not_two_cubes (α₁ β₁ α₂ β₂ : ℂ)
    (h : ∀ t : ℂ, t = (α₁ + β₁ * t) ^ 3 + (α₂ + β₂ * t) ^ 3) : False := by
  have e0 := h 0
  have e1 := h 1
  have em := h (-1)
  have e2 := h 2
  have hc3 : β₁ ^ 3 + β₂ ^ 3 = 0 := by
    linear_combination (-(1:ℂ)/6) * e2 - (1/2) * e0 + (1/2) * e1 + (1/6) * em
  have hc2 : α₁ * β₁ ^ 2 + α₂ * β₂ ^ 2 = 0 := by
    linear_combination (-(1:ℂ)/6) * e1 - (1/6) * em + (1/3) * e0
  have hc1 : 3 * (α₁ ^ 2 * β₁ + α₂ ^ 2 * β₂) = 1 := by
    linear_combination -e1 + e0 - hc3 - 3 * hc2
  have hb1 : β₁ ^ 3 = 0 := by
    linear_combination (-β₁ ^ 3) * hc1 + 3 * (α₁ * β₁ ^ 2 - α₂ * β₂ ^ 2) * hc2 +
      3 * α₂ ^ 2 * β₂ * hc3
  have hb2 : β₂ ^ 3 = 0 := by linear_combination hc3 - hb1
  rw [pow_eq_zero_iff (by norm_num)] at hb1 hb2
  rw [hb1, hb2] at hc1
  norm_num at hc1

lemma eval_linForm (a : Fin 2 → ℂ) (t : ℂ) :
    eval ![1, t] (linForm a) = a 0 + a 1 * t := by
  simp [linForm, Fin.sum_univ_two]

theorem waringRank_F0_ge : 3 ≤ waringRank 3 (F0 ℂ) := by
  refine le_iInf₂ fun r ⟨a, ha⟩ => ?_
  have key : ∀ t : ℂ, t = ∑ i, (a i 0 + a i 1 * t) ^ 3 := by
    intro t
    have := congrArg (eval ![1, t]) ha
    simpa [F0, eval_linForm] using this
  by_contra hr
  have hr' : r < 3 := by exact_mod_cast not_le.1 hr
  interval_cases r
  · simpa using key 1
  · exact not_two_cubes (a 0 0) (a 0 1) 0 0 (fun t => by simpa using key t)
  · exact not_two_cubes (a 0 0) (a 0 1) (a 1 0) (a 1 1)
      (fun t => by simpa [Fin.sum_univ_two] using key t)

/-- An explicit decomposition `x^2 y = (c x + c y)^3 + (-c x + c y)^3 + (-e c y)^3` with
`c^3 = 1/6`, `e^3 = 2`, from `6 x^2 y = (x+y)^3 - (x-y)^3 - 2 y^3`. -/
theorem waringRank_F0_le : waringRank 3 (F0 ℂ) ≤ 3 := by
  set c : ℝ := ((6 : ℝ)⁻¹) ^ ((1 : ℝ) / 3)
  set e : ℝ := (2 : ℝ) ^ ((1 : ℝ) / 3)
  have hc : c ^ 3 * 6 = 1 := by
    rw [← Real.rpow_natCast, ← Real.rpow_mul (by norm_num)]; norm_num
  have he : e ^ 3 = 2 := by
    rw [← Real.rpow_natCast, ← Real.rpow_mul (by norm_num)]; norm_num
  have hC : (C (c : ℂ) : MvPolynomial (Fin 2) ℂ) ^ 3 * 6 = 1 := by
    have h' : (c : ℂ) ^ 3 * 6 = 1 := by exact_mod_cast hc
    rw [← map_pow, ← map_ofNat C 6, ← map_mul, h', map_one]
  have hE : (C (e : ℂ) : MvPolynomial (Fin 2) ℂ) ^ 3 = 2 := by
    have h' : (e : ℂ) ^ 3 = 2 := by exact_mod_cast he
    rw [← map_pow, h', map_ofNat]
  refine iInf₂_le 3 ⟨![![c, c], ![-c, c], ![0, -(e * c)]], ?_⟩
  simp only [linForm, Fin.sum_univ_two, Fin.sum_univ_three, F0]
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two,
    Matrix.vecHead, Matrix.vecTail, Function.comp_apply, Fin.succ_zero_eq_one, map_neg, map_mul, map_zero, zero_mul]
  linear_combination (-(X 0 ^ 2 * X 1 : MvPolynomial (Fin 2) ℂ)) * hC +
    ((C (c : ℂ)) ^ 3 * X 1 ^ 3) * hE

theorem waringRank_F0 : waringRank 3 (F0 ℂ) = 3 :=
  le_antisymm waringRank_F0_le waringRank_F0_ge

/-! ### The conjecture fails -/

theorem F0_ne_zero : F0 ℂ ≠ 0 :=
  mul_ne_zero (pow_ne_zero _ (X_ne_zero _)) (X_ne_zero _)

theorem F0_isHomogeneous : (F0 ℂ).IsHomogeneous 3 :=
  (isHomogeneous_X_pow (0 : Fin 2) 2).mul (isHomogeneous_X ℂ (1 : Fin 2))

/-- `x^2 y`: cactus rank `≤ 2 < 3 =` Waring rank (both apolarity conventions). -/
theorem F0_separates :
    cactusRank (F0 ℂ) < waringRank 3 (F0 ℂ) ∧
      cactusRankContract (F0 ℂ) < waringRank 3 (F0 ℂ) := by
  rw [waringRank_F0]
  exact ⟨cactusRank_F0_le.trans_lt (by norm_num),
    cactusRankContract_F0_le.trans_lt (by norm_num)⟩

theorem three_mem_separatingDegrees : 3 ∈ separatingDegrees :=
  ⟨by norm_num, 2, F0 ℂ, F0_ne_zero, F0_isHomogeneous, F0_separates.1⟩

/-- **Conjecture 00000002853 is false.**  Cactus rank already falls below Waring rank in the
positive degree `3` (witness `x_0^2 x_1`), so `5` is not the minimal such positive degree; in
particular the conjunction claimed by the conjecture fails. -/
theorem conjecture_false :
    3 ∈ separatingDegrees ∧ ¬ IsLeast separatingDegrees 5 ∧ sInf separatingDegrees ≤ 3 := by
  refine ⟨three_mem_separatingDegrees, fun h => ?_, Nat.sInf_le three_mem_separatingDegrees⟩
  have := h.2 three_mem_separatingDegrees
  omega

end C2853
