import Conjecture7668

#print Conjecture7668.qPochhammer
#print Conjecture7668.rootModulusProduct
#print Conjecture7668.geometricMean
#print Conjecture7668.claimedMainTerm
#print Conjecture7668.errorScale
#print Conjecture7668.relativeError
#print Conjecture7668.RelativeAsymptotic
#print Conjecture7668.NecessaryClause

#check Conjecture7668.qPochhammer_eval
#print axioms Conjecture7668.qPochhammer_eval
#check Conjecture7668.linear_factor_ne_zero
#print axioms Conjecture7668.linear_factor_ne_zero
#check Conjecture7668.qPochhammer_ne_zero
#print axioms Conjecture7668.qPochhammer_ne_zero
#check Conjecture7668.linear_factor_roots
#print axioms Conjecture7668.linear_factor_roots
#check Conjecture7668.qPochhammer_roots
#print axioms Conjecture7668.qPochhammer_roots
#check Conjecture7668.qPochhammer_roots_card
#print axioms Conjecture7668.qPochhammer_roots_card
#check Conjecture7668.rootModulusProduct_eq
#print axioms Conjecture7668.rootModulusProduct_eq
#check Conjecture7668.sum_range_real
#print axioms Conjecture7668.sum_range_real
#check Conjecture7668.rootModulusProduct_rpow
#print axioms Conjecture7668.rootModulusProduct_rpow
#check Conjecture7668.geometricMean_eq
#print axioms Conjecture7668.geometricMean_eq
#check Conjecture7668.rootModulusProduct_nonneg
#print axioms Conjecture7668.rootModulusProduct_nonneg
#check Conjecture7668.geometricMean_nonneg
#print axioms Conjecture7668.geometricMean_nonneg
#check Conjecture7668.geometricMean_pow
#print axioms Conjecture7668.geometricMean_pow
#check Conjecture7668.errorScale_nonneg
#print axioms Conjecture7668.errorScale_nonneg
#check Conjecture7668.relativeAsymptotic_iff_isBigO
#print axioms Conjecture7668.relativeAsymptotic_iff_isBigO
#check Conjecture7668.relativeError_eq
#print axioms Conjecture7668.relativeError_eq
#check Conjecture7668.errorScale_tendsto_zero
#print axioms Conjecture7668.errorScale_tendsto_zero
#check Conjecture7668.not_relativeAsymptotic
#print axioms Conjecture7668.not_relativeAsymptotic
#check Conjecture7668.conjecture7668_disproof
#print axioms Conjecture7668.conjecture7668_disproof
#check Conjecture7668.not_relative_isBigO
#print axioms Conjecture7668.not_relative_isBigO
#check Conjecture7668.no_completion
#print axioms Conjecture7668.no_completion
