name = "tlmc5960"
version = "1.0.0"
defaultTargets = ["Conjecture5960"]

[[lean_lib]]
name = "Conjecture5960"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.19.0"
