import Mathlib

/-!
# Conjecture 00000000086 (Burnside order asymptotics) is false

**Definition.** The free Burnside group `B(m,p)` is the largest `m`-generated group satisfying
`x^p = 1`.

**Conjecture.** `log |B(m,p)|` is asymptotic to `(m-1)^2/2 * log p` as `p` tends to infinity.

We build `B(m,p)` as the free group on `Fin m` modulo the normal closure of all `p`-th powers,
and prove that it is the largest `m`-generated group satisfying `x^p = 1`: it is generated by
`m` elements, it satisfies `x^p = 1`, every map of the generators into a group satisfying
`x^p = 1` extends uniquely to a homomorphism, and so `B(m,p)` maps onto every `m`-generated group
satisfying `x^p = 1`.

In particular `B(m,p)` maps onto the abelian group `(ℤ/p)^m` (elementary abelian when `p` is prime). So either `B(m,p)` is
infinite, or `|B(m,p)| ≥ p^m`, i.e. `log |B(m,p)| ≥ m log p`. For `m ∈ {1,2,3}` we have
`m > (m-1)^2/2`, and the claimed asymptotic fails along every filter `l ≤ atTop` that is not
`⊥` (in particular along all integers and along the primes). This holds both when the
conjecture requires `B(m,p)` to be (eventually) finite, and under Mathlib's junk value
`Nat.card = 0` for infinite types (for `m = 1` and `p ≥ 1` the group is finite).
The results hold for *any* family of groups having the "largest" property, not only for our
construction.
-/

open Filter Asymptotics

namespace Conjecture86

/-! ## The free Burnside group and its universal property -/

/-- The set of all `p`-th powers in the free group on `m` generators. -/
def powers (m p : ℕ) : Set (FreeGroup (Fin m)) := Set.range fun g => g ^ p

/-- The free Burnside group `B(m,p)`: the free group on `m` generators modulo the normal subgroup
generated by all `p`-th powers. -/
abbrev B (m p : ℕ) : Type := FreeGroup (Fin m) ⧸ Subgroup.normalClosure (powers m p)

/-- The `m` canonical generators of `B(m,p)`. -/
def gen (m p : ℕ) (i : Fin m) : B m p := QuotientGroup.mk (FreeGroup.of i)

/-- `B(m,p)` satisfies the law `x^p = 1`. -/
theorem B_pow_eq_one (m p : ℕ) (x : B m p) : x ^ p = 1 := by
  induction x using QuotientGroup.induction_on with
  | H g =>
    rw [← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
    exact Subgroup.subset_normalClosure ⟨g, rfl⟩

/-- `B(m,p)` is generated by the `m` elements `gen m p i`. -/
theorem closure_range_gen (m p : ℕ) : Subgroup.closure (Set.range (gen m p)) = ⊤ := by
  have h : Set.range (gen m p) = (QuotientGroup.mk' _) '' Set.range FreeGroup.of := by
    rw [← Set.range_comp]; rfl
  rw [h, ← MonoidHom.map_closure, FreeGroup.closure_range_of, ← MonoidHom.range_eq_map,
    MonoidHom.range_eq_top]
  exact QuotientGroup.mk'_surjective _

/-- Universal property, existence: a map `f` of the generators into a group satisfying `x^p = 1`
extends to a homomorphism `B(m,p) →* H`. -/
def lift {m p : ℕ} {H : Type*} [Group H] (hH : ∀ x : H, x ^ p = 1) (f : Fin m → H) :
    B m p →* H :=
  QuotientGroup.lift _ (FreeGroup.lift f) (Subgroup.normalClosure_le_normal (by
    rintro _ ⟨g, rfl⟩
    simp [MonoidHom.mem_ker, hH]))

theorem lift_gen {m p : ℕ} {H : Type*} [Group H] (hH : ∀ x : H, x ^ p = 1) (f : Fin m → H)
    (i : Fin m) : lift hH f (gen m p i) = f i := by
  simp [lift, gen]

/-- Universal property, uniqueness: a homomorphism out of `B(m,p)` is determined by its values on
the generators. -/
theorem hom_ext {m p : ℕ} {H : Type*} [Group H] (φ ψ : B m p →* H)
    (h : ∀ i, φ (gen m p i) = ψ (gen m p i)) : φ = ψ :=
  QuotientGroup.monoidHom_ext _ (FreeGroup.ext_hom _ _ h)

/-- `G` is the largest `m`-generated group satisfying `x^p = 1`: it is generated by `m` elements,
satisfies `x^p = 1`, and maps onto every `m`-generated group satisfying `x^p = 1`. -/
def IsLargest (m p : ℕ) (G : Type) [Group G] : Prop :=
  (∃ g : Fin m → G, Subgroup.closure (Set.range g) = ⊤) ∧ (∀ x : G, x ^ p = 1) ∧
    ∀ (H : Type) [Group H], (∃ h : Fin m → H, Subgroup.closure (Set.range h) = ⊤) →
      (∀ x : H, x ^ p = 1) → ∃ φ : G →* H, Function.Surjective φ

theorem lift_surjective {m p : ℕ} {H : Type*} [Group H] (hH : ∀ x : H, x ^ p = 1)
    (f : Fin m → H) (hf : Subgroup.closure (Set.range f) = ⊤) :
    Function.Surjective (lift (m := m) hH f) := by
  rw [← MonoidHom.range_eq_top, eq_top_iff, ← hf, Subgroup.closure_le]
  rintro _ ⟨i, rfl⟩
  exact ⟨gen m p i, lift_gen hH f i⟩

/-- Our `B(m,p)` is the largest `m`-generated group satisfying `x^p = 1`. -/
theorem B_isLargest (m p : ℕ) : IsLargest m p (B m p) :=
  ⟨⟨gen m p, closure_range_gen m p⟩, B_pow_eq_one m p,
    fun _ _ ⟨f, hf⟩ hH => ⟨lift hH f, lift_surjective hH f hf⟩⟩

/-! ## The abelian quotient `(ℤ/p)^m` -/

/-- The abelian group `(ℤ/p)^m` (elementary abelian for prime `p`), written multiplicatively. -/
abbrev E (m p : ℕ) : Type := Multiplicative (Fin m → ZMod p)

/-- The standard basis vectors of `(ℤ/p)^m`. -/
def egen (m p : ℕ) (i : Fin m) : E m p := Multiplicative.ofAdd (Pi.single i 1)

theorem E_pow_eq_one (m p : ℕ) (x : E m p) : x ^ p = 1 := by
  apply Multiplicative.toAdd.injective
  funext i
  simp

theorem closure_range_egen (m p : ℕ) [NeZero p] :
    Subgroup.closure (Set.range (egen m p)) = ⊤ := by
  rw [eq_top_iff]
  intro x _
  have hx : x = ∏ i, egen m p i ^ (Multiplicative.toAdd x i).val := by
    apply Multiplicative.toAdd.injective
    simp only [toAdd_prod, toAdd_pow, egen, toAdd_ofAdd]
    funext j
    rw [Finset.sum_apply]
    simp only [Pi.smul_apply, Pi.single_apply, smul_ite, smul_zero, Finset.sum_ite_eq,
      Finset.mem_univ, if_true, nsmul_eq_mul, mul_one, ZMod.natCast_zmod_val]
  rw [hx]
  exact Subgroup.prod_mem _ fun i _ => Subgroup.pow_mem _ (Subgroup.subset_closure (Set.mem_range_self i)) _

theorem card_E (m p : ℕ) : Nat.card (E m p) = p ^ m := by
  rw [Nat.card_congr Multiplicative.toAdd, Nat.card_fun, Nat.card_zmod, Nat.card_fin]

/-- A largest `m`-generated group satisfying `x^p = 1`, if finite, has order at least `p^m`. -/
theorem card_ge (m p : ℕ) (hp : 1 ≤ p) (G : Type) [Group G] (hG : IsLargest m p G) [Finite G] :
    p ^ m ≤ Nat.card G := by
  have : NeZero p := ⟨by omega⟩
  have hgen : ∃ h : Fin m → E m p, Subgroup.closure (Set.range h) = ⊤ :=
    ⟨egen m p, closure_range_egen m p⟩
  obtain ⟨φ, hφ⟩ := hG.2.2 (E m p) hgen (E_pow_eq_one m p)
  rw [← card_E m p]
  exact Nat.card_le_card_of_surjective φ hφ

/-- A largest `1`-generated group satisfying `x^p = 1` (`p ≥ 1`) is finite. -/
theorem finite_of_isLargest_one (p : ℕ) (hp : 1 ≤ p) (G : Type) [Group G]
    (hG : IsLargest 1 p G) : Finite G := by
  obtain ⟨g, hg⟩ := hG.1
  have hfin : IsOfFinOrder (g 0) := isOfFinOrder_iff_pow_eq_one.2 ⟨p, hp, hG.2.1 _⟩
  have htop : Subgroup.zpowers (g 0) = ⊤ := by
    rw [Subgroup.zpowers_eq_closure, ← hg]
    congr 1
    ext x
    simp [Fin.fin_one_eq_zero, eq_comm]
  have h := hfin.finite_zpowers
  rw [htop, Subgroup.coe_top] at h
  exact Set.finite_univ_iff.1 h

/-! ## The asymptotic fails -/

/-- The conjectured size `(m-1)^2/2 * log p`. -/
noncomputable def target (m : ℕ) (p : ℕ) : ℝ := ((m : ℝ) - 1) ^ 2 / 2 * Real.log p

/-- `log |G p|`, with Mathlib's junk value `Nat.card = 0` (so `log = 0`) for infinite groups. -/
noncomputable def logOrder (G : ℕ → Type) (p : ℕ) : ℝ := Real.log (Nat.card (G p))

/-- If `‖u - v‖ > η ‖v‖` eventually, for a fixed `η > 0`, then `u` is not asymptotic to `v`. -/
theorem not_isEquivalent_of_gap {l : Filter ℕ} [l.NeBot] {u v : ℕ → ℝ} {η : ℝ} (hη : 0 < η)
    (h : ∀ᶠ p in l, η * ‖v p‖ < ‖u p - v p‖) : ¬ u ~[l] v := by
  intro huv
  obtain ⟨p, h1, h2⟩ := (h.and (huv.isLittleO.def hη)).exists
  simp only [Pi.sub_apply] at h2
  linarith

/-- The pointwise gap, for `m ∈ {1,2,3}` and `p ≥ 2`, covering finite and infinite `G`. -/
theorem gap (m p : ℕ) (hm : m = 1 ∨ m = 2 ∨ m = 3) (hp : 2 ≤ p) (G : Type) [Group G]
    (hG : IsLargest m p G) :
    1 / 4 * ‖target m p‖ < ‖Real.log (Nat.card G) - target m p‖ := by
  have hp1 : (1 : ℝ) < p := by exact_mod_cast hp
  have hL : 0 < Real.log p := Real.log_pos hp1
  rw [Real.norm_eq_abs, Real.norm_eq_abs, abs_of_nonneg (by unfold target; positivity)]
  by_cases hfin : Finite G
  · have hc : ((p ^ m : ℕ) : ℝ) ≤ Nat.card G := by exact_mod_cast card_ge m p (by omega) G hG
    have hl : (m : ℝ) * Real.log p ≤ Real.log (Nat.card G) := by
      rw [← Real.log_pow, ← Nat.cast_pow]
      exact Real.log_le_log (by positivity) hc
    refine lt_of_lt_of_le ?_ (le_abs_self _)
    unfold target
    rcases hm with rfl | rfl | rfl <;> norm_num at hl ⊢ <;> linarith
  · have hm' : m = 2 ∨ m = 3 := by
      rcases hm with rfl | h | h
      · exact absurd (finite_of_isLargest_one p (by omega) G hG) hfin
      · exact Or.inl h
      · exact Or.inr h
    rw [not_finite_iff_infinite] at hfin
    rw [Nat.card_eq_zero_of_infinite, Nat.cast_zero, Real.log_zero]
    refine lt_of_lt_of_le ?_ (neg_le_abs _)
    unfold target
    rcases hm' with rfl | rfl <;> norm_num <;> linarith

/-- **Main result (any largest family).** For `m ∈ {1,2,3}` and any family `G p` of largest
`m`-generated groups satisfying `x^p = 1`, `log |G p|` is not asymptotic to `(m-1)^2/2 * log p`
along any filter `l ≤ atTop` with `l ≠ ⊥` (junk convention `log |G p| = 0` if `G p` is infinite). -/
theorem not_asymptotic_of_isLargest (l : Filter ℕ) [l.NeBot] (hl : l ≤ atTop) (m : ℕ)
    (hm : m = 1 ∨ m = 2 ∨ m = 3) (G : ℕ → Type) [∀ p, Group (G p)]
    (hG : ∀ p, IsLargest m p (G p)) : ¬ logOrder G ~[l] target m :=
  not_isEquivalent_of_gap (η := 1 / 4) (by norm_num) <|
    ((eventually_ge_atTop 2).filter_mono hl).mono fun p hp => gap m p hm hp (G p) (hG p)

/-- The claim for one `m` along a filter `l` of exponents, in the strict reading: `B(m,p)` is
eventually finite (so that `log |B(m,p)|` is a real number) and the asymptotic holds. -/
def Claim (l : Filter ℕ) (m : ℕ) (G : ℕ → Type) : Prop :=
  (∀ᶠ p in l, Finite (G p)) ∧ logOrder G ~[l] target m

/-- The conjecture along a filter `l` of exponents: the claim for every `m ≥ 2`. -/
def Conjecture (l : Filter ℕ) : Prop := ∀ m : ℕ, 2 ≤ m → Claim l m (B m)

/-- Junk reading for the free Burnside groups, `m ∈ {1,2,3}`. -/
theorem burnside_not_asymptotic (l : Filter ℕ) [l.NeBot] (hl : l ≤ atTop) (m : ℕ)
    (hm : m = 1 ∨ m = 2 ∨ m = 3) : ¬ logOrder (B m) ~[l] target m :=
  not_asymptotic_of_isLargest l hl m hm (B m) (B_isLargest m)

/-- Strict reading for the free Burnside groups, `m ∈ {1,2,3}`. -/
theorem burnside_not_claim (l : Filter ℕ) [l.NeBot] (hl : l ≤ atTop) (m : ℕ)
    (hm : m = 1 ∨ m = 2 ∨ m = 3) : ¬ Claim l m (B m) :=
  fun h => burnside_not_asymptotic l hl m hm h.2

/-- The primes, as a filter of exponents tending to infinity. -/
theorem primes_neBot : (atTop ⊓ 𝓟 {p : ℕ | p.Prime}).NeBot :=
  frequently_iff_neBot.1 (Nat.frequently_atTop_iff_infinite.2 Nat.infinite_setOfPred_prime)

/-- **Main theorem.** The conjecture fails (already at `m = 2`) along every filter `l ≤ atTop`,
`l ≠ ⊥`. -/
theorem conjecture86_false (l : Filter ℕ) [l.NeBot] (hl : l ≤ atTop) : ¬ Conjecture l :=
  fun h => burnside_not_claim l hl 2 (by norm_num) (h 2 le_rfl)

/-- The conjecture fails as `p → ∞` through all integers. -/
theorem conjecture86_false_atTop : ¬ Conjecture atTop := conjecture86_false atTop le_rfl

/-- The conjecture fails as `p → ∞` through the primes. -/
theorem conjecture86_false_primes : ¬ Conjecture (atTop ⊓ 𝓟 {p : ℕ | p.Prime}) :=
  have := primes_neBot
  conjecture86_false _ inf_le_left

end Conjecture86
