import Mathlib

/-!
# Conjecture 00000003888 is false

The conjecture: the Hilbert-Kunz density function of a fixed ideal is piecewise linear with
finitely many breakpoints; conversely, there exist explicit one-parameter ideal families whose
breakpoint counts grow unboundedly.

We use Trivedi's Hilbert-Kunz density function: for a standard graded `R` of dimension `d`
over a field `k` of characteristic `p > 0` and a homogeneous ideal `I` of finite colength,
`HKd(R, I)(x) = lim_{n → ∞} f_n(x)`, `f_n(x) = (1/q^(d-1)) ℓ(R/I^[q])_{⌊xq⌋}`, `q = p^n`,
where `I^[q]` is the ideal generated by the `q`-th powers of the elements of `I`.

For `R = k[x, y, z]` (standard grading, `d = 3`) and `I = (x, y, z)` we have
`I^[q] = (x^q, y^q, z^q)`, every monomial of degree `m < q` is standard, so
`ℓ(R/I^[q])_m = C(m+2, 2)` and `f_n(x) → x^2/2` for `0 ≤ x < 1`.  A function equal to
`x^2/2` on `(0, 1)` is not affine on any nondegenerate subinterval, hence not piecewise linear
with finitely many breakpoints.  So the first clause, and with it the conjecture, fails.

The block "graded pieces of monomial quotients" is reused (with credit) from the accepted
solution of conjecture 00000000539 (`Tlmc/C539.lean`).
-/

open MvPolynomial Module Finset Filter Topology

namespace C3888

variable {σ : Type*} {K : Type*} [Field K]

/-! ### Graded pieces of monomial quotients (from the solution of 00000000539) -/

/-- The monomial ideal of `K[x_σ]` generated by the monomials `x^g`, `g ∈ G`. -/
noncomputable def monomialIdeal (K : Type*) [Field K] (G : Set (σ →₀ ℕ)) :
    Ideal (MvPolynomial σ K) :=
  Ideal.span ((fun g => monomial g (1 : K)) '' G)

/-- The degree-`j` component `(S/J)_j` of the graded quotient: the image of the degree-`j`
homogeneous polynomials under the quotient map. -/
noncomputable def gradedPiece (J : Ideal (MvPolynomial σ K)) (j : ℕ) :
    Submodule K (MvPolynomial σ K ⧸ J) :=
  (homogeneousSubmodule σ K j).map (Ideal.Quotient.mkₐ K J).toLinearMap

/-- The Hilbert function `j ↦ ℓ((S/J)_j) = dim_K (S/J)_j`. -/
noncomputable def hilbertFunction (J : Ideal (MvPolynomial σ K)) (j : ℕ) : ℕ :=
  finrank K (gradedPiece J j)

/-- The standard monomials of degree `j`: degree-`j` exponents dominating no generator. -/
noncomputable def standard [Fintype σ] (G : Set (σ →₀ ℕ)) (j : ℕ) : Finset (σ →₀ ℕ) := by
  classical
  exact (univ.finsuppAntidiag j).filter fun m => ∀ g ∈ G, ¬ g ≤ m

lemma mem_standard [Fintype σ] {G : Set (σ →₀ ℕ)} {j : ℕ} {m : σ →₀ ℕ} :
    m ∈ standard G j ↔ m.degree = j ∧ ∀ g ∈ G, ¬ g ≤ m := by
  classical
  simp [standard, mem_finsuppAntidiag, Finsupp.degree_eq_sum]

theorem hilbertFunction_monomialIdeal [Fintype σ] (G : Set (σ →₀ ℕ)) (j : ℕ) :
    hilbertFunction (monomialIdeal K G) j = (standard G j).card := by
  classical
  set I := monomialIdeal K G
  set T := standard G j
  let mk := (Ideal.Quotient.mkₐ K I).toLinearMap
  let w : T → MvPolynomial σ K := fun m => monomial m.1 1
  have hw : LinearIndependent K w := by
    have h := (basisMonomials σ K).linearIndependent.comp (Subtype.val : T → _)
      Subtype.val_injective
    have e : w = ⇑(basisMonomials σ K) ∘ Subtype.val := by
      funext m; simp [w, coe_basisMonomials]
    rw [e]; exact h
  have hspanw : Submodule.span K (Set.range w) = restrictSupport K (T : Set (σ →₀ ℕ)) := by
    rw [restrictSupport_eq_span]; congr 1; ext p; simp [w]
  have hdisj : Disjoint (Submodule.span K (Set.range w)) (LinearMap.ker mk) := by
    rw [Submodule.disjoint_def, hspanw]
    intro p hp hpI
    have hpI' : p ∈ I := by
      simpa [mk, Ideal.Quotient.eq_zero_iff_mem] using hpI
    rw [mem_restrictSupport_iff] at hp
    by_contra hne
    obtain ⟨m, hm⟩ := (support_nonempty (p := p)).2 hne
    obtain ⟨g, hg, hgm⟩ := (mem_ideal_span_monomial_image.1 hpI') m hm
    exact (mem_standard.1 (hp hm)).2 g hg hgm
  have hli : LinearIndependent K (mk ∘ w) := hw.map hdisj
  have hspan : Submodule.span K (Set.range (mk ∘ w)) = gradedPiece I j := by
    unfold gradedPiece
    rw [homogeneousSubmodule_eq_finsupp_supported, ← restrictSupport,
      restrictSupport_eq_span, Submodule.map_span]
    apply le_antisymm
    · rw [Submodule.span_le]
      rintro _ ⟨m, rfl⟩
      exact Submodule.subset_span ⟨monomial m.1 1, ⟨m.1, (mem_standard.1 m.2).1, rfl⟩, rfl⟩
    · rw [Submodule.span_le]
      rintro _ ⟨_, ⟨m, hm, rfl⟩, rfl⟩
      by_cases hs : ∀ g ∈ G, ¬ g ≤ m
      · exact Submodule.subset_span ⟨⟨m, mem_standard.2 ⟨hm, hs⟩⟩, rfl⟩
      · push Not at hs
        obtain ⟨g, hg, hgm⟩ := hs
        have : monomial m (1 : K) ∈ I := by
          refine mem_ideal_span_monomial_image.2 ?_
          intro xi hxi
          rw [support_monomial, if_neg one_ne_zero, Finset.mem_singleton] at hxi
          exact ⟨g, hg, hxi ▸ hgm⟩
        have h0 : (Ideal.Quotient.mkₐ K I).toLinearMap (monomial m 1) = 0 := by
          simpa [Ideal.Quotient.eq_zero_iff_mem] using this
        rw [SetLike.mem_coe, h0]
        exact Submodule.zero_mem _
  unfold hilbertFunction
  rw [← hspan, finrank_span_eq_card hli, Fintype.card_coe]

/-! ### Trivedi's Hilbert-Kunz density function -/

/-- The Frobenius power `I^[q]`: the ideal generated by the `q`-th powers of elements of `I`. -/
def frobeniusPower {R : Type*} [CommRing R] (I : Ideal R) (q : ℕ) : Ideal R :=
  Ideal.span ((· ^ q) '' (I : Set R))

/-- `ℓ((S/J)_m)` for an integer degree `m`; the graded pieces in negative degree are zero. -/
noncomputable def lengthPiece (J : Ideal (MvPolynomial σ K)) (m : ℤ) : ℕ :=
  if 0 ≤ m then hilbertFunction J m.toNat else 0

/-- Trivedi's `f_n(x) = (1/q^(d-1)) ℓ(R/I^[q])_{⌊xq⌋}` with `q = p^n`, `p = char K`, and
`d = |σ| = dim K[x_σ]` (see `ringKrullDim_eq`). -/
noncomputable def hkApprox (I : Ideal (MvPolynomial σ K)) (n : ℕ) (x : ℝ) : ℝ :=
  (((ringChar K : ℝ) ^ n) ^ (Nat.card σ - 1))⁻¹ *
    lengthPiece (frobeniusPower I (ringChar K ^ n)) ⌊x * (ringChar K : ℝ) ^ n⌋

/-- Trivedi's Hilbert-Kunz density function `HKd(R, I)(x) = lim_{n → ∞} f_n(x)` (as a
function `ℝ → ℝ`; `limUnder` returns the limit wherever it exists). -/
noncomputable def hkDensity (I : Ideal (MvPolynomial σ K)) (x : ℝ) : ℝ :=
  limUnder atTop fun n => hkApprox I n x

/-- The number `d` used in `hkApprox` is the Krull dimension of `K[x_σ]`. -/
theorem ringKrullDim_eq [Finite σ] : ringKrullDim (MvPolynomial σ K) = Nat.card σ := by
  rw [MvPolynomial.ringKrullDim_of_isNoetherianRing, ringKrullDim_eq_zero_of_field, zero_add]

/-! ### Piecewise linearity -/

/-- `f` is piecewise linear (piecewise affine) on `s` with finitely many breakpoints: there is
a finite set `B` of breakpoints such that `f` is affine on every open interval contained in
`s \ B`.  (Values at the breakpoints are unconstrained and no continuity is required; the
partition form `IsPiecewiseLinearPartition` implies it, see
`IsPiecewiseLinearPartition.isPiecewiseLinearOn`.) -/
def IsPiecewiseLinearOn (f : ℝ → ℝ) (s : Set ℝ) : Prop :=
  ∃ B : Finset ℝ, ∀ a b : ℝ, Set.Ioo a b ⊆ s \ ↑B →
    ∃ μ c : ℝ, ∀ x ∈ Set.Ioo a b, f x = μ * x + c

/-- The partition form on `[a, b]`: `a = t_0 < t_1 < ... < t_k = b` and `f` is affine on each
`[t_i, t_{i+1}]`. -/
def IsPiecewiseLinearPartition (f : ℝ → ℝ) (a b : ℝ) : Prop :=
  ∃ (k : ℕ) (t : ℕ → ℝ), (∀ i < k, t i < t (i + 1)) ∧ t 0 = a ∧ t k = b ∧
    ∀ i < k, ∃ μ c : ℝ, ∀ x ∈ Set.Icc (t i) (t (i + 1)), f x = μ * x + c

/-- The partition form implies `IsPiecewiseLinearOn` (with breakpoints `t_0, ..., t_k`). -/
theorem IsPiecewiseLinearPartition.isPiecewiseLinearOn {f : ℝ → ℝ} {a b : ℝ}
    (h : IsPiecewiseLinearPartition f a b) : IsPiecewiseLinearOn f (Set.Icc a b) := by
  classical
  obtain ⟨k, t, -, h0, hk, hf⟩ := h
  refine ⟨(Finset.range (k + 1)).image t, fun u v huv => ?_⟩
  by_cases hlt : v ≤ u
  · exact ⟨0, 0, fun x hx => absurd (hx.1.trans hx.2) (not_lt.2 hlt)⟩
  push Not at hlt
  have hx0 : (u + v) / 2 ∈ Set.Ioo u v := ⟨by linarith, by linarith⟩
  obtain ⟨⟨hax, hxb⟩, hxB⟩ := huv hx0
  have hB : ∀ i ≤ k, t i ∉ Set.Ioo u v := fun i hi hm =>
    (huv hm).2 (Finset.mem_image.2 ⟨i, Finset.mem_range.2 (by omega), rfl⟩)
  have htk : (u + v) / 2 < t k := lt_of_le_of_ne (hk ▸ hxb) fun e =>
    hxB (Finset.mem_image.2 ⟨k, Finset.mem_range.2 (by omega), e.symm⟩)
  have hex : ∃ j, (u + v) / 2 < t j := ⟨k, htk⟩
  set j := Nat.find hex
  have hjk : j ≤ k := Nat.find_min' hex htk
  have hj0 : j ≠ 0 := fun e => by
    have := Nat.find_spec hex; rw [show Nat.find hex = 0 from e, h0] at this; linarith
  have hti : t (j - 1) ≤ (u + v) / 2 := not_lt.1 (Nat.find_min hex (by omega))
  have htj : (u + v) / 2 < t j := Nat.find_spec hex
  obtain ⟨μ, c, hμ⟩ := hf (j - 1) (by omega)
  refine ⟨μ, c, fun y hy => hμ y ⟨?_, ?_⟩⟩
  · by_contra hc; push Not at hc
    exact hB (j - 1) (by omega) ⟨hy.1.trans hc, lt_of_le_of_lt hti hx0.2⟩
  · rw [show j - 1 + 1 = j by omega]
    by_contra hc; push Not at hc
    exact hB j hjk ⟨hx0.1.trans htj, hc.trans hy.2⟩

/-- A function that equals `x^2/2` on `(0,1)` is not affine on any nondegenerate open
subinterval of `(0,1)`. -/
theorem not_affine {f : ℝ → ℝ} (hf : ∀ x ∈ Set.Ioo (0 : ℝ) 1, f x = x ^ 2 / 2) {a b : ℝ}
    (hab : a < b) (hs : Set.Ioo a b ⊆ Set.Ioo 0 1) :
    ¬ ∃ μ c : ℝ, ∀ x ∈ Set.Ioo a b, f x = μ * x + c := by
  rintro ⟨μ, c, h⟩
  have m1 : (3 * a + b) / 4 ∈ Set.Ioo a b := ⟨by linarith, by linarith⟩
  have m2 : (a + b) / 2 ∈ Set.Ioo a b := ⟨by linarith, by linarith⟩
  have m3 : (a + 3 * b) / 4 ∈ Set.Ioo a b := ⟨by linarith, by linarith⟩
  have e1 := (hf _ (hs m1)).symm.trans (h _ m1)
  have e2 := (hf _ (hs m2)).symm.trans (h _ m2)
  have e3 := (hf _ (hs m3)).symm.trans (h _ m3)
  nlinarith [sq_pos_of_pos (sub_pos.2 hab)]

/-- A function equal to `x^2/2` on `(0,1)` is not piecewise linear with finitely many
breakpoints on any set `s ⊇ (0,1)`. -/
theorem not_isPiecewiseLinearOn {f : ℝ → ℝ} (hf : ∀ x ∈ Set.Ioo (0 : ℝ) 1, f x = x ^ 2 / 2)
    {s : Set ℝ} (hs : Set.Ioo 0 1 ⊆ s) : ¬ IsPiecewiseLinearOn f s := by
  rintro ⟨B, hB⟩
  obtain ⟨x, hx, hxB⟩ := ((Set.Ioo_infinite (zero_lt_one' ℝ)).sdiff B.finite_toSet).nonempty
  have hopen : IsOpen (Set.Ioo (0 : ℝ) 1 \ ↑B) := isOpen_Ioo.sdiff B.finite_toSet.isClosed
  obtain ⟨ε, hε, hball⟩ := Metric.isOpen_iff.1 hopen x ⟨hx, hxB⟩
  rw [Real.ball_eq_Ioo] at hball
  have hsub : Set.Ioo (x - ε) (x + ε) ⊆ Set.Ioo 0 1 := fun y hy => (hball hy).1
  refine not_affine hf (by linarith) hsub (hB _ _ fun y hy => ⟨hs (hball hy).1, (hball hy).2⟩)

/-! ### The example `R = K[x, y, z]`, `I = (x, y, z)` -/

/-- The homogeneous maximal ideal `(x, y, z)` of `K[x, y, z]`. -/
noncomputable def maxIdeal (K : Type*) [Field K] : Ideal (MvPolynomial (Fin 3) K) :=
  Ideal.span (Set.range X)

attribute [local instance] MvPolynomial.gradedAlgebra in
/-- `(x, y, z)` is a homogeneous ideal (for the standard grading). -/
theorem maxIdeal_isHomogeneous : (maxIdeal K).IsHomogeneous (homogeneousSubmodule (Fin 3) K) :=
  Ideal.homogeneous_span _ _ (by rintro _ ⟨i, rfl⟩; exact ⟨1, isHomogeneous_X K i⟩)

/-- `(x, y, z)` has finite colength: `K[x, y, z]/(x, y, z) ≅ K` has dimension `1`. -/
theorem finrank_quotient_maxIdeal :
    finrank K (MvPolynomial (Fin 3) K ⧸ maxIdeal K) = 1 := by
  let φ : MvPolynomial (Fin 3) K →ₐ[K] K := aeval 0
  have hφ : ∀ f, φ f = constantCoeff f := fun f => by simp [φ]
  have hker : RingHom.ker φ = maxIdeal K := by
    have hX : (Set.range (X : Fin 3 → MvPolynomial (Fin 3) K)) =
        (fun g => monomial g (1 : K)) '' Set.range fun i => Finsupp.single i 1 := by
      rw [← Set.range_comp]; rfl
    ext f
    rw [RingHom.mem_ker, hφ, maxIdeal, hX, mem_ideal_span_monomial_image]
    constructor
    · intro h0 m hm
      have hm0 : m ≠ 0 := by
        rintro rfl; exact (mem_support_iff.1 hm) (by rwa [← constantCoeff_eq])
      obtain ⟨i, hi⟩ := Finsupp.ne_iff.1 hm0
      exact ⟨_, ⟨i, rfl⟩, Finsupp.single_le_iff.2 (Nat.one_le_iff_ne_zero.2 hi)⟩
    · intro h
      by_contra h0
      have : (0 : Fin 3 →₀ ℕ) ∈ f.support := mem_support_iff.2 (by rwa [← constantCoeff_eq])
      obtain ⟨_, ⟨i, rfl⟩, hle⟩ := h 0 this
      simpa using hle i
  have hsurj : Function.Surjective φ := fun c => ⟨C c, by simp [hφ]⟩
  let e := (Ideal.quotientEquivAlgOfEq K hker.symm).trans
    (Ideal.quotientKerAlgEquivOfSurjective hsurj)
  rw [e.toLinearEquiv.finrank_eq, finrank_self]

/-- Exponents of `x^q, y^q, z^q`. -/
def Gq (q : ℕ) : Set (Fin 3 →₀ ℕ) := Set.range fun i => Finsupp.single i q

/-- `(x, y, z)^[q] = (x^q, y^q, z^q)` when `q = p^n`, `p = char K`. -/
theorem frobeniusPower_maxIdeal (p : ℕ) [Fact p.Prime] [CharP K p] (n : ℕ) :
    frobeniusPower (maxIdeal K) (p ^ n) = monomialIdeal K (Gq (p ^ n)) := by
  have hq : p ^ n ≠ 0 := pow_ne_zero _ (Fact.out : p.Prime).ne_zero
  have hG : (fun g => monomial g (1 : K)) '' Gq (p ^ n) = Set.range fun i => X i ^ p ^ n := by
    rw [Gq, ← Set.range_comp]; congr 1; funext i; simp [X_pow_eq_monomial]
  rw [monomialIdeal, hG]
  apply le_antisymm
  · rw [frobeniusPower, Ideal.span_le]
    rintro _ ⟨f, hf, rfl⟩
    induction hf using Submodule.span_induction with
    | mem x hx => obtain ⟨i, rfl⟩ := hx; exact Ideal.subset_span ⟨i, rfl⟩
    | zero => simp [zero_pow hq]
    | add a b _ _ ha hb => simp only [add_pow_char_pow]; exact add_mem ha hb
    | smul r a _ ha =>
      change (r * a) ^ p ^ n ∈ _; rw [mul_pow]; exact Ideal.mul_mem_left _ _ ha
  · rw [Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    exact Ideal.subset_span ⟨X i, Ideal.subset_span ⟨i, rfl⟩, rfl⟩

/-- In degree `m < q` every monomial is standard for `(x^q, y^q, z^q)`. -/
theorem hilbertFunction_Gq {q m : ℕ} (hm : m < q) :
    hilbertFunction (monomialIdeal K (Gq q)) m = (m + 2).choose 2 := by
  classical
  rw [hilbertFunction_monomialIdeal]
  have : standard (Gq q) m = univ.finsuppAntidiag m := by
    ext a
    rw [mem_standard, mem_finsuppAntidiag, Finsupp.degree_eq_sum]
    refine ⟨fun h => ⟨h.1, Finset.subset_univ _⟩, fun h => ⟨h.1, ?_⟩⟩
    rintro _ ⟨i, rfl⟩ hle
    have h1 := hle i
    rw [Finsupp.single_eq_same] at h1
    have h2 : a i ≤ m := by
      rw [← h.1]; exact Finset.single_le_sum (fun _ _ => Nat.zero_le _) (Finset.mem_univ i)
    omega
  rw [this, card_finsuppAntidiag_nat_eq_choose, card_univ, Fintype.card_fin,
    show 3 + m - 1 = m + 2 by omega, Nat.choose_symm_add]

/-- For `0 ≤ x < 1`, `f_n(x) → x^2/2` along `q = p^n`, `n → ∞`. -/
theorem tendsto_hkApprox (p : ℕ) [hp : Fact p.Prime] [CharP K p] {x : ℝ} (hx0 : 0 ≤ x)
    (hx1 : x < 1) : Tendsto (fun n => hkApprox (maxIdeal K) n x) atTop (𝓝 (x ^ 2 / 2)) := by
  have hp1 : (1 : ℝ) < p := by exact_mod_cast hp.out.one_lt
  have hqpos : ∀ n : ℕ, (0 : ℝ) < (p : ℝ) ^ n := fun n => pow_pos (by linarith) n
  have hv : Tendsto (fun n : ℕ => ((p : ℝ) ^ n)⁻¹) atTop (𝓝 0) :=
    (tendsto_pow_atTop_atTop_of_one_lt hp1).inv_tendsto_atTop
  have hu : Tendsto (fun n : ℕ => (⌊x * (p : ℝ) ^ n⌋ : ℝ) / (p : ℝ) ^ n) atTop (𝓝 x) := by
    have hlow : Tendsto (fun n : ℕ => x - ((p : ℝ) ^ n)⁻¹) atTop (𝓝 x) := by
      simpa using (tendsto_const_nhds (x := x)).sub hv
    refine tendsto_of_tendsto_of_tendsto_of_le_of_le hlow tendsto_const_nhds (fun n => ?_)
      (fun n => ?_)
    · have h1 := Int.lt_floor_add_one (x * (p : ℝ) ^ n)
      rw [le_div_iff₀ (hqpos n), sub_mul, inv_mul_cancel₀ (hqpos n).ne']
      linarith
    · rw [div_le_iff₀ (hqpos n)]; exact Int.floor_le _
  have key : ∀ n : ℕ, hkApprox (maxIdeal K) n x =
      ((⌊x * (p : ℝ) ^ n⌋ : ℝ) / (p : ℝ) ^ n + 2 * ((p : ℝ) ^ n)⁻¹) *
        ((⌊x * (p : ℝ) ^ n⌋ : ℝ) / (p : ℝ) ^ n + ((p : ℝ) ^ n)⁻¹) / 2 := by
    intro n
    have h0 : 0 ≤ ⌊x * (p : ℝ) ^ n⌋ := Int.floor_nonneg.2 (mul_nonneg hx0 (hqpos n).le)
    have hc : ((⌊x * (p : ℝ) ^ n⌋.toNat : ℕ) : ℝ) = (⌊x * (p : ℝ) ^ n⌋ : ℝ) := by
      exact_mod_cast Int.toNat_of_nonneg h0
    have hlt : ⌊x * (p : ℝ) ^ n⌋.toNat < p ^ n := by
      have h2 : (⌊x * (p : ℝ) ^ n⌋ : ℝ) ≤ x * (p : ℝ) ^ n := Int.floor_le _
      have h3 : x * (p : ℝ) ^ n < (p : ℝ) ^ n := by nlinarith [hqpos n]
      have : ((⌊x * (p : ℝ) ^ n⌋.toNat : ℕ) : ℝ) < ((p ^ n : ℕ) : ℝ) := by
        rw [hc]; push_cast; linarith
      exact_mod_cast this
    unfold hkApprox lengthPiece
    rw [ringChar.eq K p, if_pos h0, frobeniusPower_maxIdeal p n, hilbertFunction_Gq hlt,
      Nat.card_eq_fintype_card, Fintype.card_fin, Nat.cast_choose_two]
    push_cast
    rw [hc]
    field_simp [(hqpos n).ne']
    ring
  simp_rw [key]
  have := ((hu.add (hv.const_mul 2)).mul (hu.add hv)).div_const 2
  convert this using 2
  ring

/-- `HKd(K[x, y, z], (x, y, z))(x) = x^2/2` for `0 ≤ x < 1`. -/
theorem hkDensity_maxIdeal (p : ℕ) [Fact p.Prime] [CharP K p] {x : ℝ} (hx0 : 0 ≤ x)
    (hx1 : x < 1) : hkDensity (maxIdeal K) x = x ^ 2 / 2 :=
  (tendsto_hkApprox p hx0 hx1).limUnder_eq

/-- Any function `f` that is the limit of Trivedi's `f_n` on `(0, 1)` (in particular
`HKd(K[x, y, z], (x, y, z))` itself) is not piecewise linear with finitely many breakpoints
on any set containing `(0, 1)`. -/
theorem limit_not_isPiecewiseLinearOn (p : ℕ) [Fact p.Prime] [CharP K p] {f : ℝ → ℝ}
    (hf : ∀ x ∈ Set.Ioo (0 : ℝ) 1,
      Tendsto (fun n => hkApprox (maxIdeal K) n x) atTop (𝓝 (f x)))
    {s : Set ℝ} (hs : Set.Ioo 0 1 ⊆ s) : ¬ IsPiecewiseLinearOn f s :=
  not_isPiecewiseLinearOn (fun x hx =>
    tendsto_nhds_unique (hf x hx) (tendsto_hkApprox p hx.1.le hx.2)) hs

/-- `HKd(K[x, y, z], (x, y, z))` is not piecewise linear with finitely many breakpoints on any
set containing `(0, 1)` (e.g. on `ℝ`, on `[0, ∞)`, or on `[0, 3]`). -/
theorem hkDensity_not_isPiecewiseLinearOn (p : ℕ) [Fact p.Prime] [CharP K p] {s : Set ℝ}
    (hs : Set.Ioo 0 1 ⊆ s) : ¬ IsPiecewiseLinearOn (hkDensity (maxIdeal K)) s :=
  not_isPiecewiseLinearOn (fun _ hx => hkDensity_maxIdeal p hx.1.le hx.2) hs

/-- Partition form: there is no partition `a = t_0 < ... < t_k = b` of any interval
`[a, b] ⊇ [0, 1]` with `HKd(K[x, y, z], (x, y, z))` affine on each piece. -/
theorem hkDensity_not_isPiecewiseLinearPartition (p : ℕ) [Fact p.Prime] [CharP K p]
    {a b : ℝ} (ha : a ≤ 0) (hb : 1 ≤ b) :
    ¬ IsPiecewiseLinearPartition (hkDensity (maxIdeal K)) a b := fun h =>
  hkDensity_not_isPiecewiseLinearOn p
    (fun _ hx => Set.mem_Icc.2 ⟨ha.trans hx.1.le, hx.2.le.trans hb⟩) h.isPiecewiseLinearOn

attribute [local instance] MvPolynomial.gradedAlgebra in
/-- The first clause of the conjecture, over a field `K` of characteristic `p > 0`, for the
polynomial rings `K[x_1, ..., x_n]` (standard grading): the HK density function of every
homogeneous ideal of finite colength is piecewise linear on `ℝ` with finitely many breakpoints. -/
def Clause1 (K : Type*) [Field K] : Prop :=
  ∀ (n : ℕ) (I : Ideal (MvPolynomial (Fin n) K)), I.IsHomogeneous (homogeneousSubmodule (Fin n) K) →
    Module.Finite K (MvPolynomial (Fin n) K ⧸ I) → IsPiecewiseLinearOn (hkDensity I) Set.univ

theorem not_clause1 (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p] : ¬ Clause1 K :=
  fun H => hkDensity_not_isPiecewiseLinearOn (K := K) p (Set.subset_univ _)
    (H 3 (maxIdeal K) maxIdeal_isHomogeneous
      (Module.finite_of_finrank_pos (by rw [finrank_quotient_maxIdeal]; norm_num)))

/-- **Conjecture 00000003888 is false.** Over every field `K` of characteristic `p > 0`, the
first clause fails, so its conjunction with any second clause `Clause2` fails. -/
theorem conjecture_false (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p]
    (Clause2 : Prop) : ¬ (Clause1 K ∧ Clause2) :=
  fun h => not_clause1 K p h.1

end C3888
