import Mathlib

/-!
# Conjecture 00000001213 is false: opening with the prime `5` wins Sylver coinage

Conjecture 00000001213 reads:

> Definition: Sylver Coinage: two players alternately name positive integers that may not be
> nonnegative integer combinations of previously named ones; naming 1 loses. Conjecture: The first
> player wins, and every winning first move is composite; no prime first move is winning -- after a
> prime opening the second player has a winning response.

The first clause is true, but the other two are false. By Hutchings' theorem, every prime `p ≥ 5`
is a winning opening. We prove this in Lean for every such `p` (`prime_opening_wins`) and then
specialise it to `p = 5`.

Proof, by strategy stealing. Let the second player reply `q`. Then `q` is not a multiple of `p`,
so `gcd(p, q) = 1`, and `t = pq - p - q` is the Frobenius number of `⟨p, q⟩` (Mathlib's
`Nat.frobeniusNumber_pair`). Every gap `x` of `⟨p, q⟩` satisfies `t - x ∈ ⟨p, q⟩`. The game from
`{p, q}` is finite, so it is determined. If naming `t` leaves the opponent lost, name `t`.
Otherwise the opponent has a winning reply `x` to `t`. Naming `x` directly gives a position with
the same closure (`t = x + (t - x)`), and so with the same outcome.

The game formalization (`Legal`, `Outcome`, `anyNumber`, `not_win_and_lose`) is reused, with
credit, from the accepted solution of conjecture 00000008869 by feiyuceng06-prog
(`solutions/00000008869/feiyuceng06-prog_submission_20261003111927`, GPL-3.0).
-/

namespace Submission00000001213

/-- `n` is a legal move after the numbers in `S` have been named: `n` is positive and is not a
nonnegative integer combination of named numbers (not in the additive submonoid generated by `S`).
(From the accepted solution of 00000008869.) -/
def Legal (S : Finset ℕ) (n : ℕ) : Prop :=
  0 < n ∧ n ∉ AddSubmonoid.closure (S : Set ℕ)

/-- Game values of Sylver coinage when only numbers satisfying `allowed` may be named.
`Outcome allowed true S`: the player to move from `S` has a winning strategy.
`Outcome allowed false S`: the player to move from `S` loses against best play.
Naming `1` loses at once, so it is never a winning move. (From the accepted solution of
00000008869.) -/
inductive Outcome (allowed : ℕ → Prop) : Bool → Finset ℕ → Prop
  | win (S : Finset ℕ) (n : ℕ) : allowed n → Legal S n → n ≠ 1 →
      Outcome allowed false (insert n S) → Outcome allowed true S
  | lose (S : Finset ℕ) :
      (∀ n, allowed n → Legal S n → n ≠ 1 → Outcome allowed true (insert n S)) →
      Outcome allowed false S

/-- The usual game: every positive integer may be named. -/
def anyNumber : ℕ → Prop := fun _ => True

/-- A position is not both a win and a loss for the player to move. (From 00000008869.) -/
theorem not_win_and_lose (allowed : ℕ → Prop) {b : Bool} {S : Finset ℕ}
    (h : Outcome allowed b S) : ¬ Outcome allowed (!b) S := by
  induction h with
  | win S n ha hl hn hlose ih =>
    intro h'
    cases h' with
    | lose _ hall => exact ih (hall n ha hl hn)
  | lose S hall ih =>
    intro h'
    cases h' with
    | win _ n ha hl hn hlose => exact ih n ha hl hn hlose

/-! ## The statement -/

/-- `n` is a winning first move: it can be named at the start, it is not `1`, and the second
player, now to move, loses. -/
def WinningFirstMove (n : ℕ) : Prop :=
  Legal ∅ n ∧ n ≠ 1 ∧ Outcome anyNumber false {n}

/-- A composite number: greater than `1` and not prime. -/
def Composite (n : ℕ) : Prop := 1 < n ∧ ¬ n.Prime

/-- Clause 1: the first player wins. -/
def Clause1 : Prop := Outcome anyNumber true ∅

/-- Clause 2: every winning first move is composite. -/
def Clause2 : Prop := ∀ n, WinningFirstMove n → Composite n

/-- Clause 3, first phrasing: no prime first move is winning. -/
def Clause3 : Prop := ∀ p : ℕ, p.Prime → ¬ WinningFirstMove p

/-- Clause 3, second phrasing: after a prime opening, the second player (now to move) has a
winning response. -/
def Clause3' : Prop := ∀ p : ℕ, p.Prime → Outcome anyNumber true {p}

/-- The conjecture: all of its clauses. -/
def Conjecture : Prop := Clause1 ∧ Clause2 ∧ Clause3 ∧ Clause3'

/-! ## General facts about the game -/

theorem legal_mono {S T : Finset ℕ} (hST : S ⊆ T) {n : ℕ} (h : Legal T n) : Legal S n :=
  ⟨h.1, fun hn => h.2 (AddSubmonoid.closure_mono (by exact_mod_cast hST) hn)⟩

theorem closure_insert_eq {S T : Finset ℕ}
    (h : AddSubmonoid.closure (S : Set ℕ) = AddSubmonoid.closure (T : Set ℕ)) (n : ℕ) :
    AddSubmonoid.closure ((insert n S : Finset ℕ) : Set ℕ) =
      AddSubmonoid.closure ((insert n T : Finset ℕ) : Set ℕ) := by
  simp only [Finset.coe_insert, Set.insert_eq, AddSubmonoid.closure_union, h]

/-- The outcome of a position depends only on the submonoid that its named numbers generate. -/
theorem outcome_congr {a : ℕ → Prop} {b : Bool} {S : Finset ℕ} (h : Outcome a b S) :
    ∀ T : Finset ℕ, AddSubmonoid.closure (S : Set ℕ) = AddSubmonoid.closure (T : Set ℕ) →
      Outcome a b T := by
  induction h with
  | win S n ha hl hn _ ih =>
    intro T hST
    refine Outcome.win T n ha ⟨hl.1, by rw [← hST]; exact hl.2⟩ hn ?_
    exact ih _ (closure_insert_eq hST n)
  | lose S _ ih =>
    intro T hST
    refine Outcome.lose T fun n ha hl hn => ?_
    exact ih n ha ⟨hl.1, by rw [hST]; exact hl.2⟩ hn _ (closure_insert_eq hST n)

open Classical in
/-- Number of legal moves below `B`. -/
noncomputable def gaps (B : ℕ) (S : Finset ℕ) : ℕ :=
  ((Finset.range B).filter (Legal S)).card

theorem gaps_lt {B : ℕ} {S : Finset ℕ} {n : ℕ} (hl : Legal S n) (hB : n < B) :
    gaps B (insert n S) < gaps B S := by
  classical
  unfold gaps
  apply Finset.card_lt_card
  refine Finset.ssubset_iff_of_subset ?_ |>.2 ⟨n, ?_, ?_⟩
  · intro k hk
    simp only [Finset.mem_filter] at hk ⊢
    exact ⟨hk.1, legal_mono (Finset.subset_insert _ _) hk.2⟩
  · simp [Finset.mem_filter, hB, hl]
  · simp only [Finset.mem_filter, not_and]
    intro _ h
    exact h.2 (AddSubmonoid.subset_closure (by simp))

/-- **Determinacy.** If every legal move is below `B`, the game is finite, and so the player to
move either wins or loses. -/
theorem determined (a : ℕ → Prop) (B : ℕ) :
    ∀ S : Finset ℕ, (∀ n, Legal S n → n < B) → Outcome a true S ∨ Outcome a false S := by
  intro S
  induction hm : gaps B S using Nat.strong_induction_on generalizing S with
  | _ m ih =>
    intro hB
    by_cases hw : ∃ n, a n ∧ Legal S n ∧ n ≠ 1 ∧ Outcome a false (insert n S)
    · obtain ⟨n, ha, hl, hn, hlose⟩ := hw
      exact Or.inl (Outcome.win S n ha hl hn hlose)
    · refine Or.inr (Outcome.lose S fun n ha hl hn => ?_)
      have hlt : gaps B (insert n S) < m := hm ▸ gaps_lt hl (hB n hl)
      rcases ih _ hlt (insert n S) rfl
          (fun k hk => hB k (legal_mono (Finset.subset_insert _ _) hk)) with h | h
      · exact h
      · exact absurd ⟨n, ha, hl, hn, h⟩ hw

/-! ## Two-generator numerical semigroups -/

/-- **Symmetry.** If `gcd(p, q) = 1`, `t = qp - q - p` and `x` is a gap of `⟨q, p⟩`, then
`x ≤ t` and `t - x ∈ ⟨q, p⟩`. -/
theorem gap_symm {p q : ℕ} (cop : Nat.Coprime q p) (hp : 1 < p) (hq : 1 < q) {x : ℕ}
    (hx : x ∉ AddSubmonoid.closure ({q, p} : Set ℕ)) :
    x ≤ q * p - q - p ∧ q * p - q - p - x ∈ AddSubmonoid.closure ({q, p} : Set ℕ) := by
  have hF := frobeniusNumber_pair cop hq hp
  have hxt : x ≤ q * p - q - p := hF.2 hx
  refine ⟨hxt, ?_⟩
  have hqp : q + p ≤ q * p := add_le_mul hq hp
  -- `x + qp` exceeds the Frobenius number, so it is `a q + b p`
  have hbig : x + q * p ∈ AddSubmonoid.closure ({q, p} : Set ℕ) := by
    by_contra hc
    have := hF.2 hc
    omega
  obtain ⟨a, b, hab⟩ := (AddSubmonoid.mem_closure_pair q p _).1 hbig
  simp only [smul_eq_mul] at hab
  -- `a < p` and `b < q`, since otherwise `x` itself would be in `⟨q, p⟩`
  have ha : a < p := by
    by_contra h
    replace h := Nat.le_of_not_lt h
    apply hx
    refine (AddSubmonoid.mem_closure_pair q p x).2 ⟨a - p, b, ?_⟩
    simp only [smul_eq_mul]
    have : (a - p) * q + p * q = a * q := by rw [← add_mul, Nat.sub_add_cancel h]
    nlinarith
  have hb : b < q := by
    by_contra h
    replace h := Nat.le_of_not_lt h
    apply hx
    refine (AddSubmonoid.mem_closure_pair q p x).2 ⟨a, b - q, ?_⟩
    simp only [smul_eq_mul]
    have : (b - q) * p + q * p = b * p := by rw [← add_mul, Nat.sub_add_cancel h]
    nlinarith
  -- `t - x = (p - 1 - a) q + (q - 1 - b) p`
  obtain ⟨a', rfl⟩ : ∃ a', p = a + a' + 1 := ⟨p - a - 1, by omega⟩
  obtain ⟨b', rfl⟩ : ∃ b', q = b + b' + 1 := ⟨q - b - 1, by omega⟩
  refine (AddSubmonoid.mem_closure_pair _ _ _).2 ⟨a', b', ?_⟩
  simp only [smul_eq_mul]
  have key : x + (a' * (b + b' + 1) + b' * (a + a' + 1)) + (b + b' + 1) + (a + a' + 1) =
      (b + b' + 1) * (a + a' + 1) := by nlinarith
  omega

/-! ## Hutchings' theorem: a prime `p ≥ 5` is a winning opening -/

/-- After `p` and a coprime reply `q > 1`, the player to move (the first player) wins. -/
theorem two_generator_win {p q : ℕ} (cop : Nat.Coprime q p) (hp : 5 ≤ p) (hq : 1 < q) :
    Outcome anyNumber true (insert q {p}) := by
  set t := q * p - q - p with ht_def
  have hqp : q + p ≤ q * p := add_le_mul hq (by omega)
  have ht2 : 2 ≤ t := by
    have h1 : 2 * p ≤ q * p := Nat.mul_le_mul_right p (by omega)
    have h2 : q * 5 ≤ q * p := Nat.mul_le_mul_left q hp
    omega
  have hcoe : ((insert q {p} : Finset ℕ) : Set ℕ) = {q, p} := by simp
  have hF := frobeniusNumber_pair cop hq (by omega : 1 < p)
  -- `t` is legal after `{p, q}`
  have htl : Legal (insert q {p}) t := ⟨by omega, by rw [hcoe]; exact hF.1⟩
  let T : Finset ℕ := insert t (insert q {p})
  -- the game from `T` is finite: every legal move is at most `t`
  have hB : ∀ n, Legal T n → n < t + 1 := by
    intro n hn
    have h1 := legal_mono (Finset.subset_insert _ _) hn
    have h2 := (gap_symm cop (by omega) hq (by rw [← hcoe]; exact h1.2)).1
    omega
  rcases determined anyNumber (t + 1) T hB with hT | hT
  · -- the opponent can win after `t`: steal the winning reply `x`
    obtain ⟨x, hxa, hxl, hx1, hxlose⟩ : ∃ x, anyNumber x ∧ Legal T x ∧ x ≠ 1 ∧
        Outcome anyNumber false (insert x T) := by
      cases hT with
      | win _ x ha hl hn hlose => exact ⟨x, ha, hl, hn, hlose⟩
    have hxl' : Legal (insert q {p}) x := legal_mono (Finset.subset_insert _ _) hxl
    obtain ⟨_, hsymm⟩ := gap_symm cop (by omega) hq (by rw [← hcoe]; exact hxl'.2)
    have hxt : x ≤ t := (gap_symm cop (by omega) hq (by rw [← hcoe]; exact hxl'.2)).1
    refine Outcome.win _ x hxa hxl' hx1 (outcome_congr hxlose _ ?_)
    -- naming `x` after `{p, q}` generates the same submonoid as naming `t` and then `x`
    apply le_antisymm
    · rw [AddSubmonoid.closure_le]
      intro y hy
      simp only [T, Finset.coe_insert, Finset.coe_singleton, Set.mem_insert_iff,
        Set.mem_singleton_iff] at hy
      have hmono : AddSubmonoid.closure ({q, p} : Set ℕ) ≤
          AddSubmonoid.closure ((insert x (insert q {p}) : Finset ℕ) : Set ℕ) :=
        AddSubmonoid.closure_mono (by intro z hz; simp at hz ⊢; tauto)
      have hxmem : x ∈ AddSubmonoid.closure ((insert x (insert q {p}) : Finset ℕ) : Set ℕ) :=
        AddSubmonoid.subset_closure (by simp)
      rcases hy with rfl | rfl | rfl | rfl
      · exact hxmem
      · rw [show t = x + (t - x) by omega]
        exact AddSubmonoid.add_mem _ hxmem (hmono hsymm)
      · exact AddSubmonoid.subset_closure (by simp)
      · exact AddSubmonoid.subset_closure (by simp)
    · exact AddSubmonoid.closure_mono (by intro z hz; simp [T] at hz ⊢; tauto)
  · -- naming `t` leaves the opponent lost
    exact Outcome.win _ t trivial htl (by omega) hT

/-- **Hutchings' theorem.** For every prime `p ≥ 5`, naming `p` first leaves the second player
lost. -/
theorem prime_opening_wins {p : ℕ} (hp : p.Prime) (h5 : 5 ≤ p) :
    Outcome anyNumber false {p} := by
  refine Outcome.lose _ fun q _ hl hq1 => ?_
  have hq : 1 < q := by have := hl.1; omega
  have hndvd : ¬ p ∣ q := by
    rintro ⟨k, rfl⟩
    have h2 := hl.2
    rw [Finset.coe_singleton, AddSubmonoid.mem_closure_singleton] at h2
    exact h2 ⟨k, by rw [smul_eq_mul, mul_comm]⟩
  have cop : Nat.Coprime q p := ((Nat.Prime.coprime_iff_not_dvd hp).2 hndvd).symm
  exact two_generator_win cop h5 hq

theorem legal_five : Legal ∅ 5 := ⟨by norm_num, by simp⟩

/-- Every prime `p ≥ 5` is a winning first move. -/
theorem hutchings {p : ℕ} (hp : p.Prime) (h5 : 5 ≤ p) : WinningFirstMove p :=
  ⟨⟨by omega, by simp; omega⟩, by omega, prime_opening_wins hp h5⟩

/-- `5` is a winning first move. -/
theorem five_wins : WinningFirstMove 5 := hutchings Nat.prime_five le_rfl

/-- Clause 1 is true: the first player wins by naming `5`. -/
theorem clause1_true : Clause1 :=
  Outcome.win ∅ 5 trivial legal_five (by norm_num) (prime_opening_wins Nat.prime_five le_rfl)

/-- Clause 2 is false: the winning first move `5` is prime, not composite. -/
theorem not_clause2 : ¬ Clause2 := fun h => (h 5 five_wins).2 Nat.prime_five

/-- Clause 3 is false: the prime first move `5` wins. -/
theorem not_clause3 : ¬ Clause3 := fun h => h 5 Nat.prime_five five_wins

/-- Clause 3' is false: after the prime opening `5` the second player has no winning response. -/
theorem not_clause3' : ¬ Clause3' := fun h =>
  not_win_and_lose anyNumber (prime_opening_wins Nat.prime_five le_rfl) (h 5 Nat.prime_five)

/-- **Conjecture 00000001213 is false.** Clauses 2, 3 and 3' each fail on their own (clause 1 holds,
`clause1_true`). -/
theorem conjecture_00000001213_false : ¬ Conjecture := fun h => not_clause2 h.2.1

end Submission00000001213

#print axioms Submission00000001213.conjecture_00000001213_false
#print axioms Submission00000001213.not_clause3
#print axioms Submission00000001213.not_clause3'
#print axioms Submission00000001213.hutchings
#print axioms Submission00000001213.clause1_true
