name = "Conj1186"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Conj1186"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "Conj1186"
globs = ["Conj1186"]
