import Std

/-! The class of abelian groups of prime-power order, with the prime allowed
to vary as in the statement, is not classified by its subgroup lattice.
The actual subgroup lattices of C2 and C3 are explicitly order-isomorphic.
Subgroups here are arbitrary Prop-valued predicates with the group axioms,
so no finite-subset coding or unproved enumeration is used. -/
namespace Conjecture04294

structure AbelianGroupData (A : Type) where
  zero : A
  add : A → A → A
  neg : A → A
  add_assoc : ∀ x y z, add (add x y) z = add x (add y z)
  zero_add : ∀ x, add zero x = x
  add_zero : ∀ x, add x zero = x
  neg_add : ∀ x, add (neg x) x = zero
  add_comm : ∀ x y, add x y = add y x

structure Bijection (A B : Type) where
  forward : A → B
  backward : B → A
  left_inverse : ∀ a, backward (forward a) = a
  right_inverse : ∀ b, forward (backward b) = b

def Prime (p : Nat) : Prop :=
  2 ≤ p ∧ ∀ d : Nat, d ∣ p → d = 1 ∨ d = p

def HasPrimePowerOrder (A : Type) : Prop :=
  ∃ p e : Nat, Prime p ∧ 0 < e ∧ Nonempty (Bijection A (Fin (p^e)))

structure Subgroup {A : Type} (D : AbelianGroupData A) where
  carrier : A → Prop
  zero_mem : carrier D.zero
  add_mem : ∀ x y, carrier x → carrier y → carrier (D.add x y)
  neg_mem : ∀ x, carrier x → carrier (D.neg x)

def Included {A : Type} {D : AbelianGroupData A} (H K : Subgroup D) : Prop :=
  ∀ x, H.carrier x → K.carrier x

theorem subgroup_ext {A : Type} {D : AbelianGroupData A}
    (H K : Subgroup D) (h : ∀ x, H.carrier x ↔ K.carrier x) : H = K := by
  cases H with
  | mk hc hz ha hn =>
    cases K with
    | mk kc kz ka kn =>
      have he : hc = kc := funext (fun x => propext (h x))
      cases he
      rfl

def meet {A : Type} {D : AbelianGroupData A} (H K : Subgroup D) : Subgroup D where
  carrier x := H.carrier x ∧ K.carrier x
  zero_mem := ⟨H.zero_mem, K.zero_mem⟩
  add_mem x y hx hy := ⟨H.add_mem x y hx.1 hy.1, K.add_mem x y hx.2 hy.2⟩
  neg_mem x hx := ⟨H.neg_mem x hx.1, K.neg_mem x hx.2⟩

/-- The subgroup generated by the union, defined as the intersection of
all subgroups containing both inputs. -/
def join {A : Type} {D : AbelianGroupData A} (H K : Subgroup D) : Subgroup D where
  carrier x := ∀ L : Subgroup D, Included H L → Included K L → L.carrier x
  zero_mem L _ _ := L.zero_mem
  add_mem x y hx hy L hH hK := L.add_mem x y (hx L hH hK) (hy L hH hK)
  neg_mem x hx L hH hK := L.neg_mem x (hx L hH hK)

theorem meet_le_left {A : Type} {D : AbelianGroupData A} (H K : Subgroup D) :
    Included (meet H K) H := fun _ h => h.1

theorem meet_le_right {A : Type} {D : AbelianGroupData A} (H K : Subgroup D) :
    Included (meet H K) K := fun _ h => h.2

theorem left_le_join {A : Type} {D : AbelianGroupData A} (H K : Subgroup D) :
    Included H (join H K) := fun x hx _ hH _ => hH x hx

theorem right_le_join {A : Type} {D : AbelianGroupData A} (H K : Subgroup D) :
    Included K (join H K) := fun x hx _ _ hK => hK x hx

structure SubgroupOrderIso {A B : Type}
    (D : AbelianGroupData A) (E : AbelianGroupData B) where
  forward : Subgroup D → Subgroup E
  backward : Subgroup E → Subgroup D
  left_inverse : ∀ H, backward (forward H) = H
  right_inverse : ∀ K, forward (backward K) = K
  order_iff : ∀ H K, Included (forward H) (forward K) ↔ Included H K

/-- An order isomorphism of these actual subgroup lattices preserves meet. -/
theorem orderIso_preserves_meet {A B : Type}
    {D : AbelianGroupData A} {E : AbelianGroupData B}
    (f : SubgroupOrderIso D E) (H K : Subgroup D) :
    f.forward (meet H K) = meet (f.forward H) (f.forward K) := by
  apply subgroup_ext
  intro x
  constructor
  · intro hx
    exact ⟨((f.order_iff _ _).mpr (meet_le_left H K)) x hx,
      ((f.order_iff _ _).mpr (meet_le_right H K)) x hx⟩
  · intro hx
    let M := meet (f.forward H) (f.forward K)
    have h1 : Included (f.backward M) H := by
      apply (f.order_iff _ _).mp
      rw [f.right_inverse]
      exact meet_le_left _ _
    have h2 : Included (f.backward M) K := by
      apply (f.order_iff _ _).mp
      rw [f.right_inverse]
      exact meet_le_right _ _
    have hm : Included (f.backward M) (meet H K) := fun y hy => ⟨h1 y hy, h2 y hy⟩
    have hf := (f.order_iff _ _).mpr hm
    rw [f.right_inverse] at hf
    exact hf x hx

/-- The same isomorphism preserves the subgroup generated by each union. -/
theorem orderIso_preserves_join {A B : Type}
    {D : AbelianGroupData A} {E : AbelianGroupData B}
    (f : SubgroupOrderIso D E) (H K : Subgroup D) :
    f.forward (join H K) = join (f.forward H) (f.forward K) := by
  apply subgroup_ext
  intro x
  constructor
  · intro hx L hH hK
    have h1 : Included H (f.backward L) := by
      apply (f.order_iff _ _).mp
      rw [f.right_inverse]
      exact hH
    have h2 : Included K (f.backward L) := by
      apply (f.order_iff _ _).mp
      rw [f.right_inverse]
      exact hK
    have hj : Included (join H K) (f.backward L) := fun y hy => hy _ h1 h2
    have hf := (f.order_iff _ _).mpr hj
    rw [f.right_inverse] at hf
    exact hf x hx
  · intro hx
    exact hx (f.forward (join H K))
      ((f.order_iff _ _).mpr (left_le_join H K))
      ((f.order_iff _ _).mpr (right_le_join H K))

def group2 : AbelianGroupData (Fin 2) where
  zero := 0
  add := (·+·)
  neg x := 0-x
  add_assoc := by decide
  zero_add := by decide
  add_zero := by decide
  neg_add := by decide
  add_comm := by decide

def group3 : AbelianGroupData (Fin 3) where
  zero := 0
  add := (·+·)
  neg x := 0-x
  add_assoc := by decide
  zero_add := by decide
  add_zero := by decide
  neg_add := by decide
  add_comm := by decide

theorem prime_two : Prime 2 := by
  refine ⟨by decide, ?_⟩
  intro d hd
  have hle : d ≤ 2 := Nat.le_of_dvd (by decide) hd
  exact (by decide : ∀ d : Fin 3, d.val ∣ 2 → d.val = 1 ∨ d.val = 2) ⟨d,by omega⟩ hd

theorem prime_three : Prime 3 := by
  refine ⟨by decide, ?_⟩
  intro d hd
  have hle : d ≤ 3 := Nat.le_of_dvd (by decide) hd
  exact (by decide : ∀ d : Fin 4, d.val ∣ 3 → d.val = 1 ∨ d.val = 3) ⟨d,by omega⟩ hd

theorem order2_prime_power : HasPrimePowerOrder (Fin 2) :=
  ⟨2, 1, prime_two, by decide, ⟨⟨id, id, fun _ => rfl, fun _ => rfl⟩⟩⟩

theorem order3_prime_power : HasPrimePowerOrder (Fin 3) :=
  ⟨3, 1, prime_three, by decide, ⟨⟨id, id, fun _ => rfl, fun _ => rfl⟩⟩⟩

/-- This statement quantifies over all actual subgroup predicates. -/
theorem subgroup2_membership (H : Subgroup group2) (x : Fin 2) :
    H.carrier x ↔ x = 0 ∨ H.carrier 1 := by
  have hc : ∀ x : Fin 2, x = 0 ∨ x = 1 := by decide
  rcases hc x with rfl | rfl
  · exact ⟨fun _ => Or.inl rfl, fun _ => H.zero_mem⟩
  · constructor
    · exact Or.inr
    · intro h
      rcases h with h | h
      · exact False.elim ((by decide : (1 : Fin 2) ≠ 0) h)
      · exact h

theorem subgroup3_membership (H : Subgroup group3) (x : Fin 3) :
    H.carrier x ↔ x = 0 ∨ H.carrier 1 := by
  have h12 : H.carrier 1 → H.carrier 2 := fun h => H.add_mem 1 1 h h
  have h21 : H.carrier 2 → H.carrier 1 := fun h => H.add_mem 2 2 h h
  have hc : ∀ x : Fin 3, x = 0 ∨ x = 1 ∨ x = 2 := by decide
  rcases hc x with rfl | rfl | rfl
  · exact ⟨fun _ => Or.inl rfl, fun _ => H.zero_mem⟩
  · constructor
    · exact Or.inr
    · intro h
      rcases h with h | h
      · exact False.elim ((by decide : (1 : Fin 3) ≠ 0) h)
      · exact h
  · constructor
    · exact fun h => Or.inr (h21 h)
    · intro h
      rcases h with h | h
      · exact False.elim ((by decide : (2 : Fin 3) ≠ 0) h)
      · exact h12 h

/-- The subgroup is trivial when P is false and the whole group when true.
It is defined directly by predicates, without using a classical decision. -/
def flagSubgroup {A : Type} (D : AbelianGroupData A) (P : Prop) : Subgroup D where
  carrier x := x = D.zero ∨ P
  zero_mem := Or.inl rfl
  add_mem x y hx hy := by
    rcases hx with rfl | hp
    · rcases hy with rfl | hp
      · exact Or.inl (D.zero_add D.zero)
      · exact Or.inr hp
    · exact Or.inr hp
  neg_mem x hx := by
    rcases hx with rfl | hp
    · exact Or.inl ((D.add_zero (D.neg D.zero)).symm.trans (D.neg_add D.zero))
    · exact Or.inr hp

def to3 (H : Subgroup group2) : Subgroup group3 := flagSubgroup group3 (H.carrier 1)
def to2 (K : Subgroup group3) : Subgroup group2 := flagSubgroup group2 (K.carrier 1)

theorem to3_one (H : Subgroup group2) : (to3 H).carrier 1 ↔ H.carrier 1 := by
  change ((1 : Fin 3) = 0 ∨ H.carrier 1) ↔ H.carrier 1
  simp

theorem to2_one (K : Subgroup group3) : (to2 K).carrier 1 ↔ K.carrier 1 := by
  change ((1 : Fin 2) = 0 ∨ K.carrier 1) ↔ K.carrier 1
  simp

theorem to2_to3 (H : Subgroup group2) : to2 (to3 H) = H := by
  apply subgroup_ext
  intro x
  change (x = 0 ∨ (to3 H).carrier 1) ↔ H.carrier x
  rw [to3_one]
  exact (subgroup2_membership H x).symm

theorem to3_to2 (K : Subgroup group3) : to3 (to2 K) = K := by
  apply subgroup_ext
  intro x
  change (x = 0 ∨ (to2 K).carrier 1) ↔ K.carrier x
  rw [to2_one]
  exact (subgroup3_membership K x).symm

theorem to3_order (H K : Subgroup group2) : Included (to3 H) (to3 K) ↔ Included H K := by
  constructor
  · intro h x hx
    rcases (subgroup2_membership H x).mp hx with rfl | h1
    · exact K.zero_mem
    · exact (subgroup2_membership K x).mpr
        (Or.inr ((to3_one K).mp (h 1 ((to3_one H).mpr h1))))
  · intro h x hx
    rcases hx with hx | hp
    · exact Or.inl hx
    · exact Or.inr (h 1 hp)

def subgroupLatticesIso : SubgroupOrderIso group2 group3 where
  forward := to3
  backward := to2
  left_inverse := to2_to3
  right_inverse := to3_to2
  order_iff := to3_order

theorem lattice_meet_preserved (H K : Subgroup group2) :
    to3 (meet H K) = meet (to3 H) (to3 K) := orderIso_preserves_meet subgroupLatticesIso H K

theorem lattice_join_preserved (H K : Subgroup group2) :
    to3 (join H K) = join (to3 H) (to3 K) := orderIso_preserves_join subgroupLatticesIso H K

structure GroupIso {A B : Type} (D : AbelianGroupData A) (E : AbelianGroupData B)
    extends Bijection A B where
  additive : ∀ x y, forward (D.add x y) = E.add (forward x) (forward y)

theorem no_injection_three_two (f : Fin 3 → Fin 2) :
    ¬ (∀ x y, f x = f y → x = y) := by
  intro hi
  have hp : ∀ a b c : Fin 2, a = b ∨ a = c ∨ b = c := by decide
  rcases hp (f 0) (f 1) (f 2) with h | h | h
  · exact (by decide : (0 : Fin 3) ≠ 1) (hi 0 1 h)
  · exact (by decide : (0 : Fin 3) ≠ 2) (hi 0 2 h)
  · exact (by decide : (1 : Fin 3) ≠ 2) (hi 1 2 h)

theorem groups_not_isomorphic : ¬ Nonempty (GroupIso group2 group3) := by
  rintro ⟨f⟩
  apply no_injection_three_two f.backward
  intro x y h
  have he := congrArg f.forward h
  simpa only [f.right_inverse] using he

/-- The asserted completeness, restricted only to the prime-power-order
part of the class. The statement does not fix one common prime. -/
def PrimePowerLatticeCompleteness : Prop :=
  ∀ (A B : Type) (D : AbelianGroupData A) (E : AbelianGroupData B),
    HasPrimePowerOrder A → HasPrimePowerOrder B →
    Nonempty (SubgroupOrderIso D E) → Nonempty (GroupIso D E)

theorem conjecture04294_false : ¬ PrimePowerLatticeCompleteness := by
  intro h
  exact groups_not_isomorphic
    (h (Fin 2) (Fin 3) group2 group3 order2_prime_power order3_prime_power ⟨subgroupLatticesIso⟩)

theorem full_conjecture_false (OtherAssertions : Prop) :
    ¬ (PrimePowerLatticeCompleteness ∧ OtherAssertions) := by
  intro h
  exact conjecture04294_false h.1

#print axioms group2
#print axioms group3
#print axioms order2_prime_power
#print axioms order3_prime_power
#print axioms subgroupLatticesIso
#print axioms lattice_meet_preserved
#print axioms lattice_join_preserved
#print axioms groups_not_isomorphic
#print axioms conjecture04294_false
#print axioms full_conjecture_false
end Conjecture04294
