import Mathlib

/-!
# Conjecture 00000003905 is false

The conjecture: for a fixed ideal `I` (of a Noetherian ring of characteristic `p`), the number
`μ(I^{[p^e]})` of minimal generators of the Frobenius power is, for `e ≥ e₀`, a polynomial in
`p^e` of degree `dim R - ht I` (and its leading coefficient depends only on the initial ideal).

Counterexample: `R = k[x, y]` with `k` any field of characteristic `p`, and `I = (x)`.
Then `dim R = 2` and `ht I = 1`, so the predicted degree is `1`, but `I^{[q]} = (x^q)` needs
exactly one generator for every `q = p^e`; any polynomial `P` with `P(p^e) = μ(I^{[p^e]})` for all
large `e` is the constant `1`, of degree `0`.

Conventions.
* `frobeniusPow I q` is the ideal generated by `{a ^ q | a ∈ I}`; `frobeniusPow_eq_span_pow_gens`
  proves that it equals the ideal generated by the `q`-th powers of ANY generating set of `I`
  when `q = p ^ e` and `R` has characteristic `p`, so the textbook (generator-wise) definition is
  well defined and agrees with ours.
* `μ` is Mathlib's `Submodule.spanFinrank`: the least cardinality of a generating set
  (`0` only if no finite generating set exists, which does not happen in Noetherian rings).
* Dimension is Mathlib's `ringKrullDim`, height is Mathlib's `Ideal.height`.
* "Polynomial in `p^e`" is read with coefficients in an arbitrary characteristic-zero field `K`
  (e.g. `ℚ` or `ℝ`), which covers integer- and rational-coefficient polynomials.
-/

open MvPolynomial

namespace C3905

section Frobenius

variable {R : Type*} [CommRing R]

/-- The Frobenius power `I^{[q]}`: the ideal generated by the `q`-th powers of elements of `I`. -/
def frobeniusPow (I : Ideal R) (q : ℕ) : Ideal R :=
  Ideal.span ((· ^ q) '' (I : Set R))

/-- In characteristic `p`, the Frobenius power `I^{[p^e]}` is the ideal generated by the
`p^e`-th powers of the elements of any generating set `s` of `I` (generator independence). -/
theorem frobeniusPow_eq_span_pow_gens (p : ℕ) [hp : Fact p.Prime] [CharP R p] (e : ℕ)
    (s : Set R) :
    frobeniusPow (Ideal.span s) (p ^ e) = Ideal.span ((· ^ (p ^ e)) '' s) := by
  apply le_antisymm
  · rw [frobeniusPow, Ideal.span_le]
    rintro _ ⟨a, ha, rfl⟩
    induction ha using Submodule.span_induction with
    | mem x hx => exact Ideal.subset_span ⟨x, hx, rfl⟩
    | zero =>
        simp only [zero_pow (pow_ne_zero e hp.out.ne_zero), SetLike.mem_coe]
        exact Submodule.zero_mem _
    | add x y _ _ hx hy =>
        simp only [SetLike.mem_coe] at hx hy ⊢
        rw [add_pow_char_pow]
        exact add_mem hx hy
    | smul r x _ hx =>
        simp only [SetLike.mem_coe] at hx ⊢
        rw [smul_eq_mul, mul_pow]
        exact Ideal.mul_mem_left _ _ hx
  · exact Ideal.span_mono (Set.image_mono Ideal.subset_span)

end Frobenius

section Example

variable (k : Type*) [Field k]

/-- The ideal `I = (x)` of `k[x, y] = MvPolynomial (Fin 2) k`. -/
noncomputable def I : Ideal (MvPolynomial (Fin 2) k) := Ideal.span {X 0}

/-- `dim k[x, y] = 2`. -/
theorem ringKrullDim_eq_two : ringKrullDim (MvPolynomial (Fin 2) k) = 2 := by
  rw [MvPolynomial.ringKrullDim_of_isNoetherianRing, ringKrullDim_eq_zero_of_field]
  simp

theorem X_zero_not_isUnit : ¬ IsUnit (X 0 : MvPolynomial (Fin 2) k) := by
  intro h
  have h' := h.map (MvPolynomial.eval (fun _ : Fin 2 => (0 : k)))
  simp at h'

/-- `ht (x) = 1` in `k[x, y]`. -/
theorem height_I : (I k).height = 1 :=
  Ideal.height_span_singleton_eq_one_of_mem_nonZeroDivisors
    (mem_nonZeroDivisors_of_ne_zero (X_ne_zero 0)) (X_zero_not_isUnit k)

/-- `(x)^{[p^e]} = (x^{p^e})`. -/
theorem frobeniusPow_I (p : ℕ) [Fact p.Prime] [CharP k p] (e : ℕ) :
    frobeniusPow (I k) (p ^ e) = Ideal.span {(X 0 : MvPolynomial (Fin 2) k) ^ (p ^ e)} := by
  rw [I, frobeniusPow_eq_span_pow_gens p e, Set.image_singleton]

/-- `μ((x)^{[p^e]}) = 1` for every `e`. -/
theorem mu_frobeniusPow_I (p : ℕ) [Fact p.Prime] [CharP k p] (e : ℕ) :
    (frobeniusPow (I k) (p ^ e)).spanFinrank = 1 := by
  rw [frobeniusPow_I k p e]
  exact Submodule.spanFinrank_singleton (pow_ne_zero _ (X_ne_zero 0))

end Example

section Interpolation

variable {K : Type*} [Field K] [CharZero K]

/-- A polynomial that takes the value `1` at `p^e` for all `e ≥ e₀` (with `p ≥ 2`) is the constant
polynomial `1`. -/
theorem eq_one_of_eval_pow (p : ℕ) (hp : 2 ≤ p) (e₀ : ℕ) (P : Polynomial K)
    (h : ∀ e ≥ e₀, P.eval ((p : K) ^ e) = 1) : P = Polynomial.C 1 := by
  apply Polynomial.eq_of_infinite_eval_eq
  have hinj : Function.Injective (fun e : ℕ => (p : K) ^ (e + e₀)) := by
    intro a b hab
    simp only at hab
    have : p ^ (a + e₀) = p ^ (b + e₀) := by exact_mod_cast hab
    have := Nat.pow_right_injective hp this
    omega
  refine Set.infinite_of_injective_forall_mem hinj fun e => ?_
  simp only [Set.mem_ofPred_eq, Polynomial.eval_C]
  exact h _ (Nat.le_add_left _ _)

end Interpolation

/-- **Main theorem.** For every prime `p`, every field `k` of characteristic `p` and every
characteristic-zero coefficient field `K`: in `R = k[x, y]` with `I = (x)` we have
`dim R = 2`, `ht I = 1`, and there is NO `e₀` and polynomial `P ∈ K[t]` with
`μ(I^{[p^e]}) = P(p^e)` for all `e ≥ e₀` and `deg P + ht I = dim R` (i.e. `deg P = dim R - ht I`).
In fact every such `P` is the constant `1` (`frobenius_mu_polynomial_is_one`). -/
theorem conjecture_3905_false (p : ℕ) [hp : Fact p.Prime] (k : Type*) [Field k] [CharP k p]
    (K : Type*) [Field K] [CharZero K] :
    ringKrullDim (MvPolynomial (Fin 2) k) = 2 ∧ (I k).height = 1 ∧
    ¬ ∃ (e₀ : ℕ) (P : Polynomial K),
        (∀ e ≥ e₀, (((frobeniusPow (I k) (p ^ e)).spanFinrank : ℕ) : K) = P.eval ((p : K) ^ e)) ∧
        ((P.natDegree : ℕ∞) : WithBot ℕ∞) + ((I k).height : WithBot ℕ∞) =
          ringKrullDim (MvPolynomial (Fin 2) k) := by
  refine ⟨ringKrullDim_eq_two k, height_I k, ?_⟩
  rintro ⟨e₀, P, hP, hdeg⟩
  have hP1 : P = Polynomial.C 1 := by
    refine eq_one_of_eval_pow p hp.out.two_le e₀ P fun e he => ?_
    rw [← hP e he, mu_frobeniusPow_I k p e, Nat.cast_one]
  rw [hP1, Polynomial.natDegree_C, height_I, ringKrullDim_eq_two] at hdeg
  norm_num at hdeg

/-- Every polynomial interpolating `e ↦ μ((x)^{[p^e]})` for large `e` is the constant `1`, so it
has degree `0` (also in the `Polynomial.degree` sense). -/
theorem frobenius_mu_polynomial_is_one (p : ℕ) [hp : Fact p.Prime] (k : Type*) [Field k]
    [CharP k p] {K : Type*} [Field K] [CharZero K] (e₀ : ℕ) (P : Polynomial K)
    (hP : ∀ e ≥ e₀, (((frobeniusPow (I k) (p ^ e)).spanFinrank : ℕ) : K) = P.eval ((p : K) ^ e)) :
    P = Polynomial.C 1 ∧ P.degree = 0 := by
  have hP1 : P = Polynomial.C 1 := by
    refine eq_one_of_eval_pow p hp.out.two_le e₀ P fun e he => ?_
    rw [← hP e he, mu_frobeniusPow_I k p e, Nat.cast_one]
  exact ⟨hP1, by rw [hP1, Polynomial.degree_C one_ne_zero]⟩

end C3905
