import Conjecture464

#print Conjecture464.SpanningTree
#print Conjecture464.spanningTreeCount
#print Conjecture464.largestPrimeFactor
#check Conjecture464.conjecture464_counterexample
#print axioms Conjecture464.cycle_delete_connected
#print axioms Conjecture464.cycle_spanningTreeCount_of_three_le
#print axioms Conjecture464.largestPrimeFactor_vertexCount
#print axioms Conjecture464.cycleFamily_connected
#print axioms Conjecture464.cycleFamily_regular
#print axioms Conjecture464.cycleFamily_order_tendsto
#print axioms Conjecture464.cycleFamily_spanningTreeCount
#print axioms Conjecture464.cycleFamily_largestPrimeFactor
#print axioms Conjecture464.cycleFamily_eventually_violates
#print axioms Conjecture464.no_eventual_logarithmic_lower_bound
#print axioms Conjecture464.conjecture464_counterexample
