import Mathlib.Algebra.FreeMonoid.Basic
import Mathlib.GroupTheory.Congruence.Basic
import Mathlib.Data.Set.Card
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Fintype.Pi
import Mathlib.Data.Fintype.Option
import Mathlib.Data.Fintype.Vector
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Order.Fin.Basic

/-! The number of hypoplactic classes of words of length `ℓ` (or of length at most `ℓ`) over an
`n`-letter alphabet is not the number of plane partitions in a `2 × n × ℓ` box. The hypoplactic
monoid is the quotient of Mathlib's free monoid by the congruence generated by the Knuth
relations and the two quartic hypoplactic relations. -/
namespace Conjecture3842

open FreeMonoid

/-- Over an alphabet with at most one letter a word is determined by its length. -/
theorem list_eq_of_length_eq {α : Type} [Subsingleton α] :
    ∀ u v : List α, u.length = v.length → u = v
  | [], [], _ => rfl
  | [], _ :: _, h => by simp at h
  | _ :: _, [], h => by simp at h
  | a :: u, b :: v, h => by
    rw [Subsingleton.elim a b, list_eq_of_length_eq u v (by simpa using h)]

/-! ### The plactic and hypoplactic congruences -/

section Monoids

variable {α : Type} [LinearOrder α]

/-- The Knuth relations `acb ≡ cab` (`a ≤ b < c`) and `bac ≡ bca` (`a < b ≤ c`). -/
inductive KnuthRel : FreeMonoid α → FreeMonoid α → Prop
  | left (a b c : α) (hab : a ≤ b) (hbc : b < c) :
      KnuthRel (of a * of c * of b) (of c * of a * of b)
  | right (a b c : α) (hab : a < b) (hbc : b ≤ c) :
      KnuthRel (of b * of a * of c) (of b * of c * of a)

/-- The quartic hypoplactic relations `cadb ≡ acbd` (`a ≤ b < c ≤ d`) and `bdac ≡ dbca`
(`a < b ≤ c < d`). -/
inductive QuarticRel : FreeMonoid α → FreeMonoid α → Prop
  | left (a b c d : α) (hab : a ≤ b) (hbc : b < c) (hcd : c ≤ d) :
      QuarticRel (of c * of a * of d * of b) (of a * of c * of b * of d)
  | right (a b c d : α) (hab : a < b) (hbc : b ≤ c) (hcd : c < d) :
      QuarticRel (of b * of d * of a * of c) (of d * of b * of c * of a)

/-- The defining relations of the hypoplactic monoid: Knuth relations and quartic relations. -/
def HypoRel (u v : FreeMonoid α) : Prop := KnuthRel u v ∨ QuarticRel u v

variable (α) in
/-- The plactic congruence (Knuth equivalence). -/
def placticCon : Con (FreeMonoid α) := conGen KnuthRel

variable (α) in
/-- The hypoplactic congruence. -/
def hypoCon : Con (FreeMonoid α) := conGen HypoRel

/-- The hypoplactic congruence contains Knuth equivalence: the hypoplactic monoid is a
quotient of the plactic monoid. -/
theorem placticCon_le_hypoCon : placticCon α ≤ hypoCon α :=
  Con.conGen_mono fun _ _ h => Or.inl h

variable (α) in
/-- The hypoplactic monoid over the alphabet `α`. -/
abbrev Hypo : Type := (hypoCon α).Quotient

/-- The hypoplactic monoid is a monoid, with Mathlib's quotient-monoid structure. -/
example : Monoid (Hypo α) := inferInstance

theorem HypoRel.length_eq {u v : FreeMonoid α} (h : HypoRel u v) : u.length = v.length := by
  rcases h with h | h <;> cases h <;> rfl

theorem HypoRel.three_le {u v : FreeMonoid α} (h : HypoRel u v) : 3 ≤ u.length := by
  rcases h with h | h <;> cases h <;> simp [length_mul, length_of]

theorem length_eq_of_rel {u v : FreeMonoid α} (h : ConGen.Rel HypoRel u v) :
    u.length = v.length := by
  induction h with
  | of x y hxy => exact hxy.length_eq
  | refl x => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih1 ih2 => exact ih1.trans ih2
  | mul _ _ ih1 ih2 => rw [length_mul, length_mul, ih1, ih2]

/-- Hypoplactically equivalent words have the same length. -/
theorem length_eq_of_hypoCon {u v : FreeMonoid α} (h : hypoCon α u v) :
    u.length = v.length :=
  length_eq_of_rel h

theorem eq_or_three_le_of_rel {u v : FreeMonoid α} (h : ConGen.Rel HypoRel u v) :
    u = v ∨ (3 ≤ u.length ∧ 3 ≤ v.length) := by
  induction h with
  | of x y hxy => exact Or.inr ⟨hxy.three_le, hxy.length_eq ▸ hxy.three_le⟩
  | refl x => exact Or.inl rfl
  | symm _ ih => exact ih.elim (fun e => Or.inl e.symm) (fun e => Or.inr ⟨e.2, e.1⟩)
  | trans _ _ ih1 ih2 =>
    rcases ih1 with rfl | h1
    · exact ih2
    · rcases ih2 with rfl | h2
      · exact Or.inr h1
      · exact Or.inr ⟨h1.1, h2.2⟩
  | mul _ _ ih1 ih2 =>
    rcases ih1 with rfl | h1
    · rcases ih2 with rfl | h2
      · exact Or.inl rfl
      · right
        rw [length_mul, length_mul]
        omega
    · right
      rw [length_mul, length_mul]
      omega

/-- Two distinct hypoplactically equivalent words have length at least three, because every
defining relation has length three or four. -/
theorem eq_or_three_le_of_hypoCon {u v : FreeMonoid α} (h : hypoCon α u v) :
    u = v ∨ (3 ≤ u.length ∧ 3 ≤ v.length) :=
  eq_or_three_le_of_rel h

variable (α) in
/-- The hypoplactic classes of words of length exactly `ℓ`. -/
def classesOfLength (ℓ : ℕ) : Set (Hypo α) :=
  {c | ∃ w : FreeMonoid α, w.length = ℓ ∧ (w : Hypo α) = c}

variable (α) in
/-- The hypoplactic classes of words of length at most `ℓ`. -/
def classesUpToLength (ℓ : ℕ) : Set (Hypo α) :=
  {c | ∃ w : FreeMonoid α, w.length ≤ ℓ ∧ (w : Hypo α) = c}

theorem classesOfLength_eq_image (ℓ : ℕ) :
    classesOfLength α ℓ =
      (fun w : FreeMonoid α => (w : Hypo α)) '' {w : FreeMonoid α | w.length = ℓ} := by
  ext c
  simp [classesOfLength]

theorem finite_words (α : Type) [Finite α] (ℓ : ℕ) :
    {w : FreeMonoid α | w.length = ℓ}.Finite := by
  haveI := Fintype.ofFinite α
  exact Set.finite_coe_iff.mp (inferInstanceAs (Finite (List.Vector α ℓ)))

theorem finite_classesOfLength [Finite α] (ℓ : ℕ) : (classesOfLength α ℓ).Finite := by
  rw [classesOfLength_eq_image]
  exact (finite_words α ℓ).image _

theorem classesUpToLength_zero : classesUpToLength α 0 = classesOfLength α 0 := by
  ext c
  simp [classesUpToLength, classesOfLength]

theorem classesUpToLength_succ (ℓ : ℕ) :
    classesUpToLength α (ℓ + 1) = classesUpToLength α ℓ ∪ classesOfLength α (ℓ + 1) := by
  ext c
  simp only [classesUpToLength, classesOfLength, Set.mem_setOf_eq, Set.mem_union]
  constructor
  · rintro ⟨w, hw, rfl⟩
    rcases Nat.lt_or_ge w.length (ℓ + 1) with h | h
    · exact Or.inl ⟨w, by omega, rfl⟩
    · exact Or.inr ⟨w, by omega, rfl⟩
  · rintro (⟨w, hw, rfl⟩ | ⟨w, hw, rfl⟩)
    · exact ⟨w, by omega, rfl⟩
    · exact ⟨w, by omega, rfl⟩

theorem disjoint_classes (ℓ : ℕ) :
    Disjoint (classesUpToLength α ℓ) (classesOfLength α (ℓ + 1)) := by
  rw [Set.disjoint_left]
  rintro c ⟨w, hw, rfl⟩ ⟨w', hw', h⟩
  have := length_eq_of_hypoCon ((hypoCon α).eq.mp h)
  omega

theorem finite_classesUpToLength [Finite α] (ℓ : ℕ) : (classesUpToLength α ℓ).Finite := by
  induction ℓ with
  | zero => rw [classesUpToLength_zero]; exact finite_classesOfLength 0
  | succ ℓ ih => rw [classesUpToLength_succ]; exact ih.union (finite_classesOfLength _)

/-- The counts by exact length add up to the count by length at most `ℓ`. -/
theorem ncard_classesUpToLength_succ [Finite α] (ℓ : ℕ) :
    (classesUpToLength α (ℓ + 1)).ncard =
      (classesUpToLength α ℓ).ncard + (classesOfLength α (ℓ + 1)).ncard := by
  rw [classesUpToLength_succ]
  exact Set.ncard_union_eq (disjoint_classes ℓ) (finite_classesUpToLength ℓ)
    (finite_classesOfLength _)

/-- Words of length at most two are alone in their hypoplactic class, so for `ℓ ≤ 2` the
number of classes of length `ℓ` is the number of words of length `ℓ`. -/
theorem ncard_classesOfLength_of_le_two [Fintype α] (ℓ : ℕ) (hℓ : ℓ ≤ 2) :
    (classesOfLength α ℓ).ncard = Fintype.card α ^ ℓ := by
  rw [classesOfLength_eq_image, Set.ncard_image_of_injOn]
  · rw [← Set.Nat.card_coe_set_eq]
    change Nat.card (List.Vector α ℓ) = _
    rw [Nat.card_eq_fintype_card, card_vector]
  · intro u hu v hv huv
    rcases eq_or_three_le_of_hypoCon ((hypoCon α).eq.mp huv) with h | h
    · exact h
    · have hu' : u.length = ℓ := hu
      omega

/-- Over a one-letter alphabet there is exactly one class of each length. -/
theorem ncard_classesOfLength_of_unique [Unique α] (ℓ : ℕ) :
    (classesOfLength α ℓ).ncard = 1 := by
  rw [Set.ncard_eq_one]
  refine ⟨((ofList (List.replicate ℓ default) : FreeMonoid α) : Hypo α), ?_⟩
  ext c
  simp only [classesOfLength, Set.mem_setOf_eq, Set.mem_singleton_iff]
  constructor
  · rintro ⟨w, hw, rfl⟩
    have : w = ofList (List.replicate ℓ default) :=
      list_eq_of_length_eq (α := α) w (List.replicate ℓ default) (by simpa using hw)
    rw [this]
  · rintro rfl
    exact ⟨ofList (List.replicate ℓ default), by simp [FreeMonoid.length], rfl⟩

/-- Over a one-letter alphabet there are exactly `ℓ + 1` classes of length at most `ℓ`. -/
theorem ncard_classesUpToLength_of_unique [Unique α] (ℓ : ℕ) :
    (classesUpToLength α ℓ).ncard = ℓ + 1 := by
  induction ℓ with
  | zero => rw [classesUpToLength_zero, ncard_classesOfLength_of_unique]
  | succ ℓ ih => rw [ncard_classesUpToLength_succ, ih, ncard_classesOfLength_of_unique]

theorem ncard_classesUpToLength_one [Fintype α] :
    (classesUpToLength α 1).ncard = 1 + Fintype.card α := by
  rw [ncard_classesUpToLength_succ, classesUpToLength_zero,
    ncard_classesOfLength_of_le_two 0 (by omega), ncard_classesOfLength_of_le_two 1 (by omega)]
  simp

theorem ncard_classesUpToLength_two [Fintype α] :
    (classesUpToLength α 2).ncard = 1 + Fintype.card α + Fintype.card α ^ 2 := by
  rw [ncard_classesUpToLength_succ, ncard_classesUpToLength_one,
    ncard_classesOfLength_of_le_two 2 (by omega)]

end Monoids

/-! ### The relations are not vacuous -/

/-- A Knuth relation in the hypoplactic monoid over two letters: `010 ≡ 100`. -/
theorem knuth_instance :
    ((of 0 * of 1 * of 0 : FreeMonoid (Fin 2)) : Hypo (Fin 2)) =
      ((of 1 * of 0 * of 0 : FreeMonoid (Fin 2)) : Hypo (Fin 2)) :=
  (hypoCon (Fin 2)).eq.mpr
    (ConGen.Rel.of _ _ (Or.inl (KnuthRel.left 0 0 1 (by decide) (by decide))))

/-- A quartic relation in the hypoplactic monoid over two letters: `1010 ≡ 0101`. -/
theorem quartic_instance :
    ((of 1 * of 0 * of 1 * of 0 : FreeMonoid (Fin 2)) : Hypo (Fin 2)) =
      ((of 0 * of 1 * of 0 * of 1 : FreeMonoid (Fin 2)) : Hypo (Fin 2)) :=
  (hypoCon (Fin 2)).eq.mpr
    (ConGen.Rel.of _ _ (Or.inr (QuarticRel.left 0 0 1 1 (by decide) (by decide) (by decide))))

/-! ### Plane partitions in a box -/

/-- A plane partition in an `a × b × c` box: an `a × b` array with entries in `{0, …, c}` that
is weakly decreasing along every row and along every column. -/
def IsPlanePartition {a b c : ℕ} (π : Fin a → Fin b → Fin (c + 1)) : Prop :=
  (∀ i j j', j ≤ j' → π i j' ≤ π i j) ∧ (∀ i i' j, i ≤ i' → π i' j ≤ π i j)

instance {a b c : ℕ} : DecidablePred (IsPlanePartition (a := a) (b := b) (c := c)) :=
  fun π => by unfold IsPlanePartition; infer_instance

/-- The plane partitions in an `a × b × c` box. -/
abbrev PlanePartition (a b c : ℕ) : Type :=
  {π : Fin a → Fin b → Fin (c + 1) // IsPlanePartition π}

/-- The constant array. -/
def ppConst (a b c : ℕ) (k : Fin (c + 1)) : PlanePartition a b c :=
  ⟨fun _ _ => k, fun _ _ _ _ => le_rfl, fun _ _ _ _ => le_rfl⟩

/-- The two-row array with first row `1` and second row `0`. -/
def ppStep (b c : ℕ) : PlanePartition 2 b (c + 1) :=
  ⟨fun i _ => if i = 0 then 1 else 0, fun _ _ _ _ => le_rfl, fun i i' _ h => by
    by_cases hi : i' = 0
    · have : i = 0 := le_antisymm (hi ▸ h) (Fin.zero_le i)
      simp [hi, this]
    · simp [hi]⟩

/-- The two-row array with entries in `{0, 1}` whose first row is `1` in the first `k` columns
and whose second row is `0`. -/
def ppRow (n : ℕ) (k : Fin (n + 1)) : PlanePartition 2 n 1 :=
  ⟨fun i j => if i = 0 ∧ j.val < k.val then 1 else 0, fun i j j' h => by
    by_cases h' : i = 0 ∧ j'.val < k.val
    · have : i = 0 ∧ j.val < k.val := ⟨h'.1, lt_of_le_of_lt h h'.2⟩
      simp [h', this]
    · simp [h'], fun i i' j h => by
    by_cases h' : i' = 0 ∧ j.val < k.val
    · have : i = 0 ∧ j.val < k.val := ⟨le_antisymm (h'.1 ▸ h) (Fin.zero_le i), h'.2⟩
      simp [h', this]
    · simp [h']⟩

/-- A `2 × 1 × ℓ` box with `ℓ ≥ 1` contains at least `ℓ + 2` plane partitions. -/
theorem card_pp_one_column (c : ℕ) : c + 3 ≤ Fintype.card (PlanePartition 2 1 (c + 1)) := by
  let f : Option (Fin (c + 2)) → PlanePartition 2 1 (c + 1) := fun o =>
    o.elim (ppStep 1 c) (ppConst 2 1 (c + 1))
  have hstep : ∀ k, ppConst 2 1 (c + 1) k ≠ ppStep 1 c := by
    intro k h
    have h0 := congrFun (congrFun (congrArg Subtype.val h) 0) 0
    have h1 := congrFun (congrFun (congrArg Subtype.val h) 1) 0
    simp [ppConst, ppStep] at h0 h1
    rw [h0] at h1
    exact absurd h1 (by simp [Fin.ext_iff])
  have hf : Function.Injective f := by
    rintro (_ | k) (_ | k') h
    · rfl
    · exact absurd h.symm (hstep k')
    · exact absurd h (hstep k)
    · have h0 := congrFun (congrFun (congrArg Subtype.val h) 0) 0
      simp [f, ppConst] at h0
      rw [h0]
  have := Fintype.card_le_of_injective f hf
  simpa using this

/-- A `2 × n × 1` box with `n ≥ 1` contains at least `n + 2` plane partitions. -/
theorem card_pp_height_one (n : ℕ) (hn : 1 ≤ n) :
    n + 2 ≤ Fintype.card (PlanePartition 2 n 1) := by
  let f : Option (Fin (n + 1)) → PlanePartition 2 n 1 := fun o =>
    o.elim (ppConst 2 n 1 1) (ppRow n)
  have hrow : ∀ k, ppRow n k ≠ ppConst 2 n 1 1 := by
    intro k h
    have h1 := congrFun (congrFun (congrArg Subtype.val h) 1) ⟨0, hn⟩
    simp [ppConst, ppRow] at h1
  have key : ∀ k k' : Fin (n + 1), k.val < k'.val → ppRow n k ≠ ppRow n k' := by
    intro k k' hk h
    have h0 := congrFun (congrFun (congrArg Subtype.val h) 0) ⟨k.val, by omega⟩
    simp [ppRow, hk] at h0
  have hf : Function.Injective f := by
    rintro (_ | k) (_ | k') h
    · rfl
    · exact absurd h.symm (hrow k')
    · exact absurd h (hrow k)
    · rcases Nat.lt_trichotomy k.val k'.val with hk | hk | hk
      · exact absurd h (key k k' hk)
      · rw [Fin.ext hk]
      · exact absurd h.symm (key k' k hk)
  have := Fintype.card_le_of_injective f hf
  simpa using this

/-- The `2 × 2 × 2` box contains exactly twenty plane partitions. -/
theorem card_pp_222 : Fintype.card (PlanePartition 2 2 2) = 20 := by decide

/-- The `2 × 1 × 1` box contains exactly three plane partitions. -/
theorem card_pp_211 : Fintype.card (PlanePartition 2 1 1) = 3 := by decide

/-! ### The conjectured identity and its negation -/

/-- The identity as in the English source: classes of words of length at most `ℓ`. -/
def ClaimedIdentityUpTo : Prop :=
  ∀ n ℓ : ℕ, (classesUpToLength (Fin n) ℓ).ncard = Fintype.card (PlanePartition 2 n ℓ)

/-- The identity as in the Chinese source: classes of words of length exactly `ℓ`. -/
def ClaimedIdentityExact : Prop :=
  ∀ n ℓ : ℕ, (classesOfLength (Fin n) ℓ).ncard = Fintype.card (PlanePartition 2 n ℓ)

/-- Two letters, length two: `4` classes of length two and `7` of length at most two, against
`20` plane partitions. -/
theorem two_letters_length_two :
    (classesOfLength (Fin 2) 2).ncard = 4 ∧ (classesUpToLength (Fin 2) 2).ncard = 7 ∧
      Fintype.card (PlanePartition 2 2 2) = 20 := by
  refine ⟨?_, ?_, card_pp_222⟩
  · rw [ncard_classesOfLength_of_le_two 2 le_rfl]; rfl
  · rw [ncard_classesUpToLength_two]; rfl

/-- One letter: for every `ℓ ≥ 1` both counts are smaller than the number of plane
partitions. -/
theorem one_letter (ℓ : ℕ) (hℓ : 1 ≤ ℓ) :
    (classesOfLength (Fin 1) ℓ).ncard < (classesUpToLength (Fin 1) ℓ).ncard ∧
      (classesUpToLength (Fin 1) ℓ).ncard < Fintype.card (PlanePartition 2 1 ℓ) := by
  obtain ⟨c, rfl⟩ : ∃ c, ℓ = c + 1 := ⟨ℓ - 1, by omega⟩
  have := card_pp_one_column c
  rw [ncard_classesOfLength_of_unique, ncard_classesUpToLength_of_unique]
  omega

/-- Length one: for every `n ≥ 1` both counts are smaller than the number of plane
partitions. -/
theorem length_one (n : ℕ) (hn : 1 ≤ n) :
    (classesOfLength (Fin n) 1).ncard < (classesUpToLength (Fin n) 1).ncard ∧
      (classesUpToLength (Fin n) 1).ncard < Fintype.card (PlanePartition 2 n 1) := by
  have := card_pp_height_one n hn
  rw [ncard_classesOfLength_of_le_two 1 (by omega), ncard_classesUpToLength_one]
  simp only [Fintype.card_fin, pow_one]
  omega

theorem conjecture_false_upTo : ¬ ClaimedIdentityUpTo := fun h => by
  have h1 := h 2 2
  rw [two_letters_length_two.2.1, card_pp_222] at h1
  exact absurd h1 (by decide)

theorem conjecture_false_exact : ¬ ClaimedIdentityExact := fun h => by
  have h1 := h 2 2
  rw [two_letters_length_two.1, card_pp_222] at h1
  exact absurd h1 (by decide)

#print axioms placticCon_le_hypoCon
#print axioms length_eq_of_hypoCon
#print axioms eq_or_three_le_of_hypoCon
#print axioms ncard_classesOfLength_of_le_two
#print axioms ncard_classesOfLength_of_unique
#print axioms ncard_classesUpToLength_of_unique
#print axioms knuth_instance
#print axioms quartic_instance
#print axioms card_pp_222
#print axioms two_letters_length_two
#print axioms one_letter
#print axioms length_one
#print axioms conjecture_false_upTo
#print axioms conjecture_false_exact

end Conjecture3842
