import Main

/-! Axiom audit: every theorem must print `does not depend on any axioms`. -/

#print axioms and_true_l
#print axioms and_true_r
#print axioms dlogOk_implies
#print axioms not_inOrbit_self
#print axioms dlog_ok_3
#print axioms dl_len_3
#print axioms cover_3
#print axioms pr_3
#print axioms pw_3
#print axioms lm_3
#print axioms dlog_ok_5
#print axioms dl_len_5
#print axioms cover_5
#print axioms pr_5
#print axioms pw_5
#print axioms lm_5
#print axioms dlog_ok_11
#print axioms dl_len_11
#print axioms cover_11
#print axioms pr_11
#print axioms pw_11
#print axioms lm_11
#print axioms dlog_ok_13
#print axioms dl_len_13
#print axioms cover_13
#print axioms pr_13
#print axioms pw_13
#print axioms lm_13
#print axioms dlog_ok_19
#print axioms dl_len_19
#print axioms cover_19
#print axioms pr_19
#print axioms pw_19
#print axioms lm_19
#print axioms dlog_ok_29
#print axioms dl_len_29
#print axioms cover_29
#print axioms pr_29
#print axioms pw_29
#print axioms lm_29
#print axioms dlog_ok_37
#print axioms dl_len_37
#print axioms cover_37
#print axioms pr_37
#print axioms pw_37
#print axioms lm_37
#print axioms dlog_ok_53
#print axioms dl_len_53
#print axioms cover_53
#print axioms pr_53
#print axioms pw_53
#print axioms lm_53
#print axioms dlog_ok_59
#print axioms dl_len_59
#print axioms cover_59
#print axioms pr_59
#print axioms pw_59
#print axioms lm_59
#print axioms dlog_ok_61
#print axioms dl_len_61
#print axioms cover_61
#print axioms pr_61
#print axioms pw_61
#print axioms lm_61
#print axioms dlog_ok_67
#print axioms dl_len_67
#print axioms cover_67
#print axioms pr_67
#print axioms pw_67
#print axioms lm_67
#print axioms dlog_ok_83
#print axioms dl_len_83
#print axioms cover_83
#print axioms pr_83
#print axioms pw_83
#print axioms lm_83
#print axioms dlog_ok_101
#print axioms dl_len_101
#print axioms cover_101
#print axioms pr_101
#print axioms pw_101
#print axioms lm_101
#print axioms dlog_ok_107
#print axioms dl_len_107
#print axioms cover_107
#print axioms pr_107
#print axioms pw_107
#print axioms lm_107
#print axioms dlog_ok_131
#print axioms dl_len_131
#print axioms cover_131
#print axioms pr_131
#print axioms pw_131
#print axioms lm_131
#print axioms dlog_ok_139
#print axioms dl_len_139
#print axioms cover_139
#print axioms pr_139
#print axioms pw_139
#print axioms lm_139
#print axioms dlog_ok_149
#print axioms dl_len_149
#print axioms cover_149
#print axioms pr_149
#print axioms pw_149
#print axioms lm_149
#print axioms dlog_ok_163
#print axioms dl_len_163
#print axioms cover_163
#print axioms pr_163
#print axioms pw_163
#print axioms lm_163
#print axioms dlog_ok_173
#print axioms dl_len_173
#print axioms cover_173
#print axioms pr_173
#print axioms pw_173
#print axioms lm_173
#print axioms dlog_ok_179
#print axioms dl_len_179
#print axioms cover_179
#print axioms pr_179
#print axioms pw_179
#print axioms lm_179
#print axioms dlog_ok_181
#print axioms dl_len_181
#print axioms cover_181
#print axioms pr_181
#print axioms pw_181
#print axioms lm_181
#print axioms dlog_ok_197
#print axioms dl_len_197
#print axioms cover_197
#print axioms pr_197
#print axioms pw_197
#print axioms lm_197
#print axioms attack_101
#print axioms attack_3
