name = "conjecture37"
version = "0.1.0"
defaultTargets = ["Conjecture37"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "Conjecture37"
