name = "NimSumPeriod"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["NimSumPeriod"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "NimSumPeriod"
globs = ["NimSumPeriod"]
