"""Independent exact arithmetic check for Conjecture 6551 only."""
from fractions import Fraction as Q
from itertools import product
from math import factorial
from pathlib import Path
import json

stages = [(0,Q(3,4)),(1,Q(1)),(0,Q(1,4))]
words = [w for degree in range(3) for w in product((0,1),repeat=degree)]
coeff = {():Q(1)}
for letter,a in stages:
    factor = {tuple([letter]*n):a**n/factorial(n) for n in range(3)}
    nxt = {}
    for u,cu in coeff.items():
        for v,cv in factor.items():
            if len(u+v)<=2:
                nxt[u+v]=nxt.get(u+v,Q(0))+cu*cv
    coeff=nxt
for w in words:
    exact=Q(1,factorial(len(w)))
    error=coeff.get(w,Q(0))-exact
    wanted=Q(1,4) if w==(0,1) else Q(-1,4) if w==(1,0) else Q(0)
    assert error==wanted
assert coeff[(0,1)]!=Q(1,2)
assert sum(a for b,a in stages if b==0)==1
assert sum(a for b,a in stages if b==1)==1
def mul(A,B):
    return [[sum((A[i][k]*B[k][j] for k in range(2)),Q(0)) for j in range(2)] for i in range(2)]
A=[[Q(0),Q(1)],[Q(0),Q(0)]]
B=[[Q(0),Q(0)],[Q(1),Q(0)]]
AB,BA=mul(A,B),mul(B,A)
assert AB!=BA
matrix_error=[[Q(0),Q(0)],[Q(0),Q(0)]]
for w in product((0,1),repeat=2):
    M=mul(A if w[0]==0 else B,A if w[1]==0 else B)
    c=coeff[w]-Q(1,2)
    for i in range(2):
        for j in range(2):
            matrix_error[i][j]+=c*M[i][j]
assert matrix_error==[[Q(1,4),Q(0)],[Q(0),Q(-1,4)]]
result={'id':6551,'all_words_through_degree':2,'words_checked':len(words),
        'formal_order_exactly':1,'leading_commutator_coefficient':'1/4',
        'actual_matrix_error':[['1/4','0'],['0','-1/4']],
        'pdf_validation':'separate; no PDF generated by this check'}
Path(__file__).with_name('independent_check.json').write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8')
print(json.dumps(result))
