#!/usr/bin/env python3
"""
Independent recomputation for the disproof of TLMC conjecture 00000000548.

Conjecture: for every monomial ideal I, iota(I) <= beta0(I), where
  * iota(I)  = minimal number of components in an irredundant irreducible
    decomposition of I,
  * beta0(I) = minimal number of monomial generators of I (0-th Betti number).

Attack: I = (xyz) in k[x,y,z].  Claimed numbers: iota((xyz)) = 3 > 1 = beta0.

This script re-derives every number from scratch by finite enumeration in the
exponent box [0,4]^3 (any global statement of these ideals is componentwise,
so equality/irredundancy/minimality inside the box lifts verbatim to the
polynomial ring).  Standard library only; runs in about a second.

Checks performed
  1. (xyz) == (x) & (y) & (z)                      as monomial sets.
  2. irredundancy: yz, xz, xy witnesses.
  3. beta0((xyz)) = 1   (brute force over generator sets).
  4. (x), (y), (z) irreducible (exhaustive over all 252 box super-ideals).
  5. iota((xyz)) = 3    (no 1- or 2-component irreducible-form realization
     exists; the 3-component one does).
Then the verdict is compared against the claimed attack numbers.
"""
import sys
from itertools import combinations, product

B = 4  # exponent box [0, B]^3
BOX = [(a, b, c) for a, b, c in product(range(B + 1), repeat=3)]


def upclosure(gens):
    """Monomial ideal generated by `gens`, restricted to the box."""
    return frozenset(
        e for e in BOX
        if any(all(gi <= ei for gi, ei in zip(g, e)) for g in gens)
    )


XYZ = upclosure([(1, 1, 1)])   # ideal (xyz)
CX = upclosure([(1, 0, 0)])    # component (x)
CY = upclosure([(0, 1, 0)])    # component (y)
CZ = upclosure([(0, 0, 1)])    # component (z)

ok = True


def report(name, value):
    global ok
    ok = ok and bool(value)
    print(f"{name}: {value}", flush=True)


# ---- check 1: set equality (xyz) == (x) & (y) & (z) -------------------------
report("check1  (xyz)==(x)∩(y)∩(z)", (CX & CY & CZ) == XYZ)

# ---- check 2: irredundancy, witness monomials -------------------------------
report("check2  yz=(0,1,1) in (y)∩(z) but not (xyz)",
       (0, 1, 1) in (CY & CZ) - XYZ)
report("check2  xz=(1,0,1) in (x)∩(z) but not (xyz)",
       (1, 0, 1) in (CX & CZ) - XYZ)
report("check2  xy=(1,1,0) in (x)∩(y) but not (xyz)",
       (1, 1, 0) in (CX & CY) - XYZ)

# ---- check 3: beta0((xyz)) = 1 ----------------------------------------------
def beta0(ideal):
    for k in range(4):
        for gens in combinations(BOX, k):
            if upclosure(gens) == ideal:
                return k, gens
    return None


k0, g0 = beta0(XYZ)
report("check3  beta0((xyz)) =", f"{k0}   minimal generator set {g0}")

# ---- check 4: every component irreducible (exhaustive inside the box) -------
def all_ideals_containing(kernel):
    """All up-sets U with kernel <= U, as complements of down-sets of BOX\\kernel."""
    P = [e for e in BOX if e not in kernel]
    preds = {
        e: [f for f in P
            if f != e and all(fi <= ei for fi, ei in zip(f, e))]
        for e in P
    }
    seen = {frozenset()}
    stack = [frozenset()]
    while stack:
        d = stack.pop()
        for e in P:
            if e in d:
                continue
            if all(p in d for p in preds[e]):
                d2 = frozenset(d | {e})
                if d2 not in seen:
                    seen.add(d2)
                    stack.append(d2)
    return [frozenset(set(BOX) - d) for d in seen]


for name, comp in (("(x)", CX), ("(y)", CY), ("(z)", CZ)):
    ideals = all_ideals_containing(comp)
    kset = set(comp)
    split = [ (I, J) for I in ideals for J in ideals
              if I != comp and J != comp and set(I) & set(J) == kset ]
    report(f"check4  {name} irreducible "
           f"(no split among {len(ideals)} box super-ideals)", not split)

# ---- check 5: minimal number of irreducible-form components = iota ----------
# Irreducible monomial ideals are exactly the pure-power generated ones
# (x^a if a>0, y^b if b>0, z^c if c>0); enumerate all of them in the box.
TRIPLES = [(a, b, c) for a, b, c in product(range(B + 2), repeat=3)]


def irred_ideal(t):
    a, b, c = t
    return frozenset(
        e for e in BOX
        if (a > 0 and e[0] >= a) or (b > 0 and e[1] >= b) or (c > 0 and e[2] >= c)
    )


IR = {t: irred_ideal(t) for t in TRIPLES}
report("check5a comps are irreducible-form",
       IR[(1, 0, 0)] == CX and IR[(0, 1, 0)] == CY and IR[(0, 0, 1)] == CZ)
report("check5b 1-component realizations",
       [t for t in TRIPLES if IR[t] == XYZ] == [])
report("check5c 2-component realizations",
       [(t1, t2) for t1, t2 in combinations(TRIPLES, 2)
        if IR[t1] & IR[t2] == XYZ] == [])
report("check5d 3-component realization works",
       IR[(1, 0, 0)] & IR[(0, 1, 0)] & IR[(0, 0, 1)] == XYZ)

# ---- verdict -----------------------------------------------------------------
IOTA, BETA0 = 3, k0
print(flush=True)
print(f"recomputed: iota((xyz)) = {IOTA}, beta0((xyz)) = {BETA0}", flush=True)
claimed = (3, 1)
print(f"claimed   : iota = {claimed[0]}, beta0 = {claimed[1]}", flush=True)
report("recomputation matches claimed attack numbers", (IOTA, BETA0) == claimed)
report("VERDICT  iota > beta0 (conjecture 00000000548 FALSE)", IOTA > BETA0)

sys.exit(0 if ok else 1)
