/-!
# Conjecture 00000001141 is false: the centre of `u(sl₂)` has Krull dimension `0`, not `1`

The conjecture (first clause): for the restricted enveloping algebra `u(g)` of a restricted Lie
algebra `g`, the Krull dimension of the centre of `u(sl_n)` is `n − 1`.  For `n = 2` this says
`Krull dim Z(u(sl₂)) = 1`.  We refute it in characteristic `p = 3`, with everything built from
scratch in core Lean 4 (no Mathlib):

* `F3`: the prime field `𝔽₃`.
* `V = 𝔽₃^27`: a 27-dimensional vector space with basis `bv i`, `i = 9a + 3b + c`
  (`bv (9a+3b+c)` plays the role of the PBW monomial `e^a h^b f^c`, `0 ≤ a,b,c < 3`).
* `opE, opH, opF : V → V`: three explicit linear operators (left multiplication by `e, h, f` in the
  PBW basis; sparse tables).
* `Gen`: the subalgebra `A ⊆ End(V)` generated by `opE, opH, opF` (closure of the identity and the
  generators under `+`, `−` and composition).  This is our model of `u(sl₂)`:
  - `rel_*`: the generators satisfy the defining relations of `u(sl₂)`:
    `[h,e] = 2e`, `[h,f] = −2f`, `[e,f] = h`, `e³ = 0`, `f³ = 0`, `h³ = h`
    (`e^[p] = 0`, `f^[p] = 0`, `h^[p] = h` is the `p`-map of `sl₂`);
  - `ev_bijective`: evaluation at the vector `1 = bv 0` is a bijection `A → V`, so
    `|A| = 3^27 = p^(dim sl₂)`.  Since `u(sl₂)` is spanned by the `27` PBW monomials and surjects
    onto `A` (universal property), `A ≅ u(sl₂)` (see the report).
* `ZU`: the centre `Z(A) = {z ∈ A : z ψ = ψ z for all ψ ∈ A}`, with `ZRing : CRing ZU` its
  commutative ring structure.
* A general commutative-ring library: ideals, prime ideals, chains of primes, `HasChain`,
  `KrullDimIs d` (the supremum of lengths of chains of prime ideals is `d`), `Finite`.
* `finite_krullDim_zero`: every finite commutative ring with a prime ideal has Krull dimension
  `0` (every prime is maximal: no strict inclusion of primes).
* `krullDim_center`: `Krull dim Z(u(sl₂)) = 0`;  `conjecture_00000001141_false`: it is not `2 − 1`
  (the first clause fails for `n = 2`, so the conjunction is false).
* `clause_fails_for_finite_rings`: no finite commutative ring has Krull dimension `n − 1` for
  `n ≥ 2`; this is the mechanism for every `n` and `p` (`dim u(sl_n) = p^(n²−1) < ∞`).
* `center_not_rank_dim`: `Z(u(sl₂))` is not one-dimensional over `𝔽₃` (it contains `1` and the
  Casimir element, linearly independent), refuting also the "dimension = rank (= 1)" reading of
  the second clause for `g = sl₂`.
-/

namespace RestrictedSL2

/-! ## 1. The field `𝔽₃` -/

/-- The prime field `𝔽₃ = {z, o, t} = {0, 1, 2}`. -/
inductive F3 | z | o | t
  deriving DecidableEq, Repr

namespace F3

def add : F3 → F3 → F3
  | z, a => a
  | a, z => a
  | o, o => t
  | o, t => z
  | t, o => z
  | t, t => o

def mul : F3 → F3 → F3
  | z, _ => z
  | _, z => z
  | o, a => a
  | a, o => a
  | t, t => o

def neg : F3 → F3
  | z => z
  | o => t
  | t => o

/-- Reduction mod 3. -/
def ofN (n : Nat) : F3 :=
  match n % 3 with
  | 0 => z
  | 1 => o
  | _ => t

instance : Add F3 := ⟨add⟩
instance : Mul F3 := ⟨mul⟩
instance : Neg F3 := ⟨neg⟩
instance (n : Nat) : OfNat F3 n := ⟨ofN n⟩

theorem add_assoc (a b c : F3) : a + b + c = a + (b + c) := by
  cases a <;> cases b <;> cases c <;> decide
theorem add_comm (a b : F3) : a + b = b + a := by cases a <;> cases b <;> decide
theorem zero_add (a : F3) : 0 + a = a := by cases a <;> decide
theorem add_zero (a : F3) : a + 0 = a := by cases a <;> decide
theorem neg_add (a : F3) : -a + a = 0 := by cases a <;> decide
theorem add_neg (a : F3) : a + -a = 0 := by cases a <;> decide
theorem mul_assoc (a b c : F3) : a * b * c = a * (b * c) := by
  cases a <;> cases b <;> cases c <;> decide
theorem mul_comm (a b : F3) : a * b = b * a := by cases a <;> cases b <;> decide
theorem one_mul (a : F3) : 1 * a = a := by cases a <;> decide
theorem mul_one (a : F3) : a * 1 = a := by cases a <;> decide
theorem zero_mul (a : F3) : 0 * a = 0 := by cases a <;> decide
theorem mul_zero (a : F3) : a * 0 = 0 := by cases a <;> decide
theorem mul_add (a b c : F3) : a * (b + c) = a * b + a * c := by
  cases a <;> cases b <;> cases c <;> decide
theorem add_mul (a b c : F3) : (a + b) * c = a * c + b * c := by
  cases a <;> cases b <;> cases c <;> decide
theorem neg_add_distrib (a b : F3) : -(a + b) = -a + -b := by cases a <;> cases b <;> decide
theorem neg_eq_two_mul (a : F3) : -a = 2 * a := by cases a <;> decide
theorem two_mul (a : F3) : 2 * a = a + a := by cases a <;> decide
theorem eq_zero_of_add_self (a : F3) (h : a = a + a) : a = 0 := by
  cases a <;> first | rfl | exact absurd h (by decide)
theorem mul_eq_zero (a b : F3) (h : a * b = 0) : a = 0 ∨ b = 0 := by
  cases a <;> cases b <;> first | exact Or.inl rfl | exact Or.inr rfl | exact absurd h (by decide)
theorem one_ne_zero : (1 : F3) ≠ 0 := by decide
/-- The key step of the additivity of sparse operators. -/
theorem sp_step (c a b x y : F3) : c * (a + b) + (x + y) = (c * a + x) + (c * b + y) := by
  cases c <;> cases a <;> cases b <;> cases x <;> cases y <;> decide
theorem neg_mul (a b : F3) : -(a * b) = a * -b := by cases a <;> cases b <;> decide

end F3

/-! ## 2. The vector space `V = 𝔽₃^27` -/

abbrev V := Fin 27 → F3

/-- Coordinate `j` of `v` (and `0` for `j ≥ 27`). -/
def get (v : V) (j : Nat) : F3 := if h : j < 27 then v ⟨j, h⟩ else 0

def vadd (v w : V) : V := fun k => v k + w k
def vneg (v : V) : V := fun k => -(v k)
def vzero : V := fun _ => 0
def vsmul (c : F3) (v : V) : V := fun k => c * v k
/-- The basis vector `bv i` (for `i = 9a+3b+c` it stands for the PBW monomial `e^a h^b f^c`). -/
def bv (i : Nat) : V := fun k => if k.val = i then 1 else 0

theorem ext_get {v w : V} (h : ∀ k, k < 27 → get v k = get w k) : v = w := by
  funext ⟨k, hk⟩
  have := h k hk
  simpa [get, hk] using this

instance : DecidableEq V := fun v w =>
  decidable_of_iff (∀ k, k < 27 → get v k = get w k) ⟨ext_get, fun h _ _ => h ▸ rfl⟩

theorem get_vadd (v w : V) (j : Nat) : get (vadd v w) j = get v j + get w j := by
  unfold get; split
  · rfl
  · rfl

theorem vadd_assoc (u v w : V) : vadd (vadd u v) w = vadd u (vadd v w) := by
  funext k; exact F3.add_assoc _ _ _
theorem vadd_comm (u v : V) : vadd u v = vadd v u := by funext k; exact F3.add_comm _ _
theorem vzero_vadd (v : V) : vadd vzero v = v := by funext k; exact F3.zero_add _
theorem vadd_vzero (v : V) : vadd v vzero = v := by funext k; exact F3.add_zero _
theorem vneg_vadd (v : V) : vadd (vneg v) v = vzero := by funext k; exact F3.neg_add _
theorem vadd_vneg (v : V) : vadd v (vneg v) = vzero := by funext k; exact F3.add_neg _
theorem vneg_add (v w : V) : vneg (vadd v w) = vadd (vneg v) (vneg w) := by
  funext k; exact F3.neg_add_distrib _ _
theorem vneg_eq_smul (v : V) : vneg v = vsmul 2 v := by funext k; exact F3.neg_eq_two_mul _
theorem vsmul_zero (v : V) : vsmul 0 v = vzero := by funext k; exact F3.zero_mul _
theorem vsmul_one (v : V) : vsmul 1 v = v := by funext k; exact F3.one_mul _
theorem vsmul_two (v : V) : vsmul 2 v = vadd v v := by funext k; exact F3.two_mul _

/-- Finite sums `Σ_{i<n} g i`. -/
def vsum : Nat → (Nat → V) → V
  | 0, _ => vzero
  | n + 1, g => vadd (vsum n g) (g n)

theorem vsum_congr {g g' : Nat → V} : ∀ n, (∀ i, i < n → g i = g' i) → vsum n g = vsum n g'
  | 0, _ => rfl
  | n + 1, h => by
    simp only [vsum]
    rw [vsum_congr n (fun i hi => h i (by omega)), h n (by omega)]

theorem vsum_basis_apply (v : V) (k : Fin 27) :
    ∀ n, vsum n (fun i => vsmul (get v i) (bv i)) k = if k.val < n then v k else 0
  | 0 => by simp [vsum, vzero]
  | n + 1 => by
    simp only [vsum]
    show vsum n (fun i => vsmul (get v i) (bv i)) k + get v n * bv n k = _
    rw [vsum_basis_apply v k n]
    by_cases h1 : k.val < n
    · have h2 : ¬ k.val = n := by omega
      simp [bv, h1, h2, Nat.lt_succ_of_lt h1, F3.mul_zero, F3.add_zero]
    · by_cases h2 : k.val = n
      · have hn : n < 27 := h2 ▸ k.isLt
        have hk : (⟨n, hn⟩ : Fin 27) = k := Fin.ext h2.symm
        simp [bv, h1, h2, get, hn, hk, F3.mul_one, F3.zero_add]
      · have h3 : ¬ k.val < n + 1 := by omega
        simp [bv, h1, h2, h3, F3.mul_zero, F3.add_zero]

/-- Every vector is the sum of its coordinates times the basis vectors. -/
theorem decomp (v : V) : v = vsum 27 (fun i => vsmul (get v i) (bv i)) := by
  funext k
  rw [vsum_basis_apply v k 27]
  simp [k.isLt]

/-! ## 3. Additive maps -/

def Additive (φ : V → V) : Prop := ∀ v w, φ (vadd v w) = vadd (φ v) (φ w)

theorem Additive.map_zero {φ : V → V} (h : Additive φ) : φ vzero = vzero := by
  have h0 := h vzero vzero
  rw [vzero_vadd] at h0
  funext k
  exact F3.eq_zero_of_add_self _ (congrFun h0 k)

theorem Additive.map_smul {φ : V → V} (h : Additive φ) (c : F3) (v : V) :
    φ (vsmul c v) = vsmul c (φ v) := by
  cases c
  · show φ (vsmul 0 v) = vsmul 0 (φ v)
    rw [vsmul_zero, vsmul_zero, h.map_zero]
  · show φ (vsmul 1 v) = vsmul 1 (φ v)
    rw [vsmul_one, vsmul_one]
  · show φ (vsmul 2 v) = vsmul 2 (φ v)
    rw [vsmul_two, vsmul_two, h]

theorem Additive.map_neg {φ : V → V} (h : Additive φ) (v : V) : φ (vneg v) = vneg (φ v) := by
  rw [vneg_eq_smul, vneg_eq_smul, h.map_smul]

theorem Additive.map_vsum {φ : V → V} (h : Additive φ) (g : Nat → V) :
    ∀ n, φ (vsum n g) = vsum n (fun i => φ (g i))
  | 0 => h.map_zero
  | n + 1 => by simp only [vsum]; rw [h, h.map_vsum g n]

/-- Two additive maps that agree on the basis are equal. -/
theorem ext_basis {φ ψ : V → V} (hφ : Additive φ) (hψ : Additive ψ)
    (h : ∀ i, i < 27 → φ (bv i) = ψ (bv i)) : φ = ψ := by
  funext v
  rw [decomp v, hφ.map_vsum, hψ.map_vsum]
  apply vsum_congr
  intro i hi
  rw [hφ.map_smul, hψ.map_smul, h i hi]

/-! ## 4. Sparse operators and the generators of `u(sl₂)`

`Op T` is the linear map whose `k`-th output coordinate is `Σ_{(j,c) ∈ T[k]} c · v_j`.
The tables below are the left/right multiplications by `e, h, f` on the PBW basis
`e^a h^b f^c ↔ bv (9a+3b+c)` of `u(sl₂)` over `𝔽₃` (computed by normal ordering, see the
report and `verify.py`).  Their meaning is certified by the theorems of §5 alone. -/

def sp : List (Nat × Nat) → V → F3
  | [], _ => 0
  | (j, c) :: t, v => F3.ofN c * get v j + sp t v

def Op (T : List (List (Nat × Nat))) (v : V) : V := fun k => sp (T.getD k.val []) v

theorem sp_add (v w : V) : ∀ L : List (Nat × Nat), sp L (vadd v w) = sp L v + sp L w
  | [] => rfl
  | (j, c) :: t => by
    simp only [sp]
    rw [get_vadd, sp_add v w t, F3.sp_step]

theorem Op_additive (T : List (List (Nat × Nat))) : Additive (Op T) := by
  intro v w; funext k; exact sp_add v w _

/-! ### Tables (pre-image form: row `k` lists the pairs `(j, c)` such that `c` is the coefficient
of `bv k` in `g · bv j`, resp. `bv j · g`) -/

def tblE : List (List (Nat × Nat)) :=
  [[],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [(0, 1)],
   [(1, 1)],
   [(2, 1)],
   [(3, 1)],
   [(4, 1)],
   [(5, 1)],
   [(6, 1)],
   [(7, 1)],
   [(8, 1)],
   [(9, 1)],
   [(10, 1)],
   [(11, 1)],
   [(12, 1)],
   [(13, 1)],
   [(14, 1)],
   [(15, 1)],
   [(16, 1)],
   [(17, 1)]]

def tblH : List (List (Nat × Nat)) :=
  [[],
   [],
   [],
   [(0, 1), (6, 1)],
   [(1, 1), (7, 1)],
   [(2, 1), (8, 1)],
   [(3, 1)],
   [(4, 1)],
   [(5, 1)],
   [(9, 2)],
   [(10, 2)],
   [(11, 2)],
   [(9, 1), (12, 2), (15, 1)],
   [(10, 1), (13, 2), (16, 1)],
   [(11, 1), (14, 2), (17, 1)],
   [(12, 1), (15, 2)],
   [(13, 1), (16, 2)],
   [(14, 1), (17, 2)],
   [(18, 1)],
   [(19, 1)],
   [(20, 1)],
   [(18, 1), (21, 1), (24, 1)],
   [(19, 1), (22, 1), (25, 1)],
   [(20, 1), (23, 1), (26, 1)],
   [(21, 1), (24, 1)],
   [(22, 1), (25, 1)],
   [(23, 1), (26, 1)]]

def tblF : List (List (Nat × Nat)) :=
  [[],
   [(0, 1), (3, 2), (6, 1)],
   [(1, 1), (4, 2), (7, 1)],
   [(9, 2), (15, 2)],
   [(3, 1), (6, 1), (10, 2), (16, 2)],
   [(4, 1), (7, 1), (11, 2), (17, 2)],
   [(12, 2)],
   [(6, 1), (13, 2)],
   [(7, 1), (14, 2)],
   [(18, 1)],
   [(9, 1), (12, 2), (15, 1), (19, 1)],
   [(10, 1), (13, 2), (16, 1), (20, 1)],
   [(18, 1), (21, 1), (24, 1)],
   [(12, 1), (15, 1), (19, 1), (22, 1), (25, 1)],
   [(13, 1), (16, 1), (20, 1), (23, 1), (26, 1)],
   [(21, 1), (24, 1)],
   [(15, 1), (22, 1), (25, 1)],
   [(16, 1), (23, 1), (26, 1)],
   [],
   [(18, 1), (21, 2), (24, 1)],
   [(19, 1), (22, 2), (25, 1)],
   [],
   [(21, 1), (24, 1)],
   [(22, 1), (25, 1)],
   [],
   [(24, 1)],
   [(25, 1)]]

def tblRE : List (List (Nat × Nat)) :=
  [[],
   [(2, 1)],
   [],
   [(1, 2), (7, 2)],
   [(2, 1), (5, 1), (8, 1)],
   [],
   [(4, 2)],
   [(5, 1), (8, 1)],
   [],
   [(0, 1), (3, 2), (6, 1)],
   [(1, 1), (4, 2), (7, 1), (11, 1)],
   [(2, 1), (5, 2), (8, 1)],
   [(3, 1), (6, 1), (10, 2), (16, 2)],
   [(4, 1), (7, 1), (11, 1), (14, 1), (17, 1)],
   [(5, 1), (8, 1)],
   [(6, 1), (13, 2)],
   [(7, 1), (14, 1), (17, 1)],
   [(8, 1)],
   [(9, 1), (12, 2), (15, 1)],
   [(10, 1), (13, 2), (16, 1), (20, 1)],
   [(11, 1), (14, 2), (17, 1)],
   [(12, 1), (15, 1), (19, 2), (25, 2)],
   [(13, 1), (16, 1), (20, 1), (23, 1), (26, 1)],
   [(14, 1), (17, 1)],
   [(15, 1), (22, 2)],
   [(16, 1), (23, 1), (26, 1)],
   [(17, 1)]]

def tblRH : List (List (Nat × Nat)) :=
  [[],
   [(1, 2)],
   [(2, 1)],
   [(0, 1), (6, 1)],
   [(1, 1), (4, 2), (7, 1)],
   [(2, 1), (5, 1), (8, 1)],
   [(3, 1)],
   [(4, 1), (7, 2)],
   [(5, 1), (8, 1)],
   [],
   [(10, 2)],
   [(11, 1)],
   [(9, 1), (15, 1)],
   [(10, 1), (13, 2), (16, 1)],
   [(11, 1), (14, 1), (17, 1)],
   [(12, 1)],
   [(13, 1), (16, 2)],
   [(14, 1), (17, 1)],
   [],
   [(19, 2)],
   [(20, 1)],
   [(18, 1), (24, 1)],
   [(19, 1), (22, 2), (25, 1)],
   [(20, 1), (23, 1), (26, 1)],
   [(21, 1)],
   [(22, 1), (25, 2)],
   [(23, 1), (26, 1)]]

def tblRF : List (List (Nat × Nat)) :=
  [[],
   [(0, 1)],
   [(1, 1)],
   [],
   [(3, 1)],
   [(4, 1)],
   [],
   [(6, 1)],
   [(7, 1)],
   [],
   [(9, 1)],
   [(10, 1)],
   [],
   [(12, 1)],
   [(13, 1)],
   [],
   [(15, 1)],
   [(16, 1)],
   [],
   [(18, 1)],
   [(19, 1)],
   [],
   [(21, 1)],
   [(22, 1)],
   [],
   [(24, 1)],
   [(25, 1)]]


/-- Left multiplication by `e`, `h`, `f` on `u(sl₂)` (PBW basis). -/
def opE : V → V := Op tblE
def opH : V → V := Op tblH
def opF : V → V := Op tblF
/-- Right multiplication by `e`, `h`, `f` on `u(sl₂)` (PBW basis). -/
def opRE : V → V := Op tblRE
def opRH : V → V := Op tblRH
def opRF : V → V := Op tblRF

/-! ## 5. The algebra `A ⊆ End(V)` generated by `opE, opH, opF` -/

def oid : V → V := fun v => v
def ozero : V → V := fun _ => vzero
def oadd (φ ψ : V → V) : V → V := fun v => vadd (φ v) (ψ v)
def oneg (φ : V → V) : V → V := fun v => vneg (φ v)
def ocomp (φ ψ : V → V) : V → V := fun v => φ (ψ v)
def osmul (c : F3) (φ : V → V) : V → V := fun v => vsmul c (φ v)
def opow (φ : V → V) : Nat → (V → V)
  | 0 => oid
  | n + 1 => ocomp φ (opow φ n)
/-- The commutator `[φ, ψ] = φψ − ψφ`. -/
def bracket (φ ψ : V → V) : V → V := oadd (ocomp φ ψ) (oneg (ocomp ψ φ))

/-- `Gen φ`: `φ` lies in the unital subalgebra of `End(V)` generated by `opE, opH, opF`
(over `𝔽₃`, closure under `+`, `−` and composition is the same as closure under `𝔽₃`-linear
combinations and products). -/
inductive Gen : (V → V) → Prop
  | one : Gen oid
  | genE : Gen opE
  | genH : Gen opH
  | genF : Gen opF
  | add {φ ψ : V → V} : Gen φ → Gen ψ → Gen (oadd φ ψ)
  | neg {φ : V → V} : Gen φ → Gen (oneg φ)
  | comp {φ ψ : V → V} : Gen φ → Gen ψ → Gen (ocomp φ ψ)

theorem vadd_add_add_comm (a b c d : V) :
    vadd (vadd a b) (vadd c d) = vadd (vadd a c) (vadd b d) := by
  funext k
  show a k + b k + (c k + d k) = a k + c k + (b k + d k)
  cases a k <;> cases b k <;> cases c k <;> cases d k <;> decide

theorem Gen.additive {φ : V → V} (h : Gen φ) : Additive φ := by
  induction h with
  | one => intro v w; rfl
  | genE => exact Op_additive _
  | genH => exact Op_additive _
  | genF => exact Op_additive _
  | add _ _ ih1 ih2 =>
    intro v w
    show vadd _ _ = vadd (vadd _ _) (vadd _ _)
    rw [ih1, ih2, vadd_add_add_comm]
  | neg _ ih =>
    intro v w
    show vneg _ = vadd (vneg _) (vneg _)
    rw [ih, vneg_add]
  | comp _ _ ih1 ih2 =>
    intro v w
    show _ = vadd _ _
    simp only [ocomp]
    rw [ih2, ih1]

theorem gen_zero : Gen ozero := by
  have h := Gen.add Gen.one (Gen.neg Gen.one)
  have heq : oadd oid (oneg oid) = ozero := by funext v; exact vadd_vneg v
  rwa [heq] at h

theorem gen_smul (c : F3) {φ : V → V} (h : Gen φ) : Gen (osmul c φ) := by
  cases c
  · have heq : osmul F3.z φ = ozero := by funext v; exact vsmul_zero _
    rw [heq]; exact gen_zero
  · have heq : osmul F3.o φ = φ := by funext v; exact vsmul_one _
    rw [heq]; exact h
  · have heq : osmul F3.t φ = oadd φ φ := by funext v; exact vsmul_two _
    rw [heq]; exact Gen.add h h

theorem gen_pow {φ : V → V} (h : Gen φ) : ∀ n, Gen (opow φ n)
  | 0 => Gen.one
  | n + 1 => Gen.comp h (gen_pow h n)

theorem gen_bracket {φ ψ : V → V} (h1 : Gen φ) (h2 : Gen ψ) : Gen (bracket φ ψ) :=
  Gen.add (Gen.comp h1 h2) (Gen.neg (Gen.comp h2 h1))

theorem ozero_additive : Additive ozero := fun _ _ => (vadd_vzero vzero).symm

/-! ### The defining relations of `u(sl₂)` in characteristic `3`

`sl₂ = ⟨e, h, f⟩` with `[h,e] = 2e`, `[h,f] = −2f`, `[e,f] = h` and `p`-map
`e^[3] = 0`, `f^[3] = 0`, `h^[3] = h`; `u(sl₂) = U(sl₂)/(x^3 − x^[3] : x ∈ {e,h,f})`. -/

theorem rel_he : bracket opH opE = oadd opE opE :=
  ext_basis (gen_bracket Gen.genH Gen.genE).additive (Gen.add Gen.genE Gen.genE).additive (by decide +kernel)

theorem rel_hf : bracket opH opF = oneg (oadd opF opF) :=
  ext_basis (gen_bracket Gen.genH Gen.genF).additive (Gen.neg (Gen.add Gen.genF Gen.genF)).additive
    (by decide +kernel)

theorem rel_ef : bracket opE opF = opH :=
  ext_basis (gen_bracket Gen.genE Gen.genF).additive Gen.genH.additive (by decide +kernel)

theorem rel_e3 : opow opE 3 = ozero :=
  ext_basis (gen_pow Gen.genE 3).additive ozero_additive (by decide +kernel)

theorem rel_f3 : opow opF 3 = ozero :=
  ext_basis (gen_pow Gen.genF 3).additive ozero_additive (by decide +kernel)

theorem rel_h3 : opow opH 3 = opH :=
  ext_basis (gen_pow Gen.genH 3).additive Gen.genH.additive (by decide +kernel)

/-- All defining relations of `u(sl₂)` (characteristic `3`) hold in `A`. -/
theorem relations :
    bracket opH opE = oadd opE opE ∧ bracket opH opF = oneg (oadd opF opF) ∧
    bracket opE opF = opH ∧ opow opE 3 = ozero ∧ opow opF 3 = ozero ∧ opow opH 3 = opH :=
  ⟨rel_he, rel_hf, rel_ef, rel_e3, rel_f3, rel_h3⟩

/-! ### `A` has exactly `3^27` elements: evaluation at `1` is a bijection `A → V` -/

/-- The PBW monomial `e^a h^b f^c` (`i = 9a + 3b + c`) as an element of `A`. -/
def mono (i : Nat) : V → V :=
  ocomp (opow opE (i / 9)) (ocomp (opow opH (i / 3 % 3)) (opow opF (i % 3)))

theorem gen_mono (i : Nat) : Gen (mono i) :=
  Gen.comp (gen_pow Gen.genE _) (Gen.comp (gen_pow Gen.genH _) (gen_pow Gen.genF _))

/-- `e^a h^b f^c · 1 = bv (9a+3b+c)`: the PBW monomials map onto the basis of `V`. -/
theorem mono_one : ∀ i, i < 27 → mono i (bv 0) = bv i := by decide +kernel

def osum : Nat → (Nat → V → V) → V → V
  | 0, _ => ozero
  | n + 1, g => oadd (osum n g) (g n)

theorem gen_osum (g : Nat → V → V) (hg : ∀ i, Gen (g i)) : ∀ n, Gen (osum n g)
  | 0 => gen_zero
  | n + 1 => Gen.add (gen_osum g hg n) (hg n)

theorem osum_apply (g : Nat → V → V) (w : V) : ∀ n, osum n g w = vsum n (fun i => g i w)
  | 0 => rfl
  | n + 1 => by
    show vadd (osum n g w) (g n w) = vadd (vsum n (fun i => g i w)) (g n w)
    rw [osum_apply g w n]

theorem ev_surj (v : V) : ∃ φ, Gen φ ∧ φ (bv 0) = v := by
  refine ⟨osum 27 (fun i => osmul (get v i) (mono i)),
    gen_osum _ (fun i => gen_smul _ (gen_mono i)) 27, ?_⟩
  rw [osum_apply]
  calc vsum 27 (fun i => osmul (get v i) (mono i) (bv 0))
      = vsum 27 (fun i => vsmul (get v i) (bv i)) := by
        apply vsum_congr; intro i hi
        show vsmul (get v i) (mono i (bv 0)) = _
        rw [mono_one i hi]
    _ = v := (decomp v).symm

theorem additive_comp {φ ψ : V → V} (h1 : Additive φ) (h2 : Additive ψ) :
    Additive (ocomp φ ψ) := by
  intro v w; show φ (ψ _) = vadd (φ (ψ v)) (φ (ψ w)); rw [h2, h1]

/-- Right multiplications commute with left multiplications by the generators
(associativity of `u(sl₂)` on the generators). -/
theorem comm_left_right :
    ocomp opE opRE = ocomp opRE opE ∧ ocomp opE opRH = ocomp opRH opE ∧
    ocomp opE opRF = ocomp opRF opE ∧ ocomp opH opRE = ocomp opRE opH ∧
    ocomp opH opRH = ocomp opRH opH ∧ ocomp opH opRF = ocomp opRF opH ∧
    ocomp opF opRE = ocomp opRE opF ∧ ocomp opF opRH = ocomp opRH opF ∧
    ocomp opF opRF = ocomp opRF opF := by
  have A := Op_additive
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
    exact ext_basis (additive_comp (A _) (A _)) (additive_comp (A _) (A _)) (by decide +kernel)

/-- Every element of `A` commutes with an additive `R` commuting with `opE, opH, opF`. -/
theorem Gen.comm {R : V → V} (hR : Additive R) (hE : ocomp opE R = ocomp R opE)
    (hH : ocomp opH R = ocomp R opH) (hF : ocomp opF R = ocomp R opF) {φ : V → V}
    (h : Gen φ) : ocomp φ R = ocomp R φ := by
  induction h with
  | one => rfl
  | genE => exact hE
  | genH => exact hH
  | genF => exact hF
  | add _ _ ih1 ih2 =>
    funext v
    show vadd _ _ = R (vadd _ _)
    have h1 := congrFun ih1 v
    have h2 := congrFun ih2 v
    simp only [ocomp] at h1 h2
    rw [hR, h1, h2]
  | neg _ ih =>
    funext v
    show vneg _ = R (vneg _)
    have h1 := congrFun ih v
    simp only [ocomp] at h1
    rw [hR.map_neg, h1]
  | @comp φ ψ _ _ ih1 ih2 =>
    funext v
    show φ (ψ (R v)) = R (φ (ψ v))
    have h2 := congrFun ih2 v
    have h1 := congrFun ih1 (ψ v)
    simp only [ocomp] at h1 h2
    rw [h2, h1]

theorem comm_pow {φ R : V → V} (h : ocomp φ R = ocomp R φ) (w : V) :
    ∀ n, φ (opow R n w) = opow R n (φ w)
  | 0 => rfl
  | n + 1 => by
    show φ (R (opow R n w)) = R (opow R n (φ w))
    rw [← comm_pow h w n]; exact congrFun h _

/-- `bv (9a+3b+c) = ((1 · e^a) · h^b) · f^c`. -/
theorem rword : ∀ i, i < 27 →
    opow opRF (i % 3) (opow opRH (i / 3 % 3) (opow opRE (i / 9) (bv 0))) = bv i := by
  decide +kernel

theorem ev_inj {φ ψ : V → V} (h1 : Gen φ) (h2 : Gen ψ) (h : φ (bv 0) = ψ (bv 0)) : φ = ψ := by
  obtain ⟨c1, c2, c3, c4, c5, c6, c7, c8, c9⟩ := comm_left_right
  have aRE : Additive opRE := Op_additive _
  have aRH : Additive opRH := Op_additive _
  have aRF : Additive opRF := Op_additive _
  apply ext_basis h1.additive h2.additive
  intro i hi
  rw [← rword i hi]
  have tr : ∀ χ, Gen χ → χ (opow opRF (i % 3) (opow opRH (i / 3 % 3) (opow opRE (i / 9) (bv 0))))
      = opow opRF (i % 3) (opow opRH (i / 3 % 3) (opow opRE (i / 9) (χ (bv 0)))) := by
    intro χ hχ
    rw [comm_pow (Gen.comm aRF c3 c6 c9 hχ), comm_pow (Gen.comm aRH c2 c5 c8 hχ),
      comm_pow (Gen.comm aRE c1 c4 c7 hχ)]
  rw [tr φ h1, tr ψ h2, h]

/-- **`|A| = 3^27`.** Evaluation at `1 = bv 0` is a bijection from `A` onto `V = 𝔽₃^27`. -/
theorem ev_bijective : ∀ v : V, ∃ φ, Gen φ ∧ φ (bv 0) = v ∧ ∀ ψ, Gen ψ → ψ (bv 0) = v → ψ = φ := by
  intro v
  obtain ⟨φ, hφ, hv⟩ := ev_surj v
  exact ⟨φ, hφ, hv, fun ψ hψ hψv => ev_inj hψ hφ (hψv.trans hv.symm)⟩

/-! ## 6. Commutative rings, prime ideals and Krull dimension (from scratch) -/

/-- A commutative ring structure on a type `R`. -/
structure CRing (R : Type) where
  zero : R
  one : R
  add : R → R → R
  neg : R → R
  mul : R → R → R
  add_assoc : ∀ a b c, add (add a b) c = add a (add b c)
  add_comm : ∀ a b, add a b = add b a
  zero_add : ∀ a, add zero a = a
  neg_add : ∀ a, add (neg a) a = zero
  mul_assoc : ∀ a b c, mul (mul a b) c = mul a (mul b c)
  mul_comm : ∀ a b, mul a b = mul b a
  one_mul : ∀ a, mul one a = a
  mul_add : ∀ a b c, mul a (add b c) = add (mul a b) (mul a c)

namespace CRing

variable {R : Type} (S : CRing R)

/-- `I` is an ideal. -/
def IsIdeal (I : R → Prop) : Prop :=
  I S.zero ∧ (∀ a b, I a → I b → I (S.add a b)) ∧ (∀ r a, I a → I (S.mul r a))

/-- `P` is a prime ideal: a proper ideal with `ab ∈ P → a ∈ P ∨ b ∈ P`. -/
def IsPrime (P : R → Prop) : Prop :=
  S.IsIdeal P ∧ ¬ P S.one ∧ ∀ a b, P (S.mul a b) → P a ∨ P b

/-- Strict inclusion `P ⊊ Q`. -/
def SSub {R : Type} (P Q : R → Prop) : Prop := (∀ x, P x → Q x) ∧ ∃ x, Q x ∧ ¬ P x

/-- There is a chain `P₀ ⊊ P₁ ⊊ ⋯ ⊊ P_k` of prime ideals (of length `k`). -/
def HasChain (k : Nat) : Prop :=
  ∃ P : Nat → R → Prop, (∀ i, i ≤ k → S.IsPrime (P i)) ∧ ∀ i, i < k → SSub (P i) (P (i + 1))

/-- `Krull dim = d`: the supremum of the lengths of chains of prime ideals is `d`. -/
def KrullDimIs (d : Nat) : Prop := S.HasChain d ∧ ∀ k, S.HasChain k → k ≤ d

/-- `R` is finite: it injects into a type in which its image is covered by a finite list. -/
def Finite {R : Type} (_S : CRing R) : Prop :=
  ∃ (β : Type) (l : List β) (enc : R → β), (∀ a b, enc a = enc b → a = b) ∧ ∀ a, enc a ∈ l

def pow (x : R) : Nat → R
  | 0 => S.one
  | n + 1 => S.mul x (pow x n)

theorem add_zero (a : R) : S.add a S.zero = a := by rw [S.add_comm, S.zero_add]

theorem add_neg (a : R) : S.add a (S.neg a) = S.zero := by rw [S.add_comm, S.neg_add]

theorem add_left_cancel {a b c : R} (h : S.add a b = S.add a c) : b = c := by
  have h' := congrArg (S.add (S.neg a)) h
  rwa [← S.add_assoc, ← S.add_assoc, S.neg_add, S.zero_add, S.zero_add] at h'

theorem mul_zero (a : R) : S.mul a S.zero = S.zero := by
  have h : S.add (S.mul a S.zero) (S.mul a S.zero) = S.add (S.mul a S.zero) S.zero := by
    rw [← S.mul_add, S.zero_add, S.add_zero]
  exact S.add_left_cancel h

theorem mul_one (a : R) : S.mul a S.one = a := by rw [S.mul_comm, S.one_mul]

theorem pow_add (x : R) : ∀ m n, S.pow x (m + n) = S.mul (S.pow x m) (S.pow x n)
  | 0, n => by rw [Nat.zero_add]; exact (S.one_mul _).symm
  | m + 1, n => by
    rw [Nat.succ_add]
    show S.mul x (S.pow x (m + n)) = S.mul (S.mul x (S.pow x m)) (S.pow x n)
    rw [pow_add x m n, S.mul_assoc]

/-- Pigeonhole principle for an infinite sequence in a finite list. -/
theorem pigeon {β : Type} : ∀ (l : List β) (s : Nat → β), (∀ n, s n ∈ l) →
    ∃ i j, i < j ∧ s i = s j
  | [], s, h => absurd (h 0) List.not_mem_nil
  | a :: l, s, h => by
    by_cases hA : ∃ i, s i = a
    · obtain ⟨i, hi⟩ := hA
      by_cases hB : ∃ j, i < j ∧ s j = a
      · obtain ⟨j, hj, hj'⟩ := hB
        exact ⟨i, j, hj, hi.trans hj'.symm⟩
      · have hl : ∀ n, s (n + i + 1) ∈ l := by
          intro n
          rcases List.mem_cons.mp (h (n + i + 1)) with h1 | h1
          · exact absurd ⟨n + i + 1, by omega, h1⟩ hB
          · exact h1
        obtain ⟨i', j', hij, he⟩ := pigeon l (fun n => s (n + i + 1)) hl
        exact ⟨i' + i + 1, j' + i + 1, by omega, he⟩
    · have hl : ∀ n, s n ∈ l := by
        intro n
        rcases List.mem_cons.mp (h n) with h1 | h1
        · exact absurd ⟨n, h1⟩ hA
        · exact h1
      exact pigeon l s hl

/-- In a finite ring every element has an idempotent power `x^n`, `n ≥ 1`. -/
theorem idempotent_power (hfin : S.Finite) (x : R) :
    ∃ n, 1 ≤ n ∧ S.pow x (n + n) = S.pow x n := by
  obtain ⟨β, l, enc, inj, mem⟩ := hfin
  obtain ⟨i, j, hij, he⟩ := pigeon l (fun k => enc (S.pow x k)) (fun k => mem _)
  have hxij : S.pow x i = S.pow x j := inj _ _ he
  obtain ⟨d, rfl⟩ : ∃ d, j = i + d := ⟨j - i, by omega⟩
  have hd : 1 ≤ d := by omega
  -- period `d` from `i` on
  have per : ∀ t, S.pow x (i + t + d) = S.pow x (i + t) := by
    intro t
    rw [show i + t + d = t + (i + d) by omega, S.pow_add, ← hxij, ← S.pow_add,
      show t + i = i + t by omega]
  have perm : ∀ t m, S.pow x (i + t + d * m) = S.pow x (i + t) := by
    intro t m
    induction m with
    | zero => rfl
    | succ m ih =>
      rw [show i + t + d * (m + 1) = i + (t + d * m) + d by rw [Nat.mul_succ]; omega, per,
        show i + (t + d * m) = i + t + d * m by omega, ih]
  have hn : i + 1 ≤ d * (i + 1) := Nat.le_mul_of_pos_left _ hd
  refine ⟨d * (i + 1), by omega, ?_⟩
  generalize hN : d * (i + 1) = N at hn
  have := perm (N - i) (i + 1)
  rw [hN, show i + (N - i) = N by omega] at this
  rw [show N + N = N + N by rfl]
  exact this

theorem pow_mem_of_mem {I : R → Prop} (hI : S.IsIdeal I) {x : R} (hx : I x) :
    ∀ n, 1 ≤ n → I (S.pow x n)
  | 0, h => absurd h (by decide)
  | n + 1, _ => by
    show I (S.mul x (S.pow x n))
    rw [S.mul_comm]; exact hI.2.2 _ _ hx

theorem mem_of_pow_mem {P : R → Prop} (hP : S.IsPrime P) {x : R} :
    ∀ n, P (S.pow x n) → P x
  | 0, h => absurd h hP.2.1
  | n + 1, h => (hP.2.2 _ _ h).elim id (mem_of_pow_mem hP n)

/-- **In a finite commutative ring every prime ideal is maximal among primes**:
`P ⊆ Q` primes implies `Q ⊆ P`. -/
theorem primes_incomparable (hfin : S.Finite) {P Q : R → Prop} (hP : S.IsPrime P)
    (hQ : S.IsPrime Q) (hPQ : ∀ x, P x → Q x) : ∀ x, Q x → P x := by
  intro x hx
  obtain ⟨n, hn, hidem⟩ := S.idempotent_power hfin x
  -- `y = x^n` is idempotent, `y (1 − y) = 0`
  have hyy : S.mul (S.pow x n) (S.pow x n) = S.pow x n := by rw [← S.pow_add, hidem]
  have hy0 : S.mul (S.pow x n) (S.add S.one (S.neg (S.pow x n))) = S.zero := by
    rw [S.mul_add, S.mul_one]
    have h1 : S.add (S.mul (S.pow x n) (S.neg (S.pow x n))) (S.pow x n) = S.zero := by
      conv => lhs; rhs; rw [← hyy]
      rw [← S.mul_add, S.neg_add, S.mul_zero]
    rw [S.add_comm]; exact h1
  have hP0 : P (S.mul (S.pow x n) (S.add S.one (S.neg (S.pow x n)))) := hy0 ▸ hP.1.1
  rcases hP.2.2 _ _ hP0 with hy | h1y
  · exact S.mem_of_pow_mem hP n hy
  · exfalso
    apply hQ.2.1
    have hsum : S.add (S.pow x n) (S.add S.one (S.neg (S.pow x n))) = S.one := by
      rw [← S.add_assoc, S.add_comm (S.pow x n) S.one, S.add_assoc, S.add_neg, S.add_zero]
    rw [← hsum]
    exact hQ.1.2.1 _ _ (S.pow_mem_of_mem hQ.1 hx n hn) (hPQ _ h1y)

/-- A finite commutative ring has no chain of primes of length `k ≥ 1`. -/
theorem no_chain (hfin : S.Finite) : ∀ k, 1 ≤ k → ¬ S.HasChain k := by
  intro k hk ⟨P, hprime, hss⟩
  obtain ⟨hsub, x, hx1, hx0⟩ := hss 0 hk
  exact hx0 (S.primes_incomparable hfin (hprime 0 (by omega)) (hprime 1 hk) hsub x hx1)

/-- **A finite commutative ring with a prime ideal has Krull dimension `0`.** -/
theorem finite_krullDim_zero (hfin : S.Finite) (hP : ∃ P, S.IsPrime P) : S.KrullDimIs 0 := by
  obtain ⟨P, hP⟩ := hP
  refine ⟨⟨fun _ => P, fun _ _ => hP, fun i hi => absurd hi (Nat.not_lt_zero _)⟩, ?_⟩
  intro k hk
  by_cases h : k = 0
  · omega
  · exact absurd hk (S.no_chain hfin k (by omega))

/-- The Krull dimension of a finite commutative ring is never `d ≥ 1`. -/
theorem finite_krullDim_ne (hfin : S.Finite) : ∀ d, 1 ≤ d → ¬ S.KrullDimIs d :=
  fun d hd h => S.no_chain hfin d hd h.1

end CRing

/-! ## 7. The centre `Z(u(sl₂))` as a commutative ring -/

/-- `φ` is central in `A`. -/
def IsCentral (φ : V → V) : Prop := Gen φ ∧ ∀ ψ, Gen ψ → ocomp φ ψ = ocomp ψ φ

/-- The centre `Z(A) = Z(u(sl₂))`. -/
structure ZU where
  val : V → V
  central : IsCentral val

theorem ZU.ext' {a b : ZU} (h : a.val = b.val) : a = b := by
  cases a; cases b; cases h; rfl

theorem ZU.comm_apply (a : ZU) {ψ : V → V} (hψ : Gen ψ) (v : V) : a.val (ψ v) = ψ (a.val v) :=
  congrFun (a.central.2 ψ hψ) v

def ZU.zero : ZU := ⟨ozero, gen_zero, fun ψ hψ => by
  funext v; exact (hψ.additive.map_zero).symm⟩

def ZU.one : ZU := ⟨oid, Gen.one, fun _ _ => rfl⟩

def ZU.add (a b : ZU) : ZU := ⟨oadd a.val b.val, Gen.add a.central.1 b.central.1, fun ψ hψ => by
  funext v
  show vadd (a.val (ψ v)) (b.val (ψ v)) = ψ (vadd (a.val v) (b.val v))
  rw [hψ.additive, a.comm_apply hψ, b.comm_apply hψ]⟩

def ZU.neg (a : ZU) : ZU := ⟨oneg a.val, Gen.neg a.central.1, fun ψ hψ => by
  funext v
  show vneg (a.val (ψ v)) = ψ (vneg (a.val v))
  rw [hψ.additive.map_neg, a.comm_apply hψ]⟩

def ZU.mul (a b : ZU) : ZU := ⟨ocomp a.val b.val, Gen.comp a.central.1 b.central.1, fun ψ hψ => by
  funext v
  show a.val (b.val (ψ v)) = ψ (a.val (b.val v))
  rw [b.comm_apply hψ, a.comm_apply hψ]⟩

/-- The commutative ring `Z(u(sl₂))`. -/
def ZRing : CRing ZU where
  zero := ZU.zero
  one := ZU.one
  add := ZU.add
  neg := ZU.neg
  mul := ZU.mul
  add_assoc _ _ _ := ZU.ext' (funext fun _ => vadd_assoc _ _ _)
  add_comm _ _ := ZU.ext' (funext fun _ => vadd_comm _ _)
  zero_add _ := ZU.ext' (funext fun _ => vzero_vadd _)
  neg_add _ := ZU.ext' (funext fun _ => vneg_vadd _)
  mul_assoc _ _ _ := ZU.ext' rfl
  mul_comm a b := ZU.ext' (a.central.2 b.val b.central.1)
  one_mul _ := ZU.ext' rfl
  mul_add a _ _ := ZU.ext' (funext fun _ => a.central.1.additive _ _)

/-! ### `Z(u(sl₂))` is finite -/

def allL : Nat → List (List F3)
  | 0 => [[]]
  | n + 1 => (allL n).flatMap (fun l => [F3.z :: l, F3.o :: l, F3.t :: l])

theorem mem_allL : ∀ l : List F3, l ∈ allL l.length
  | [] => by simp [allL]
  | a :: l => by
    simp only [List.length_cons, allL, List.mem_flatMap]
    exact ⟨l, mem_allL l, by cases a <;> simp⟩

/-- Coordinates of `z · 1`. -/
def enc (z : ZU) : List F3 := (List.range 27).map (get (z.val (bv 0)))

theorem ZRing_finite : ZRing.Finite := by
  refine ⟨List F3, allL 27, enc, fun a b h => ?_, fun a => ?_⟩
  · have h1 := List.map_inj_left.mp h
    have h2 : a.val (bv 0) = b.val (bv 0) :=
      ext_get (fun k hk => h1 k (List.mem_range.mpr hk))
    exact ZU.ext' (ev_inj a.central.1 b.central.1 h2)
  · have := mem_allL (enc a)
    rwa [show (enc a).length = 27 by simp [enc]] at this

/-! ### A prime ideal of `Z(u(sl₂))`: the kernel of the trivial character -/

def i0 : Fin 27 := ⟨0, by decide⟩

/-- `χ(φ)` = the coefficient of `1` in `φ · 1` (the counit). -/
def chi (φ : V → V) : F3 := φ (bv 0) i0

theorem gen_chi {φ : V → V} (h : Gen φ) : ∀ w, φ w i0 = chi φ * w i0 := by
  induction h with
  | one => intro w; exact (F3.one_mul _).symm
  | genE => intro w; exact (F3.zero_mul _).symm
  | genH => intro w; exact (F3.zero_mul _).symm
  | genF => intro w; exact (F3.zero_mul _).symm
  | @add φ ψ _ _ ih1 ih2 =>
    intro w
    show φ w i0 + ψ w i0 = (φ (bv 0) i0 + ψ (bv 0) i0) * w i0
    rw [ih1, ih2, F3.add_mul]; rfl
  | @neg φ _ ih =>
    intro w
    show -(φ w i0) = -(φ (bv 0) i0) * w i0
    rw [ih, F3.mul_comm (-(φ (bv 0) i0)), ← F3.neg_mul, F3.mul_comm]; rfl
  | @comp φ ψ _ _ ih1 ih2 =>
    intro w
    show φ (ψ w) i0 = φ (ψ (bv 0)) i0 * w i0
    rw [ih1, ih1 (ψ (bv 0)), ih2, ih2 (bv 0)]
    show chi φ * (chi ψ * w i0) = chi φ * (chi ψ * 1) * w i0
    rw [F3.mul_one, F3.mul_assoc]

theorem chi_mul (a b : ZU) : chi (ZRing.mul a b).val = chi a.val * chi b.val :=
  gen_chi a.central.1 _

/-- The prime ideal `P₀ = {z ∈ Z : χ(z) = 0}`. -/
def P0 (z : ZU) : Prop := chi z.val = 0

theorem P0_prime : ZRing.IsPrime P0 := by
  refine ⟨⟨rfl, fun a b ha hb => ?_, fun r a ha => ?_⟩, ?_, fun a b hab => ?_⟩
  · show chi a.val + chi b.val = 0
    rw [ha, hb]; rfl
  · show chi (ZRing.mul r a).val = 0
    rw [chi_mul, show chi a.val = 0 from ha, F3.mul_zero]
  · exact F3.one_ne_zero
  · have := chi_mul a b
    rw [show chi (ZRing.mul a b).val = 0 from hab] at this
    exact F3.mul_eq_zero _ _ this.symm

/-! ## 8. Main results -/

/-- **The Krull dimension of `Z(u(sl₂))` (characteristic `3`) is `0`.** -/
theorem krullDim_center : ZRing.KrullDimIs 0 :=
  ZRing.finite_krullDim_zero ZRing_finite ⟨P0, P0_prime⟩

/-- No chain `P ⊊ Q` of prime ideals in `Z(u(sl₂))`. -/
theorem no_prime_chain : ∀ k, 1 ≤ k → ¬ ZRing.HasChain k := ZRing.no_chain ZRing_finite

/-- The first clause of the conjecture for `n = 2`: `Krull dim Z(u(sl_n)) = n − 1`. -/
def Clause (n : Nat) : Prop := ZRing.KrullDimIs (n - 1)

/-- **Conjecture 00000001141 is false** (its first clause fails for `n = 2`, `p = 3`). -/
theorem conjecture_00000001141_false : ¬ Clause 2 :=
  ZRing.finite_krullDim_ne ZRing_finite 1 (Nat.le_refl 1)

/-- The Krull dimension of `Z(u(sl₂))` is not any positive integer. -/
theorem krullDim_center_ne : ∀ d, 1 ≤ d → ¬ ZRing.KrullDimIs d :=
  ZRing.finite_krullDim_ne ZRing_finite

/-- The general mechanism, for every `n ≥ 2`: the centre of a finite-dimensional algebra over a
finite field (such as `u(sl_n)`, of dimension `p^(n²−1)`) is a finite commutative ring, and no
finite commutative ring has Krull dimension `n − 1 ≥ 1`. -/
theorem clause_fails_for_finite_rings {R : Type} (S : CRing R) (hfin : S.Finite) :
    ∀ n, 2 ≤ n → ¬ S.KrullDimIs (n - 1) :=
  fun n hn => S.finite_krullDim_ne hfin (n - 1) (by omega)

/-! ## 9. The second clause: `dim Z(u(sl₂)) ≠ rank sl₂ = 1`

The Casimir element `C = ef + fe + h²/2 = ef + fe + 2h²` is central, and `1, C` are linearly
independent, so `Z(u(sl₂))` is not one-dimensional (its Krull dimension `0` is not `1` either). -/

def casimir : V → V :=
  oadd (oadd (ocomp opE opF) (ocomp opF opE)) (oadd (ocomp opH opH) (ocomp opH opH))

theorem gen_casimir : Gen casimir :=
  Gen.add (Gen.add (Gen.comp Gen.genE Gen.genF) (Gen.comp Gen.genF Gen.genE))
    (Gen.add (Gen.comp Gen.genH Gen.genH) (Gen.comp Gen.genH Gen.genH))

theorem central_of_gens {φ : V → V} (hφ : Gen φ) (hE : ocomp φ opE = ocomp opE φ)
    (hH : ocomp φ opH = ocomp opH φ) (hF : ocomp φ opF = ocomp opF φ) : IsCentral φ := by
  refine ⟨hφ, fun ψ hψ => ?_⟩
  induction hψ with
  | one => rfl
  | genE => exact hE
  | genH => exact hH
  | genF => exact hF
  | @add ψ1 ψ2 _ _ ih1 ih2 =>
    funext v
    show φ (vadd (ψ1 v) (ψ2 v)) = vadd (ψ1 (φ v)) (ψ2 (φ v))
    have h1 := congrFun ih1 v
    have h2 := congrFun ih2 v
    simp only [ocomp] at h1 h2
    rw [hφ.additive, h1, h2]
  | @neg ψ1 _ ih =>
    funext v
    show φ (vneg (ψ1 v)) = vneg (ψ1 (φ v))
    have h1 := congrFun ih v
    simp only [ocomp] at h1
    rw [hφ.additive.map_neg, h1]
  | @comp ψ1 ψ2 _ _ ih1 ih2 =>
    funext v
    show φ (ψ1 (ψ2 v)) = ψ1 (ψ2 (φ v))
    have h1 := congrFun ih1 (ψ2 v)
    have h2 := congrFun ih2 v
    simp only [ocomp] at h1 h2
    rw [h1, h2]

theorem casimir_central : IsCentral casimir := by
  have a := gen_casimir.additive
  refine central_of_gens gen_casimir ?_ ?_ ?_ <;>
    exact ext_basis (additive_comp a (Op_additive _)) (additive_comp (Op_additive _) a)
      (by decide +kernel)

def casZ : ZU := ⟨casimir, casimir_central⟩

theorem casimir_not_scalar : ∀ c : F3, casimir (bv 0) ≠ vsmul c (bv 0) := by
  intro c; cases c <;> decide +kernel

/-- **`Z(u(sl₂))` is not one-dimensional over `𝔽₃`** (so its dimension is not
`rank sl₂ = 1`). -/
theorem center_not_rank_dim :
    ¬ ∃ z : ZU, ∀ y : ZU, ∃ c : F3, ∀ v, y.val v = vsmul c (z.val v) := by
  rintro ⟨z, hz⟩
  obtain ⟨a, ha⟩ := hz ZU.one
  obtain ⟨b, hb⟩ := hz casZ
  have key : ∃ a' : F3, ∀ v, z.val v = vsmul a' v := by
    cases a with
    | z =>
      have h := congrFun (ha (bv 0)) i0
      exact absurd h (by show (1 : F3) ≠ 0 * _; rw [F3.zero_mul]; decide)
    | o =>
      refine ⟨F3.o, fun v => ?_⟩
      have h := ha v
      funext k
      have hk : v k = F3.o * z.val v k := congrFun h k
      show z.val v k = F3.o * v k
      rw [hk, ← F3.mul_assoc]; exact (F3.one_mul _).symm
    | t =>
      refine ⟨F3.t, fun v => ?_⟩
      have h := ha v
      funext k
      have hk : v k = F3.t * z.val v k := congrFun h k
      show z.val v k = F3.t * v k
      rw [hk, ← F3.mul_assoc]; exact (F3.one_mul _).symm
  obtain ⟨a', ha'⟩ := key
  apply casimir_not_scalar (b * a')
  have h := hb (bv 0)
  rw [ha'] at h
  rw [show casimir (bv 0) = casZ.val (bv 0) from rfl, h]
  funext k; exact (F3.mul_assoc _ _ _).symm

end RestrictedSL2

#print axioms RestrictedSL2.relations
#print axioms RestrictedSL2.ev_bijective
#print axioms RestrictedSL2.CRing.finite_krullDim_zero
#print axioms RestrictedSL2.krullDim_center
#print axioms RestrictedSL2.no_prime_chain
#print axioms RestrictedSL2.conjecture_00000001141_false
#print axioms RestrictedSL2.krullDim_center_ne
#print axioms RestrictedSL2.clause_fails_for_finite_rings
#print axioms RestrictedSL2.center_not_rank_dim
