import Mathlib

/-!
# Conjecture 00000000543 is false

The conjecture asserts: for a hyperplane arrangement `A` with matroid `M(A)`, the depth of the
Orlik–Terao algebra `OT(A)` equals `rank M(A) - 1 - β(M(A))`, where `β` is Crapo's beta invariant.

We refute it with the arrangement of the three lines `x = 0`, `y = 0`, `x + y = 0` in `k²`
(`k` any field of characteristic zero, e.g. `ℚ`): its matroid is `U_{2,3}`, of rank `2` with
`β = 1`, so the formula predicts depth `0`; but `1/x` is a regular element of the irrelevant
ideal of `OT(A)`, so the depth is at least `1`.

A second witness, the four lines `x, y, x + y, x + 2y` (matroid `U_{2,4}`, rank `2`, `β = 2`),
gives `rank - 1 - β = -1`, which no depth (an element of `ℕ ∪ {∞}`) can equal.

Conventions.
* An arrangement of `m` hyperplanes in `kⁿ` is given by coefficient vectors `v i : Fin n → k`;
  the defining linear form of the `i`-th hyperplane is `α_i = ∑_j v_i(j) x_j`.
* `OT(A)` is the `k`-subalgebra of the field of rational functions
  `k(x_1,…,x_n) = FractionRing k[x_1,…,x_n]` generated by the reciprocals `1/α_i`.
  It is graded with each `1/α_i` in degree one; since it is generated in degree one, its
  irrelevant (homogeneous maximal) ideal is the ideal generated by the `1/α_i`.
* `depth OT(A)` is the depth with respect to that ideal: the supremum (in `ℕ∞`) of the lengths
  of `OT(A)`-regular sequences of elements of the irrelevant ideal, where "regular" is Mathlib's
  `RingTheory.Sequence.IsRegular` (each element is a nonzerodivisor modulo the previous ones,
  and the quotient by all of them is nonzero). Same pattern as package C537.
* The rank function of the matroid is `r(S) = dim_k span {v_i : i ∈ S}`; the rank of the matroid
  is `r(E)`, and Crapo's beta invariant is `β = (-1)^{r(E)} ∑_{S ⊆ E} (-1)^{|S|} r(S)`.
-/

open MvPolynomial RingTheory.Sequence
open LaurentPolynomial (T isUnit_T T_add)

local notation "LC" => LaurentPolynomial.C

namespace C543

variable {k : Type*} [Field k]

section Defs

variable {m n : ℕ} (v : Fin m → Fin n → k)

/-- The defining linear form `α_i = ∑_j v_i(j) x_j` of the `i`-th hyperplane. -/
noncomputable def α (i : Fin m) : MvPolynomial (Fin n) k := ∑ j, C (v i j) * X j

/-- The reciprocal `1/α_i`, a rational function in `k(x_1, …, x_n)`. -/
noncomputable def y (i : Fin m) : FractionRing (MvPolynomial (Fin n) k) :=
  (algebraMap (MvPolynomial (Fin n) k) (FractionRing (MvPolynomial (Fin n) k)) (α v i))⁻¹

/-- The Orlik–Terao algebra `OT(A)`: the `k`-subalgebra of `k(x_1, …, x_n)` generated by the
reciprocals `1/α_i` of the defining linear forms. -/
noncomputable def OT : Subalgebra k (FractionRing (MvPolynomial (Fin n) k)) :=
  Algebra.adjoin k (Set.range (y v))

/-- The generator `1/α_i` as an element of `OT(A)`. -/
noncomputable def gen (i : Fin m) : OT v := ⟨y v i, Algebra.subset_adjoin ⟨i, rfl⟩⟩

/-- The irrelevant (homogeneous maximal) ideal of `OT(A)`, generated by the degree-one
generators `1/α_i`. -/
noncomputable def irr : Ideal (OT v) := Ideal.span (Set.range (gen v))

/-- `depth OT(A)`: the supremum of the lengths of `OT(A)`-regular sequences in the irrelevant
ideal. -/
noncomputable def depth : ℕ∞ :=
  ⨆ (rs : List (OT v)) (_ : (∀ r ∈ rs, r ∈ irr v) ∧ IsRegular (OT v) rs), (rs.length : ℕ∞)

/-- The rank function of the matroid of `A`: `r(S) = dim span {v_i : i ∈ S}`. -/
noncomputable def rk (S : Finset (Fin m)) : ℕ :=
  Module.finrank k (Submodule.span k (v '' (S : Set (Fin m))))

/-- Crapo's beta invariant `β = (-1)^{r(E)} ∑_{S ⊆ E} (-1)^{|S|} r(S)`. -/
noncomputable def beta : ℤ :=
  (-1) ^ rk v Finset.univ *
    ∑ S ∈ (Finset.univ : Finset (Fin m)).powerset, (-1) ^ S.card * (rk v S : ℤ)

end Defs

section Lower

variable {m n : ℕ} (v : Fin m → Fin n → k)

local notation "P" => MvPolynomial (Fin n) k
local notation "K" => FractionRing (MvPolynomial (Fin n) k)

theorem α_ne_zero (hc : ∀ i, ∑ j, v i j ≠ 0) (i : Fin m) : α v i ≠ 0 := by
  intro h
  have := congrArg (MvPolynomial.eval (fun _ => (1 : k))) h
  simp [α] at this
  exact hc i this

theorem alg_α_ne_zero (hc : ∀ i, ∑ j, v i j ≠ 0) (i : Fin m) : algebraMap P K (α v i) ≠ 0 :=
  (map_ne_zero_iff _ (IsFractionRing.injective P K)).mpr (α_ne_zero v hc i)

/-- The product `Q = ∏ α_i` of the defining forms. -/
noncomputable def Q : P := ∏ i, α v i

theorem powers_le (hc : ∀ i, ∑ j, v i j ≠ 0) : Submonoid.powers (Q v) ≤ nonZeroDivisors P :=
  powers_le_nonZeroDivisors_of_noZeroDivisors
    (Finset.prod_ne_zero_iff.mpr fun i _ => α_ne_zero v hc i)

/-- The ring `k[x][1/Q] ⊆ k(x)` of rational functions regular off the arrangement. -/
noncomputable abbrev Lsub (hc : ∀ i, ∑ j, v i j ≠ 0) : Subalgebra P K :=
  Localization.subalgebra.ofField K (Submonoid.powers (Q v)) (powers_le v hc)

theorem y_mem (hc : ∀ i, ∑ j, v i j ≠ 0) (i : Fin m) : y v i ∈ Lsub v hc := by
  change ∃ (a s : P) (_ : s ∈ Submonoid.powers (Q v)),
    y v i = algebraMap P K a * (algebraMap P K s)⁻¹
  refine ⟨∏ j ∈ Finset.univ.erase i, α v j, Q v, Submonoid.mem_powers _, ?_⟩
  have h1 := alg_α_ne_zero v hc i
  have h2 : algebraMap P K (∏ j ∈ Finset.univ.erase i, α v j) ≠ 0 :=
    (map_ne_zero_iff _ (IsFractionRing.injective P K)).mpr
      (Finset.prod_ne_zero_iff.mpr fun j _ => α_ne_zero v hc j)
  rw [y, Q, ← Finset.mul_prod_erase Finset.univ (α v) (Finset.mem_univ i), map_mul, mul_inv,
    ← mul_assoc, mul_comm _ (algebraMap P K (α v i))⁻¹, mul_assoc, mul_inv_cancel₀ h2, mul_one]

/-- The specialisation `x_j ↦ T⁻¹` into Laurent polynomials. -/
noncomputable def g : P →+* LaurentPolynomial k :=
  (aeval fun _ : Fin n => (T (-1) : LaurentPolynomial k)).toRingHom

theorem g_α (i : Fin m) : g (α v i) = LC (∑ j, v i j) * T (-1) := by
  simp [g, α, map_sum, Finset.sum_mul, LaurentPolynomial.algebraMap_apply]

theorem g_Q_isUnit (hc : ∀ i, ∑ j, v i j ≠ 0) : IsUnit (g (Q v)) := by
  rw [Q, map_prod, IsUnit.prod_univ_iff]
  intro i
  rw [g_α]
  exact ((isUnit_iff_ne_zero.mpr (hc i)).map LC).mul (isUnit_T _)

/-- The induced map `k[x][1/Q] → k[T, T⁻¹]`. -/
noncomputable def ev (hc : ∀ i, ∑ j, v i j ≠ 0) : Lsub v hc →+* LaurentPolynomial k :=
  IsLocalization.Away.lift (Q v) (g_Q_isUnit v hc)

theorem ev_y (hc : ∀ i, ∑ j, v i j ≠ 0) (i : Fin m) :
    ev v hc ⟨y v i, y_mem v hc i⟩ =
      Polynomial.toLaurent (Polynomial.C (∑ j, v i j)⁻¹ * Polynomial.X) := by
  have h1 : (⟨y v i, y_mem v hc i⟩ : Lsub v hc) * algebraMap P (Lsub v hc) (α v i) = 1 :=
    Subtype.ext (inv_mul_cancel₀ (alg_α_ne_zero v hc i))
  have h2 : ev v hc (⟨y v i, y_mem v hc i⟩ : Lsub v hc) * (LC (∑ j, v i j) * T (-1)) = 1 := by
    have := congrArg (ev v hc) h1
    rwa [map_mul, map_one, show ev v hc (algebraMap P (Lsub v hc) (α v i)) = g (α v i) from
      IsLocalization.Away.lift_eq _ _ _, g_α] at this
  have h3 : (LC (∑ j, v i j)⁻¹ * T 1 : LaurentPolynomial k) * (LC (∑ j, v i j) * T (-1)) = 1 := by
    rw [show (LC (∑ j, v i j)⁻¹ * T 1 : LaurentPolynomial k) * (LC (∑ j, v i j) * T (-1)) =
      LC ((∑ j, v i j)⁻¹ * ∑ j, v i j) * (T 1 * T (-1)) by rw [map_mul]; ring,
      inv_mul_cancel₀ (hc i), map_one, ← T_add]
    simp
  simp only [map_mul, Polynomial.toLaurent_C, Polynomial.toLaurent_X]
  linear_combination (LC (∑ j, v i j)⁻¹ * T 1 : LaurentPolynomial k) * h2 -
    (ev v hc (⟨y v i, y_mem v hc i⟩ : Lsub v hc)) * h3

/-- Every element of `OT(A)` lies in `k[x][1/Q]` and is sent into `k[T] ⊆ k[T, T⁻¹]`. -/
theorem ev_OT (hc : ∀ i, ∑ j, v i j ≠ 0) {f : K} (hf : f ∈ OT v) :
    ∃ h : f ∈ Lsub v hc, ev v hc ⟨f, h⟩ ∈ (Polynomial.toLaurent (R := k)).range := by
  induction hf using Algebra.adjoin_induction with
  | mem x hx =>
    obtain ⟨i, rfl⟩ := hx
    exact ⟨y_mem v hc i, _, (ev_y v hc i).symm⟩
  | algebraMap r =>
    have e : algebraMap k K r = algebraMap P K (MvPolynomial.C r) := by
      rw [IsScalarTower.algebraMap_apply k P K, MvPolynomial.algebraMap_eq]
    have hm : algebraMap k K r ∈ Lsub v hc := e ▸ (Lsub v hc).algebraMap_mem _
    refine ⟨hm, Polynomial.C r, ?_⟩
    have : (⟨algebraMap k K r, hm⟩ : Lsub v hc) = algebraMap P (Lsub v hc) (MvPolynomial.C r) :=
      Subtype.ext e
    rw [this, ev, IsLocalization.Away.lift_eq]
    simp [g, Polynomial.toLaurent_C, LaurentPolynomial.algebraMap_apply]
  | add a b _ _ iha ihb =>
    obtain ⟨ha, pa, hpa⟩ := iha
    obtain ⟨hb, pb, hpb⟩ := ihb
    refine ⟨add_mem ha hb, pa + pb, ?_⟩
    rw [map_add, hpa, hpb, ← map_add]
    rfl
  | mul a b _ _ iha ihb =>
    obtain ⟨ha, pa, hpa⟩ := iha
    obtain ⟨hb, pb, hpb⟩ := ihb
    refine ⟨mul_mem ha hb, pa * pb, ?_⟩
    rw [map_mul, hpa, hpb, ← map_mul]
    rfl

/-- `1/α_i` is not a unit of `OT(A)`. -/
theorem not_isUnit_gen (hc : ∀ i, ∑ j, v i j ≠ 0) (i : Fin m) : ¬ IsUnit (gen v i) := by
  intro hu
  obtain ⟨f, hf⟩ := hu.exists_right_inv
  obtain ⟨hfm, p, hp⟩ := ev_OT v hc f.2
  have h1 : (⟨y v i, y_mem v hc i⟩ : Lsub v hc) * ⟨f, hfm⟩ = 1 :=
    Subtype.ext (show y v i * (f : K) = 1 from congrArg Subtype.val hf)
  have h2 := congrArg (ev v hc) h1
  rw [map_mul, map_one, ev_y, ← hp, ← map_mul, ← map_one (Polynomial.toLaurent (R := k))] at h2
  have h3 := Polynomial.toLaurent_injective h2
  apply Polynomial.not_isUnit_X (R := k)
  exact IsUnit.of_mul_eq_one (Polynomial.C (∑ j, v i j)⁻¹ * p) (by rw [← h3]; ring)

theorem gen_ne_zero (hc : ∀ i, ∑ j, v i j ≠ 0) (i : Fin m) : gen v i ≠ 0 := by
  intro h
  have : y v i = 0 := congrArg Subtype.val h
  exact alg_α_ne_zero v hc i (inv_eq_zero.mp this)

/-- `[1/α_i]` is an `OT(A)`-regular sequence. -/
theorem isRegular_gen (hc : ∀ i, ∑ j, v i j ≠ 0) (i : Fin m) : IsRegular (OT v) [gen v i] := by
  refine ⟨(isWeaklyRegular_singleton_iff _ _).mpr
    fun a b hab => mul_left_cancel₀ (gen_ne_zero v hc i) hab, ?_⟩
  rw [Ideal.ofList_singleton, smul_eq_mul, Ideal.mul_top]
  exact fun h => not_isUnit_gen v hc i (Ideal.span_singleton_eq_top.mp h.symm)

/-- If every `α_i(1, …, 1) = ∑_j v_i(j)` is nonzero (and `m ≥ 1`), then `depth OT(A) ≥ 1`. -/
theorem one_le_depth (hc : ∀ i, ∑ j, v i j ≠ 0) (i : Fin m) : 1 ≤ depth v := by
  refine le_iSup₂_of_le [gen v i] ⟨fun r hr => ?_, isRegular_gen v hc i⟩ (by simp)
  rw [List.mem_singleton] at hr
  exact hr ▸ Ideal.subset_span ⟨i, rfl⟩

end Lower

section Witness

variable [CharZero k]

/-- The arrangement `x = 0`, `y = 0`, `x + y = 0` in `k²` (matroid `U_{2,3}`). -/
def vA : Fin 3 → Fin 2 → k := ![![1, 0], ![0, 1], ![1, 1]]

theorem hcA : ∀ i, ∑ j, (vA (k := k)) i j ≠ 0 := by
  intro i; fin_cases i <;> norm_num [vA, Fin.sum_univ_two]

theorem vA_ne_zero : ∀ i, (vA (k := k)) i ≠ 0 :=
  fun i h => hcA i (by rw [h]; simp)

omit [CharZero k] in
theorem vA_pair : ∀ i j : Fin 3, i ≠ j → LinearIndependent k ![(vA (k := k)) i, vA j] := by
  intro i j hij
  rw [LinearIndependent.pair_iff]
  intro s t h
  have h0 := congrFun h 0
  have h1 := congrFun h 1
  fin_cases i <;> fin_cases j <;> simp_all [vA]

omit [CharZero k] in
/-- For plane arrangements of pairwise independent nonzero vectors (matroid `U_{2,m}`),
`r(S) = min(|S|, 2)`. -/
theorem rk_eq_min {m : ℕ} (v : Fin m → Fin 2 → k) (hne : ∀ i, v i ≠ 0)
    (hp : ∀ i j, i ≠ j → LinearIndependent k ![v i, v j]) (S : Finset (Fin m)) :
    rk v S = min S.card 2 := by
  have hle : rk v S ≤ 2 := (Submodule.finrank_le _).trans (by simp)
  rcases Nat.lt_or_ge 1 S.card with h | h
  · obtain ⟨i, hi, j, hj, hij⟩ := Finset.one_lt_card.mp h
    have h2 : Module.finrank k (Submodule.span k {v i, v j}) = 2 := by
      have := finrank_span_eq_card (hp i j hij)
      rwa [Matrix.range_cons_cons_empty, Fintype.card_fin] at this
    have hge : 2 ≤ rk v S :=
      h2.ge.trans <| Submodule.finrank_mono (Submodule.span_mono (Set.insert_subset
        (Set.mem_image_of_mem _ hi) (Set.singleton_subset_iff.mpr (Set.mem_image_of_mem _ hj))))
    omega
  · rcases Nat.le_one_iff_eq_zero_or_eq_one.mp h with h | h
    · rw [Finset.card_eq_zero.mp h, rk, Finset.coe_empty, Set.image_empty, Submodule.span_empty,
        finrank_bot]
      rfl
    · obtain ⟨i, rfl⟩ := Finset.card_eq_one.mp h
      rw [rk, Finset.coe_singleton, Set.image_singleton, finrank_span_singleton (hne i)]
      rfl

theorem rk_vA (S : Finset (Fin 3)) : rk (vA (k := k)) S = min S.card 2 :=
  rk_eq_min _ vA_ne_zero vA_pair S

theorem rk_vA_univ : rk (vA (k := k)) Finset.univ = 2 := by
  rw [rk_vA, Finset.card_univ, Fintype.card_fin]; rfl

theorem beta_vA : beta (vA (k := k)) = 1 := by
  unfold beta
  simp only [rk_vA]
  rw [Finset.sum_powerset_apply_card (fun m => (-1 : ℤ) ^ m * ((min m 2 : ℕ) : ℤ)),
    Finset.card_univ, Fintype.card_fin]
  simp [Finset.sum_range_succ, Nat.choose]

/-- For the arrangement `{x, y, x + y}`: rank `2`, `β = 1`, so `rank - 1 - β = 0`, but
`depth OT(A) ≥ 1`. -/
theorem witness :
    rk (vA (k := k)) Finset.univ = 2 ∧ beta (vA (k := k)) = 1 ∧ 1 ≤ depth (vA (k := k)) ∧
      ¬ ∃ d : ℕ, depth (vA (k := k)) = d ∧
        (d : ℤ) = (rk (vA (k := k)) Finset.univ : ℤ) - 1 - beta (vA (k := k)) := by
  refine ⟨rk_vA_univ, beta_vA, one_le_depth _ hcA 0, ?_⟩
  rintro ⟨d, hd, hd'⟩
  rw [rk_vA_univ, beta_vA] at hd'
  have hd0 : d = 0 := by omega
  have := one_le_depth _ (hcA (k := k)) 0
  rw [hd, hd0] at this
  simp at this

/-- **Conjecture 00000000543 is false** (over every field `k` of characteristic zero): it is not
true that every essential arrangement of distinct hyperplanes satisfies
`depth OT(A) = rank M(A) - 1 - β(M(A))`. -/
theorem conjecture_543_false :
    ¬ ∀ (m n : ℕ) (v : Fin m → Fin n → k), (∀ i, v i ≠ 0) →
        (∀ i j, i ≠ j → LinearIndependent k ![v i, v j]) → rk v Finset.univ = n →
        ∃ d : ℕ, depth v = d ∧ (d : ℤ) = (rk v Finset.univ : ℤ) - 1 - beta v := by
  intro h
  exact (witness (k := k)).2.2.2 (h 3 2 vA vA_ne_zero vA_pair rk_vA_univ)

/-- Four lines `x, y, x + y, x + 2y` in `k²` (matroid `U_{2,4}`). -/
def vB : Fin 4 → Fin 2 → k := ![![1, 0], ![0, 1], ![1, 1], ![1, 2]]

theorem vB_ne_zero : ∀ i, (vB (k := k)) i ≠ 0 := by
  intro i h
  have h0 := congrFun h 0
  have h1 := congrFun h 1
  fin_cases i <;> simp_all [vB]

theorem vB_pair : ∀ i j : Fin 4, i ≠ j → LinearIndependent k ![(vB (k := k)) i, vB j] := by
  intro i j hij
  rw [LinearIndependent.pair_iff]
  intro s t h
  have h0 := congrFun h 0
  have h1 := congrFun h 1
  fin_cases i <;> fin_cases j <;> simp_all [vB] <;> grind

/-- For `U_{2,4}` the right-hand side `rank - 1 - β` equals `-1`, so no value of a depth (an
element of `ℕ ∪ {∞}`) can satisfy the formula, whatever the reading of depth or of `OT(A)`. -/
theorem formula_U24 :
    rk (vB (k := k)) Finset.univ = 2 ∧ beta (vB (k := k)) = 2 ∧
      (rk (vB (k := k)) Finset.univ : ℤ) - 1 - beta (vB (k := k)) = -1 := by
  have hr := rk_eq_min (vB (k := k)) vB_ne_zero vB_pair
  have h1 : rk (vB (k := k)) Finset.univ = 2 := by
    rw [hr, Finset.card_univ, Fintype.card_fin]; rfl
  have h2 : beta (vB (k := k)) = 2 := by
    unfold beta
    simp only [hr]
    rw [Finset.sum_powerset_apply_card (fun m => (-1 : ℤ) ^ m * ((min m 2 : ℕ) : ℤ)),
      Finset.card_univ, Fintype.card_fin]
    simp [Finset.sum_range_succ, Nat.choose]
  refine ⟨h1, h2, ?_⟩
  rw [h1, h2]
  norm_num

theorem not_formula_U24 (D : ℕ∞) :
    ¬ ∃ d : ℕ, D = d ∧ (d : ℤ) = (rk (vB (k := k)) Finset.univ : ℤ) - 1 - beta (vB (k := k)) := by
  rintro ⟨d, -, hd⟩
  rw [(formula_U24 (k := k)).2.2] at hd
  omega

end Witness

end C543
