import Mathlib.Data.Multiset.Bind
import Mathlib.Data.Finset.Card
import Mathlib.Data.Finsupp.Multiset
import Mathlib.Logic.Relation
import Mathlib.Tactic

namespace CompleteGraph
variable (V : Type*) [DecidableEq V]
abbrev Edge := {s : Finset V // s.card = 2}
noncomputable def edge (a b : V) (h : a ≠ b) : Edge V := ⟨{a,b}, by simp [h]⟩
noncomputable def ends (e : Edge V) : Multiset V := e.val.val
noncomputable def degree (M : Multiset (Edge V)) : Multiset V := M.bind (ends V)

variable {V}
@[simp] theorem ends_edge (a b : V) (h : a ≠ b) :
    ends V (edge V a b h) = {a,b} := by
  simp [ends, edge, Finset.insert_val_of_not_mem, h]

omit [DecidableEq V] in
@[simp] theorem degree_zero : degree V 0 = 0 := by simp [degree]
omit [DecidableEq V] in
@[simp] theorem degree_add (M N : Multiset (Edge V)) :
    degree V (M + N) = degree V M + degree V N := by simp [degree]
omit [DecidableEq V] in
@[simp] theorem degree_cons (e : Edge V) (M : Multiset (Edge V)) :
    degree V (e ::ₘ M) = ends V e + degree V M := by simp [degree]
omit [DecidableEq V] in
@[simp] theorem card_ends (e : Edge V) : (ends V e).card = 2 := e.property
omit [DecidableEq V] in
@[simp] theorem card_degree (M : Multiset (Edge V)) :
    (degree V M).card = 2 * M.card := by
  induction M using Multiset.induction_on with
  | empty => simp
  | @cons e M ih => simp [ih]; omega

theorem edge_symm (a b : V) (h : a ≠ b) :
    edge V a b h = edge V b a h.symm := by
  apply Subtype.ext
  exact Finset.pair_comm a b

theorem incident (e : Edge V) (a : V) (ha : a ∈ ends V e) :
    ∃ b, ∃ h : a ≠ b, e = edge V a b h := by
  obtain ⟨x,y,hxy,he⟩ := Finset.card_eq_two.mp e.property
  have hm : a = x ∨ a = y := by simpa [ends, he] using ha
  rcases hm with rfl | rfl
  · exact ⟨y,hxy,Subtype.ext he⟩
  · exact ⟨x,hxy.symm,Subtype.ext (he.trans (Finset.pair_comm _ _))⟩

theorem edge_rep (e : Edge V) : ∃ a b, ∃ h : a ≠ b, e = edge V a b h := by
  obtain ⟨a,b,h,he⟩ := Finset.card_eq_two.mp e.property
  exact ⟨a,b,h,Subtype.ext he⟩

/-- The congruence generated by degree-preserving replacements of two edges. -/
inductive SwitchEquiv : Multiset (Edge V) → Multiset (Edge V) → Prop
  | refl (M) : SwitchEquiv M M
  | trans {M N P} : SwitchEquiv M N → SwitchEquiv N P → SwitchEquiv M P
  | add {M N} (R) : SwitchEquiv M N → SwitchEquiv (M + R) (N + R)
  | quad (A B) : A.card = 2 → B.card = 2 → degree V A = degree V B → SwitchEquiv A B

theorem switch (a b c d : V) (hab : a ≠ b) (hcd : c ≠ d)
    (hac : a ≠ c) (hbd : b ≠ d) :
    SwitchEquiv ({edge V a b hab, edge V c d hcd})
      ({edge V a c hac, edge V b d hbd}) := by
  apply SwitchEquiv.quad
  · simp
  · simp
  · simp [degree, ends_edge, Multiset.cons_add, Multiset.add_cons,
      Multiset.cons_swap]

omit [DecidableEq V] in
theorem SwitchEquiv.cons {M N : Multiset (Edge V)} (e : Edge V)
    (h : SwitchEquiv M N) : SwitchEquiv (e ::ₘ M) (e ::ₘ N) := by
  simpa only [add_comm M, add_comm N, Multiset.singleton_add] using h.add {e}

omit [DecidableEq V] in
theorem SwitchEquiv.degree_eq {M N : Multiset (Edge V)} (h : SwitchEquiv M N) :
    degree V M = degree V N := by
  induction h with
  | refl => rfl
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | add R _ ih => simp only [degree_add, ih]
  | quad _ _ _ _ h => exact h

theorem count_degree_le_card (M : Multiset (Edge V)) (a : V) :
    (degree V M).count a ≤ M.card := by
  induction M using Multiset.induction_on with
  | empty => simp
  | @cons e M ih =>
    have he : (ends V e).count a ≤ 1 :=
      Multiset.nodup_iff_count_le_one.mp e.val.nodup a
    simp only [degree_cons, Multiset.count_add, Multiset.card_cons]
    omega

theorem exists_avoiding (M : Multiset (Edge V)) (a : V)
    (h : (degree V M).count a < M.card) : ∃ e ∈ M, a ∉ ends V e := by
  induction M using Multiset.induction_on with
  | empty => simp at h
  | @cons e M ih =>
    by_cases he : a ∈ ends V e
    · have hc : (ends V e).count a = 1 :=
        Multiset.count_eq_one_of_mem e.val.nodup he
      have hM : (degree V M).count a < M.card := by
        simpa only [degree_cons, Multiset.count_add, hc, Multiset.card_cons,
          Nat.add_comm 1, Nat.add_lt_add_iff_right] using h
      obtain ⟨f,hf,ha⟩ := ih hM
      exact ⟨f,Multiset.mem_cons_of_mem hf,ha⟩
    · exact ⟨e,Multiset.mem_cons_self _ _,he⟩

theorem extract_incident (M : Multiset (Edge V)) (a : V) (h : a ∈ degree V M) :
    ∃ b, ∃ hab : a ≠ b, ∃ R, M = edge V a b hab ::ₘ R := by
  obtain ⟨e,he,ha⟩ := Multiset.mem_bind.mp h
  obtain ⟨b,hab,rfl⟩ := incident e a ha
  obtain ⟨R,hR⟩ := Multiset.exists_cons_of_mem he
  exact ⟨b,hab,R,hR⟩

theorem edge_rep_first_ne (e : Edge V) (a : V) :
    ∃ x y, ∃ hxy : x ≠ y, x ≠ a ∧ e = edge V x y hxy := by
  obtain ⟨x,y,hxy,rfl⟩ := edge_rep e
  by_cases hxa : x = a
  · exact ⟨y,x,hxy.symm,by simpa [← hxa] using hxy.symm,edge_symm _ _ _⟩
  · exact ⟨x,y,hxy,hxa,rfl⟩

/-- Insert one prescribed edge using at most two quadratic switches. -/
theorem insert_edge (a b : V) (hab : a ≠ b) (M Q : Multiset (Edge V))
    (h : degree V M = degree V (edge V a b hab ::ₘ Q)) :
    ∃ R, SwitchEquiv M (edge V a b hab ::ₘ R) := by
  have ha : a ∈ degree V M := by rw [h]; simp
  obtain ⟨c,hac,R,rfl⟩ := extract_incident M a ha
  by_cases hcb : c = b
  · subst c
    exact ⟨R,SwitchEquiv.refl _⟩
  have hb : b ∈ degree V R := by
    have hb' : b ∈ degree V (edge V a c hac ::ₘ R) := by rw [h]; simp
    simpa [hab.symm, Ne.symm hcb] using hb'
  obtain ⟨d,hbd,S,rfl⟩ := extract_incident R b hb
  by_cases hcd : c = d
  · subst d
    have hcount := congrArg (Multiset.count c) h
    have hcard := congrArg Multiset.card h
    have hQ := count_degree_le_card Q c
    have hlt : (degree V S).count c < S.card := by
      simp [hac.symm, hbd.symm] at hcount
      simp only [card_degree, Multiset.card_cons] at hcard
      omega
    obtain ⟨e,he,hce⟩ := exists_avoiding S c hlt
    obtain ⟨T,rfl⟩ := Multiset.exists_cons_of_mem he
    obtain ⟨x,y,hxy,hxa,rfl⟩ := edge_rep_first_ne e a
    have hcx : c ≠ x := by simpa using (fun hx => hce (by simp [hx]))
    have hcy : c ≠ y := by simpa using (fun hy => hce (by simp [hy]))
    refine ⟨edge V c x hcx ::ₘ edge V c y hcy ::ₘ T, ?_⟩
    have h₁ := (switch a c x y hac hxy hxa.symm hcy).add
      (edge V b c hbd ::ₘ T)
    have h₂ := (switch a x b c hxa.symm hbd hab hcx.symm).add
      (edge V c y hcy ::ₘ T)
    have hs : edge V x c hcx.symm = edge V c x hcx := edge_symm _ _ _
    apply SwitchEquiv.trans
      (show SwitchEquiv (edge V a c hac ::ₘ edge V b c hbd ::ₘ
          edge V x y hxy ::ₘ T)
        (edge V a x hxa.symm ::ₘ edge V b c hbd ::ₘ
          edge V c y hcy ::ₘ T) from by
        simpa [Multiset.cons_swap] using h₁)
    simpa [hs, Multiset.cons_swap] using h₂
  · refine ⟨edge V c d hcd ::ₘ S, ?_⟩
    have hs := (switch a c b d hac hbd hab hcd).add S
    simpa using hs

/-- Every complete-graph degree fiber, with arbitrary edge multiplicities, is
connected by quadratic moves. -/
theorem connected_of_degree_eq (M N : Multiset (Edge V))
    (h : degree V M = degree V N) : SwitchEquiv M N := by
  induction N using Multiset.induction_on generalizing M with
  | empty =>
    have hc := congrArg Multiset.card h
    simp only [card_degree, Multiset.card_zero, mul_zero] at hc
    have hM : M = 0 := Multiset.card_eq_zero.mp (by omega)
    subst M
    exact SwitchEquiv.refl _
  | @cons e N ih =>
    obtain ⟨a,b,hab,rfl⟩ := edge_rep e
    obtain ⟨R,hR⟩ := insert_edge a b hab M N h
    have hdeg : degree V R = degree V N := by
      have hh := hR.degree_eq.symm.trans h
      simpa only [degree_cons, add_right_inj] using hh
    exact hR.trans ((ih R hdeg).cons _)
end CompleteGraph
