name = "conjecture469"
version = "0.1.0"
defaultTargets = ["Main"]

[[lean_lib]]
name = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "aaf410c71d42d5dc083c7735e47f56443afca3c0"
