import Mathlib

/-!
# Conjecture 00000002221 (disproved)

*Definition.* The constructible topology on `Spec R`.
*Conjecture.* The cardinality of the Stone space of the Booleanization (complemented-closure
algebra) of the spectrum is at most `2^(2^d)`, `d = dim R`.

Counterexample: `R = K^N = Fin N → K` for a field `K` and `N ≥ 3`.  Then `dim R = 0`, so the
claimed bound is `2^(2^0) = 2`, but `Spec R` is a discrete space with (at least) `N` points, every
subset of it is clopen and constructible, and the Stone space of each candidate Boolean algebra has
at least `N ≥ 3` points.

The Stone space of a Boolean algebra `B` is `Hom(B, 2)`, here `BoundedLatticeHom B Bool`
(equivalently, the ultrafilters of `B`).  Readings covered:
* `stone_constructible_card` : `B` = the Boolean algebra of constructible subsets of `Spec R`
  (Mathlib's `Topology.IsConstructible`: Boolean subalgebra generated by retrocompact opens);
* `stone_clopens_card` : `B` = the Boolean algebra of clopen subsets of `Spec R`;
* `constructibleTopology_card` : the Stone space realized as `Spec R` with the constructible
  topology (`WithConstructibleTopology`);
* `stone_card_of_hom` : any Boolean algebra `B` with a bounded lattice map to the subsets of
  `Spec R` whose image contains every singleton (e.g. the full power set).
-/

open Topology PrimeSpectrum Cardinal

universe u

namespace C2221

/-- The Stone space of a Boolean algebra `B`: Boolean homomorphisms `B → 2`. -/
abbrev StoneSpace (B : Type u) [BooleanAlgebra B] := BoundedLatticeHom B Bool

/-- The Boolean algebra of constructible subsets of `Spec R` (the Boolean subalgebra of
`Set (Spec R)` generated by the retrocompact open sets). -/
def constructibleAlgebra (R : Type u) [CommRing R] :
    BooleanSubalgebra (Set (PrimeSpectrum R)) :=
  BooleanSubalgebra.closure {U | IsOpen U ∧ IsRetrocompact U}

lemma mem_constructibleAlgebra_iff {R : Type u} [CommRing R] {s : Set (PrimeSpectrum R)} :
    s ∈ constructibleAlgebra R ↔ IsConstructible s := Iff.rfl

/-- The inclusion of the clopen sets into all subsets, as a bounded lattice map. -/
def clopensHom (X : Type u) [TopologicalSpace X] :
    BoundedLatticeHom (TopologicalSpace.Clopens X) (Set X) where
  toFun := (↑)
  map_sup' := TopologicalSpace.Clopens.coe_sup
  map_inf' := TopologicalSpace.Clopens.coe_inf
  map_top' := TopologicalSpace.Clopens.coe_top
  map_bot' := TopologicalSpace.Clopens.coe_bot

/-! ### Points give points of the Stone space -/

section Eval

variable {X B : Type u} [BooleanAlgebra B]

open Classical in
/-- The point of the Stone space of `B` given by evaluating at a point `x` (the evaluation ultrafilter;
principal when `B` is a finite power-set algebra). -/
noncomputable def evalAt (φ : BoundedLatticeHom B (Set X)) (x : X) : StoneSpace B where
  toFun b := decide (x ∈ φ b)
  map_sup' a b := by simp [map_sup, Bool.decide_or]
  map_inf' a b := by simp [map_inf, Bool.decide_and]
  map_top' := by simp
  map_bot' := by simp

open Classical in
/-- If `φ(B)` contains every singleton, distinct points give distinct points of the Stone space. -/
lemma evalAt_injective (φ : BoundedLatticeHom B (Set X)) (hφ : ∀ x, ∃ b, φ b = {x}) :
    Function.Injective (evalAt φ) := by
  intro x y h
  obtain ⟨b, hb⟩ := hφ x
  have h' := DFunLike.congr_fun h b
  simp only [evalAt, BoundedLatticeHom.coe_mk, LatticeHom.coe_mk, SupHom.coe_mk, hb,
    Set.mem_singleton_iff, decide_true] at h'
  exact (of_decide_eq_true h'.symm).symm

lemma mk_le_stone (φ : BoundedLatticeHom B (Set X)) (hφ : ∀ x, ∃ b, φ b = {x}) :
    #X ≤ #(StoneSpace B) :=
  mk_le_of_injective (evalAt_injective φ hφ)

end Eval

/-! ### The ring `K^N` -/

section Ring

variable (K : Type u) [Field K] (N : ℕ)

/-- `K^N` has Krull dimension `0` (it is Artinian and nonzero). -/
theorem ringKrullDim_pi [NeZero N] : ringKrullDim (Fin N → K) = 0 :=
  ringKrullDimZero_iff_ringKrullDim_eq_zero.1 inferInstance

instance discrete_spec : DiscreteTopology (PrimeSpectrum (Fin N → K)) :=
  (sigmaToPiHomeo fun _ : Fin N => K).discreteTopology

instance finite_spec : Finite (PrimeSpectrum (Fin N → K)) :=
  Finite.of_equiv _ (sigmaToPiHomeo fun _ : Fin N => K).toEquiv

/-- The `N` primes `ker(evᵢ)` of `K^N`. -/
noncomputable def pt (i : Fin N) : PrimeSpectrum (Fin N → K) :=
  sigmaToPi (fun _ : Fin N => K) ⟨i, default⟩

lemma pt_injective : Function.Injective (pt K N) := by
  intro i j h
  have := sigmaToPi_injective (fun _ : Fin N => K) h
  exact (Sigma.mk.inj_iff.1 this).1

/-- `Spec K^N` has at least `N` points. -/
lemma card_spec : (N : Cardinal) ≤ #(PrimeSpectrum (Fin N → K)) := by
  have := Cardinal.lift_mk_le_lift_mk_of_injective (pt_injective K N)
  simpa using this

/-- Every subset of `Spec K^N` is clopen and constructible: the clopen algebra and the
constructible algebra are both the full power set. -/
theorem every_subset (s : Set (PrimeSpectrum (Fin N → K))) :
    IsClopen s ∧ IsConstructible s := by
  refine ⟨isClopen_discrete s, BooleanSubalgebra.subset_closure ⟨isOpen_discrete s, ?_⟩⟩
  intro U _ _
  exact (Set.toFinite _).isCompact

/-- Any Boolean algebra mapping onto a family of subsets of `Spec K^N` that contains all
singletons has a Stone space with at least `N` points. -/
theorem stone_card_of_hom {B : Type u} [BooleanAlgebra B]
    (φ : BoundedLatticeHom B (Set (PrimeSpectrum (Fin N → K)))) (hφ : ∀ x, ∃ b, φ b = {x}) :
    (N : Cardinal) ≤ #(StoneSpace B) :=
  (card_spec K N).trans (mk_le_stone φ hφ)

/-- Reading 1: the Stone space of the constructible Boolean algebra of `Spec K^N`. -/
theorem stone_constructible_card :
    (N : Cardinal) ≤ #(StoneSpace (constructibleAlgebra (Fin N → K))) :=
  stone_card_of_hom K N (constructibleAlgebra _).subtype
    fun x => ⟨⟨{x}, (every_subset K N {x}).2⟩, rfl⟩

/-- Reading 2: the Stone space of the Boolean algebra of clopen subsets of `Spec K^N`. -/
theorem stone_clopens_card :
    (N : Cardinal) ≤ #(StoneSpace (TopologicalSpace.Clopens (PrimeSpectrum (Fin N → K)))) :=
  stone_card_of_hom K N (clopensHom _) fun x => ⟨⟨{x}, (every_subset K N {x}).1⟩, rfl⟩

/-- Reading 3: `Spec K^N` with the constructible topology has at least `N` points. -/
theorem constructibleTopology_card :
    (N : Cardinal) ≤ #(WithConstructibleTopology (PrimeSpectrum (Fin N → K))) :=
  (card_spec K N).trans_eq (Cardinal.mk_congr (WithTopology.equiv _ _).symm)

end Ring

/-! ### The conjecture fails -/

/-- The bound `2^(2^d)` as a cardinal. -/
def bound (d : ℕ) : Cardinal := ((2 ^ 2 ^ d : ℕ) : Cardinal)

lemma three_not_le_bound_zero {c : Cardinal} (h3 : (3 : Cardinal) ≤ c) : ¬ c ≤ bound 0 := by
  intro h
  have : (3 : Cardinal) ≤ ((2 : ℕ) : Cardinal) := h3.trans (by simpa [bound] using h)
  exact absurd (Nat.cast_le.1 this) (by norm_num)

/-- **Disproof, constructible reading.** `R = (ZMod 2)^3` has Krull dimension `0`, but the
Stone space of its constructible Boolean algebra has `≥ 3 > 2 = 2^(2^0)` points. -/
theorem conjecture_false_constructible :
    ¬ ∀ (R : Type) [CommRing R] (d : ℕ), ringKrullDim R = d →
      #(StoneSpace (constructibleAlgebra R)) ≤ bound d := by
  intro h
  refine three_not_le_bound_zero
    (by exact_mod_cast stone_constructible_card (ZMod 2) 3)
    (h (Fin 3 → ZMod 2) 0 (by simpa using ringKrullDim_pi (ZMod 2) 3))

/-- **Disproof, clopen reading.** Same counterexample for the Boolean algebra of clopens. -/
theorem conjecture_false_clopens :
    ¬ ∀ (R : Type) [CommRing R] (d : ℕ), ringKrullDim R = d →
      #(StoneSpace (TopologicalSpace.Clopens (PrimeSpectrum R))) ≤ bound d := by
  intro h
  refine three_not_le_bound_zero
    (by exact_mod_cast stone_clopens_card (ZMod 2) 3)
    (h (Fin 3 → ZMod 2) 0 (by simpa using ringKrullDim_pi (ZMod 2) 3))

/-- **Disproof, constructible-topology reading.** -/
theorem conjecture_false_constructibleTopology :
    ¬ ∀ (R : Type) [CommRing R] (d : ℕ), ringKrullDim R = d →
      #(WithConstructibleTopology (PrimeSpectrum R)) ≤ bound d := by
  intro h
  refine three_not_le_bound_zero
    (by exact_mod_cast constructibleTopology_card (ZMod 2) 3)
    (h (Fin 3 → ZMod 2) 0 (by simpa using ringKrullDim_pi (ZMod 2) 3))

end C2221
