import Mathlib

/-!
# Conjecture 00000000539 is false

The conjecture: the h-vector of a quadratic monomial ideal has no three adjacent strictly
decreasing terms.  We build, over an arbitrary field `K`, the graded quotient `S/I` of
`S = K[x_0, ..., x_{n-1}]` by a monomial ideal `I`, its Hilbert function
`j ↦ dim_K (S/I)_j`, its Hilbert series, and its h-polynomial (the polynomial `h` with
`HS(t) * (1-t)^d = h(t)` and `h(1) ≠ 0`).  For the quadratic monomial ideal
`I = (x_0^2, x_1^2, x_2^2, x_3^2)` in four variables the h-polynomial is `(1+t)^4`, so the
h-vector is `(1, 4, 6, 4, 1)`, which contains the strictly decreasing run `6 > 4 > 1`.
-/

open MvPolynomial Module Finset

namespace C539

variable {σ : Type*} {K : Type*} [Field K]

/-- The monomial ideal of `K[x_σ]` generated by the monomials `x^g`, `g ∈ G`. -/
noncomputable def monomialIdeal (K : Type*) [Field K] (G : Set (σ →₀ ℕ)) :
    Ideal (MvPolynomial σ K) :=
  Ideal.span ((fun g => monomial g (1 : K)) '' G)

/-- A quadratic monomial ideal: an ideal generated by monomials of total degree `2`. -/
def IsQuadraticMonomialIdeal (I : Ideal (MvPolynomial σ K)) : Prop :=
  ∃ G : Set (σ →₀ ℕ), (∀ g ∈ G, g.degree = 2) ∧ I = monomialIdeal K G

/-- The degree-`j` component `(S/I)_j` of the graded quotient: the image of the degree-`j`
homogeneous polynomials under the quotient map. -/
noncomputable def gradedPiece (I : Ideal (MvPolynomial σ K)) (j : ℕ) :
    Submodule K (MvPolynomial σ K ⧸ I) :=
  (homogeneousSubmodule σ K j).map (Ideal.Quotient.mkₐ K I).toLinearMap

/-- The Hilbert function `j ↦ dim_K (S/I)_j`. -/
noncomputable def hilbertFunction (I : Ideal (MvPolynomial σ K)) (j : ℕ) : ℕ :=
  finrank K (gradedPiece I j)

/-- The Hilbert series `∑_j dim_K (S/I)_j t^j`. -/
noncomputable def hilbertSeries (I : Ideal (MvPolynomial σ K)) : PowerSeries ℤ :=
  PowerSeries.mk fun j => (hilbertFunction I j : ℤ)

/-- `h` is the h-polynomial of `S/I`: for some `d`, `HS(t) * (1-t)^d = h(t)` and `h(1) ≠ 0`.
(`d` is then the Krull dimension; see `isHPolynomial_unique` for uniqueness in our example.) -/
def IsHPolynomial (I : Ideal (MvPolynomial σ K)) (h : Polynomial ℤ) : Prop :=
  ∃ d : ℕ, hilbertSeries I * (1 - PowerSeries.X) ^ d = (h : PowerSeries ℤ) ∧ h.eval 1 ≠ 0

/-- The h-vector `(h_0, ..., h_s)`, `s = deg h`, has three adjacent strictly decreasing
terms `h_i > h_{i+1} > h_{i+2}` (all three indices inside the vector). -/
def HasTripleDescent (h : Polynomial ℤ) : Prop :=
  ∃ i, i + 2 ≤ h.natDegree ∧ h.coeff (i + 1) < h.coeff i ∧ h.coeff (i + 2) < h.coeff (i + 1)

/-! ### Hilbert function of a monomial quotient = number of standard monomials -/

/-- The standard monomials of degree `j`: degree-`j` exponents dominating no generator. -/
noncomputable def standard [Fintype σ] (G : Set (σ →₀ ℕ)) (j : ℕ) : Finset (σ →₀ ℕ) := by
  classical
  exact (univ.finsuppAntidiag j).filter fun m => ∀ g ∈ G, ¬ g ≤ m

lemma mem_standard [Fintype σ] {G : Set (σ →₀ ℕ)} {j : ℕ} {m : σ →₀ ℕ} :
    m ∈ standard G j ↔ m.degree = j ∧ ∀ g ∈ G, ¬ g ≤ m := by
  classical
  simp [standard, mem_finsuppAntidiag, Finsupp.degree_eq_sum]

theorem hilbertFunction_monomialIdeal [Fintype σ] (G : Set (σ →₀ ℕ)) (j : ℕ) :
    hilbertFunction (monomialIdeal K G) j = (standard G j).card := by
  classical
  set I := monomialIdeal K G
  set T := standard G j
  let mk := (Ideal.Quotient.mkₐ K I).toLinearMap
  let w : T → MvPolynomial σ K := fun m => monomial m.1 1
  have hw : LinearIndependent K w := by
    have h := (basisMonomials σ K).linearIndependent.comp (Subtype.val : T → _)
      Subtype.val_injective
    have e : w = ⇑(basisMonomials σ K) ∘ Subtype.val := by
      funext m; simp [w, coe_basisMonomials]
    rw [e]; exact h
  have hspanw : Submodule.span K (Set.range w) = restrictSupport K (T : Set (σ →₀ ℕ)) := by
    rw [restrictSupport_eq_span]; congr 1; ext p; simp [w]
  have hdisj : Disjoint (Submodule.span K (Set.range w)) (LinearMap.ker mk) := by
    rw [Submodule.disjoint_def, hspanw]
    intro p hp hpI
    have hpI' : p ∈ I := by
      simpa [mk, Ideal.Quotient.eq_zero_iff_mem] using hpI
    rw [mem_restrictSupport_iff] at hp
    by_contra hne
    obtain ⟨m, hm⟩ := (support_nonempty (p := p)).2 hne
    obtain ⟨g, hg, hgm⟩ := (mem_ideal_span_monomial_image.1 hpI') m hm
    exact (mem_standard.1 (hp hm)).2 g hg hgm
  have hli : LinearIndependent K (mk ∘ w) := hw.map hdisj
  have hspan : Submodule.span K (Set.range (mk ∘ w)) = gradedPiece I j := by
    unfold gradedPiece
    rw [homogeneousSubmodule_eq_finsupp_supported, ← restrictSupport,
      restrictSupport_eq_span, Submodule.map_span]
    apply le_antisymm
    · rw [Submodule.span_le]
      rintro _ ⟨m, rfl⟩
      exact Submodule.subset_span ⟨monomial m.1 1, ⟨m.1, (mem_standard.1 m.2).1, rfl⟩, rfl⟩
    · rw [Submodule.span_le]
      rintro _ ⟨_, ⟨m, hm, rfl⟩, rfl⟩
      by_cases hs : ∀ g ∈ G, ¬ g ≤ m
      · exact Submodule.subset_span ⟨⟨m, mem_standard.2 ⟨hm, hs⟩⟩, rfl⟩
      · push Not at hs
        obtain ⟨g, hg, hgm⟩ := hs
        have : monomial m (1 : K) ∈ I := by
          refine mem_ideal_span_monomial_image.2 ?_
          intro xi hxi
          rw [support_monomial, if_neg one_ne_zero, Finset.mem_singleton] at hxi
          exact ⟨g, hg, hxi ▸ hgm⟩
        have h0 : (Ideal.Quotient.mkₐ K I).toLinearMap (monomial m 1) = 0 := by
          simpa [Ideal.Quotient.eq_zero_iff_mem] using this
        rw [SetLike.mem_coe, h0]
        exact Submodule.zero_mem _
  unfold hilbertFunction
  rw [← hspan, finrank_span_eq_card hli, Fintype.card_coe]

/-! ### The example `I = (x_0^2, x_1^2, x_2^2, x_3^2)` -/

/-- Exponents of the four generators `x_i^2`. -/
def G4 : Set (Fin 4 →₀ ℕ) := Set.range fun i => Finsupp.single i 2

/-- The quadratic monomial ideal `(x_0^2, x_1^2, x_2^2, x_3^2)` of `K[x_0, x_1, x_2, x_3]`. -/
noncomputable def I4 (K : Type*) [Field K] : Ideal (MvPolynomial (Fin 4) K) := monomialIdeal K G4

theorem I4_quadratic : IsQuadraticMonomialIdeal (I4 K) :=
  ⟨G4, by rintro _ ⟨i, rfl⟩; simp, rfl⟩

lemma not_dvd_G4 (m : Fin 4 →₀ ℕ) : (∀ g ∈ G4, ¬ g ≤ m) ↔ ∀ i, m i ≤ 1 := by
  simp only [G4, Set.mem_range, forall_exists_index, forall_apply_eq_imp_iff,
    Finsupp.single_le_iff]
  exact forall_congr' fun i => by omega

lemma degree_eq_card_support {m : Fin 4 →₀ ℕ} (hm : ∀ i, m i ≤ 1) :
    m.degree = m.support.card := by
  rw [Finsupp.degree, Finset.card_eq_sum_ones]
  refine Finset.sum_congr rfl fun i hi => ?_
  have := hm i; have := Finsupp.mem_support_iff.1 hi; omega

theorem card_standard_G4 (j : ℕ) : (standard G4 j).card = Nat.choose 4 j := by
  classical
  rw [show Nat.choose 4 j = (powersetCard j (univ : Finset (Fin 4))).card by simp]
  refine Finset.card_bij (fun m _ => m.support) ?_ ?_ ?_
  · intro m hm
    rw [mem_standard, not_dvd_G4] at hm
    rw [Finset.mem_powersetCard]
    exact ⟨Finset.subset_univ _, (degree_eq_card_support hm.2).symm.trans hm.1⟩
  · intro m₁ h₁ m₂ h₂ he
    rw [mem_standard, not_dvd_G4] at h₁ h₂
    ext i
    have e := congrArg (i ∈ ·) he
    simp only [Finsupp.mem_support_iff, eq_iff_iff] at e
    have := h₁.2 i; have := h₂.2 i
    omega
  · intro s hs
    rw [Finset.mem_powersetCard] at hs
    let m : Fin 4 →₀ ℕ := Finsupp.onFinset s (fun i => if i ∈ s then 1 else 0)
      (by intro i hi; by_contra h; simp [h] at hi)
    have hm1 : ∀ i, m i ≤ 1 := by intro i; simp only [m, Finsupp.onFinset_apply]; split <;> omega
    have hsupp : m.support = s := by
      ext i; simp [m, Finsupp.onFinset_apply]
    refine ⟨m, ?_, hsupp⟩
    rw [mem_standard, not_dvd_G4]
    exact ⟨(degree_eq_card_support hm1).trans (by rw [hsupp, hs.2]), hm1⟩

theorem hilbertFunction_I4 (j : ℕ) : hilbertFunction (I4 K) j = Nat.choose 4 j := by
  rw [I4, hilbertFunction_monomialIdeal, card_standard_G4]

/-- The h-polynomial of the example. -/
noncomputable def h4 : Polynomial ℤ := (1 + Polynomial.X) ^ 4

theorem hilbertSeries_I4 : hilbertSeries (I4 K) = (h4 : PowerSeries ℤ) := by
  ext j
  rw [hilbertSeries, PowerSeries.coeff_mk, Polynomial.coeff_coe, h4,
    Polynomial.coeff_one_add_X_pow, hilbertFunction_I4]

/-- `(1+t)^4` is an h-polynomial of `S/I4` (with `d = 0`: `S/I4` is Artinian). -/
theorem isHPolynomial_I4 : IsHPolynomial (I4 K) h4 :=
  ⟨0, by simp [hilbertSeries_I4], by simp [h4]⟩

/-- Uniqueness: every h-polynomial of `S/I4` equals `(1+t)^4` (and forces `d = 0`). -/
theorem isHPolynomial_unique {h : Polynomial ℤ} (hh : IsHPolynomial (I4 K) h) : h = h4 := by
  obtain ⟨d, hd, h1⟩ := hh
  have hpoly : h4 * (1 - Polynomial.X) ^ d = h := by
    apply Polynomial.coe_injective
    rw [← hd, hilbertSeries_I4]
    push_cast; rfl
  subst hpoly
  cases d with
  | zero => simp
  | succ d => exact absurd (by simp) h1

theorem h4_coeffs : h4.natDegree = 4 ∧ h4.coeff 2 = 6 ∧ h4.coeff 3 = 4 ∧ h4.coeff 4 = 1 := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · rw [h4, add_comm, Polynomial.natDegree_pow, ← Polynomial.C_1, Polynomial.natDegree_X_add_C]
  all_goals simp [h4, Polynomial.coeff_one_add_X_pow, Nat.choose]

theorem h4_tripleDescent : HasTripleDescent h4 := by
  obtain ⟨hd, h2, h3, h4'⟩ := h4_coeffs
  exact ⟨2, by omega, by rw [h3, h2]; norm_num, by rw [h4', h3]; norm_num⟩

/-- **Counterexample.** Over every field `K`, `I = (x_0^2, x_1^2, x_2^2, x_3^2)` is a quadratic
monomial ideal whose (unique) h-polynomial is `(1+t)^4`; its h-vector `(1,4,6,4,1)` has the
three adjacent strictly decreasing terms `6 > 4 > 1`. -/
theorem counterexample :
    IsQuadraticMonomialIdeal (I4 K) ∧ IsHPolynomial (I4 K) h4 ∧
      (∀ h, IsHPolynomial (I4 K) h → h = h4) ∧ HasTripleDescent h4 :=
  ⟨I4_quadratic, isHPolynomial_I4, fun _ hh => isHPolynomial_unique hh, h4_tripleDescent⟩

/-- **Conjecture 00000000539 is false** (over every field `K`): it is not true that the
h-vector of every quadratic monomial ideal has no three adjacent strictly decreasing terms. -/
theorem conjecture_false (K : Type*) [Field K] :
    ¬ ∀ (n : ℕ) (I : Ideal (MvPolynomial (Fin n) K)), IsQuadraticMonomialIdeal I →
      ∀ h : Polynomial ℤ, IsHPolynomial I h → ¬ HasTripleDescent h :=
  fun H => H 4 (I4 K) I4_quadratic h4 isHPolynomial_I4 h4_tripleDescent

/-! ### Second reading: the Hilbert function of the ideal `I` itself

The Definition speaks of "the Hilbert function of a graded ideal".  The standard convention
(used above) is the Hilbert function of the quotient `S/I`.  Read literally as the Hilbert
function `j ↦ dim_K I_j` of the graded module `I`, the conjecture also fails for `I4`. -/

/-- The degree-`j` component `I_j = I ∩ S_j`, as a subspace of `S_j`. -/
noncomputable def idealPiece (I : Ideal (MvPolynomial σ K)) (j : ℕ) :
    Submodule K (homogeneousSubmodule σ K j) :=
  (I.restrictScalars K).comap (homogeneousSubmodule σ K j).subtype

/-- The Hilbert function `j ↦ dim_K I_j` of the graded ideal `I`. -/
noncomputable def idealHilbertFunction (I : Ideal (MvPolynomial σ K)) (j : ℕ) : ℕ :=
  finrank K (idealPiece I j)

/-- The Hilbert series `∑_j dim_K I_j t^j` of the graded ideal `I`. -/
noncomputable def idealHilbertSeries (I : Ideal (MvPolynomial σ K)) : PowerSeries ℤ :=
  PowerSeries.mk fun j => (idealHilbertFunction I j : ℤ)

/-- `h` is the h-polynomial of the graded module `I`: `HS_I(t) * (1-t)^d = h(t)`, `h(1) ≠ 0`. -/
def IsIdealHPolynomial (I : Ideal (MvPolynomial σ K)) (h : Polynomial ℤ) : Prop :=
  ∃ d : ℕ, idealHilbertSeries I * (1 - PowerSeries.X) ^ d = (h : PowerSeries ℤ) ∧ h.eval 1 ≠ 0

/-- `dim_K S_j + 0 = dim_K I_j + dim_K (S/I)_j` (rank-nullity for `S_j → (S/I)_j`). -/
theorem idealHF_add_HF [Finite σ] (I : Ideal (MvPolynomial σ K)) (j : ℕ) :
    idealHilbertFunction I j + hilbertFunction I j = finrank K (homogeneousSubmodule σ K j) := by
  have : FiniteDimensional K (homogeneousSubmodule σ K j) :=
    Module.Finite.iff_fg.mpr (homogeneousSubmodule_fg σ K j)
  let f := (Ideal.Quotient.mkₐ K I).toLinearMap ∘ₗ (homogeneousSubmodule σ K j).subtype
  have hr : LinearMap.range f = gradedPiece I j := by
    rw [LinearMap.range_comp, Submodule.range_subtype]; rfl
  have hk : LinearMap.ker f = idealPiece I j := by
    rw [LinearMap.ker_comp]; unfold idealPiece; congr 1
    ext p; simp [Ideal.Quotient.eq_zero_iff_mem]
  rw [← f.finrank_range_add_finrank_ker, hr, hk, add_comm]; rfl

/-- `dim_K S_j = C(j+3, 3)` in four variables. -/
theorem finrank_homogeneous_four (j : ℕ) :
    finrank K (homogeneousSubmodule (Fin 4) K j) = (3 + j).choose 3 := by
  classical
  rw [homogeneousSubmodule_eq_finsupp_supported]
  change finrank K (restrictSupport K _) = _
  rw [finrank_eq_nat_card_basis (basisRestrictSupport K {d : Fin 4 →₀ ℕ | d.degree = j})]
  have hs : {d : Fin 4 →₀ ℕ | d.degree = j} = ↑((univ : Finset (Fin 4)).finsuppAntidiag j) := by
    ext d; simp [mem_finsuppAntidiag, Finsupp.degree_eq_sum]
  rw [hs, Nat.card_coe_set_eq, Set.ncard_coe_finset, card_finsuppAntidiag_nat_eq_choose,
    card_univ, Fintype.card_fin, show 4 + j - 1 = 3 + j by omega, Nat.choose_symm_add]

theorem idealHilbertSeries_I4 :
    idealHilbertSeries (I4 K) =
      (PowerSeries.mk fun n => ((3 + n).choose 3 : ℤ)) - (h4 : PowerSeries ℤ) := by
  ext j
  have e := idealHF_add_HF (I4 K) j
  rw [finrank_homogeneous_four, hilbertFunction_I4] at e
  rw [idealHilbertSeries, map_sub, PowerSeries.coeff_mk, PowerSeries.coeff_mk,
    Polynomial.coeff_coe, h4, Polynomial.coeff_one_add_X_pow]
  omega

/-- The h-polynomial of the ideal `I4` (as a graded module): `1 - (1+t)^4 (1-t)^4`. -/
noncomputable def hI : Polynomial ℤ :=
  Polynomial.C 4 * Polynomial.X ^ 2 - Polynomial.C 6 * Polynomial.X ^ 4 +
    Polynomial.C 4 * Polynomial.X ^ 6 - Polynomial.X ^ 8

theorem hI_eq : hI = 1 - h4 * (1 - Polynomial.X) ^ 4 := by
  simp only [hI, h4, map_ofNat]; ring

theorem idealHilbertSeries_I4_mul :
    idealHilbertSeries (I4 K) * (1 - PowerSeries.X) ^ 4 = (hI : PowerSeries ℤ) := by
  rw [idealHilbertSeries_I4, sub_mul,
    PowerSeries.mk_add_choose_mul_one_sub_pow_eq_one (S := ℤ) (d := 3), hI_eq]
  push_cast; rfl

theorem hI_eval : hI.eval 1 = 1 := by simp [hI]

theorem isIdealHPolynomial_I4 : IsIdealHPolynomial (I4 K) hI :=
  ⟨4, idealHilbertSeries_I4_mul, by rw [hI_eval]; norm_num⟩

/-- If `F (1-t)^a = p` and `F (1-t)^b = q` with `p(1), q(1) ≠ 0`, then `p = q`. -/
theorem hpoly_unique {F : PowerSeries ℤ} {a b : ℕ} {p q : Polynomial ℤ}
    (hp : F * (1 - PowerSeries.X : PowerSeries ℤ) ^ a = (p : PowerSeries ℤ))
    (hq : F * (1 - PowerSeries.X : PowerSeries ℤ) ^ b = (q : PowerSeries ℤ))
    (hp1 : p.eval 1 ≠ 0) (hq1 : q.eval 1 ≠ 0) : p = q := by
  have key : ∀ {a b : ℕ} {p q : Polynomial ℤ}, a ≤ b →
      F * (1 - PowerSeries.X : PowerSeries ℤ) ^ a = (p : PowerSeries ℤ) →
      F * (1 - PowerSeries.X : PowerSeries ℤ) ^ b = (q : PowerSeries ℤ) → q.eval 1 ≠ 0 →
      p = q := by
    intro a b p q hab hp hq hq1
    obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hab
    have : q = p * (1 - Polynomial.X) ^ k := by
      apply Polynomial.coe_injective
      rw [← hq, pow_add, ← mul_assoc, hp]; push_cast; rfl
    subst this
    cases k with
    | zero => simp
    | succ k => exact absurd (by simp) hq1
  rcases le_total a b with h | h
  · exact key h hp hq hq1
  · exact (key h hq hp hp1).symm

theorem isIdealHPolynomial_unique {h : Polynomial ℤ} (hh : IsIdealHPolynomial (I4 K) h) :
    h = hI := by
  obtain ⟨d, hd, h1⟩ := hh
  exact hpoly_unique hd idealHilbertSeries_I4_mul h1 (by rw [hI_eval]; norm_num)

theorem hI_tripleDescent : HasTripleDescent hI := by
  have hd : hI.natDegree = 8 := by unfold hI; compute_degree!
  refine ⟨2, by omega, ?_, ?_⟩ <;> simp [hI, Polynomial.coeff_X_pow]

/-- **Second reading.** With the Hilbert function of the ideal `I` itself, the h-polynomial of
`I4` is (uniquely) `4t^2 - 6t^4 + 4t^6 - t^8`, with h-vector `(0,0,4,0,-6,0,4,0,-1)`, which has
the strictly decreasing run `4 > 0 > -6`. -/
theorem conjecture_false_ideal_reading (K : Type*) [Field K] :
    ¬ ∀ (n : ℕ) (I : Ideal (MvPolynomial (Fin n) K)), IsQuadraticMonomialIdeal I →
      ∀ h : Polynomial ℤ, IsIdealHPolynomial I h → ¬ HasTripleDescent h :=
  fun H => H 4 (I4 K) I4_quadratic hI isIdealHPolynomial_I4 hI_tripleDescent

end C539
