name = "tlmc7158"
version = "1.0.0"
defaultTargets = ["Conjecture7158"]

[[lean_lib]]
name = "Conjecture7158"
moreLeanArgs = ["-DwarningAsError=true"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.19.0"
