import Audit407

#print axioms Conjecture407.LRTableau
#print axioms Conjecture407.LRTableau._sizeOf_1
#print axioms Conjecture407.LRTableau._sizeOf_inst
#print axioms Conjecture407.LRTableau.casesOn
#print axioms Conjecture407.LRTableau.colStrict
#print axioms Conjecture407.LRTableau.contained
#print axioms Conjecture407.LRTableau.content
#print axioms Conjecture407.LRTableau.entry
#print axioms Conjecture407.LRTableau.entry_injective
#print axioms Conjecture407.LRTableau.entry_lt
#print axioms Conjecture407.LRTableau.lattice
#print axioms Conjecture407.LRTableau.mk
#print axioms Conjecture407.LRTableau.mk._flat_ctor
#print axioms Conjecture407.LRTableau.mk.inj
#print axioms Conjecture407.LRTableau.mk.injEq
#print axioms Conjecture407.LRTableau.mk.sizeOf_spec
#print axioms Conjecture407.LRTableau.noConfusion
#print axioms Conjecture407.LRTableau.noConfusionType
#print axioms Conjecture407.LRTableau.rec
#print axioms Conjecture407.LRTableau.recOn
#print axioms Conjecture407.LRTableau.rowWeak
#print axioms Conjecture407.LRTableau.size_balance
#print axioms Conjecture407.LRTableau.size_balance._proof_1
#print axioms Conjecture407.NonzeroEntry
#print axioms Conjecture407.Partition
#print axioms Conjecture407.RatioAsymptotic
#print axioms Conjecture407.ReadingLE
#print axioms Conjecture407.ReadingLE.eq_1
#print axioms Conjecture407.SkewCell
#print axioms Conjecture407.cell_col_lt_card
#print axioms Conjecture407.cell_row_lt_card
#print axioms Conjecture407.conjecture407_false
#print axioms Conjecture407.diagram_card_eq_sum_rowLen
#print axioms Conjecture407.entryCount
#print axioms Conjecture407.entryCount.eq_1
#print axioms Conjecture407.lrCoefficient
#print axioms Conjecture407.lrCoefficient_eq_zero
#print axioms Conjecture407.lrCoefficient_eq_zero_of_not_contained
#print axioms Conjecture407.lrCoefficient_eq_zero_of_size_ne
#print axioms Conjecture407.lrTableauFinite
#print axioms Conjecture407.no_real_ratio_constant
#print axioms Conjecture407.no_tableau_same_positive_size
#print axioms Conjecture407.no_tableau_same_positive_size._proof_1
#print axioms Conjecture407.nonzeroCount
#print axioms Conjecture407.nonzeroCount_eq_zero
#print axioms Conjecture407.nonzeroEntryFinite
#print axioms Conjecture407.normalized_eventually_zero
#print axioms Conjecture407.normalized_tendsto_zero
#print axioms Conjecture407.not_ratioAsymptotic
#print axioms Conjecture407.not_ratioAsymptotic._proof_3
#print axioms Conjecture407.not_ratioAsymptotic._proof_4
#print axioms Conjecture407.partitionFinite
#print axioms Conjecture407.prefixCount
#print axioms Conjecture407.readingLE_antisymm
#print axioms Conjecture407.readingLE_antisymm._proof_1
#print axioms Conjecture407.readingLE_antisymm._proof_2
#print axioms Conjecture407.readingLE_refl
#print axioms Conjecture407.readingLE_total
#print axioms Conjecture407.readingLE_total._proof_1
#print axioms Conjecture407.readingLE_trans
#print axioms Conjecture407.readingLE_trans._proof_1
#print axioms Conjecture407.scale
#print axioms Conjecture407.scale._proof_1
#print axioms Conjecture407.scale._proof_2
#print axioms Conjecture407.scale_pos
#print axioms Conjecture407Audit.emptyPartition
#print axioms Conjecture407Audit.emptyPartition._proof_6
#print axioms Conjecture407Audit.emptyTableau
#print axioms Conjecture407Audit.emptyTableau._proof_1
#print axioms Conjecture407Audit.emptyTableau._proof_2
#print axioms Conjecture407Audit.emptyTableau._proof_3
#print axioms Conjecture407Audit.emptyTableau._proof_4
#print axioms Conjecture407Audit.emptyTableau._proof_5
#print axioms Conjecture407Audit.empty_coefficient_one
#print axioms Conjecture407Audit.partition_zero_unique
#print axioms Conjecture407Audit.table_one_zero
#print axioms Conjecture407Audit.table_two_zero
#print axioms Conjecture407Audit.table_zero_one
