name = "tlmc1554"
version = "1.0.0"
defaultTargets = ["Conjecture1554"]

[[lean_lib]]
name = "Conjecture1554"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.19.0"
