import Std

namespace Conjecture8657
universe u v
set_option maxRecDepth 100000
set_option maxHeartbeats 10000000

/-- Ordinary groups, with no extra identities imposed. -/
structure Group (A : Type u) where
  mul : A → A → A
  one : A
  inv : A → A
  assoc : ∀ a b c, mul (mul a b) c = mul a (mul b c)
  one_mul : ∀ a, mul one a = a
  mul_one : ∀ a, mul a one = a
  inv_mul : ∀ a, mul (inv a) a = one
  mul_inv : ∀ a, mul a (inv a) = one

abbrev Letter (A : Type u) := A × Bool
abbrev Word (A : Type u) := List (Letter A)
def flip {A : Type u} (x : Letter A) : Letter A := (x.1, !x.2)
@[simp] theorem flip_flip {A : Type u} (x : Letter A) : flip (flip x)=x := by
  cases x with | mk a b => cases b <;> rfl
def inverseWord {A : Type u} (w : Word A) : Word A := (w.map flip).reverse
@[simp] theorem inverse_append {A : Type u} (w z : Word A) :
    inverseWord (w++z)=inverseWord z++inverseWord w := by
  simp [inverseWord]
@[simp] theorem inverse_inverse {A : Type u} (w : Word A) : inverseWord (inverseWord w)=w := by
  simp [inverseWord, List.map_reverse, List.map_map, Function.comp_def]

/-- The congruence generated by free cancellation AND the square of every
    finite word. This is precisely the exponent-two Burnside presentation. -/
inductive WordRel {A : Type u} : Word A → Word A → Prop
  | refl (w) : WordRel w w
  | symm {w z} : WordRel w z → WordRel z w
  | trans {w z t} : WordRel w z → WordRel z t → WordRel w t
  | append {w z t s} : WordRel w z → WordRel t s → WordRel (w++t) (z++s)
  | cancel (x : Letter A) : WordRel [x, flip x] []
  | square (w : Word A) : WordRel (w++w) []

def wordSetoid (A : Type u) : Setoid (Word A) where
  r := WordRel
  iseqv := ⟨WordRel.refl, WordRel.symm, WordRel.trans⟩
abbrev BurnsideTwo (A : Type u) := Quotient (wordSetoid A)
def ofWord {A : Type u} (w : Word A) : BurnsideTwo A := Quotient.mk _ w
def burnsideMul {A : Type u} (x y : BurnsideTwo A) : BurnsideTwo A :=
  Quotient.liftOn₂ x y (fun w z => ofWord (w++z))
    (fun _ _ _ _ h k => Quotient.sound (WordRel.append h k))

theorem inverse_respects {A : Type u} {w z : Word A} (h : WordRel w z) :
    WordRel (inverseWord w) (inverseWord z) := by
  induction h with
  | refl w => exact WordRel.refl _
  | symm _ ih => exact WordRel.symm ih
  | trans _ _ ih ik => exact WordRel.trans ih ik
  | append _ _ ih ik => simpa using WordRel.append ik ih
  | cancel x => simpa [inverseWord] using WordRel.cancel x
  | square w => simpa [inverseWord] using WordRel.square (inverseWord w)
def burnsideInv {A : Type u} (x : BurnsideTwo A) : BurnsideTwo A :=
  Quotient.liftOn x (fun w => ofWord (inverseWord w))
    (fun _ _ h => Quotient.sound (inverse_respects h))
theorem contextual {A : Type u} {w z : Word A} (h : WordRel w z) (p s : Word A) :
    WordRel ((p++w)++s) ((p++z)++s) :=
  WordRel.append (WordRel.append (WordRel.refl p) h) (WordRel.refl s)
theorem word_mul_inverse {A : Type u} (w : Word A) : WordRel (w++inverseWord w) [] := by
  induction w with
  | nil => exact WordRel.refl []
  | cons x w ih =>
    have h : WordRel ((x::w)++inverseWord (x::w)) [x,flip x] := by
      simpa [inverseWord, List.append_assoc] using contextual ih [x] [flip x]
    exact WordRel.trans h (WordRel.cancel x)
theorem word_inverse_mul {A : Type u} (w : Word A) : WordRel (inverseWord w++w) [] := by
  simpa using word_mul_inverse (inverseWord w)

def burnsideGroup (A : Type u) : Group (BurnsideTwo A) where
  mul := burnsideMul
  one := ofWord []
  inv := burnsideInv
  assoc := by
    intro x y z
    refine Quotient.inductionOn₃ x y z ?_
    intro w t s
    change ofWord ((w++t)++s)=ofWord (w++(t++s))
    rw [List.append_assoc]
  one_mul := by
    intro x; refine Quotient.inductionOn x ?_; intro w; rfl
  mul_one := by
    intro x; refine Quotient.inductionOn x ?_; intro w
    change ofWord (w++[])=ofWord w
    rw [List.append_nil]
  inv_mul := by
    intro x; refine Quotient.inductionOn x ?_; intro w
    exact Quotient.sound (word_inverse_mul w)
  mul_inv := by
    intro x; refine Quotient.inductionOn x ?_; intro w
    exact Quotient.sound (word_mul_inverse w)

def ExponentTwo {B : Type v} (G : Group B) : Prop := ∀ x, G.mul x x=G.one
theorem burnside_exponent_two (A : Type u) : ExponentTwo (burnsideGroup A) := by
  intro x
  refine Quotient.inductionOn x ?_
  intro w
  exact Quotient.sound (WordRel.square w)

/-- The universal property into every exponent-two group. -/
def letterEval {A : Type u} {B : Type v} (G : Group B) (f : A → B) (x : Letter A) : B :=
  if x.2 then G.inv (f x.1) else f x.1
def eval {A : Type u} {B : Type v} (G : Group B) (f : A → B) : Word A → B
  | [] => G.one
  | x::w => G.mul (letterEval G f x) (eval G f w)
theorem eval_append {A : Type u} {B : Type v} (G : Group B) (f : A → B) (w z : Word A) :
    eval G f (w++z)=G.mul (eval G f w) (eval G f z) := by
  induction w with
  | nil => exact (G.one_mul _).symm
  | cons x w ih => simp only [List.cons_append, eval, ih, G.assoc]
theorem eval_respects {A : Type u} {B : Type v} (G : Group B) (hG : ExponentTwo G) (f : A → B)
    {w z : Word A} (h : WordRel w z) : eval G f w=eval G f z := by
  induction h with
  | refl w => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih ik => exact ih.trans ik
  | append _ _ ih ik => simp only [eval_append, ih, ik]
  | cancel x =>
    cases x with
    | mk a b => cases b <;> simp [eval, letterEval, flip, G.mul_one, G.mul_inv, G.inv_mul]
  | square w => simpa only [eval_append, eval] using hG (eval G f w)
def lift {A : Type u} {B : Type v} (G : Group B) (hG : ExponentTwo G) (f : A → B) (x : BurnsideTwo A) : B :=
  Quotient.liftOn x (eval G f) (fun _ _ h => eval_respects G hG f h)

def Hom {A : Type u} {B : Type v} (G : Group A) (H : Group B) (f : A → B) : Prop :=
  f G.one=H.one ∧ ∀ x y, f (G.mul x y)=H.mul (f x) (f y)
theorem inverse_unique {B : Type v} (G : Group B) {x y : B}
    (h : G.mul y x=G.one) : y=G.inv x := by
  calc
    y = G.mul y G.one := (G.mul_one y).symm
    _ = G.mul y (G.mul x (G.inv x)) := congrArg (G.mul y) (G.mul_inv x).symm
    _ = G.mul (G.mul y x) (G.inv x) := (G.assoc _ _ _).symm
    _ = G.inv x := by rw [h, G.one_mul]
theorem hom_preserves_inverse {A : Type u} {B : Type v} (G : Group A) (H : Group B)
    (f : A → B) (hf : Hom G H f) (x : A) : f (G.inv x)=H.inv (f x) := by
  apply inverse_unique H
  rw [← hf.2, G.inv_mul, hf.1]
theorem lift_hom {A : Type u} {B : Type v} (G : Group B) (hG : ExponentTwo G) (f : A → B) :
    Hom (burnsideGroup A) G (lift G hG f) := by
  refine ⟨rfl, ?_⟩
  intro x y
  refine Quotient.inductionOn₂ x y ?_
  exact eval_append G f
def generator {A : Type u} (a : A) : BurnsideTwo A := ofWord [(a,false)]
theorem lift_generators {A : Type u} {B : Type v} (G : Group B) (hG : ExponentTwo G) (f : A → B) (a : A) :
    lift G hG f (generator a)=f a := G.mul_one _
theorem hom_determined {A : Type u} {B : Type v} (G : Group B) (hG : ExponentTwo G) (f : A → B)
    (h : BurnsideTwo A → B) (hh : Hom (burnsideGroup A) G h)
    (hg : ∀ a, h (generator a)=f a) : h=lift G hG f := by
  funext x
  refine Quotient.inductionOn x ?_
  intro w
  induction w with
  | nil => exact hh.1
  | cons x w ih =>
    change h (burnsideMul (ofWord [x]) (ofWord w)) = G.mul (letterEval G f x) (eval G f w)
    have hm := hh.2 (ofWord [x]) (ofWord w)
    change h (burnsideMul (ofWord [x]) (ofWord w)) = G.mul (h (ofWord [x])) (h (ofWord w)) at hm
    change h (ofWord w)=eval G f w at ih
    rw [hm, ih]
    apply congrArg (fun z => G.mul z (eval G f w))
    cases x with
    | mk a b =>
      cases b
      · exact hg a
      · have hi := hom_preserves_inverse (burnsideGroup A) G h hh (generator a)
        change h (ofWord [(a,true)]) = G.inv (h (generator a)) at hi
        exact hi.trans (congrArg G.inv (hg a))
theorem burnside_universal_property {A : Type u} {B : Type v} (G : Group B) (hG : ExponentTwo G) (f : A → B) :
    ∃ h : BurnsideTwo A → B, Hom (burnsideGroup A) G h ∧ (∀ a, h (generator a)=f a) ∧
      ∀ k : BurnsideTwo A → B, Hom (burnsideGroup A) G k → (∀ a, k (generator a)=f a) → k=h :=
  ⟨lift G hG f, lift_hom G hG f, lift_generators G hG f, fun k hk hg => hom_determined G hG f k hk hg⟩


theorem exponent_two_inverse {B : Type v} (G : Group B) (hG : ExponentTwo G) (x : B) :
    G.inv x=x := (inverse_unique G (hG x)).symm
theorem exponent_two_commutative {B : Type v} (G : Group B) (hG : ExponentTwo G) (x y : B) :
    G.mul x y=G.mul y x := by
  have hi : G.mul (G.mul y x) (G.mul x y)=G.one := by
    calc
      G.mul (G.mul y x) (G.mul x y) = G.mul y (G.mul x (G.mul x y)) := G.assoc _ _ _
      _ = G.mul y (G.mul (G.mul x x) y) := congrArg (G.mul y) (G.assoc x x y).symm
      _ = G.one := by rw [hG x, G.one_mul, hG y]
  exact (inverse_unique G (hG (G.mul x y))).trans (inverse_unique G hi).symm
theorem left_multiply_exchange {B : Type v} (G : Group B) (hG : ExponentTwo G) (x y z : B) :
    G.mul x (G.mul y z)=G.mul y (G.mul x z) := by
  rw [← G.assoc, exponent_two_commutative G hG x y, G.assoc]

/-- A finite list of all products of subsets of a finite generating list.
    Repetitions are allowed; a covering list already proves finiteness. -/
def subsetProducts {B : Type v} (G : Group B) : List B → List B
  | [] => [G.one]
  | g::gs => subsetProducts G gs ++ (subsetProducts G gs).map (G.mul g)
theorem subsetProducts_length {B : Type v} (G : Group B) (gs : List B) :
    (subsetProducts G gs).length=2^gs.length := by
  induction gs with
  | nil => rfl
  | cons g gs ih =>
    simp only [subsetProducts, List.length_append, List.length_map, ih, List.length_cons, Nat.pow_succ]
    omega
theorem one_in_products {B : Type v} (G : Group B) (gs : List B) :
    G.one ∈ subsetProducts G gs := by
  induction gs with
  | nil => simp [subsetProducts]
  | cons g gs ih => exact List.mem_append_left _ ih

theorem generator_mul_products {B : Type v} (G : Group B) (hG : ExponentTwo G)
    (gs : List B) (g x : B) (hg : g∈gs) (hx : x∈subsetProducts G gs) :
    G.mul g x ∈ subsetProducts G gs := by
  induction gs generalizing g x with
  | nil => simp at hg
  | cons a gs ih =>
    have hx' : x∈subsetProducts G gs ∨ x∈(subsetProducts G gs).map (G.mul a) :=
      List.mem_append.mp hx
    rcases List.mem_cons.mp hg with he | hg
    · subst g
      rcases hx' with hx | hx
      · apply List.mem_append_right
        exact List.mem_map.mpr ⟨x, hx, rfl⟩
      · obtain ⟨y, hy, hxy⟩ := List.mem_map.mp hx
        subst x
        have he : G.mul a (G.mul a y)=y := by rw [← G.assoc, hG a, G.one_mul]
        rw [he]
        exact List.mem_append_left _ hy
    · rcases hx' with hx | hx
      · exact List.mem_append_left _ (ih g x hg hx)
      · obtain ⟨y, hy, hxy⟩ := List.mem_map.mp hx
        subst x
        rw [left_multiply_exchange G hG g a y]
        apply List.mem_append_right
        exact List.mem_map.mpr ⟨G.mul g y, ih g y hg hy, rfl⟩

theorem singleton_is_generator {A : Type u} (x : Letter A) : ofWord [x]=generator x.1 := by
  cases x with
  | mk a b =>
    cases b
    · rfl
    · exact exponent_two_inverse (burnsideGroup A) (burnside_exponent_two A) (generator a)
def generatingList (m : Nat) : List (BurnsideTwo (Fin m)) :=
  (List.finRange m).map generator
def coveringList (m : Nat) : List (BurnsideTwo (Fin m)) :=
  subsetProducts (burnsideGroup (Fin m)) (generatingList m)
theorem coveringList_length (m : Nat) : (coveringList m).length=2^m := by
  simp [coveringList, subsetProducts_length, generatingList, List.length_finRange]
theorem each_generator_listed (m : Nat) (a : Fin m) : generator a ∈ generatingList m := by
  apply List.mem_map.mpr
  exact ⟨a, List.mem_ofFn.mpr ⟨a, rfl⟩, rfl⟩
theorem every_word_covered (m : Nat) (w : Word (Fin m)) : ofWord w ∈ coveringList m := by
  induction w with
  | nil => exact one_in_products (burnsideGroup (Fin m)) (generatingList m)
  | cons x w ih =>
    change (burnsideGroup (Fin m)).mul (ofWord [x]) (ofWord w) ∈ coveringList m
    rw [singleton_is_generator]
    exact generator_mul_products (burnsideGroup (Fin m)) (burnside_exponent_two (Fin m))
      (generatingList m) (generator x.1) (ofWord w) (each_generator_listed m x.1) ih
theorem every_burnside_element_covered (m : Nat) (x : BurnsideTwo (Fin m)) : x∈coveringList m := by
  refine Quotient.inductionOn x ?_
  exact every_word_covered m
def HasFiniteCarrier (A : Type u) : Prop := ∃ xs : List A, ∀ x : A, x∈xs
theorem burnside_two_is_finite (m : Nat) : HasFiniteCarrier (BurnsideTwo (Fin m)) :=
  ⟨coveringList m, every_burnside_element_covered m⟩

/-- A bound on the first coordinates of ANY proposed finite parameter list. -/
def parameterBound : List (Nat × Nat) → Nat
  | [] => 2
  | (m,_)::ps => m+parameterBound ps
theorem parameterBound_ge_two (ps : List (Nat × Nat)) : 2≤parameterBound ps := by
  induction ps with
  | nil => decide
  | cons p ps ih => simp only [parameterBound]; omega
theorem listed_first_coordinate_le {m n : Nat} {ps : List (Nat × Nat)}
    (h : (m,n)∈ps) : m≤parameterBound ps := by
  induction ps with
  | nil => simp at h
  | cons p ps ih =>
    rcases List.mem_cons.mp h with he | h
    · subst p; simp only [parameterBound]; omega
    · have hi := ih h
      simp only [parameterBound]
      omega

theorem conjecture8657_counterexample (ps : List (Nat × Nat)) :
    ∃ m : Nat, 2≤m ∧ HasFiniteCarrier (BurnsideTwo (Fin m)) ∧ (m,2)∉ps := by
  refine ⟨parameterBound ps+1, ?_, burnside_two_is_finite _, ?_⟩
  · have hb := parameterBound_ge_two ps
    omega
  · intro h
    have hi := listed_first_coordinate_le h
    omega

theorem no_complete_finite_parameter_list :
    ¬∃ ps : List (Nat × Nat), ∀ m : Nat, 2≤m →
      HasFiniteCarrier (BurnsideTwo (Fin m)) → (m,2)∈ps := by
  rintro ⟨ps, hp⟩
  obtain ⟨m, hm, hf, hn⟩ := conjecture8657_counterexample ps
  exact hn (hp m hm hf)

end Conjecture8657
#print axioms Conjecture8657.burnside_universal_property
#print axioms Conjecture8657.every_burnside_element_covered
#print axioms Conjecture8657.conjecture8657_counterexample
#print axioms Conjecture8657.no_complete_finite_parameter_list
