import Mathlib.MeasureTheory.Measure.Prod
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.Logic.Relation
import Mathlib.Tactic.NormNum

/-!
# A graphon class with no finite-step representative

The unit interval is represented by the real line with Lebesgue measure
restricted to [0,1].  Equivalence is generated by measure-preserving
simultaneous relabellings of both variables and almost-everywhere equality.
-/

noncomputable section

open Set MeasureTheory
open scoped ENNReal

namespace Counterexample4408

def unitMeasure : Measure ℝ := volume.restrict (Icc 0 1)

instance unitMeasure_probability : IsProbabilityMeasure unitMeasure := by
  constructor
  simp [unitMeasure, Real.volume_Icc]

instance unitMeasure_noAtoms : NoAtoms unitMeasure := by
  unfold unitMeasure
  infer_instance

def squareMeasure : Measure (ℝ × ℝ) := unitMeasure.prod unitMeasure

instance squareMeasure_probability : IsProbabilityMeasure squareMeasure := by
  unfold squareMeasure
  infer_instance

abbrev Kernel := {f : ℝ × ℝ → ℝ // AEMeasurable f squareMeasure}

def productKernel : Kernel :=
  ⟨fun z => z.1 * z.2, (measurable_fst.mul measurable_snd).aemeasurable⟩

theorem productKernel_measurable : Measurable productKernel.1 :=
  measurable_fst.mul measurable_snd

theorem productKernel_symmetric (x y : ℝ) :
    productKernel.1 (x, y) = productKernel.1 (y, x) := by
  exact mul_comm x y

theorem productKernel_range {x y : ℝ} (hx : x ∈ Icc (0 : ℝ) 1)
    (hy : y ∈ Icc (0 : ℝ) 1) : productKernel.1 (x, y) ∈ Icc (0 : ℝ) 1 := by
  exact ⟨mul_nonneg hx.1 hy.1, mul_le_one₀ hx.2 hy.1 hy.2⟩

/-- Every countable set of values has a null inverse image under xy. -/
theorem productKernel_avoids_countable (S : Set ℝ) (hS : S.Countable) :
    ∀ᵐ z ∂squareMeasure, productKernel.1 z ∉ S := by
  apply (Measure.ae_prod_iff_ae_ae
    (hS.measurableSet.preimage productKernel_measurable).compl).mpr
  have hx : ∀ᵐ x ∂unitMeasure, x ≠ (0 : ℝ) := by
    simpa using (Set.countable_singleton (0 : ℝ)).ae_not_mem unitMeasure
  filter_upwards [hx] with x hx
  exact (hS.preimage (mul_right_injective₀ hx)).ae_not_mem unitMeasure

def valueLaw (U : Kernel) : Measure ℝ := squareMeasure.map U.1

theorem productKernel_valueLaw_countable (S : Set ℝ) (hS : S.Countable) :
    valueLaw productKernel S = 0 := by
  rw [valueLaw, Measure.map_apply productKernel_measurable hS.measurableSet]
  simpa only [ae_iff, not_not] using productKernel_avoids_countable S hS

/-- A generating operation: null modification, or simultaneous measure-preserving
relabeling followed by a null modification. No invertibility is required. -/
def Elementary (U V : Kernel) : Prop :=
  (U.1 =ᵐ[squareMeasure] V.1) ∨
  ∃ φ : ℝ → ℝ, MeasurePreserving φ unitMeasure unitMeasure ∧
    V.1 =ᵐ[squareMeasure] U.1 ∘ Prod.map φ φ

def ReconstructionEquivalent : Kernel → Kernel → Prop := Relation.EqvGen Elementary

theorem elementary_preserves_valueLaw {U V : Kernel} (h : Elementary U V) :
    valueLaw U = valueLaw V := by
  rcases h with h | ⟨φ, hφ, heq⟩
  · exact Measure.map_congr h
  · have hpair : MeasurePreserving (Prod.map φ φ) squareMeasure squareMeasure :=
      hφ.prod hφ
    have hU : AEMeasurable U.1 (squareMeasure.map (Prod.map φ φ)) := by
      rw [hpair.map_eq]
      exact U.2
    unfold valueLaw
    calc
      squareMeasure.map U.1 =
          (squareMeasure.map (Prod.map φ φ)).map U.1 := by rw [hpair.map_eq]
      _ = squareMeasure.map (U.1 ∘ Prod.map φ φ) :=
        hU.map_map_of_aemeasurable hpair.aemeasurable
      _ = squareMeasure.map V.1 := Measure.map_congr heq.symm

theorem equivalence_preserves_valueLaw {U V : Kernel}
    (h : ReconstructionEquivalent U V) : valueLaw U = valueLaw V := by
  induction h with
  | rel U V h => exact elementary_preserves_valueLaw h
  | refl U => rfl
  | symm U V h ih => exact ih.symm
  | trans U V Z hUV hVZ ihUV ihVZ => exact ihUV.trans ihVZ

def EssentiallyCountablyValued (U : Kernel) : Prop :=
  ∃ S : Set ℝ, S.Countable ∧ ∀ᵐ z ∂squareMeasure, U.1 z ∈ S

theorem no_countably_valued_representative {V : Kernel}
    (heq : ReconstructionEquivalent productKernel V) :
    ¬ EssentiallyCountablyValued V := by
  rintro ⟨S, hS, hmem⟩
  have hzero : squareMeasure (V.1 ⁻¹' S) = 0 := by
    calc
      squareMeasure (V.1 ⁻¹' S) = valueLaw V S :=
        (Measure.map_apply_of_aemeasurable V.2 hS.measurableSet).symm
      _ = valueLaw productKernel S := by rw [equivalence_preserves_valueLaw heq]
      _ = 0 := productKernel_valueLaw_countable S hS
  have hnot : ∀ᵐ z ∂squareMeasure, V.1 z ∉ S := by
    simpa only [ae_iff, not_not] using hzero
  obtain ⟨z, hz, hnz⟩ := (hmem.and hnot).exists
  exact hnz hz

/-- Algebraic finite-step form, allowing any assignment of vertices to finitely
many blocks. Omitting measurability of the assignment makes this predicate
broader than the usual finite-step graphon condition. -/
def HasFiniteStepForm (U : Kernel) : Prop :=
  ∃ n : ℕ, ∃ block : ℝ → Fin n, ∃ weights : Fin n → Fin n → ℝ,
    U.1 =ᵐ[squareMeasure] fun z => weights (block z.1) (block z.2)

theorem finiteStep_essentiallyCountablyValued {U : Kernel}
    (h : HasFiniteStepForm U) : EssentiallyCountablyValued U := by
  rcases h with ⟨n, block, weights, heq⟩
  let S : Set ℝ := Set.range (fun p : Fin n × Fin n => weights p.1 p.2)
  refine ⟨S, (Set.finite_range _).countable, ?_⟩
  filter_upwards [heq] with z hz
  exact ⟨(block z.1, block z.2), hz.symm⟩

/-- Main counterexample: the class of W(x,y)=xy contains no finite-step kernel. -/
theorem no_finite_step_representative {V : Kernel}
    (heq : ReconstructionEquivalent productKernel V) : ¬ HasFiniteStepForm V := by
  intro h
  exact no_countably_valued_representative heq (finiteStep_essentiallyCountablyValued h)

theorem no_finite_step_in_productKernel_class :
    ¬ ∃ V : Kernel, ReconstructionEquivalent productKernel V ∧ HasFiniteStepForm V := by
  rintro ⟨V, hV, hstep⟩
  exact no_finite_step_representative hV hstep

#print axioms productKernel_measurable
#print axioms productKernel_symmetric
#print axioms productKernel_range
#print axioms productKernel_avoids_countable
#print axioms equivalence_preserves_valueLaw
#print axioms no_countably_valued_representative
#print axioms no_finite_step_in_productKernel_class

end Counterexample4408
