#!/usr/bin/env python3
"""Independent check for conjecture 00000003824 (Python 3 standard library only).

Monomial crystals are implemented directly from the defining formulas
(phi, eps as maxima over ALL integers n in a window, by brute force; this is a
different method from the prefix/suffix scans used in Lean).  Monomials are
dicts {(i, m): exponent}.  We check:

 1. sl2, main reading: the subcrystal generated by Y_0^lam is a single string
    B(lam) for lam = 0..8 (so B(lam-2) is missing for every lam >= 2), in
    two index conventions (Kashiwara's A_m = Y_m Y_{m+1} with sums over k <= n,
    and the mirrored convention with sums over k >= n).  Nakajima's
    Y_{i,aq^k} convention is the same crystal after re-indexing.
 2. sl2, union reading: all highest-weight monomials of weight lam with
    support in a window -> many copies of B(lam), no B(mu) with mu < lam.
 3. sl2, tensor-power reading: products of lam fundamental monomials give
    B(1)^{(x)lam}; multiplicities = Clebsch-Gordan numbers; lam=2 is
    B(2)+B(0) (holds), lam=3 is B(3)+2B(1) (fails).
 4. sl3 (extra evidence): M(omega1+omega2) is B(theta) with 8 elements; the
    predicted B(theta)+B(0) would have 9.
"""
import sys
from itertools import product

FAIL = []


def check(cond, msg):
    print(("ok   " if cond else "FAIL ") + msg)
    if not cond:
        FAIL.append(msg)


def norm(M):
    return tuple(sorted((k, v) for k, v in M.items() if v != 0))


class MonomialCrystal:
    """Kashiwara monomial crystal for a Cartan matrix `a` with constants c.

    order = +1: phi_i = max_n sum_{k<=n} y_i(k)  (Kashiwara's convention)
    order = -1: the mirrored convention (sums over k>=n), obtained by m -> -m.
    A_{i,m} = Y_{i,m} Y_{i,m+1} prod_{j!=i} Y_{j,m+c_ji}^{a_ji}  (shift = 1).
    """

    def __init__(self, a, c, order=1, shift=1):
        self.a, self.c, self.order, self.shift = a, c, order, shift
        self.r = len(a)

    def A(self, i, m):
        d = {(i, m): 1}
        d[(i, m + self.shift)] = d.get((i, m + self.shift), 0) + 1
        for j in range(self.r):
            if j != i and self.a[j][i] != 0:
                key = (j, m + self.c[j][i])
                d[key] = d.get(key, 0) + self.a[j][i]
        return d

    def mul(self, M, D, s):
        R = dict(M)
        for k, v in D.items():
            R[k] = R.get(k, 0) + s * v
        return {k: v for k, v in R.items() if v != 0}

    def window(self, M, i):
        ms = [m for (j, m) in M if j == i]
        lo, hi = (min(ms) - 3, max(ms) + 3) if ms else (-3, 3)
        return lo, hi

    def P(self, M, i, n):
        # partial sum "up to n" in the chosen order
        if self.order == 1:
            return sum(v for (j, m), v in M.items() if j == i and m <= n)
        return sum(v for (j, m), v in M.items() if j == i and m >= n)

    def Q(self, M, i, n):
        # minus the complementary sum
        if self.order == 1:
            return -sum(v for (j, m), v in M.items() if j == i and m > n)
        return -sum(v for (j, m), v in M.items() if j == i and m < n)

    def phi(self, M, i):
        lo, hi = self.window(M, i)
        return max(self.P(M, i, n) for n in range(lo, hi + 1))

    def eps(self, M, i):
        lo, hi = self.window(M, i)
        return max(self.Q(M, i, n) for n in range(lo, hi + 1))

    def wt(self, M, i):
        return sum(v for (j, m), v in M.items() if j == i)

    def f(self, M, i):
        p = self.phi(M, i)
        if p <= 0:
            return None
        lo, hi = self.window(M, i)
        hits = [n for n in range(lo, hi + 1) if self.P(M, i, n) == p]
        n = min(hits) if self.order == 1 else max(hits)
        if self.order == 1:
            return self.mul(M, self.A(i, n), -1)
        return self.mul(M, self.A(i, n - self.shift), -1)

    def e(self, M, i):
        q = self.eps(M, i)
        if q <= 0:
            return None
        lo, hi = self.window(M, i)
        hits = [n for n in range(lo, hi + 1) if self.Q(M, i, n) == q]
        if self.order == 1:
            return self.mul(M, self.A(i, max(hits)), 1)
        return self.mul(M, self.A(i, min(hits) - self.shift), 1)

    def component(self, starts):
        seen = {norm(s): s for s in starts}
        todo = list(starts)
        while todo:
            M = todo.pop()
            for i in range(self.r):
                for N in (self.f(M, i), self.e(M, i)):
                    if N is not None and norm(N) not in seen:
                        seen[norm(N)] = N
                        todo.append(N)
        return list(seen.values())

    def check_axioms(self, comp):
        for M in comp:
            for i in range(self.r):
                if self.phi(M, i) - self.eps(M, i) != self.wt(M, i):
                    return False
                N = self.f(M, i)
                if N is not None and (self.e(N, i) is None or norm(self.e(N, i)) != norm(M)):
                    return False
                N = self.e(M, i)
                if N is not None and (self.f(N, i) is None or norm(self.f(N, i)) != norm(M)):
                    return False
        return True

    def hw_weights(self, comp):
        """Weights of highest-weight vertices (= highest weights of components)."""
        out = []
        for M in comp:
            if all(self.e(M, i) is None for i in range(self.r)):
                out.append(tuple(self.wt(M, i) for i in range(self.r)))
        return sorted(out)

    def components(self, verts):
        keys = {norm(M): M for M in verts}
        parent = {k: k for k in keys}

        def find(k):
            while parent[k] != k:
                parent[k] = parent[parent[k]]
                k = parent[k]
            return k
        for k, M in keys.items():
            for i in range(self.r):
                for N in (self.f(M, i), self.e(M, i)):
                    if N is not None:
                        parent[find(k)] = find(norm(N))
        comps = {}
        for k in keys:
            comps.setdefault(find(k), []).append(keys[k])
        return list(comps.values())


def predicted_sl2(lam):
    """Conjectured multiset of highest weights: dominant mu <= lam, each once."""
    return [mu for mu in range(lam, -1, -2)]


def sl2_main():
    print("== 1. sl2, main reading M(lam) = subcrystal generated by Y_0^lam")
    convs = [("Kashiwara A_m=Y_mY_{m+1}", MonomialCrystal([[2]], [[0]], 1, 1)),
             ("mirrored order m -> -m", MonomialCrystal([[2]], [[0]], -1, 1))]
    for name, C in convs:
        for lam in range(0, 9):
            start = {(0, 0): lam} if lam else {}
            comp = C.component([start])
            hw = [w[0] for w in C.hw_weights(comp)]
            pred = predicted_sl2(lam)
            ok_axioms = C.check_axioms(comp)
            is_string = (len(comp) == lam + 1 and hw == [lam])
            holds = sorted(hw) == sorted(pred) and len(comp) == sum(m + 1 for m in pred)
            check(ok_axioms and is_string and holds == (lam <= 1),
                  f"[{name}] lam={lam}: |M(lam)|={len(comp)}, highest weights {hw}; "
                  f"conjecture predicts {pred} with {sum(m + 1 for m in pred)} vertices -> "
                  f"{'holds' if holds else 'FAILS'}")
        if name.startswith("Kashiwara"):
            comp = C.component([{(0, 0): 2}])
            got = sorted(norm(M) for M in comp)
            want = sorted([(((0, 0), 2),), (((0, 0), 1), ((0, 1), -1)), (((0, 1), -2),)])
            check(got == want, f"M(2) = {{Y0^2, Y0 Y1^-1, Y1^-2}} exactly: {got}")


def sl2_union():
    print("== 2. sl2, union reading: all highest-weight monomials of weight lam (window)")
    C = MonomialCrystal([[2]], [[0]], 1, 1)
    W = range(0, 5)
    for lam in range(0, 4):
        hws = []
        for exps in product(range(-2, 4), repeat=len(W)):
            if sum(exps) != lam:
                continue
            M = {(0, m): x for m, x in zip(W, exps) if x}
            if C.e(M, 0) is None:
                hws.append(M)
        comps = [C.component([h]) for h in hws]
        hw_all = sorted({w for comp in comps for w in C.hw_weights(comp)})
        sizes = sorted({len(c) for c in comps})
        check(len(hws) >= 2 and hw_all == [(lam,)] and sizes == [lam + 1],
              f"lam={lam}: {len(hws)} highest-weight monomials of weight {lam} with support in "
              f"Y_0..Y_4 and exponents in [-2,3]; every component is B({lam}) -> "
              f"B({lam}) has multiplicity >= {len(hws)} != 1"
              + (f", and B(mu) for mu<{lam} never occurs" if lam >= 2 else ""))


def clebsch_gordan(lam):
    # B(1)^{(x)lam}: multiplicities by repeated tensoring with B(1)
    m = {1: 1} if lam >= 1 else {0: 1}
    for _ in range(lam - 1):
        new = {}
        for mu, k in m.items():
            for nu in (mu + 1, mu - 1):
                if nu >= 0:
                    new[nu] = new.get(nu, 0) + k
        m = new
    return m


def sl2_tensor():
    print("== 3. sl2, tensor-power reading: products of lam fundamental monomials")
    C = MonomialCrystal([[2]], [[0]], 1, 1)
    for lam in range(1, 6):
        prods = []
        for choice in product([0, 1], repeat=lam):
            M = {}
            for j, c in enumerate(choice):
                M[(0, 2 * j + c)] = 1 if c == 0 else -1
            prods.append(M)
        comp = C.component(prods)
        hw = [w[0] for w in C.hw_weights(comp)]
        mult = {}
        for w in hw:
            mult[w] = mult.get(w, 0) + 1
        cg = clebsch_gordan(lam)
        pred = {mu: 1 for mu in predicted_sl2(lam)}
        check(len(comp) == 2 ** lam and mult == cg and C.check_axioms(comp)
              and (mult == pred) == (lam <= 2),
              f"lam={lam}: {len(comp)} monomials, multiplicities {dict(sorted(mult.items(), reverse=True))}"
              f" (Clebsch-Gordan {dict(sorted(cg.items(), reverse=True))}); conjecture predicts "
              f"{dict(sorted(pred.items(), reverse=True))} -> {'holds' if mult == pred else 'FAILS'}")


def sl3_adjoint():
    print("== 4. sl3 extra evidence: M(omega1+omega2)")
    a = [[2, -1], [-1, 2]]
    c = [[0, 0], [1, 0]]          # c_ij + c_ji = 1 for i != j (Kashiwara's condition)
    C = MonomialCrystal(a, c, 1, 1)
    start = {(0, 0): 1, (1, 0): 1}
    comp = C.component([start])
    hw = C.hw_weights(comp)
    check(len(comp) == 8 and hw == [(1, 1)] and C.check_axioms(comp),
          f"|M(w1+w2)| = {len(comp)} = dim of the adjoint rep, highest weights {hw}; "
          f"conjecture predicts B(theta)+B(0) with 9 vertices -> FAILS")


if __name__ == "__main__":
    sl2_main()
    sl2_union()
    sl2_tensor()
    sl3_adjoint()
    if FAIL:
        print(f"{len(FAIL)} CHECK(S) FAILED")
        sys.exit(1)
    print("ALL CHECKS PASSED")
