import Mathlib

/-!
# Conjecture 00000004280: a rank-1 pair of groups with isomorphic endomorphism rings

Conjecture 00000004280 claims that there exist two non-isomorphic abelian groups with
ring-isomorphic endomorphism rings, and that the minimal rank of such a realization is `3`.

The minimal rank is at most `1`. Let `B ≤ ℚ` be the subgroup generated by the fractions
`1/p`, `p` prime (so every `p`-adic valuation is `≥ −1` on `B`). Then:

* `ℤ` and `B` both have rank `≤ 1` (two elements of `ℚ` are always `ℤ`-linearly dependent);
* `End(ℤ) ≅ ℤ ≅ End(B)` as rings: every endomorphism of `B` is multiplication by
  `c = f(1)`, and `c` is an integer because `c/p ∈ B` for every prime `p`, which by the
  `p`-adic valuations `v_p ≥ −1` on `B` forces `v_p(c) ≥ 0`;
* `B ≇ ℤ`: in `B` the element `1 = p · (1/p)` is divisible by every prime, while a nonzero
  integer has only finitely many prime divisors.
-/

namespace Submission00000004280

/-- `A` and `B` realize the separation: their endomorphism rings are isomorphic as rings, but
the groups are not isomorphic. -/
def Separates (A B : Type) [AddCommGroup A] [AddCommGroup B] : Prop :=
  Nonempty (AddMonoid.End A ≃+* AddMonoid.End B) ∧ IsEmpty (A ≃+ B)

/-- The second claim, in its weakest form: every realization has a group of rank at least
`3`. Any reading of "the minimal rank of a realization is `3`" (minimum, maximum, or rank of
the first group) implies this. Rank is Mathlib's `Module.rank ℤ`. -/
def MinimalRankThree : Prop :=
  ∀ (A B : Type) [AddCommGroup A] [AddCommGroup B], Separates A B →
    3 ≤ Module.rank ℤ A ∨ 3 ≤ Module.rank ℤ B

/-- The subgroup of `ℚ` generated by the fractions `1/p`, `p` prime. -/
def Bsub : AddSubgroup ℚ := AddSubgroup.closure {x | ∃ p : ℕ, p.Prime ∧ x = 1 / p}

/-- The group `B`. -/
abbrev B := Bsub

theorem inv_mem {p : ℕ} (hp : p.Prime) : (1 / p : ℚ) ∈ Bsub :=
  AddSubgroup.subset_closure ⟨p, hp, rfl⟩

theorem one_mem : (1 : ℚ) ∈ Bsub := by
  have := Bsub.nsmul_mem (inv_mem Nat.prime_two) 2
  norm_num at this
  exact this

/-- `p`-adic valuations on `B` are at least `−1`. -/
theorem val_ge {x : ℚ} (hx : x ∈ Bsub) {p : ℕ} [Fact p.Prime] (hx0 : x ≠ 0) :
    -1 ≤ padicValRat p x := by
  induction hx using AddSubgroup.closure_induction with
  | mem y hy =>
    obtain ⟨q, hq, rfl⟩ := hy
    rw [one_div, padicValRat.inv, ← padicValRat_of_nat]
    have : padicValNat p q ≤ 1 := by
      by_cases hpq : p = q
      · subst hpq; simp
      · rw [padicValNat.eq_zero_of_not_dvd]
        · omega
        · intro hdvd
          exact hpq ((Nat.prime_dvd_prime_iff_eq Fact.out hq).1 hdvd)
    omega
  | zero => exact absurd rfl hx0
  | add y z _ _ ihy ihz =>
    by_cases hy0 : y = 0
    · subst hy0; simp only [zero_add] at hx0 ⊢; exact ihz hx0
    by_cases hz0 : z = 0
    · subst hz0; simp only [add_zero] at hx0 ⊢; exact ihy hx0
    exact le_trans (le_min (ihy hy0) (ihz hz0)) (padicValRat.min_le_padicValRat_add hx0)
  | neg y _ ihy =>
    rw [padicValRat.neg]
    exact ihy (neg_ne_zero.1 hx0)

/-- An element of `B`, multiplied by `1/p` for every prime `p`, staying in `B`, is an integer. -/
theorem den_eq_one {c : ℚ} (hc : ∀ p : ℕ, p.Prime → c / p ∈ Bsub) : c.den = 1 := by
  by_contra hden
  obtain ⟨q, hq, hqd⟩ := Nat.exists_prime_and_dvd hden
  have := Fact.mk hq
  have hc0 : c ≠ 0 := by
    rintro rfl; exact hden rfl
  have hval := val_ge (hc q hq) (p := q) (div_ne_zero hc0 (by exact_mod_cast hq.ne_zero))
  rw [padicValRat.div hc0 (by exact_mod_cast hq.ne_zero), padicValRat.self hq.one_lt] at hval
  -- `v_q(c) = v_q(num) − v_q(den) ≤ −1`
  have hnum : padicValInt q c.num = 0 := by
    apply padicValInt.eq_zero_of_not_dvd
    intro hdvd
    have h1 : q ∣ c.num.natAbs := by
      have := Int.natAbs_dvd_natAbs.2 hdvd
      simpa using this
    have h2 : q ∣ Nat.gcd c.num.natAbs c.den := Nat.dvd_gcd h1 hqd
    rw [Nat.Coprime.gcd_eq_one c.reduced] at h2
    exact hq.one_lt.ne' (Nat.dvd_one.1 h2)
  have hdenv : 1 ≤ padicValNat q c.den := one_le_padicValNat_of_dvd c.den_nz hqd
  have : padicValRat q c = padicValInt q c.num - padicValNat q c.den := rfl
  omega

/-- Every additive endomorphism of `B` is multiplication by `f 1`, as rationals. -/
theorem endo_apply (f : AddMonoid.End B) (x : B) :
    ((f x : ℚ)) = (x : ℚ) * (f ⟨1, one_mem⟩ : ℚ) := by
  set q : ℚ := (x : ℚ)
  have hrel : (q.den : ℕ) • x = q.num • (⟨1, one_mem⟩ : B) := by
    apply Subtype.ext
    simp only [AddSubgroup.coe_nsmul, AddSubgroup.coe_zsmul, nsmul_eq_mul, zsmul_eq_mul, mul_one]
    exact Rat.den_mul_eq_num q
  have := congrArg (fun y : B => (y : ℚ)) (congrArg f hrel)
  simp only [map_nsmul, map_zsmul, AddSubgroup.coe_nsmul, AddSubgroup.coe_zsmul, nsmul_eq_mul,
    zsmul_eq_mul] at this
  have hden : (q.den : ℚ) ≠ 0 := by exact_mod_cast q.den_nz
  calc (f x : ℚ) = (q.den : ℚ)⁻¹ * ((q.den : ℚ) * (f x : ℚ)) := by field_simp
    _ = (q.den : ℚ)⁻¹ * ((q.num : ℚ) * (f ⟨1, one_mem⟩ : ℚ)) := by rw [this]
    _ = q * (f ⟨1, one_mem⟩ : ℚ) := by
        rw [← mul_assoc]
        congr 1
        rw [inv_mul_eq_div]
        exact Rat.num_div_den q

/-- The integer `m`, viewed in the endomorphism ring, acts as multiplication by `m`. -/
theorem intCast_apply {M : Type*} [AddCommGroup M] (m : ℤ) (x : M) :
    ((m : AddMonoid.End M) x) = m • x := rfl

/-- The canonical map `ℤ → End(B)` is a ring isomorphism. -/
theorem castB_bijective : Function.Bijective (Int.castRingHom (AddMonoid.End B)) := by
  constructor
  · intro m n h
    have := congrArg (fun f : AddMonoid.End B => ((f ⟨1, one_mem⟩ : B) : ℚ)) h
    simp only [eq_intCast, intCast_apply, AddSubgroup.coe_zsmul, zsmul_eq_mul, mul_one,
      Int.cast_inj] at this
    exact this
  · intro f
    set c : ℚ := (f ⟨1, one_mem⟩ : ℚ) with hcdef
    have hc : ∀ p : ℕ, p.Prime → c / p ∈ Bsub := fun p hp => by
      have := (f ⟨1 / p, inv_mem hp⟩).2
      rw [endo_apply] at this
      simpa [div_eq_inv_mul, mul_comm] using this
    have hden := den_eq_one hc
    refine ⟨c.num, ?_⟩
    have hnum : (c.num : ℚ) = c := by
      rw [← Rat.num_div_den c, hden]; simp
    ext x
    rw [eq_intCast, intCast_apply, AddSubgroup.coe_zsmul, zsmul_eq_mul, endo_apply, ← hcdef,
      hnum, mul_comm]

/-- The canonical map `ℤ → End(ℤ)` is a ring isomorphism. -/
theorem castZ_bijective : Function.Bijective (Int.castRingHom (AddMonoid.End ℤ)) := by
  constructor
  · intro m n h
    have := congrArg (fun f : AddMonoid.End ℤ => f 1) h
    simp only [eq_intCast, intCast_apply, smul_eq_mul, mul_one] at this
    exact this
  · intro f
    refine ⟨f 1, AddMonoidHom.ext fun x => ?_⟩
    show ((f 1 : AddMonoid.End ℤ) x) = f x
    rw [intCast_apply, smul_eq_mul]
    have : f x = f (x • (1 : ℤ)) := by rw [smul_eq_mul, mul_one]
    rw [this, map_zsmul, smul_eq_mul, mul_comm]

/-- `End(ℤ) ≃+* End(B)`. -/
noncomputable def endEquiv : AddMonoid.End ℤ ≃+* AddMonoid.End B :=
  (RingEquiv.ofBijective _ castZ_bijective).symm.trans (RingEquiv.ofBijective _ castB_bijective)

/-- `ℤ ≇ B`: in `B` the element `1` is divisible by every prime. -/
theorem not_iso : IsEmpty (ℤ ≃+ B) := by
  constructor
  intro e
  set k : ℤ := e.symm ⟨1, one_mem⟩
  have hk : k ≠ 0 := by
    intro h
    have : (⟨1, one_mem⟩ : B) = 0 := by
      rw [← e.apply_symm_apply ⟨1, one_mem⟩]
      change e k = 0
      rw [h, map_zero]
    exact one_ne_zero (congrArg Subtype.val this)
  have hdiv : ∀ p : ℕ, p.Prime → (p : ℤ) ∣ k := fun p hp => by
    refine ⟨e.symm ⟨1 / p, inv_mem hp⟩, ?_⟩
    have h1 : (p : ℕ) • (⟨1 / p, inv_mem hp⟩ : B) = ⟨1, one_mem⟩ := by
      apply Subtype.ext
      simp [hp.ne_zero]
    rw [show k = e.symm ⟨1, one_mem⟩ from rfl, ← h1, map_nsmul, nsmul_eq_mul]
  obtain ⟨p, hpk, hp⟩ := Nat.exists_infinite_primes (k.natAbs + 1)
  have := Int.natAbs_dvd_natAbs.2 (hdiv p hp)
  simp only [Int.natAbs_natCast] at this
  have := Nat.le_of_dvd (Int.natAbs_pos.2 hk) this
  omega

/-- `B` has rank at most `1`: any two elements are `ℤ`-linearly dependent. -/
theorem rank_B_le : Module.rank ℤ B ≤ 1 := by
  apply rank_le
  intro s hs
  by_contra hcard
  push Not at hcard
  obtain ⟨x, hx, y, hy, hxy⟩ := Finset.one_lt_card.1 hcard
  have hs' := hs
  have hx0 : x ≠ 0 := fun h => hs.ne_zero ⟨x, hx⟩ (by simpa using h)
  have ha : (x : ℚ) ≠ 0 := fun h => hx0 (Subtype.ext h)
  set a : ℚ := (x : ℚ)
  set b : ℚ := (y : ℚ)
  rw [linearIndependent_iff'] at hs
  have key := hs {⟨x, hx⟩, ⟨y, hy⟩}
    (fun i => if i = ⟨x, hx⟩ then b.num * a.den else -(a.num * b.den)) ?_ ⟨x, hx⟩ (by simp)
  · simp only [if_true, mul_eq_zero, Int.natCast_eq_zero] at key
    rcases key with h | h
    · have hb : b = 0 := Rat.num_eq_zero.1 h
      have hy0 : y = 0 := Subtype.ext hb
      exact hs'.ne_zero ⟨y, hy⟩ (by simpa using hy0) |>.elim
    · exact a.den_nz h
  · have hne : (⟨x, hx⟩ : s) ≠ ⟨y, hy⟩ := fun h => hxy (congrArg Subtype.val h)
    rw [Finset.sum_pair hne]
    simp only [if_true, if_neg (Ne.symm hne)]
    apply Subtype.ext
    simp only [AddSubgroup.coe_add, AddSubgroup.coe_zsmul, zsmul_eq_mul, AddSubgroup.coe_zero]
    have h1 := Rat.den_mul_eq_num a
    have h2 := Rat.den_mul_eq_num b
    push_cast
    linear_combination (b.num : ℚ) * h1 - (a.num : ℚ) * h2

/-- `ℤ` has rank `1`. -/
theorem rank_Z : Module.rank ℤ ℤ = 1 := Module.rank_self ℤ

/-- `(ℤ, B)` realizes the separation. -/
theorem separates_Z_B : Separates ℤ B := ⟨⟨endEquiv⟩, not_iso⟩

/-- **Conjecture 00000004280 is false**: the realization `(ℤ, B)` has rank `1 < 3`. Whatever
the first claim (`P`) means, the conjunction is false. -/
theorem conjecture_00000004280_false (P : Prop) : ¬ (P ∧ MinimalRankThree) := by
  rintro ⟨-, h⟩
  rcases h ℤ B separates_Z_B with h3 | h3
  · rw [rank_Z] at h3
    exact absurd h3 (by norm_num)
  · have := h3.trans rank_B_le
    exact absurd this (by norm_num)

end Submission00000004280

#print axioms Submission00000004280.conjecture_00000004280_false
