import Mathlib.GroupTheory.PresentedGroup
import Mathlib.GroupTheory.Subgroup.Center
import Mathlib.GroupTheory.Subgroup.Centralizer
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.GroupTheory.Perm.Basic
import Mathlib.Tactic.Group
import Mathlib.Tactic.NormNum

/-!
# Literal square-of-full-twist claim in conjecture 00000000637

The standard Artin definition of the three-strand braid group is used directly.
Pure braids are the kernel of its canonical strand-permutation homomorphism.
The full twist is `(σ₁ σ₂)^3 = Δ²`, not the half twist `Δ = σ₁ σ₂ σ₁`.

Exact source (both conjuncts retained):
English: For n ≥ 3, Z(P_n) is generated by the square of the full twist,
and the stable commutator length of P_n/Z is bounded.
Chinese: P_n 的中心由全 twist 的平方生成(n ≥ 3),且商 P_n/Z 的稳定交换子长度有界.

This file disproves the necessary center assertion at n = 3. Its last theorem
then negates the required conjunction for every possible second proposition.
In particular, it applies to bounded stable commutator length, regardless of
the domain/uniformity convention intended in that clause. No scl theorem is
asserted, and no custom definition of scl is needed by the disproof.
-/

namespace Conjecture637

def artinRelator : FreeGroup Bool :=
  (FreeGroup.of false * FreeGroup.of true * FreeGroup.of false) *
    (FreeGroup.of true * FreeGroup.of false * FreeGroup.of true)⁻¹

def braidRelations : Set (FreeGroup Bool) := {artinRelator}

/-- The usual two-generator Artin presentation of the braid group on three strands. -/
abbrev BraidThree := PresentedGroup braidRelations

def sigmaOne : BraidThree := PresentedGroup.of false
def sigmaTwo : BraidThree := PresentedGroup.of true

theorem artin_relation : sigmaOne * sigmaTwo * sigmaOne =
    sigmaTwo * sigmaOne * sigmaTwo := by
  exact PresentedGroup.mk_eq_mk_of_mul_inv_mem (by simp [braidRelations, artinRelator])

def permutationGenerator : Bool → Equiv.Perm (Fin 3)
  | false => Equiv.swap 0 1
  | true => Equiv.swap 1 2

theorem permutation_respects_relation :
    ∀ r ∈ braidRelations, FreeGroup.lift permutationGenerator r = 1 := by
  intro r hr
  simp only [braidRelations, Set.mem_singleton_iff] at hr
  subst r
  simp only [artinRelator, map_mul, map_inv, FreeGroup.lift.of]
  decide

def strandPermutation : BraidThree →* Equiv.Perm (Fin 3) :=
  PresentedGroup.toGroup permutation_respects_relation

theorem strandPermutation_sigmaOne : strandPermutation sigmaOne = Equiv.swap 0 1 := by
  exact PresentedGroup.toGroup.of permutation_respects_relation

theorem strandPermutation_sigmaTwo : strandPermutation sigmaTwo = Equiv.swap 1 2 := by
  exact PresentedGroup.toGroup.of permutation_respects_relation

/-- The pure three-strand braid group, defined by fixing each strand. -/
def pureBraidSubgroup : Subgroup BraidThree := strandPermutation.ker
abbrev PureBraidThree := pureBraidSubgroup

def halfTwist : BraidThree := sigmaOne * sigmaTwo * sigmaOne
def fullTwist : BraidThree := (sigmaOne * sigmaTwo) ^ 3

theorem fullTwist_eq_halfTwist_sq : fullTwist = halfTwist ^ 2 := by
  unfold fullTwist halfTwist
  calc
    (sigmaOne * sigmaTwo) ^ 3 =
        (sigmaOne * sigmaTwo * sigmaOne) * (sigmaTwo * sigmaOne * sigmaTwo) := by
      simp only [pow_succ, pow_zero, one_mul, mul_assoc]
    _ = (sigmaOne * sigmaTwo * sigmaOne) * (sigmaOne * sigmaTwo * sigmaOne) := by
      rw [← artin_relation]
    _ = (sigmaOne * sigmaTwo * sigmaOne) ^ 2 := (pow_two _).symm

theorem halfTwist_mul_sigmaOne : halfTwist * sigmaOne = sigmaTwo * halfTwist := by
  unfold halfTwist
  calc
    (sigmaOne * sigmaTwo * sigmaOne) * sigmaOne =
        (sigmaTwo * sigmaOne * sigmaTwo) * sigmaOne := by rw [artin_relation]
    _ = sigmaTwo * (sigmaOne * sigmaTwo * sigmaOne) := by group

theorem halfTwist_mul_sigmaTwo : halfTwist * sigmaTwo = sigmaOne * halfTwist := by
  unfold halfTwist
  calc
    (sigmaOne * sigmaTwo * sigmaOne) * sigmaTwo =
        sigmaOne * (sigmaTwo * sigmaOne * sigmaTwo) := by group
    _ = sigmaOne * (sigmaOne * sigmaTwo * sigmaOne) := by rw [← artin_relation]

theorem fullTwist_commutes_sigmaOne : sigmaOne * fullTwist = fullTwist * sigmaOne := by
  rw [fullTwist_eq_halfTwist_sq, pow_two]
  calc
    sigmaOne * (halfTwist * halfTwist) = (sigmaOne * halfTwist) * halfTwist := by group
    _ = (halfTwist * sigmaTwo) * halfTwist := by rw [halfTwist_mul_sigmaTwo]
    _ = halfTwist * (sigmaTwo * halfTwist) := by group
    _ = halfTwist * (halfTwist * sigmaOne) := by rw [halfTwist_mul_sigmaOne]
    _ = halfTwist * halfTwist * sigmaOne := by group

theorem fullTwist_commutes_sigmaTwo : sigmaTwo * fullTwist = fullTwist * sigmaTwo := by
  rw [fullTwist_eq_halfTwist_sq, pow_two]
  calc
    sigmaTwo * (halfTwist * halfTwist) = (sigmaTwo * halfTwist) * halfTwist := by group
    _ = (halfTwist * sigmaOne) * halfTwist := by rw [halfTwist_mul_sigmaOne]
    _ = halfTwist * (sigmaOne * halfTwist) := by group
    _ = halfTwist * (halfTwist * sigmaTwo) := by rw [halfTwist_mul_sigmaTwo]
    _ = halfTwist * halfTwist * sigmaTwo := by group

theorem fullTwist_mem_center : fullTwist ∈ Subgroup.center BraidThree := by
  rw [Subgroup.mem_center_iff]
  intro g
  have generators : ∀ j : Bool, PresentedGroup.of j ∈
      Subgroup.centralizer ({fullTwist} : Set BraidThree) := by
    intro j
    cases j
    · simpa [Subgroup.mem_centralizer_iff] using fullTwist_commutes_sigmaOne.symm
    · simpa [Subgroup.mem_centralizer_iff] using fullTwist_commutes_sigmaTwo.symm
  have hg := PresentedGroup.generated_by braidRelations
    (Subgroup.centralizer ({fullTwist} : Set BraidThree)) generators g
  exact (Subgroup.mem_centralizer_iff.mp hg fullTwist (Set.mem_singleton fullTwist)).symm

theorem fullTwist_is_pure : fullTwist ∈ pureBraidSubgroup := by
  change strandPermutation fullTwist = 1
  simp only [fullTwist, map_pow, map_mul,
    strandPermutation_sigmaOne, strandPermutation_sigmaTwo]
  decide

def pureFullTwist : PureBraidThree := ⟨fullTwist, fullTwist_is_pure⟩

theorem pureFullTwist_mem_center : pureFullTwist ∈ Subgroup.center PureBraidThree := by
  rw [Subgroup.mem_center_iff]
  intro g
  apply Subtype.ext
  exact Subgroup.mem_center_iff.mp fullTwist_mem_center g.val

def exponentGenerator : Bool → Multiplicative ℤ := fun _ => Multiplicative.ofAdd 1

theorem exponent_respects_relation :
    ∀ r ∈ braidRelations, FreeGroup.lift exponentGenerator r = 1 := by
  intro r hr
  simp only [braidRelations, Set.mem_singleton_iff] at hr
  subst r
  simp [artinRelator, exponentGenerator]
  group

def exponentSum : BraidThree →* Multiplicative ℤ :=
  PresentedGroup.toGroup exponent_respects_relation

theorem exponentSum_sigmaOne : exponentSum sigmaOne = Multiplicative.ofAdd 1 := by
  exact PresentedGroup.toGroup.of exponent_respects_relation

theorem exponentSum_sigmaTwo : exponentSum sigmaTwo = Multiplicative.ofAdd 1 := by
  exact PresentedGroup.toGroup.of exponent_respects_relation

theorem exponentSum_fullTwist : exponentSum fullTwist = Multiplicative.ofAdd 6 := by
  simp [fullTwist, exponentSum_sigmaOne, exponentSum_sigmaTwo]
  rfl

theorem fullTwist_not_zpower_square (k : ℤ) : (fullTwist ^ 2) ^ k ≠ fullTwist := by
  intro h
  have he := congrArg (fun g => Multiplicative.toAdd (exponentSum g)) h
  simp only [map_zpow, map_pow, exponentSum_fullTwist, toAdd_zpow,
    toAdd_pow, toAdd_ofAdd] at he
  norm_num at he
  omega

theorem pureFullTwist_not_mem_square_zpowers :
    pureFullTwist ∉ Subgroup.zpowers (pureFullTwist ^ 2) := by
  intro h
  obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp h
  exact fullTwist_not_zpower_square k (congrArg Subtype.val hk)

theorem center_not_generated_by_square_of_fullTwist :
    Subgroup.center PureBraidThree ≠ Subgroup.zpowers (pureFullTwist ^ 2) := by
  intro h
  apply pureFullTwist_not_mem_square_zpowers
  rw [← h]
  exact pureFullTwist_mem_center

/-- Three strands meet the stated range of the original universal claim. -/
theorem three_is_in_source_range : 3 ≤ (3 : ℕ) := by decide

/-- The required n = 3 conjunction, with its second proposition left arbitrary. -/
def RequiredConjunctionAtThree (secondConjunct : Prop) : Prop :=
  Subgroup.center PureBraidThree = Subgroup.zpowers (pureFullTwist ^ 2) ∧ secondConjunct

/-- Refuting the necessary first conjunct refutes the combined source claim,
for any interpretation of its bounded-scl second conjunct. -/
theorem required_conjunction_at_three_false (secondConjunct : Prop) :
    ¬ RequiredConjunctionAtThree secondConjunct := by
  intro h
  exact center_not_generated_by_square_of_fullTwist h.1

end Conjecture637
