import Mathlib

/-!
# Conjecture 00000001144 (disproof)

"The growth rate of hyperbolic-type Weyl groups of Kac-Moody algebras is 2."

We build, for a generalized Cartan matrix (GCM) `A`, its Weyl group as the subgroup of
`GL_n(Z)` generated by the fundamental reflections `r_i(alpha_j) = alpha_j - a_ij alpha_i`
acting on the root lattice (basis of simple roots), the word-length balls and spheres with
respect to `{r_i}`, and the exponential growth rate `limsup_k (#sphere_k)^(1/k)`.

`FF` is the GCM of the over-extended algebra `A_1^{++}` (Feingold-Frenkel's hyperbolic
algebra). We prove it is hyperbolic and that its Weyl group satisfies
`#ball_k <= 13 (k+1) (5/3)^k`, so the growth rate is at most `19/10`, not `2`.
-/

open Filter Finset

namespace C1144

/-! ## 1. Generalized Cartan matrices and hyperbolic type -/

/-- A generalized Cartan matrix of rank `n`: `a_ii = 2`, `a_ij <= 0` for `i != j`,
and `a_ij = 0 <-> a_ji = 0`. -/
structure GCM (n : ℕ) where
  A : Matrix (Fin n) (Fin n) ℤ
  diag : ∀ i, A i i = 2
  off : ∀ i j, i ≠ j → A i j ≤ 0
  zero_iff : ∀ i j, A i j = 0 ↔ A j i = 0

/-- Indecomposable: no splitting of the index set into two nonempty parts `J`, `Jᶜ` with
`a_ij = 0` for all `i ∈ J`, `j ∉ J`. -/
def Indecomposable {n : ℕ} (A : Matrix (Fin n) (Fin n) ℤ) : Prop :=
  ∀ J : Finset (Fin n), J.Nonempty → J ≠ univ → ∃ i ∈ J, ∃ j ∉ J, A i j ≠ 0

/-- The quadratic form `x ↦ xᵀ S x`. -/
def qf {n : ℕ} (S : Matrix (Fin n) (Fin n) ℝ) (x : Fin n → ℝ) : ℝ := x ⬝ᵥ S.mulVec x

/-- Hyperbolic type (symmetrizable case): `A` is indecomposable and `A = D S` with `D`
diagonal with positive integer entries and `S` symmetric, `S` is indefinite, and for every
proper subset `J` of the index set the principal submatrix `S_J` is positive semidefinite
(stated for vectors supported on `J`). -/
def IsHyperbolic {n : ℕ} (C : GCM n) : Prop :=
  Indecomposable C.A ∧
  ∃ (d : Fin n → ℕ) (S : Matrix (Fin n) (Fin n) ℝ),
    (∀ i, 0 < d i) ∧ S.IsSymm ∧ (∀ i j, (C.A i j : ℝ) = d i * S i j) ∧
    (∃ x, qf S x < 0) ∧ (∃ x, 0 < qf S x) ∧
    ∀ J : Finset (Fin n), J ≠ univ → ∀ x : Fin n → ℝ, (∀ i ∉ J, x i = 0) → 0 ≤ qf S x

/-! ## 2. The Weyl group, word-length balls and spheres, growth rate -/

/-- Matrix of the fundamental reflection `r_i` on the root lattice in the basis of simple
roots: column `j` is `r_i(alpha_j) = alpha_j - a_ij alpha_i`. -/
def reflMat {n : ℕ} (A : Matrix (Fin n) (Fin n) ℤ) (i : Fin n) : Matrix (Fin n) (Fin n) ℤ :=
  1 - Matrix.of (fun k j => if k = i then A i j else 0)

lemma reflMat_mul_self {n : ℕ} (C : GCM n) (i : Fin n) :
    reflMat C.A i * reflMat C.A i = 1 := by
  let E : Matrix (Fin n) (Fin n) ℤ := Matrix.of (fun k j => if k = i then C.A i j else 0)
  have hE : E * E = E + E := by
    ext k j
    simp only [E, Matrix.mul_apply, Matrix.of_apply, Matrix.add_apply]
    split_ifs with h
    · simp [mul_ite, C.diag i, two_mul]
    · simp
  change (1 - E) * (1 - E) = 1
  rw [sub_mul, mul_sub, mul_sub, hE]
  simp only [one_mul, mul_one]
  abel

/-- The fundamental reflection `r_i` as an element of `GL_n(Z)`. -/
def refl {n : ℕ} (C : GCM n) (i : Fin n) : (Matrix (Fin n) (Fin n) ℤ)ˣ :=
  ⟨reflMat C.A i, reflMat C.A i, reflMat_mul_self C i, reflMat_mul_self C i⟩

lemma refl_mul_self {n : ℕ} (C : GCM n) (i : Fin n) : refl C i * refl C i = 1 :=
  Units.ext (reflMat_mul_self C i)

lemma refl_inv {n : ℕ} (C : GCM n) (i : Fin n) : (refl C i)⁻¹ = refl C i :=
  inv_eq_of_mul_eq_one_right (refl_mul_self C i)

/-- The Weyl group `W(A)`: the subgroup of `GL_n(Z)` generated by the fundamental reflections. -/
def weyl {n : ℕ} (C : GCM n) : Subgroup (Matrix (Fin n) (Fin n) ℤ)ˣ :=
  Subgroup.closure (Set.range (refl C))

/-- The product `r_{l_1} ⋯ r_{l_m}` of a word `l` in the generators. -/
def word {n : ℕ} (C : GCM n) (l : List (Fin n)) : (Matrix (Fin n) (Fin n) ℤ)ˣ :=
  (l.map (refl C)).prod

@[simp] lemma word_nil {n : ℕ} (C : GCM n) : word C [] = 1 := rfl
@[simp] lemma word_cons {n : ℕ} (C : GCM n) (a : Fin n) (l : List (Fin n)) :
    word C (a :: l) = refl C a * word C l := by simp [word]
lemma word_append {n : ℕ} (C : GCM n) (l₁ l₂ : List (Fin n)) :
    word C (l₁ ++ l₂) = word C l₁ * word C l₂ := by simp [word]
lemma word_inv {n : ℕ} (C : GCM n) (l : List (Fin n)) : (word C l)⁻¹ = word C l.reverse := by
  induction l with
  | nil => simp
  | cons a l ih => simp [mul_inv_rev, ih, refl_inv, word_append]

/-- Ball of radius `k` for the word metric of `W(A)` w.r.t. `S = {r_i}`. -/
def ball {n : ℕ} (C : GCM n) (k : ℕ) : Set (Matrix (Fin n) (Fin n) ℤ)ˣ :=
  {w | ∃ l : List (Fin n), l.length ≤ k ∧ word C l = w}

/-- Sphere of radius `k`: elements of word length exactly `k`. -/
def sphere {n : ℕ} (C : GCM n) (k : ℕ) : Set (Matrix (Fin n) (Fin n) ℤ)ˣ :=
  {w | w ∈ ball C k ∧ ∀ m < k, w ∉ ball C m}

lemma sphere_subset_ball {n : ℕ} (C : GCM n) (k : ℕ) : sphere C k ⊆ ball C k := fun _ h => h.1

/-- Growth rate `limsup_k a_k^(1/k)`, `a_k = #{w : ℓ(w) = k}` (inverse radius of convergence
of the growth series). -/
noncomputable def growthRate {n : ℕ} (C : GCM n) : ℝ :=
  limsup (fun k : ℕ => ((sphere C k).ncard : ℝ) ^ ((k : ℝ)⁻¹)) atTop

/-- Ball version `limsup_k (#ball_k)^(1/k)`. -/
noncomputable def ballGrowthRate {n : ℕ} (C : GCM n) : ℝ :=
  limsup (fun k : ℕ => ((ball C k).ncard : ℝ) ^ ((k : ℝ)⁻¹)) atTop

/-- The balls exhaust exactly the Weyl group, so `ball C k` is the word-length ball of `W(A)`. -/
theorem weyl_eq_iUnion_ball {n : ℕ} (C : GCM n) : (weyl C : Set _) = ⋃ k, ball C k := by
  ext w
  simp only [Set.mem_iUnion, ball, Set.mem_ofPred_eq, SetLike.mem_coe]
  constructor
  · intro hw
    induction hw using Subgroup.closure_induction with
    | mem x hx => obtain ⟨i, rfl⟩ := hx; exact ⟨1, [i], le_rfl, by simp⟩
    | one => exact ⟨0, [], le_rfl, rfl⟩
    | mul x y _ _ hx hy =>
      obtain ⟨_, l₁, -, rfl⟩ := hx
      obtain ⟨_, l₂, -, rfl⟩ := hy
      exact ⟨_, l₁ ++ l₂, le_rfl, word_append C l₁ l₂⟩
    | inv x _ hx =>
      obtain ⟨_, l, -, rfl⟩ := hx
      exact ⟨_, l.reverse, le_rfl, (word_inv C l).symm⟩
  · rintro ⟨k, l, -, rfl⟩
    induction l with
    | nil => exact one_mem _
    | cons a l ih => rw [word_cons]; exact mul_mem (Subgroup.subset_closure ⟨a, rfl⟩) ih

/-! ## 3. Reduced words and their count -/

section Words
variable {n : ℕ} (ok : Fin n → Fin n → Prop) [DecidableRel ok]

/-- `follow ok k a`: words `w` of length `k` with `a :: w` an `ok`-chain. -/
def follow : ℕ → Fin n → Finset (List (Fin n))
  | 0, _ => {[]}
  | k + 1, a => (univ.filter (ok a)).biUnion fun b => (follow k b).image (b :: ·)

lemma mem_follow : ∀ (w : List (Fin n)) (a : Fin n),
    List.IsChain ok (a :: w) → w ∈ follow ok w.length a
  | [], _, _ => by simp [follow]
  | b :: w, a, h => by
    rw [List.isChain_cons_cons] at h
    simp only [List.length_cons, follow, mem_biUnion, mem_filter, mem_univ, true_and, mem_image]
    exact ⟨b, h.1, w, mem_follow w b h.2, rfl⟩

/-- `ok`-chains of length exactly `j`. -/
def lenWords : ℕ → Finset (List (Fin n))
  | 0 => {[]}
  | m + 1 => univ.biUnion fun a => (follow ok m a).image (a :: ·)

/-- `ok`-chains of length at most `k`. -/
def redWords (k : ℕ) : Finset (List (Fin n)) := (range (k + 1)).biUnion (lenWords ok)

lemma mem_redWords {w : List (Fin n)} (hw : List.IsChain ok w) {k : ℕ} (hk : w.length ≤ k) :
    w ∈ redWords ok k := by
  simp only [redWords, mem_biUnion, mem_range]
  refine ⟨w.length, by omega, ?_⟩
  cases w with
  | nil => simp [lenWords]
  | cons a w =>
    simp only [List.length_cons, lenWords, mem_biUnion, mem_univ, true_and, mem_image]
    exact ⟨a, w, mem_follow ok w a hw, rfl⟩

lemma card_follow_succ_le (m : ℕ) (a : Fin n) :
    (follow ok (m + 1) a).card ≤ ∑ b ∈ univ.filter (ok a), (follow ok m b).card :=
  card_biUnion_le.trans (sum_le_sum fun _ _ => card_image_le)

lemma card_lenWords_succ_le (m : ℕ) : (lenWords ok (m + 1)).card ≤ ∑ a, (follow ok m a).card :=
  card_biUnion_le.trans (sum_le_sum fun _ _ => card_image_le)

end Words

/-- If every word has an `ok`-reduced word of no greater length with the same product, the ball
of radius `k` is finite with at most `#redWords ok k` elements. -/
lemma ball_bound {n : ℕ} (C : GCM n) (ok : Fin n → Fin n → Prop) [DecidableRel ok]
    (hred : ∀ l : List (Fin n), ∃ w, List.IsChain ok w ∧ w.length ≤ l.length ∧ word C w = word C l)
    (k : ℕ) : (ball C k).Finite ∧ (ball C k).ncard ≤ (redWords ok k).card := by
  classical
  have h : ball C k ⊆ ((redWords ok k).image (word C) : Set _) := by
    rintro _ ⟨l, hl, rfl⟩
    obtain ⟨w, hw, hwl, he⟩ := hred l
    rw [coe_image]
    exact ⟨w, mem_redWords ok hw (hwl.trans hl), he⟩
  refine ⟨(Finset.finite_toSet _).subset h, ?_⟩
  calc (ball C k).ncard ≤ (((redWords ok k).image (word C) : Finset _) : Set _).ncard :=
        Set.ncard_le_ncard h (Finset.finite_toSet _)
    _ = ((redWords ok k).image (word C)).card := Set.ncard_coe_finset _
    _ ≤ _ := card_image_le

/-! ## 4. From ball bounds to growth rates -/

lemma ev_lin_le_pow {A r : ℝ} (hA : 0 ≤ A) (hr : 1 < r) :
    ∀ᶠ k : ℕ in atTop, A * (k + 1) ≤ r ^ k := by
  have ht := (tendsto_pow_const_div_const_pow_of_one_lt 1 hr).eventually
    (gt_mem_nhds (show (0:ℝ) < 1 / (2 * A + 1) by positivity))
  filter_upwards [ht, eventually_ge_atTop 1] with k hk hk1
  have hrk : 0 < r ^ k := pow_pos (by linarith) k
  rw [pow_one, div_lt_div_iff₀ hrk (by positivity)] at hk
  have h1 : (1:ℝ) ≤ k := by exact_mod_cast hk1
  nlinarith [mul_nonneg hA (sub_nonneg.2 h1)]

/-- The growth-rate conclusions for a GCM whose balls are bounded by `B k`, with
`B k ≤ (19/10)^k` eventually. -/
def RateBound {n : ℕ} (C : GCM n) : Prop :=
  (∀ k, (ball C k).Finite) ∧
  (∀ᶠ k : ℕ in atTop, ((sphere C k).ncard : ℝ) ^ ((k : ℝ)⁻¹) ≤ 19/10) ∧
  (∀ᶠ k : ℕ in atTop, ((ball C k).ncard : ℝ) ^ ((k : ℝ)⁻¹) ≤ 19/10) ∧
  growthRate C ≤ 19/10 ∧ ballGrowthRate C ≤ 19/10 ∧
  ¬ Tendsto (fun k : ℕ => ((sphere C k).ncard : ℝ) ^ ((k : ℝ)⁻¹)) atTop (nhds 2) ∧
  ¬ Tendsto (fun k : ℕ => ((ball C k).ncard : ℝ) ^ ((k : ℝ)⁻¹)) atTop (nhds 2)

lemma root_bound {u : ℕ → ℝ} (h0 : ∀ k, 0 ≤ u k) (h : ∀ᶠ k in atTop, u k ≤ (19/10 : ℝ) ^ k) :
    (∀ᶠ k : ℕ in atTop, u k ^ ((k : ℝ)⁻¹) ≤ 19/10) ∧
    limsup (fun k : ℕ => u k ^ ((k : ℝ)⁻¹)) atTop ≤ 19/10 ∧
    ¬ Tendsto (fun k : ℕ => u k ^ ((k : ℝ)⁻¹)) atTop (nhds 2) := by
  have h1 : ∀ᶠ k : ℕ in atTop, u k ^ ((k : ℝ)⁻¹) ≤ 19/10 := by
    filter_upwards [h, eventually_ge_atTop 1] with k hk hk1
    calc u k ^ ((k : ℝ)⁻¹) ≤ ((19/10 : ℝ) ^ k) ^ ((k : ℝ)⁻¹) :=
          Real.rpow_le_rpow (h0 k) hk (by positivity)
      _ = 19/10 := Real.pow_rpow_inv_natCast (by norm_num) (by omega)
  refine ⟨h1, limsup_le_of_le (isCoboundedUnder_le_of_le atTop
    fun k => Real.rpow_nonneg (h0 k) _) h1, fun ht => ?_⟩
  obtain ⟨k, hk1, hk2⟩ := ((ht.eventually (lt_mem_nhds (show (19/10:ℝ) < 2 by norm_num))).and
    h1).exists
  linarith

lemma rateBound_of {n : ℕ} (C : GCM n) (B : ℕ → ℝ) (hfin : ∀ k, (ball C k).Finite)
    (hB : ∀ k, ((ball C k).ncard : ℝ) ≤ B k) (hev : ∀ᶠ k in atTop, B k ≤ (19/10 : ℝ) ^ k) :
    RateBound C := by
  have hb : ∀ᶠ k in atTop, ((ball C k).ncard : ℝ) ≤ (19/10 : ℝ) ^ k :=
    hev.mono fun k hk => (hB k).trans hk
  have hs : ∀ᶠ k in atTop, ((sphere C k).ncard : ℝ) ≤ (19/10 : ℝ) ^ k :=
    hb.mono fun k hk => le_trans (by exact_mod_cast Set.ncard_le_ncard (sphere_subset_ball C k) (hfin k)) hk
  obtain ⟨s1, s2, s3⟩ := root_bound (fun k => Nat.cast_nonneg _) hs
  obtain ⟨b1, b2, b3⟩ := root_bound (fun k => Nat.cast_nonneg _) hb
  exact ⟨hfin, s1, b1, s2, b2, s3, b3⟩

/-! ## 5. The Feingold-Frenkel GCM `A_1^{++}` (order `alpha_{-1}, alpha_0, alpha_1`) -/

/-- Entries of the GCM of `A_1^{++}`. -/
def ffG : Fin 3 → Fin 3 → ℤ := ![![2, -1, 0], ![-1, 2, -2], ![0, -2, 2]]
def ffA : Matrix (Fin 3) (Fin 3) ℤ := Matrix.of ffG

def FF : GCM 3 where
  A := ffA
  diag := by have h : ∀ i, ffG i i = 2 := by decide
             exact h
  off := by have h : ∀ i j, i ≠ j → ffG i j ≤ 0 := by decide
            exact h
  zero_iff := by have h : ∀ i j, ffG i j = 0 ↔ ffG j i = 0 := by decide
                 exact h

lemma not_univ {n : ℕ} {J : Finset (Fin n)} (hJ : J ≠ univ) : ∃ i, i ∉ J := by
  by_contra h; push Not at h; exact hJ (eq_univ_iff_forall.2 h)

theorem FF_hyperbolic : IsHyperbolic FF := by
  have hI : ∀ J : Finset (Fin 3), J.Nonempty → J ≠ univ → ∃ i ∈ J, ∃ j ∉ J, ffG i j ≠ 0 := by
    decide
  have hS : ffA.IsSymm := by decide
  refine ⟨hI, fun _ => 1, FF.A.map (↑), fun _ => one_pos, hS.map _, fun i j => by simp, ?_, ?_, ?_⟩
  · exact ⟨![1, 2, 2], by norm_num [qf, FF, ffA, ffG, dotProduct, Matrix.mulVec, Fin.sum_univ_succ]⟩
  · exact ⟨![1, 0, 0], by norm_num [qf, FF, ffA, ffG, dotProduct, Matrix.mulVec, Fin.sum_univ_succ]⟩
  · intro J hJ x hx
    obtain ⟨i, hi⟩ := not_univ hJ
    have h0 : x 0 = 0 ∨ x 1 = 0 ∨ x 2 = 0 := by
      have := hx i hi; fin_cases i <;> simp_all
    simp [qf, FF, ffA, ffG, dotProduct, Matrix.mulVec, Fin.sum_univ_three]
    rcases h0 with h | h | h <;> simp only [h] <;>
      nlinarith [sq_nonneg (x 0 - x 1), sq_nonneg (x 1 - x 2), sq_nonneg (x 0),
        sq_nonneg (x 1), sq_nonneg (x 2)]

/-- Kac-style certificate: `det A = -2` (so `A` is nonsingular, neither finite nor affine);
the connected proper subdiagrams `{0,1}` (`A_2`, minor `3`), `{1,2}` (`A_1^{(1)}`, minor `0`)
and the singletons (`A_1`) are of finite or affine type; `{0,2}` is disconnected. -/
lemma FF_minors : ffA.det = -2 ∧ (ffA.submatrix ![0, 1] ![0, 1]).det = 3 ∧
    (ffA.submatrix ![1, 2] ![1, 2]).det = 0 ∧ ffA 0 2 = 0 := by
  refine ⟨?_, ?_, ?_, rfl⟩
  · rw [Matrix.det_fin_three]; decide
  · rw [Matrix.det_fin_two]; decide
  · rw [Matrix.det_fin_two]; decide

lemma FF_comm : refl FF 0 * refl FF 2 = refl FF 2 * refl FF 0 := Units.ext (by decide)

/-- Letters allowed to follow each other in a reduced word: no `ii`, no `2 0`. -/
def okFF (a b : Fin 3) : Prop := a ≠ b ∧ ¬(a = 2 ∧ b = 0)
instance : DecidableRel okFF := fun a b => by unfold okFF; infer_instance

lemma ff_prepend (x : Fin 3) (w : List (Fin 3)) (hw : List.IsChain okFF w) :
    ∃ w', List.IsChain okFF w' ∧ w'.length ≤ w.length + 1 ∧
      word FF w' = refl FF x * word FF w := by
  cases w with
  | nil => exact ⟨[x], .singleton x, le_rfl, by simp⟩
  | cons y v =>
    by_cases hxy : okFF x y
    · exact ⟨x :: y :: v, List.isChain_cons_cons.2 ⟨hxy, hw⟩, le_rfl, by simp⟩
    by_cases he : x = y
    · subst he
      exact ⟨v, hw.tail, by simp only [List.length_cons]; omega, by simp [← mul_assoc, refl_mul_self]⟩
    obtain ⟨rfl, rfl⟩ : x = 2 ∧ y = 0 := by unfold okFF at hxy; tauto
    cases v with
    | nil => exact ⟨[0, 2], by decide, le_rfl, by simp [FF_comm]⟩
    | cons z v =>
      rw [List.isChain_cons_cons] at hw
      obtain ⟨h0z, hz⟩ := hw
      by_cases hz2 : z = 2
      · subst hz2
        refine ⟨0 :: v, ?_, by simp, ?_⟩
        · cases v with
          | nil => exact .singleton 0
          | cons u r =>
            rw [List.isChain_cons_cons] at hz ⊢
            refine ⟨?_, hz.2⟩
            have h2u := hz.1
            revert h2u; fin_cases u <;> decide
        · simp only [word_cons]
          rw [← mul_assoc, ← FF_comm, mul_assoc, ← mul_assoc (refl FF 2), refl_mul_self, one_mul]
      · obtain rfl : z = 1 := by revert h0z hz2; fin_cases z <;> decide
        refine ⟨0 :: 2 :: 1 :: v, ?_, by simp, ?_⟩
        · exact List.isChain_cons_cons.2 ⟨by decide, List.isChain_cons_cons.2 ⟨by decide, hz⟩⟩
        · simp only [word_cons, ← mul_assoc, FF_comm]

lemma ff_reduce (l : List (Fin 3)) :
    ∃ w, List.IsChain okFF w ∧ w.length ≤ l.length ∧ word FF w = word FF l := by
  induction l with
  | nil => exact ⟨[], .nil, le_rfl, rfl⟩
  | cons x l ih =>
    obtain ⟨w, hw, hwl, he⟩ := ih
    obtain ⟨w', hw', hw'l, he'⟩ := ff_prepend x w hw
    exact ⟨w', hw', by simp; omega, by rw [he', he, word_cons]⟩

lemma ff_follow_card (m : ℕ) :
    ((follow okFF m 0).card : ℝ) ≤ 5 * (5/3 : ℝ) ^ m ∧
    ((follow okFF m 1).card : ℝ) ≤ 5 * (5/3 : ℝ) ^ m ∧
    ((follow okFF m 2).card : ℝ) ≤ 3 * (5/3 : ℝ) ^ m := by
  induction m with
  | zero => norm_num [follow]
  | succ m ih =>
    obtain ⟨h0, h1, h2⟩ := ih
    have k0 := card_follow_succ_le okFF m 0
    have k1 := card_follow_succ_le okFF m 1
    have k2 := card_follow_succ_le okFF m 2
    rw [show univ.filter (okFF 0) = {1, 2} by decide, sum_pair (by decide)] at k0
    rw [show univ.filter (okFF 1) = {0, 2} by decide, sum_pair (by decide)] at k1
    rw [show univ.filter (okFF 2) = {1} by decide, sum_singleton] at k2
    have hp : (0:ℝ) ≤ (5/3) ^ m := by positivity
    have c0 : ((follow okFF (m+1) 0).card : ℝ) ≤ (follow okFF m 1).card + (follow okFF m 2).card := by
      exact_mod_cast k0
    have c1 : ((follow okFF (m+1) 1).card : ℝ) ≤ (follow okFF m 0).card + (follow okFF m 2).card := by
      exact_mod_cast k1
    have c2 : ((follow okFF (m+1) 2).card : ℝ) ≤ (follow okFF m 1).card := by exact_mod_cast k2
    rw [pow_succ]
    refine ⟨?_, ?_, ?_⟩ <;> nlinarith

lemma ff_ball_card (k : ℕ) :
    (ball FF k).Finite ∧ ((ball FF k).ncard : ℝ) ≤ 13 * (k + 1) * (5/3 : ℝ) ^ k := by
  obtain ⟨hfin, hcard⟩ := ball_bound FF okFF ff_reduce k
  refine ⟨hfin, ?_⟩
  have hl : ∀ j, ((lenWords okFF j).card : ℝ) ≤ 13 * (5/3 : ℝ) ^ j := by
    intro j
    cases j with
    | zero => norm_num [lenWords]
    | succ m =>
      have h := card_lenWords_succ_le okFF m
      rw [Fin.sum_univ_three] at h
      obtain ⟨h0, h1, h2⟩ := ff_follow_card m
      have c : ((lenWords okFF (m+1)).card : ℝ) ≤
          (follow okFF m 0).card + (follow okFF m 1).card + (follow okFF m 2).card := by
        exact_mod_cast h
      have hp : (0:ℝ) ≤ (5/3) ^ m := by positivity
      rw [pow_succ]; nlinarith
  calc ((ball FF k).ncard : ℝ) ≤ (redWords okFF k).card := by exact_mod_cast hcard
    _ ≤ ∑ j ∈ range (k + 1), ((lenWords okFF j).card : ℝ) := by
        exact_mod_cast card_biUnion_le
    _ ≤ ∑ j ∈ range (k + 1), 13 * (5/3 : ℝ) ^ k := by
        refine sum_le_sum fun j hj => (hl j).trans ?_
        have : j ≤ k := by simp at hj; omega
        gcongr; norm_num
    _ = 13 * (k + 1) * (5/3 : ℝ) ^ k := by simp; ring

theorem FF_rate : RateBound FF := by
  refine rateBound_of FF _ (fun k => (ff_ball_card k).1) (fun k => (ff_ball_card k).2) ?_
  filter_upwards [ev_lin_le_pow (A := 13) (r := 57/50) (by norm_num) (by norm_num)] with k hk
  calc 13 * ((k : ℝ) + 1) * (5/3 : ℝ) ^ k ≤ (57/50 : ℝ) ^ k * (5/3) ^ k := by gcongr
    _ = (19/10 : ℝ) ^ k := by rw [← mul_pow]; norm_num

/-! ## 6. Main theorem -/

/-- **Disproof of conjecture 00000001144.** The GCM `A_1^{++}` of the Feingold-Frenkel algebra
is hyperbolic and nonsingular; its Weyl group (generated by the fundamental reflections in
`GL_3(Z)`) is exhausted by the word-length balls, and its growth rate (sphere and ball
versions) is at most `19/10`; the `k`-th roots are eventually `≤ 19/10`, so they do not tend
to `2`. Hence it is false that every hyperbolic Weyl group has growth rate `2`. -/
theorem disproof :
    IsHyperbolic FF ∧ FF.A.det = -2 ∧ (weyl FF : Set _) = ⋃ k, ball FF k ∧ RateBound FF ∧
    growthRate FF ≠ 2 ∧ ballGrowthRate FF ≠ 2 ∧
    ¬ (∀ (n : ℕ) (C : GCM n), IsHyperbolic C → growthRate C = 2) := by
  have hF := FF_rate
  have nF : growthRate FF ≠ 2 := fun h => by linarith [hF.2.2.2.1]
  exact ⟨FF_hyperbolic, FF_minors.1, weyl_eq_iUnion_ball FF, hF, nF,
    fun h => by linarith [hF.2.2.2.2.1], fun h => nF (h 3 FF FF_hyperbolic)⟩

end C1144
