name = "tlmc3794"
version = "1.0.0"
defaultTargets = ["Conjecture3794"]

[[lean_lib]]
name = "Conjecture3794"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.19.0"
