import Mathlib.Algebra.FreeMonoid.Basic
import Mathlib.GroupTheory.Congruence.Basic
import Mathlib.GroupTheory.Congruence.Hom
import Mathlib.Algebra.Group.TypeTags.Basic
import Mathlib.Algebra.Group.TypeTags.Finite
import Mathlib.Data.Fintype.Option
import Mathlib.Data.ZMod.Basic
import Mathlib.Data.Nat.Prime.Infinite
import Mathlib.Data.Finite.Card
import Mathlib.SetTheory.Cardinal.Finite
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Order.Bounds.Defs
import Mathlib.Order.Fin.Basic
import Mathlib.Tactic.Linarith

/-! For the plactic monoid `P_n` on `n ≥ 1` letters, the real numbers `c` such that every finite
monoid `M` receives at most `|M| ^ c` surjective homomorphisms from `P_n` are exactly the reals
`c ≥ n`. So the optimal exponent is `c(n) = n`: it is at least `1` and unbounded in `n`. -/
namespace Conjecture3841

open FreeMonoid

/-! ### The plactic monoid -/

section Plactic

variable {α : Type} [LinearOrder α]

/-- The Knuth relations `acb ≡ cab` (`a ≤ b < c`) and `bac ≡ bca` (`a < b ≤ c`). -/
inductive KnuthRel : FreeMonoid α → FreeMonoid α → Prop
  | left (a b c : α) (hab : a ≤ b) (hbc : b < c) :
      KnuthRel (of a * of c * of b) (of c * of a * of b)
  | right (a b c : α) (hab : a < b) (hbc : b ≤ c) :
      KnuthRel (of b * of a * of c) (of b * of c * of a)

variable (α) in
/-- Knuth equivalence: the monoid congruence generated by the Knuth relations. -/
def placticCon : Con (FreeMonoid α) := conGen KnuthRel

end Plactic

/-- The plactic monoid `P_n`: words over the alphabet `Fin n` modulo Knuth equivalence, with
Mathlib's quotient-monoid structure. -/
abbrev Plactic (n : ℕ) : Type := (placticCon (Fin n)).Quotient

/-- The class of the letter `i`. -/
def gen {n : ℕ} (i : Fin n) : Plactic n := (placticCon (Fin n)).mk' (of i)

/-- A homomorphism out of `P_n` is determined by its values on the letters. -/
theorem hom_ext_gen {n : ℕ} {M : Type} [Monoid M] {f g : Plactic n →* M}
    (h : ∀ i, f (gen i) = g (gen i)) : f = g := by
  have hfg : f.comp (placticCon (Fin n)).mk' = g.comp (placticCon (Fin n)).mk' :=
    FreeMonoid.hom_eq h
  ext x
  induction x using Con.induction_on with
  | H w => exact DFunLike.congr_fun hfg w

/-- The values on the letters, as a function of the homomorphism. -/
def onLetters {n : ℕ} {M : Type} [Monoid M] (f : Plactic n →* M) : Fin n → M := fun i => f (gen i)

theorem onLetters_injective {n : ℕ} {M : Type} [Monoid M] :
    Function.Injective (onLetters : (Plactic n →* M) → Fin n → M) :=
  fun _ _ h => hom_ext_gen fun i => congrFun h i

instance {n : ℕ} {M : Type} [Monoid M] [Finite M] : Finite (Plactic n →* M) :=
  Finite.of_injective _ onLetters_injective

/-- The number of surjective monoid homomorphisms from `P_n` to `M`. -/
noncomputable def numSurj (n : ℕ) (M : Type) [Monoid M] : ℕ :=
  Nat.card {f : Plactic n →* M // Function.Surjective f}

/-! ### The upper bound `|M| ^ n` -/

theorem numSurj_le (n : ℕ) (M : Type) [Monoid M] [Finite M] :
    numSurj n M ≤ Nat.card M ^ n := by
  have hinj : Function.Injective
      (fun f : {f : Plactic n →* M // Function.Surjective f} => onLetters f.1) :=
    fun _ _ h => Subtype.ext (onLetters_injective h)
  calc numSurj n M ≤ Nat.card (Fin n → M) := Nat.card_le_card_of_injective _ hinj
    _ = Nat.card M ^ n := by
      rw [Nat.card_fun, Nat.card_eq_fintype_card (α := Fin n), Fintype.card_fin]

/-! ### Homomorphisms to commutative monoids -/

/-- Every assignment of the letters to elements of a commutative monoid extends to a
homomorphism from `P_n`, because the Knuth relations hold in every commutative monoid. -/
def liftComm {n : ℕ} {M : Type} [CommMonoid M] (g : Fin n → M) : Plactic n →* M :=
  (placticCon (Fin n)).lift (FreeMonoid.lift g) (Con.conGen_le fun x y h => by
    cases h with
    | left a b c _ _ =>
      simp only [Con.ker_rel, map_mul, FreeMonoid.lift_eval_of]
      rw [mul_comm (g a) (g c)]
    | right a b c _ _ =>
      simp only [Con.ker_rel, map_mul, FreeMonoid.lift_eval_of]
      rw [mul_assoc, mul_comm (g a) (g c), mul_assoc])

@[simp]
theorem liftComm_gen {n : ℕ} {M : Type} [CommMonoid M] (g : Fin n → M) (i : Fin n) :
    liftComm g (gen i) = g i := by
  simp [liftComm, gen]

/-- A nonzero residue modulo a prime is invertible. -/
theorem zmod_mul_inv {p : ℕ} [Fact p.Prime] (a : ZMod p) (ha : a ≠ 0) : a * a⁻¹ = 1 := by
  have hp : p.Prime := Fact.out
  rw [ZMod.mul_inv_eq_gcd]
  have hndvd : ¬ p ∣ a.val := fun hd => by
    have hlt := ZMod.val_lt a
    have hpos : 0 < a.val := Nat.pos_of_ne_zero fun h0 => ha ((ZMod.val_eq_zero a).mp h0)
    exact absurd (Nat.le_of_dvd hpos hd) (by omega)
  have hcop : Nat.gcd a.val p = 1 :=
    Nat.Coprime.symm ((Nat.Prime.coprime_iff_not_dvd hp).mpr hndvd)
  rw [hcop, Nat.cast_one]

/-- In the cyclic group of prime order `p`, written multiplicatively, a homomorphism sending
some letter to a non-identity element is surjective. -/
theorem surjective_liftComm {n p : ℕ} [Fact p.Prime] (g : Fin n → Multiplicative (ZMod p))
    (i : Fin n) (hi : g i ≠ 1) : Function.Surjective (liftComm g) := by
  intro b
  have ha : Multiplicative.toAdd (g i) ≠ 0 := fun h => hi (Multiplicative.toAdd.injective h)
  refine ⟨gen i ^ (Multiplicative.toAdd b * (Multiplicative.toAdd (g i))⁻¹).val, ?_⟩
  apply Multiplicative.toAdd.injective
  rw [map_pow, liftComm_gen, toAdd_pow, nsmul_eq_mul, ZMod.natCast_zmod_val, mul_assoc,
    mul_comm _ (Multiplicative.toAdd (g i)), zmod_mul_inv _ ha, mul_one]

/-- The cyclic group of prime order `p` receives at least `p ^ n - 1` surjective
homomorphisms from `P_n`. -/
theorem pow_le_numSurj_add_one (n p : ℕ) [Fact p.Prime] :
    p ^ n ≤ numSurj n (Multiplicative (ZMod p)) + 1 := by
  classical
  let F : (Fin n → Multiplicative (ZMod p)) →
      Option {f : Plactic n →* Multiplicative (ZMod p) // Function.Surjective f} := fun g =>
    if h : ∃ i, g i ≠ 1 then some ⟨liftComm g, surjective_liftComm g h.choose h.choose_spec⟩
    else none
  have hF : Function.Injective F := by
    intro g g' hgg
    by_cases h : ∃ i, g i ≠ 1 <;> by_cases h' : ∃ i, g' i ≠ 1
    · simp only [F, dif_pos h, dif_pos h', Option.some.injEq, Subtype.mk.injEq] at hgg
      funext i
      rw [← liftComm_gen g i, hgg, liftComm_gen]
    · simp [F, dif_pos h, dif_neg h'] at hgg
    · simp [F, dif_neg h, dif_pos h'] at hgg
    · push_neg at h h'
      funext i
      rw [h i, h' i]
  haveI : Fintype {f : Plactic n →* Multiplicative (ZMod p) // Function.Surjective f} :=
    Fintype.ofFinite _
  have hcard := Nat.card_le_card_of_injective F hF
  rw [Nat.card_fun, Nat.card_eq_fintype_card (α := Fin n), Fintype.card_fin,
    Finite.card_option] at hcard
  have hp : Nat.card (Multiplicative (ZMod p)) = p := Nat.card_zmod p
  rw [hp] at hcard
  exact hcard

/-! ### Admissible exponents -/

/-- The real number `c` is an admissible exponent for `P_n`: every finite monoid `M` receives
at most `|M| ^ c` surjective homomorphisms from `P_n`. -/
def IsAdmissible (n : ℕ) (c : ℝ) : Prop :=
  ∀ (M : Type) [Monoid M] [Finite M], (numSurj n M : ℝ) ≤ (Nat.card M : ℝ) ^ c

theorem isAdmissible_of_le {n : ℕ} {c : ℝ} (h : (n : ℝ) ≤ c) : IsAdmissible n c := by
  intro M _ _
  have h1 : (1 : ℝ) ≤ (Nat.card M : ℝ) := by
    exact_mod_cast Nat.one_le_iff_ne_zero.mpr Nat.card_pos.ne'
  calc (numSurj n M : ℝ) ≤ ((Nat.card M ^ n : ℕ) : ℝ) := by exact_mod_cast numSurj_le n M
    _ = (Nat.card M : ℝ) ^ (n : ℝ) := by rw [Nat.cast_pow, Real.rpow_natCast]
    _ ≤ (Nat.card M : ℝ) ^ c := Real.rpow_le_rpow_of_exponent_le h1 h

theorem not_isAdmissible_of_lt {n : ℕ} (hn : 1 ≤ n) {c : ℝ} (h : c < (n : ℝ)) :
    ¬ IsAdmissible n c := by
  intro hadm
  have hδ : 0 < (n : ℝ) - c := sub_pos.mpr h
  obtain ⟨N, hN⟩ := exists_nat_ge ((2 : ℝ) ^ (1 / ((n : ℝ) - c)))
  obtain ⟨p, hpN, hp⟩ := Nat.exists_infinite_primes (N + 3)
  haveI : Fact p.Prime := ⟨hp⟩
  have hx3 : (3 : ℝ) ≤ (p : ℝ) := by
    have : 3 ≤ p := by omega
    exact_mod_cast this
  have hxN : (2 : ℝ) ^ (1 / ((n : ℝ) - c)) ≤ (p : ℝ) := by
    have : (N : ℝ) ≤ (p : ℝ) := by
      have : N ≤ p := by omega
      exact_mod_cast this
    linarith
  have hx0 : (0 : ℝ) < (p : ℝ) := by linarith
  -- the bound of the hypothesis, for the cyclic group of order `p`
  have hbound := hadm (Multiplicative (ZMod p))
  have hcard : Nat.card (Multiplicative (ZMod p)) = p := Nat.card_zmod p
  rw [hcard] at hbound
  have hlow : ((p : ℝ)) ^ n ≤ (numSurj n (Multiplicative (ZMod p)) : ℝ) + 1 := by
    exact_mod_cast pow_le_numSurj_add_one n p
  -- `p ^ (n - c) ≥ 2`
  have h2 : (2 : ℝ) ≤ (p : ℝ) ^ ((n : ℝ) - c) := by
    calc (2 : ℝ) = ((2 : ℝ) ^ (1 / ((n : ℝ) - c))) ^ ((n : ℝ) - c) := by
          rw [← Real.rpow_mul (by norm_num), one_div_mul_cancel hδ.ne', Real.rpow_one]
      _ ≤ (p : ℝ) ^ ((n : ℝ) - c) :=
          Real.rpow_le_rpow (Real.rpow_nonneg (by norm_num) _) hxN hδ.le
  have hsplit : (p : ℝ) ^ n = (p : ℝ) ^ c * (p : ℝ) ^ ((n : ℝ) - c) := by
    rw [← Real.rpow_add hx0, add_sub_cancel, Real.rpow_natCast]
  have hc0 : 0 < (p : ℝ) ^ c := Real.rpow_pos_of_pos hx0 c
  have hpn : (p : ℝ) ≤ (p : ℝ) ^ n := le_self_pow₀ (by linarith) (by omega)
  nlinarith

/-- For `n ≥ 1` the admissible exponents are exactly the reals `c ≥ n`. -/
theorem isAdmissible_iff {n : ℕ} (hn : 1 ≤ n) (c : ℝ) : IsAdmissible n c ↔ (n : ℝ) ≤ c :=
  ⟨fun h => not_lt.mp fun hlt => not_isAdmissible_of_lt hn hlt h, isAdmissible_of_le⟩

/-- For `n ≥ 1` the optimal exponent is `n`. -/
theorem isLeast_admissible {n : ℕ} (hn : 1 ≤ n) : IsLeast {c : ℝ | IsAdmissible n c} (n : ℝ) :=
  ⟨isAdmissible_of_le le_rfl, fun _ hc => (isAdmissible_iff hn _).mp hc⟩

/-! ### The conjecture -/

/-- The statement of the conjecture: an admissible exponent exists for every `n`; for `n ≥ 1`
there is an optimal (least) admissible exponent `c(n)` and it is at least `1`; and the admissible
exponents are eventually larger than any given bound, so `c(n)` is unbounded. -/
def Conjecture : Prop :=
  (∀ n : ℕ, ∃ c : ℝ, IsAdmissible n c) ∧
  (∀ n : ℕ, 1 ≤ n → ∃ c : ℝ, IsLeast {c' : ℝ | IsAdmissible n c'} c ∧ 1 ≤ c) ∧
  (∀ B : ℝ, ∃ N : ℕ, ∀ n : ℕ, N ≤ n → ∀ c : ℝ, IsAdmissible n c → B ≤ c)

theorem conjecture_true : Conjecture := by
  refine ⟨fun n => ⟨n, isAdmissible_of_le le_rfl⟩, fun n hn => ⟨n, isLeast_admissible hn, ?_⟩,
    fun B => ?_⟩
  · exact_mod_cast hn
  · obtain ⟨N, hN⟩ := exists_nat_ge B
    refine ⟨N + 1, fun n hn c hc => ?_⟩
    have h1 : (n : ℝ) ≤ c := (isAdmissible_iff (by omega) c).mp hc
    have h2 : (N : ℝ) ≤ (n : ℝ) := by
      have : N ≤ n := by omega
      exact_mod_cast this
    linarith

#print axioms hom_ext_gen
#print axioms numSurj_le
#print axioms surjective_liftComm
#print axioms pow_le_numSurj_add_one
#print axioms isAdmissible_of_le
#print axioms not_isAdmissible_of_lt
#print axioms isAdmissible_iff
#print axioms isLeast_admissible
#print axioms conjecture_true

end Conjecture3841
