name = "Batch6_S3"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Batch6_S3"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "Batch6_S3"
globs = ["Batch6"]
