import Conjecture240

#print axioms Mahler240.cross
#print axioms Mahler240.cube
#print axioms Mahler240.signVal
#print axioms Mahler240.axis
#print axioms Mahler240.signVal_abs
#print axioms Mahler240.signVal_ne_zero
#print axioms Mahler240.signVal_injective
#print axioms Mahler240.axis_mem_cross
#print axioms Mahler240.abs_coord_le
#print axioms Mahler240.convex_cross
#print axioms Mahler240.zero_mem_hull_axes
#print axioms Mahler240.cross_eq_hull_axes
#print axioms Mahler240.coord_one_unique
#print axioms Mahler240.axis_extreme
#print axioms Mahler240.extreme_cross
#print axioms Mahler240.axis_injective
#print axioms Mahler240.ncard_extreme_cross
#print axioms Mahler240.extreme_interval
#print axioms Mahler240.extreme_cube
#print axioms Mahler240.ncard_extreme_cube
#print axioms Mahler240.E
#print axioms Mahler240.Four
#print axioms Mahler240.coords
#print axioms Mahler240.K
#print axioms Mahler240.P
#print axioms Mahler240.Cube
#print axioms Mahler240.Cross
#print axioms Mahler240.dot
#print axioms Mahler240.polar
#print axioms Mahler240.SymmetricConvexBody
#print axioms Mahler240.ambient_dimension
#print axioms Mahler240.signVal_mul
#print axioms Mahler240.polar_K
#print axioms Mahler240.continuous_l1
#print axioms Mahler240.compact_cross
#print axioms Mahler240.K_body
#print axioms Mahler240.ncard_product
#print axioms Mahler240.ncard_extreme_K
#print axioms Mahler240.ncard_extreme_Cube
#print axioms Mahler240.ncard_extreme_Cross
#print axioms Mahler240.bijective_of_image_K
#print axioms Mahler240.not_linear_image_Cube
#print axioms Mahler240.not_linear_image_Cross
#print axioms Mahler240.coords_apply
#print axioms Mahler240.dot_coords
#print axioms Mahler240.mem_Cube
#print axioms Mahler240.mem_Cross
#print axioms Mahler240.coords_measurePreserving
#print axioms Mahler240.volume_cross3
#print axioms Mahler240.volume_K
#print axioms Mahler240.measurableSet_P
#print axioms Mahler240.slice_P
#print axioms Mahler240.volume_slice_P
#print axioms Mahler240.slice_integral
#print axioms Mahler240.volume_P
#print axioms Mahler240.mahlerVolume
#print axioms Mahler240.mahlerVolume_K
#print axioms Mahler240.equality_K
#print axioms Mahler240.counterexample
#print axioms Mahler240.equality_classification_false
#print axioms Mahler240.conjecture_00000000240_english_false
#print axioms Mahler240.conjecture_00000000240_chinese_false
