/-!
# Conjecture 00000007739: the "exact free Khintchine fourth moment" formula is false

The conjecture (paraphrased): for free words `W` of length `d` generated by a free semicircular
family, `M_p(d) = ‖W‖_p / ‖W‖_2`, and

  **(C1)** `M_4(d)^2 = 2 - d⁻¹ (1 - 2^{-d})`,

  **(C2)** (a vague statement about `M_∞(d)/M_p(d)` and free group generators).

We refute (C1), hence the conjunction (C1) ∧ (C2) whatever (C2) means.

Everything is built from scratch in core Lean 4, following Voiculescu's construction of a free
semicircular family on the full Fock space:

* `Word := List Nat` indexes the orthonormal basis `e_{i₁} ⊗ ⋯ ⊗ e_{iₖ}` of the full Fock space
  `F(H) = ℂΩ ⊕ H ⊕ H^{⊗2} ⊕ ⋯` over `H = ℓ²(ℕ)` (the empty word is the vacuum `Ω`).
* `Vec := List (Word × Int)` is a finitely supported vector, i.e. a formal finite linear
  combination of basis vectors (`coeff v w` is its coordinate at `w`; repeated entries add up).
  All the vectors below have integer coordinates, so `ℤ` suffices.
* `create i` is the creation operator `ℓ(e_i) : ξ ↦ e_i ⊗ ξ`, `annih i` is the annihilation
  operator `ℓ(e_i)*` (kills `Ω`, strips a leading `e_i`, kills words starting with `e_j`, `j ≠ i`).
  Both map finitely supported vectors to finitely supported vectors.
* `X i = ℓ(e_i) + ℓ(e_i)*` is the `i`-th semicircular element; `τ(T) = ⟨Ω, T Ω⟩` is the vacuum
  state.  We prove `⟨ℓ(e_i) u, v⟩ = ⟨u, ℓ(e_i)* v⟩` and `⟨ℓ(e_i)* u, v⟩ = ⟨u, ℓ(e_i) v⟩`
  (`inner_create`, `inner_annih`), hence `X i` is symmetric (`X_selfadjoint`), and the adjoint of
  a monomial `X_{i₁} ⋯ X_{iₖ}` is the reversed monomial (`applyW_adjoint`).
* For a monomial `W = X_{i₁} ⋯ X_{i_d}` we set `‖W‖₂² = τ(W*W)` and `‖W‖₄⁴ = τ((W*W)²)`, and we
  prove `‖W‖₂² = ⟨WΩ, WΩ⟩`, `‖W‖₄⁴ = ⟨W*WΩ, W*WΩ⟩` (`norm2sq_eq`, `norm4pow4_eq`).

Results:
* `semicircle_moments`: `τ(X₀ᵏ)`, `k = 0..10`, are `1,0,1,0,2,0,5,0,14,0,42` (Catalan numbers),
  i.e. `X₀` has the standard semicircle law.
* `word1`: for `W = X₀` (the only free word of length 1 up to relabelling): `‖W‖₂² = 1`,
  `‖W‖₄⁴ = 2`, so `M_4(1)⁴ = 2`.
* `first_chaos_three`: for all real (integer) `a, b, c`, `S = aX₀+bX₁+cX₂` has
  `τ(S⁴) = 2 τ(S²)²`, so on the first chaos the ratio is the same constant; the "optimal constant"
  reading at `d = 1` gives the same `M_4(1)⁴ = 2` (`first_chaos_never_formula`).
* `words_234`: for `W = X₀X₁⋯X_{d-1}`, `‖W‖₄⁴ = d + 1` and `‖W‖₂² = 1` for `d = 2, 3, 4`.
* `clause_false_d1`, `clause_false_small`: `M_4(d)² = f(d)` fails (and so do the
  normalisations `M_4 = f(d)` and `M_4⁴ = f(d)`) for `d = 1, 2, 3, 4`.
* `conjecture_00000007739_false : ¬ (Conj ∧ C2)` for every proposition `C2`.

`M_4(d)² = f(d)` is encoded without real numbers: `M_4(d)² = √(‖W‖₄⁴/‖W‖₂⁴)`, and for `f ≥ 0`
one has `f = √y ↔ f² = y`.  With `f(d) = N(d)/D(d)`, `N(d) = 2d·2^d - 2^d + 1`, `D(d) = d·2^d`,
this is the integer identity `N(d)² · ‖W‖₂⁴ = ‖W‖₄⁴ · D(d)²` (`N(d) > 0`).
-/

namespace FreeK

/-! ## 1. The full Fock space (finitely supported part) -/

/-- A basis word `e_{i₁} ⊗ ⋯ ⊗ e_{iₖ}` of the full Fock space; `[]` is the vacuum `Ω`. -/
abbrev Word := List Nat

/-- A finitely supported vector of the full Fock space: a formal integer combination of basis
words (repeated words add up). -/
abbrev Vec := List (Word × Int)

/-- The coordinate of `v` at the basis word `w`. -/
def coeff : Vec → Word → Int
  | [], _ => 0
  | p :: v, w => (if p.1 = w then p.2 else 0) + coeff v w

/-- The inner product `⟨u, v⟩ = Σ_w coeff u w · coeff v w` (real coefficients). -/
def inner : Vec → Vec → Int
  | [], _ => 0
  | p :: u, v => p.2 * coeff v p.1 + inner u v

/-- The vacuum vector `Ω`. -/
def Ω : Vec := [([], 1)]

/-- Creation operator `ℓ(e_i) : ξ ↦ e_i ⊗ ξ`. -/
def create (i : Nat) (v : Vec) : Vec := v.map fun p => (i :: p.1, p.2)

/-- One term of the annihilation operator `ℓ(e_i)*`. -/
def annihTerm (i : Nat) : Word × Int → Option (Word × Int)
  | (j :: w, c) => if j = i then some (w, c) else none
  | ([], _) => none

/-- Annihilation operator `ℓ(e_i)* : Ω ↦ 0, e_j ⊗ ξ ↦ δ_{ij} ξ`. -/
def annih (i : Nat) (v : Vec) : Vec := v.filterMap (annihTerm i)

/-- The semicircular element `X_i = ℓ(e_i) + ℓ(e_i)*`. -/
def X (i : Nat) (v : Vec) : Vec := create i v ++ annih i v

/-! ## 2. Linear-algebra lemmas and adjointness -/

theorem coeff_append (u v : Vec) (w : Word) : coeff (u ++ v) w = coeff u w + coeff v w := by
  induction u with
  | nil => simp [coeff]
  | cons p u ih => simp [coeff, ih, Int.add_assoc]

theorem inner_append_left (u u' v : Vec) : inner (u ++ u') v = inner u v + inner u' v := by
  induction u with
  | nil => simp [inner]
  | cons p u ih => simp [inner, ih, Int.add_assoc]

theorem inner_append_right (u v v' : Vec) : inner u (v ++ v') = inner u v + inner u v' := by
  induction u with
  | nil => simp [inner]
  | cons p u ih =>
    simp only [inner, coeff_append, ih, Int.mul_add]
    omega

theorem coeff_create_cons (i : Nat) (v : Vec) (w : Word) :
    coeff (create i v) (i :: w) = coeff v w := by
  induction v with
  | nil => simp [create, coeff]
  | cons p v ih =>
    simp only [create, List.map_cons, coeff] at ih ⊢
    rw [ih]; simp

theorem coeff_create_ne (i : Nat) (v : Vec) (w : Word) (h : ∀ w', w ≠ i :: w') :
    coeff (create i v) w = 0 := by
  induction v with
  | nil => simp [create, coeff]
  | cons p v ih =>
    simp only [create, List.map_cons, coeff] at ih ⊢
    rw [ih]
    have : (i :: p.1 = w) = False := by
      apply propext; constructor
      · intro e; exact h p.1 e.symm
      · intro f; exact f.elim
    simp [this]

theorem coeff_annih (i : Nat) (v : Vec) (w : Word) :
    coeff (annih i v) w = coeff v (i :: w) := by
  induction v with
  | nil => simp [annih, coeff]
  | cons p v ih =>
    obtain ⟨pw, c⟩ := p
    simp only [annih] at ih
    cases pw with
    | nil => simp [annih, annihTerm, coeff, ih]
    | cons j pw =>
      by_cases hj : j = i
      · subst hj; simp [annih, annihTerm, coeff, ih]
      · simp [annih, annihTerm, coeff, ih, hj]

/-- `⟨ℓ(e_i) u, v⟩ = ⟨u, ℓ(e_i)* v⟩`. -/
theorem inner_create (i : Nat) (u v : Vec) :
    inner (create i u) v = inner u (annih i v) := by
  induction u with
  | nil => simp [create, inner]
  | cons p u ih =>
    simp only [create, List.map_cons, inner] at ih ⊢
    rw [ih, coeff_annih]

/-- `⟨ℓ(e_i)* u, v⟩ = ⟨u, ℓ(e_i) v⟩`. -/
theorem inner_annih (i : Nat) (u v : Vec) :
    inner (annih i u) v = inner u (create i v) := by
  induction u with
  | nil => simp [annih, inner]
  | cons p u ih =>
    obtain ⟨pw, c⟩ := p
    simp only [annih] at ih
    cases pw with
    | nil =>
      have h0 : coeff (create i v) [] = 0 := coeff_create_ne i v [] (by intro w' e; cases e)
      simp [annih, annihTerm, inner, ih, h0]
    | cons j pw =>
      by_cases hj : j = i
      · subst hj; simp [annih, annihTerm, inner, ih, coeff_create_cons]
      · have h0 : coeff (create i v) (j :: pw) = 0 :=
          coeff_create_ne i v _ (by intro w' e; injection e with e1; exact hj e1)
        simp [annih, annihTerm, inner, ih, hj, h0]

/-- **`X_i` is self-adjoint** (symmetric on finitely supported vectors). -/
theorem X_selfadjoint (i : Nat) (u v : Vec) : inner (X i u) v = inner u (X i v) := by
  simp only [X, inner_append_left, inner_append_right, inner_create, inner_annih]
  omega

/-! ## 3. Monomials, their adjoints, the vacuum trace and the norms -/

/-- The monomial `X_{i₁} X_{i₂} ⋯ X_{iₖ}` (for the list `[i₁, …, iₖ]`) applied to a vector. -/
def applyW (ws : List Nat) (v : Vec) : Vec := ws.foldr X v

theorem applyW_append (l₁ l₂ : List Nat) (v : Vec) :
    applyW (l₁ ++ l₂) v = applyW l₁ (applyW l₂ v) := by
  simp [applyW, List.foldr_append]

/-- **The adjoint of `X_{i₁} ⋯ X_{iₖ}` is `X_{iₖ} ⋯ X_{i₁}`.** -/
theorem applyW_adjoint (ws : List Nat) (u v : Vec) :
    inner (applyW ws u) v = inner u (applyW ws.reverse v) := by
  induction ws generalizing v with
  | nil => rfl
  | cons i ws ih =>
    show inner (X i (applyW ws u)) v = _
    rw [X_selfadjoint, ih, List.reverse_cons, applyW_append]
    rfl

/-- The vacuum state `τ(X_{i₁} ⋯ X_{iₖ}) = ⟨Ω, X_{i₁} ⋯ X_{iₖ} Ω⟩`. -/
def tau (ws : List Nat) : Int := inner Ω (applyW ws Ω)

/-- `‖W‖₂² = τ(W*W)` for the monomial `W` with letter list `ws` (`W* ` = reversed list). -/
def norm2sq (ws : List Nat) : Int := tau (ws.reverse ++ ws)

/-- `‖W‖₄⁴ = τ((W*W)²)`. -/
def norm4pow4 (ws : List Nat) : Int := tau (ws.reverse ++ ws ++ ws.reverse ++ ws)

/-- `‖W‖₂² = ⟨WΩ, WΩ⟩`. -/
theorem norm2sq_eq (ws : List Nat) :
    norm2sq ws = inner (applyW ws Ω) (applyW ws Ω) := by
  unfold norm2sq tau
  rw [applyW_append, ← applyW_adjoint]

/-- `‖W‖₄⁴ = ⟨W*WΩ, W*WΩ⟩ = ‖W*W Ω‖²`. -/
theorem norm4pow4_eq (ws : List Nat) :
    norm4pow4 ws = inner (applyW (ws.reverse ++ ws) Ω) (applyW (ws.reverse ++ ws) Ω) := by
  unfold norm4pow4 tau
  have h : ws.reverse ++ ws ++ ws.reverse ++ ws = (ws.reverse ++ ws) ++ (ws.reverse ++ ws) := by
    simp [List.append_assoc]
  rw [h, applyW_append]
  have := applyW_adjoint (ws.reverse ++ ws) Ω (applyW (ws.reverse ++ ws) Ω)
  simp only [List.reverse_append, List.reverse_reverse] at this
  rw [← this]

/-! ## 4. The semicircle law and the words `X₀X₁⋯X_{d-1}` -/

set_option maxRecDepth 100000 in
/-- **`X₀` is a standard semicircular element**: its moments are the Catalan numbers
`1, 1, 2, 5, 14, 42` in even degree and `0` in odd degree (which determines the semicircle law
on `[-2, 2]`). -/
theorem semicircle_moments :
    (List.range 11).map (fun k => tau (List.replicate k 0)) = [1, 0, 1, 0, 2, 0, 5, 0, 14, 0, 42] := by
  decide

/-- Mixed moments of `X₀, X₁` (consistent with freeness): `τ(X₀X₁) = 0`, `τ(X₀²X₁²) = 1`,
`τ(X₀X₁X₀X₁) = 0`, `τ(X₀²X₁X₀²X₁) = 1`. -/
theorem mixed_moments :
    tau [0, 1] = 0 ∧ tau [0, 0, 1, 1] = 1 ∧ tau [0, 1, 0, 1] = 0 ∧ tau [0, 0, 1, 0, 0, 1] = 1 := by
  decide

/-- The free word of length `d`: `W_d = X₀ X₁ ⋯ X_{d-1}` (distinct free semicirculars). -/
def word (d : Nat) : List Nat := List.range d

/-- **`d = 1`:** `W = X₀`, `‖W‖₂² = τ(X₀²) = 1`, `‖W‖₄⁴ = τ(X₀⁴) = 2`. -/
theorem word1 : word 1 = [0] ∧ norm2sq (word 1) = 1 ∧ norm4pow4 (word 1) = 2 ∧
    tau [0, 0] = 1 ∧ tau [0, 0, 0, 0] = 2 := by
  decide

/-- `‖X₀⋯X_{d-1}‖₂² = 1` and `‖X₀⋯X_{d-1}‖₄⁴ = d + 1` (Fuss–Catalan) for `d = 2, 3, 4`. -/
theorem words_234 :
    norm2sq (word 2) = 1 ∧ norm4pow4 (word 2) = 3 ∧
    norm2sq (word 3) = 1 ∧ norm4pow4 (word 3) = 4 ∧
    norm2sq (word 4) = 1 ∧ norm4pow4 (word 4) = 5 := by
  decide

/-! ## 5. The first chaos at `d = 1`: every `aX₀ + bX₁` has the same ratio -/

/-- Scalar multiple of a vector. -/
def smul (a : Int) (v : Vec) : Vec := v.map fun p => (p.1, a * p.2)

/-- The element `S = aX₀ + bX₁ + cX₂` of the first chaos (three free semicirculars), acting on
vectors. -/
def S3 (a b c : Int) (v : Vec) : Vec := smul a (X 0 v) ++ smul b (X 1 v) ++ smul c (X 2 v)

set_option maxRecDepth 100000 in
/-- **The ratio is constant on the first chaos:** for all real (here integer) `a, b, c`,
`τ(S²) = a² + b² + c²` and `τ(S⁴) = 2 (a² + b² + c²)²` (written as a sum of two equal squares),
where `τ(T) = ⟨Ω, TΩ⟩`.  Both sides are polynomials in `a, b, c`, so the identity holds for real
coefficients too.  Hence `‖S‖₄⁴/‖S‖₂⁴ = 2` for every nonzero `S`. -/
theorem first_chaos_three (a b c : Int) :
    inner Ω (S3 a b c (S3 a b c Ω)) = a * a + b * b + c * c ∧
    inner Ω (S3 a b c (S3 a b c (S3 a b c (S3 a b c Ω)))) =
      (a * a + b * b + c * c) * (a * a + b * b + c * c) +
      (a * a + b * b + c * c) * (a * a + b * b + c * c) := by
  constructor
  · simp [S3, smul, X, create, annih, annihTerm, inner, coeff, Ω]
    omega
  · simp [S3, smul, X, create, annih, annihTerm, inner, coeff, Ω, Int.mul_add, Int.add_mul]
    simp only [Int.mul_assoc, Int.mul_comm, Int.mul_left_comm]
    omega

/-- **Optimal-constant reading at `d = 1`:** no nonzero element `S = aX₀ + bX₁ + cX₂` of the first
chaos has `‖S‖₄⁴/‖S‖₂⁴` equal to `f(1)² = 9/4` (`M_4² = f`), to `f(1) = 3/2` (`M_4⁴ = f`) or to
`f(1)⁴ = 81/16` (`M_4 = f`).  So neither the supremum, nor the infimum, nor any attained value of
the ratio on the first chaos matches the formula. -/
theorem first_chaos_never_formula (a b c : Int) (h : a * a + b * b + c * c ≠ 0) :
    let t2 := inner Ω (S3 a b c (S3 a b c Ω))
    let t4 := inner Ω (S3 a b c (S3 a b c (S3 a b c (S3 a b c Ω))))
    4 * t4 ≠ 9 * t2 ^ 2 ∧ 2 * t4 ≠ 3 * t2 ^ 2 ∧ 16 * t4 ≠ 81 * t2 ^ 2 := by
  intro t2 t4
  have h2 : t2 = a * a + b * b + c * c := (first_chaos_three a b c).1
  have h4 : t4 = t2 * t2 + t2 * t2 := by rw [h2]; exact (first_chaos_three a b c).2
  have hsq : t2 * t2 ≠ 0 := by
    intro e; rcases Int.mul_eq_zero.mp e with e | e <;> exact h (h2 ▸ e)
  rw [h4, Int.pow_succ, Int.pow_succ, Int.pow_zero, Int.one_mul]
  refine ⟨?_, ?_, ?_⟩ <;> intro e <;> apply hsq <;> omega

/-! ## 6. The conjectured formula and its refutation -/

/-- Numerator of `f(d) = 2 - d⁻¹(1 - 2^{-d}) = (2d·2^d - 2^d + 1)/(d·2^d)`. -/
def fNum (d : Nat) : Int := 2 * d * 2 ^ d - 2 ^ d + 1

/-- Denominator of `f(d)`. -/
def fDen (d : Nat) : Int := d * 2 ^ d

/-- Sanity check of the formula: `f(1) = 3/2`, `f(2) = 13/8`, `f(3) = 41/24`, `f(4) = 113/64`. -/
theorem f_values :
    (fNum 1, fDen 1) = (3, 2) ∧ (fNum 2, fDen 2) = (13, 8) ∧
    (fNum 3, fDen 3) = (41, 24) ∧ (fNum 4, fDen 4) = (113, 64) := by
  decide

/-- **Clause (C1) at `d`:** `M_4(d)² = f(d)` for the free word `W_d`, i.e. (as `f(d) > 0`)
`f(d)² = M_4(d)⁴ = ‖W_d‖₄⁴ / ‖W_d‖₂⁴`, cleared of denominators. -/
def Clause (d : Nat) : Prop :=
  fNum d ^ 2 * norm2sq (word d) ^ 2 = norm4pow4 (word d) * fDen d ^ 2

/-- Variant normalisation `M_4(d) = f(d)`, i.e. `f(d)⁴ = ‖W‖₄⁴/‖W‖₂⁴`. -/
def ClauseM4 (d : Nat) : Prop :=
  fNum d ^ 4 * norm2sq (word d) ^ 2 = norm4pow4 (word d) * fDen d ^ 4

/-- Variant normalisation `M_4(d)⁴ = f(d)`. -/
def ClauseM4pow4 (d : Nat) : Prop :=
  fNum d * norm2sq (word d) ^ 2 = norm4pow4 (word d) * fDen d

instance (d : Nat) : Decidable (Clause d) := by unfold Clause; infer_instance
instance (d : Nat) : Decidable (ClauseM4 d) := by unfold ClauseM4; infer_instance
instance (d : Nat) : Decidable (ClauseM4pow4 d) := by unfold ClauseM4pow4; infer_instance

/-- The conjecture's clause (C1): `M_4(d)² = f(d)` for every length `d ≥ 1`. -/
def Conj : Prop := ∀ d, 1 ≤ d → Clause d

/-- **At `d = 1` the clause reads `(3/2)² = 2`, i.e. `9 = 8`: false.** -/
theorem clause_false_d1 : ¬ Clause 1 := by
  unfold Clause
  rw [(word1).2.1, (word1).2.2.1]
  decide

/-- The clause and both other normalisations fail for `d = k + 1 = 1, 2, 3, 4`. -/
theorem clause_false_small :
    ∀ k, k < 4 → ¬ Clause (k + 1) ∧ ¬ ClauseM4 (k + 1) ∧ ¬ ClauseM4pow4 (k + 1) := by
  decide

/-- **Conjecture 00000007739 is false**: clause (C1) fails, whatever the second clause means. -/
theorem conjecture_00000007739_false (C2 : Prop) : ¬ (Conj ∧ C2) := by
  intro h
  exact clause_false_d1 (h.1 1 (Nat.le_refl 1))

end FreeK

#print axioms FreeK.inner_create
#print axioms FreeK.inner_annih
#print axioms FreeK.X_selfadjoint
#print axioms FreeK.applyW_adjoint
#print axioms FreeK.norm2sq_eq
#print axioms FreeK.norm4pow4_eq
#print axioms FreeK.semicircle_moments
#print axioms FreeK.mixed_moments
#print axioms FreeK.word1
#print axioms FreeK.words_234
#print axioms FreeK.first_chaos_three
#print axioms FreeK.first_chaos_never_formula
#print axioms FreeK.f_values
#print axioms FreeK.clause_false_d1
#print axioms FreeK.clause_false_small
#print axioms FreeK.conjecture_00000007739_false
